zipdata({
	"0560000":[[1,"日高郡新ひだか町","","","Shinhidaka-cho, Hidaka-gun","",""]],
	"0560001":[[1,"日高郡新ひだか町","静内目名","","Shinhidaka-cho, Hidaka-gun","Shizunai Mena",""]],
	"0560002":[[1,"日高郡新ひだか町","静内神森","","Shinhidaka-cho, Hidaka-gun","Shizunai Kamimori",""]],
	"0560003":[[1,"日高郡新ひだか町","静内旭町","","Shinhidaka-cho, Hidaka-gun","Shizunai Asahicho",""]],
	"0560004":[[1,"日高郡新ひだか町","静内緑町","","Shinhidaka-cho, Hidaka-gun","Shizunai Midoricho",""]],
	"0560005":[[1,"日高郡新ひだか町","静内こうせい町","","Shinhidaka-cho, Hidaka-gun","Shizunai Koseicho",""]],
	"0560006":[[1,"日高郡新ひだか町","静内中野町","","Shinhidaka-cho, Hidaka-gun","Shizunai Nakanocho",""]],
	"0560007":[[1,"日高郡新ひだか町","静内清水丘","","Shinhidaka-cho, Hidaka-gun","Shizunai Shimizuoka",""]],
	"0560011":[[1,"日高郡新ひだか町","静内真歌","","Shinhidaka-cho, Hidaka-gun","Shizunai Mauta",""]],
	"0560013":[[1,"日高郡新ひだか町","静内入船町","","Shinhidaka-cho, Hidaka-gun","Shizunai Irifunecho",""]],
	"0560014":[[1,"日高郡新ひだか町","静内古川町","","Shinhidaka-cho, Hidaka-gun","Shizunai Furukawacho",""]],
	"0560015":[[1,"日高郡新ひだか町","静内海岸町","","Shinhidaka-cho, Hidaka-gun","Shizunai Kaigancho",""]],
	"0560016":[[1,"日高郡新ひだか町","静内本町","","Shinhidaka-cho, Hidaka-gun","Shizunai Honcho",""]],
	"0560017":[[1,"日高郡新ひだか町","静内御幸町","","Shinhidaka-cho, Hidaka-gun","Shizunai Miyukicho",""]],
	"0560018":[[1,"日高郡新ひだか町","静内吉野町","","Shinhidaka-cho, Hidaka-gun","Shizunai Yoshinocho",""]],
	"0560019":[[1,"日高郡新ひだか町","静内青柳町","","Shinhidaka-cho, Hidaka-gun","Shizunai Aoyagicho",""]],
	"0560021":[[1,"日高郡新ひだか町","静内花園","","Shinhidaka-cho, Hidaka-gun","Shizunai Hanazono",""]],
	"0560022":[[1,"日高郡新ひだか町","静内高砂町","","Shinhidaka-cho, Hidaka-gun","Shizunai Takasagocho",""]],
	"0560023":[[1,"日高郡新ひだか町","静内ときわ町","","Shinhidaka-cho, Hidaka-gun","Shizunai Tokiwacho",""]],
	"0560024":[[1,"日高郡新ひだか町","静内山手町","","Shinhidaka-cho, Hidaka-gun","Shizunai Yamatecho",""]],
	"0560025":[[1,"日高郡新ひだか町","静内木場町","","Shinhidaka-cho, Hidaka-gun","Shizunai Kibacho",""]],
	"0560026":[[1,"日高郡新ひだか町","静内末広町","","Shinhidaka-cho, Hidaka-gun","Shizunai Suehirocho",""]],
	"0560027":[[1,"日高郡新ひだか町","静内駒場","","Shinhidaka-cho, Hidaka-gun","Shizunai Komaba",""]],
	"0560028":[[1,"日高郡新ひだか町","静内柏台","","Shinhidaka-cho, Hidaka-gun","Shizunai Kashiwadai",""]],
	"0560141":[[1,"日高郡新ひだか町","静内御園","","Shinhidaka-cho, Hidaka-gun","Shizunai Misono",""]],
	"0560142":[[1,"日高郡新ひだか町","静内農屋","","Shinhidaka-cho, Hidaka-gun","Shizunai Noya",""]],
	"0560143":[[1,"日高郡新ひだか町","静内豊畑","","Shinhidaka-cho, Hidaka-gun","Shizunai Toyohata",""]],
	"0560144":[[1,"日高郡新ひだか町","静内田原","","Shinhidaka-cho, Hidaka-gun","Shizunai Tahara",""]],
	"0560145":[[1,"日高郡新ひだか町","静内目名","","Shinhidaka-cho, Hidaka-gun","Shizunai Mena",""]],
	"0560146":[[1,"日高郡新ひだか町","静内高見","","Shinhidaka-cho, Hidaka-gun","Shizunai Takami",""]]
})
