zipdata({
	"5310041":[[27,"大阪市北区","天神橋","","Kita-ku, Osaka-shi","Tenjimbashi",""]],
	"5310061":[[27,"大阪市北区","長柄西","","Kita-ku, Osaka-shi","Nagaranishi",""]],
	"5310062":[[27,"大阪市北区","長柄中","","Kita-ku, Osaka-shi","Nagaranaka",""]],
	"5310063":[[27,"大阪市北区","長柄東","","Kita-ku, Osaka-shi","Nagarahigashi",""]],
	"5310064":[[27,"大阪市北区","国分寺","","Kita-ku, Osaka-shi","Kokubunji",""]],
	"5310071":[[27,"大阪市北区","中津","","Kita-ku, Osaka-shi","Nakatsu",""]],
	"5310072":[[27,"大阪市北区","豊崎","","Kita-ku, Osaka-shi","Toyosaki",""]],
	"5310073":[[27,"大阪市北区","本庄西","","Kita-ku, Osaka-shi","Honjonishi",""]],
	"5310074":[[27,"大阪市北区","本庄東","","Kita-ku, Osaka-shi","Honjohigashi",""]],
	"5310075":[[27,"大阪市北区","大淀南","","Kita-ku, Osaka-shi","Oyodominami",""]],
	"5310076":[[27,"大阪市北区","大淀中","","Kita-ku, Osaka-shi","Oyodonaka ",""]],
	"5310077":[[27,"大阪市北区","大淀北","","Kita-ku, Osaka-shi","Oyodokita",""]],
	"5316001":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316002":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316003":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316004":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316005":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316006":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316007":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316008":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316009":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316010":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316011":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316012":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316013":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316014":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316015":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316016":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316017":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316018":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316019":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316020":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316021":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316022":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316023":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316024":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316025":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316026":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316027":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316028":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316029":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316030":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316031":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316032":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316033":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316034":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316035":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316036":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316037":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316038":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316039":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316090":[[27,"大阪市北区","大淀中梅田スカイビルタワーイース","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawaisuto",""]],
	"5316101":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316102":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316103":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316104":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316105":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316106":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316107":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316108":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316109":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316110":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316111":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316112":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316113":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316114":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316115":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316116":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316117":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316118":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316119":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316120":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316121":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316122":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316123":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316124":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316125":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316126":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316127":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316128":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316129":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316130":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316131":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316132":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316133":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316134":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316135":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316136":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316137":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316138":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316139":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]],
	"5316190":[[27,"大阪市北区","大淀中梅田スカイビルタワーウエス","","Kita-ku, Osaka-shi","Oyodonaka Umedasukaibirutawauesuto",""]]
})
