zipdata({
	"9690100":[[7,"西白河郡泉崎村","","","Izumizaki-mura, Nishishirakawa-gun","",""]],
	"9690101":[[7,"西白河郡泉崎村","泉崎","","Izumizaki-mura, Nishishirakawa-gun","Izumizaki",""]],
	"9690102":[[7,"西白河郡泉崎村","関和久","","Izumizaki-mura, Nishishirakawa-gun","Sekiwagu",""]],
	"9690103":[[7,"西白河郡泉崎村","北平山","","Izumizaki-mura, Nishishirakawa-gun","Kitahirayama",""]],
	"9690104":[[7,"西白河郡泉崎村","太田川","","Izumizaki-mura, Nishishirakawa-gun","Otagawa",""]],
	"9690105":[[7,"西白河郡泉崎村","踏瀬","","Izumizaki-mura, Nishishirakawa-gun","Fumase",""]],
	"9690106":[[7,"西白河郡泉崎村","関和久","","Izumizaki-mura, Nishishirakawa-gun","Sekiwagu ",""]],
	"9690200":[[7,"西白河郡矢吹町","","","Yabuki-machi, Nishishirakawa-gun","",""]],
	"9690201":[[7,"西白河郡矢吹町","大町","","Yabuki-machi, Nishishirakawa-gun","Omachi",""]],
	"9690202":[[7,"西白河郡矢吹町","新町","","Yabuki-machi, Nishishirakawa-gun","Shimmachi",""]],
	"9690203":[[7,"西白河郡矢吹町","北浦","","Yabuki-machi, Nishishirakawa-gun","Kitaura",""]],
	"9690204":[[7,"西白河郡矢吹町","関山","","Yabuki-machi, Nishishirakawa-gun","Sekiyama",""]],
	"9690205":[[7,"西白河郡矢吹町","五本松","","Yabuki-machi, Nishishirakawa-gun","Gohommatsu",""]],
	"9690206":[[7,"西白河郡矢吹町","赤沢","","Yabuki-machi, Nishishirakawa-gun","Akasawa",""]],
	"9690211":[[7,"西白河郡矢吹町","北町","","Yabuki-machi, Nishishirakawa-gun","Kitamachi",""]],
	"9690212":[[7,"西白河郡矢吹町","善郷内","","Yabuki-machi, Nishishirakawa-gun","Zengouchi",""]],
	"9690213":[[7,"西白河郡矢吹町","本町","","Yabuki-machi, Nishishirakawa-gun","Motomachi",""]],
	"9690221":[[7,"西白河郡矢吹町","中町","","Yabuki-machi, Nishishirakawa-gun","Nakamachi",""]],
	"9690222":[[7,"西白河郡矢吹町","八幡町","","Yabuki-machi, Nishishirakawa-gun","Hachimancho",""]],
	"9690223":[[7,"西白河郡矢吹町","文京町","","Yabuki-machi, Nishishirakawa-gun","Bunkyocho",""]],
	"9690224":[[7,"西白河郡矢吹町","大久保","","Yabuki-machi, Nishishirakawa-gun","Okubo",""]],
	"9690225":[[7,"西白河郡矢吹町","東長峰","","Yabuki-machi, Nishishirakawa-gun","Higashinagamine",""]],
	"9690226":[[7,"西白河郡矢吹町","西長峰","","Yabuki-machi, Nishishirakawa-gun","Nishinagamine",""]],
	"9690227":[[7,"西白河郡矢吹町","田町","","Yabuki-machi, Nishishirakawa-gun","Tamachi",""]],
	"9690231":[[7,"西白河郡矢吹町","中丸","","Yabuki-machi, Nishishirakawa-gun","Nakamaru",""]],
	"9690232":[[7,"西白河郡矢吹町","本城舘","","Yabuki-machi, Nishishirakawa-gun","Honjodate",""]],
	"9690233":[[7,"西白河郡矢吹町","花の里","","Yabuki-machi, Nishishirakawa-gun","Hananosato",""]],
	"9690234":[[7,"西白河郡矢吹町","前田","","Yabuki-machi, Nishishirakawa-gun","Maeda",""]],
	"9690235":[[7,"西白河郡矢吹町","丸の内","","Yabuki-machi, Nishishirakawa-gun","Marunochi",""]],
	"9690236":[[7,"西白河郡矢吹町","一本木","","Yabuki-machi, Nishishirakawa-gun","Ippongi",""],[7,"西白河郡矢吹町","中畑新田","","Yabuki-machi, Nishishirakawa-gun","Nakahatashinden",""],[7,"西白河郡矢吹町","矢吹","","Yabuki-machi, Nishishirakawa-gun","Yabuki",""]],
	"9690237":[[7,"西白河郡矢吹町","牡丹平","","Yabuki-machi, Nishishirakawa-gun","Botandaira",""]],
	"9690238":[[7,"西白河郡矢吹町","大池","","Yabuki-machi, Nishishirakawa-gun","Oike",""]],
	"9690241":[[7,"西白河郡矢吹町","陣ケ岡","","Yabuki-machi, Nishishirakawa-gun","Jingaoka",""],[7,"西白河郡矢吹町","天開","","Yabuki-machi, Nishishirakawa-gun","Tenkai",""]],
	"9690242":[[7,"西白河郡矢吹町","三城目","","Yabuki-machi, Nishishirakawa-gun","Sanjome",""]],
	"9690243":[[7,"西白河郡矢吹町","中沖","","Yabuki-machi, Nishishirakawa-gun","Nakaoki",""],[7,"西白河郡矢吹町","東川原","","Yabuki-machi, Nishishirakawa-gun","Higashikawahara",""]],
	"9690244":[[7,"西白河郡矢吹町","奉行塚","","Yabuki-machi, Nishishirakawa-gun","Bugyozuka",""],[7,"西白河郡矢吹町","谷中","","Yabuki-machi, Nishishirakawa-gun","Yanaka",""]],
	"9690245":[[7,"西白河郡矢吹町","白山","","Yabuki-machi, Nishishirakawa-gun","Hakusan",""]],
	"9690246":[[7,"西白河郡矢吹町","上宮崎","","Yabuki-machi, Nishishirakawa-gun","Kamimiyazaki",""],[7,"西白河郡矢吹町","下宮崎","","Yabuki-machi, Nishishirakawa-gun","Shimomiyazaki",""]],
	"9690247":[[7,"西白河郡矢吹町","諏訪の前","","Yabuki-machi, Nishishirakawa-gun","Suwanomae",""],[7,"西白河郡矢吹町","寺の前","","Yabuki-machi, Nishishirakawa-gun","Teranomae",""]],
	"9690248":[[7,"西白河郡矢吹町","東郷","","Yabuki-machi, Nishishirakawa-gun","Togo",""]],
	"9690251":[[7,"西白河郡矢吹町","神田東","","Yabuki-machi, Nishishirakawa-gun","Kantahigashi",""],[7,"西白河郡矢吹町","神田西","","Yabuki-machi, Nishishirakawa-gun","Kantanishi",""],[7,"西白河郡矢吹町","神田南","","Yabuki-machi, Nishishirakawa-gun","Kantaminami",""]],
	"9690252":[[7,"西白河郡矢吹町","神の内","","Yabuki-machi, Nishishirakawa-gun","Kaminochi",""],[7,"西白河郡矢吹町","堤","","Yabuki-machi, Nishishirakawa-gun","Tsutsumi",""],[7,"西白河郡矢吹町","中野目東","","Yabuki-machi, Nishishirakawa-gun","Nakanomehigashi",""],[7,"西白河郡矢吹町","中野目西","","Yabuki-machi, Nishishirakawa-gun","Nakanomenishi",""],[7,"西白河郡矢吹町","東堤","","Yabuki-machi, Nishishirakawa-gun","Higashitsutsumi",""]],
	"9690253":[[7,"西白河郡矢吹町","明新上","","Yabuki-machi, Nishishirakawa-gun","Myoshinkami",""],[7,"西白河郡矢吹町","明新中","","Yabuki-machi, Nishishirakawa-gun","Myoshinnaka",""],[7,"西白河郡矢吹町","明新下","","Yabuki-machi, Nishishirakawa-gun","Myoshinshimo",""],[7,"西白河郡矢吹町","明新原","","Yabuki-machi, Nishishirakawa-gun","Myoshinhara",""],[7,"西白河郡矢吹町","明新東","","Yabuki-machi, Nishishirakawa-gun","Myoshinhigashi",""],[7,"西白河郡矢吹町","明新西","","Yabuki-machi, Nishishirakawa-gun","Myoshinnishi",""]],
	"9690254":[[7,"西白河郡矢吹町","平鉢","","Yabuki-machi, Nishishirakawa-gun","Heibachi",""]],
	"9690255":[[7,"西白河郡矢吹町","寺内","","Yabuki-machi, Nishishirakawa-gun","Terauchi",""],[7,"西白河郡矢吹町","寺内東","","Yabuki-machi, Nishishirakawa-gun","Terauchihigashi",""],[7,"西白河郡矢吹町","寺内西","","Yabuki-machi, Nishishirakawa-gun","Terauchinishi",""],[7,"西白河郡矢吹町","寺内南","","Yabuki-machi, Nishishirakawa-gun","Terauchiminami",""]],
	"9690256":[[7,"西白河郡矢吹町","鍋内","","Yabuki-machi, Nishishirakawa-gun","Nabeuchi",""]],
	"9690257":[[7,"西白河郡矢吹町","上の前","","Yabuki-machi, Nishishirakawa-gun","Kaminomae",""],[7,"西白河郡矢吹町","住吉","","Yabuki-machi, Nishishirakawa-gun","Sumiyoshi",""],[7,"西白河郡矢吹町","前久保","","Yabuki-machi, Nishishirakawa-gun","Maekubo",""]],
	"9690258":[[7,"西白河郡矢吹町","沢尻","","Yabuki-machi, Nishishirakawa-gun","Sawajiri",""]],
	"9690261":[[7,"西白河郡矢吹町","弥栄","","Yabuki-machi, Nishishirakawa-gun","Yasakae",""]],
	"9690262":[[7,"西白河郡矢吹町","松房","","Yabuki-machi, Nishishirakawa-gun","Matsubo",""]],
	"9690263":[[7,"西白河郡矢吹町","根宿","","Yabuki-machi, Nishishirakawa-gun","Nejuku",""]],
	"9690264":[[7,"西白河郡矢吹町","中畑","","Yabuki-machi, Nishishirakawa-gun","Nakahata",""]],
	"9690265":[[7,"西白河郡矢吹町","中畑南","","Yabuki-machi, Nishishirakawa-gun","Nakahataminami",""]],
	"9690266":[[7,"西白河郡矢吹町","上敷面","","Yabuki-machi, Nishishirakawa-gun","Joshikimen",""]],
	"9690267":[[7,"西白河郡矢吹町","諏訪清水","","Yabuki-machi, Nishishirakawa-gun","Suwashimizu",""]],
	"9690268":[[7,"西白河郡矢吹町","松倉","","Yabuki-machi, Nishishirakawa-gun","Matsukura",""]],
	"9690271":[[7,"西白河郡矢吹町","小松","","Yabuki-machi, Nishishirakawa-gun","Komatsu",""]],
	"9690272":[[7,"西白河郡矢吹町","曙町","","Yabuki-machi, Nishishirakawa-gun","Akebonocho",""]],
	"9690281":[[7,"西白河郡矢吹町","境町","","Yabuki-machi, Nishishirakawa-gun","Sakaicho",""],[7,"西白河郡矢吹町","馬場","","Yabuki-machi, Nishishirakawa-gun","Baba",""]],
	"9690282":[[7,"西白河郡矢吹町","本郷町","","Yabuki-machi, Nishishirakawa-gun","Hongocho",""]],
	"9690283":[[7,"西白河郡矢吹町","南町","","Yabuki-machi, Nishishirakawa-gun","Minamimachi",""]],
	"9690284":[[7,"西白河郡矢吹町","滝八幡","","Yabuki-machi, Nishishirakawa-gun","Takihachiman",""],[7,"西白河郡矢吹町","舘沢","","Yabuki-machi, Nishishirakawa-gun","Tatesawa",""]],
	"9690285":[[7,"西白河郡矢吹町","花咲","","Yabuki-machi, Nishishirakawa-gun","Hanasaki",""]],
	"9690286":[[7,"西白河郡矢吹町","大和内","","Yabuki-machi, Nishishirakawa-gun","Yamatochi",""]],
	"9690287":[[7,"西白河郡矢吹町","井戸尻","","Yabuki-machi, Nishishirakawa-gun","Idojiri",""],[7,"西白河郡矢吹町","川原","","Yabuki-machi, Nishishirakawa-gun","Kawahara",""],[7,"西白河郡矢吹町","堰の上","","Yabuki-machi, Nishishirakawa-gun","Sekinoe",""]],
	"9690288":[[7,"西白河郡矢吹町","子ハ清水","","Yabuki-machi, Nishishirakawa-gun","Kohashimizu",""],[7,"西白河郡矢吹町","田内","","Yabuki-machi, Nishishirakawa-gun","Tauchi",""],[7,"西白河郡矢吹町","東の内","","Yabuki-machi, Nishishirakawa-gun","Higashinochi",""]],
	"9690301":[[7,"白河市","大信上新城","","Shirakawa-shi","Taishin Kamishinjo",""]],
	"9690302":[[7,"白河市","大信隈戸","","Shirakawa-shi","Taishin Kumado ",""]],
	"9690303":[[7,"白河市","大信下小屋","","Shirakawa-shi","Taishin Shimokoya",""]],
	"9690304":[[7,"白河市","大信下新城","","Shirakawa-shi","Taishin Shimoshinjo",""]],
	"9690305":[[7,"白河市","大信田園町府","","Shirakawa-shi","Taishin Denenchofu",""]],
	"9690306":[[7,"白河市","大信豊地","","Shirakawa-shi","Taishin Toyochi",""]],
	"9690307":[[7,"白河市","大信中新城","","Shirakawa-shi","Taishin Nakashinjo",""]],
	"9690308":[[7,"白河市","大信増見","","Shirakawa-shi","Taishin Masumi",""]],
	"9690309":[[7,"白河市","大信町屋","","Shirakawa-shi","Taishin Machiya",""]],
	"9690400":[[7,"岩瀬郡鏡石町","","","Kagamiishi-machi, Iwase-gun","",""]],
	"9690401":[[7,"岩瀬郡鏡石町","池ノ原","","Kagamiishi-machi, Iwase-gun","Ikenohara",""],[7,"岩瀬郡鏡石町","大池","","Kagamiishi-machi, Iwase-gun","Oike",""],[7,"岩瀬郡鏡石町","岡ノ内","","Kagamiishi-machi, Iwase-gun","Okanochi",""],[7,"岩瀬郡鏡石町","鏡田かげ沼町","","Kagamiishi-machi, Iwase-gun","Kagamidakagenumamachi",""],[7,"岩瀬郡鏡石町","鏡沼","","Kagamiishi-machi, Iwase-gun","Kagaminuma",""],[7,"岩瀬郡鏡石町","鹿島","","Kagamiishi-machi, Iwase-gun","Kashima",""],[7,"岩瀬郡鏡石町","蒲之沢町","","Kagamiishi-machi, Iwase-gun","Kabanosawamachi",""],[7,"岩瀬郡鏡石町","川崎町","","Kagamiishi-machi, Iwase-gun","Kawasakimachi",""],[7,"岩瀬郡鏡石町","五斗蒔町","","Kagamiishi-machi, Iwase-gun","Gotomakimachi",""],[7,"岩瀬郡鏡石町","境","","Kagamiishi-machi, Iwase-gun","Sakai",""],[7,"岩瀬郡鏡石町","桜町","","Kagamiishi-machi, Iwase-gun","Sakuramachi",""],[7,"岩瀬郡鏡石町","高久田","","Kagamiishi-machi, Iwase-gun","Takakuda",""],[7,"岩瀬郡鏡石町","豊田","","Kagamiishi-machi, Iwase-gun","Toyoda",""],[7,"岩瀬郡鏡石町","仁井田","","Kagamiishi-machi, Iwase-gun","Niida",""],[7,"岩瀬郡鏡石町","東鹿島","","Kagamiishi-machi, Iwase-gun","Higashikashima",""],[7,"岩瀬郡鏡石町","深内町","","Kagamiishi-machi, Iwase-gun","Fukochimachi",""],[7,"岩瀬郡鏡石町","不時沼","","Kagamiishi-machi, Iwase-gun","Fujinuma",""],[7,"岩瀬郡鏡石町","前山","","Kagamiishi-machi, Iwase-gun","Maeyama",""],[7,"岩瀬郡鏡石町","南高久田","","Kagamiishi-machi, Iwase-gun","Minamitakakuda",""],[7,"岩瀬郡鏡石町","本町","","Kagamiishi-machi, Iwase-gun","Motomachi",""]],
	"9690402":[[7,"岩瀬郡鏡石町","池の台","","Kagamiishi-machi, Iwase-gun","Ikenodai",""],[7,"岩瀬郡鏡石町","大宮","","Kagamiishi-machi, Iwase-gun","Omiya",""],[7,"岩瀬郡鏡石町","河原","","Kagamiishi-machi, Iwase-gun","Kawara",""],[7,"岩瀬郡鏡石町","北町","","Kagamiishi-machi, Iwase-gun","Kitamachi",""],[7,"岩瀬郡鏡石町","新町","","Kagamiishi-machi, Iwase-gun","Shimmachi",""],[7,"岩瀬郡鏡石町","諏訪町","","Kagamiishi-machi, Iwase-gun","Suwamachi",""],[7,"岩瀬郡鏡石町","成田","","Kagamiishi-machi, Iwase-gun","Narita",""],[7,"岩瀬郡鏡石町","成田原町","","Kagamiishi-machi, Iwase-gun","Naritaharamachi",""],[7,"岩瀬郡鏡石町","成田東","","Kagamiishi-machi, Iwase-gun","Naritahigashi",""],[7,"岩瀬郡鏡石町","東河原","","Kagamiishi-machi, Iwase-gun","Higashikawara",""]],
	"9690403":[[7,"岩瀬郡鏡石町","借宿","","Kagamiishi-machi, Iwase-gun","Kariyado",""],[7,"岩瀬郡鏡石町","久来石","","Kagamiishi-machi, Iwase-gun","Kyuraishi",""],[7,"岩瀬郡鏡石町","久来石南","","Kagamiishi-machi, Iwase-gun","Kyuraishiminami",""],[7,"岩瀬郡鏡石町","小栗山","","Kagamiishi-machi, Iwase-gun","Koguriyama",""],[7,"岩瀬郡鏡石町","桜岡","","Kagamiishi-machi, Iwase-gun","Sakuraoka",""],[7,"岩瀬郡鏡石町","城ノ内","","Kagamiishi-machi, Iwase-gun","Jonochi",""],[7,"岩瀬郡鏡石町","堂前","","Kagamiishi-machi, Iwase-gun","Domae",""]],
	"9690404":[[7,"岩瀬郡鏡石町","旭町","","Kagamiishi-machi, Iwase-gun","Asahimachi",""],[7,"岩瀬郡鏡石町","大山","","Kagamiishi-machi, Iwase-gun","Oyama",""],[7,"岩瀬郡鏡石町","岡の台","","Kagamiishi-machi, Iwase-gun","Okanodai",""],[7,"岩瀬郡鏡石町","笠石","","Kagamiishi-machi, Iwase-gun","Kasaishi",""],[7,"岩瀬郡鏡石町","笠石原町","","Kagamiishi-machi, Iwase-gun","Kasaishiharamachi",""],[7,"岩瀬郡鏡石町","中央","","Kagamiishi-machi, Iwase-gun","Chuo",""],[7,"岩瀬郡鏡石町","豊郷","","Kagamiishi-machi, Iwase-gun","Toyosato",""],[7,"岩瀬郡鏡石町","豊郷中","","Kagamiishi-machi, Iwase-gun","Toyosatonaka",""],[7,"岩瀬郡鏡石町","中町","","Kagamiishi-machi, Iwase-gun","Nakamachi",""],[7,"岩瀬郡鏡石町","羽鳥","","Kagamiishi-machi, Iwase-gun","Hatori",""],[7,"岩瀬郡鏡石町","東町","","Kagamiishi-machi, Iwase-gun","Higashimachi",""],[7,"岩瀬郡鏡石町","堀米","","Kagamiishi-machi, Iwase-gun","Horigome",""],[7,"岩瀬郡鏡石町","緑町","","Kagamiishi-machi, Iwase-gun","Midorimachi",""],[7,"岩瀬郡鏡石町","南町","","Kagamiishi-machi, Iwase-gun","Minamimachi",""]],
	"9691100":[[7,"本宮市","","","Motomiya-shi","",""]],
	"9691101":[[7,"本宮市","高木","","Motomiya-shi","Takagi",""]],
	"9691103":[[7,"本宮市","仁井田","","Motomiya-shi","Niita",""]],
	"9691104":[[7,"本宮市","荒井","","Motomiya-shi","Arai",""]],
	"9691105":[[7,"本宮市","関下","","Motomiya-shi","Sekishita",""]],
	"9691106":[[7,"本宮市","岩根","","Motomiya-shi","Iwane",""]],
	"9691107":[[7,"本宮市","青田","","Motomiya-shi","Aota",""]],
	"9691108":[[7,"本宮市","本宮堀切","","Motomiya-shi","Motomiya Hokkiri",""]],
	"9691109":[[7,"本宮市","本宮富ヶ峰","","Motomiya-shi","Motomiya Tomigamine",""]],
	"9691111":[[7,"本宮市","本宮作田","","Motomiya-shi","Motomiya Sakuta",""],[7,"本宮市","本宮作田台","","Motomiya-shi","Motomiya Sakutadai",""]],
	"9691112":[[7,"本宮市","本宮大榎","","Motomiya-shi","Motomiya Oenoki",""]],
	"9691113":[[7,"本宮市","本宮坊屋敷","","Motomiya-shi","Motomiya Boyashiki",""]],
	"9691114":[[7,"本宮市","本宮関根","","Motomiya-shi","Motomiya Sekine",""]],
	"9691115":[[7,"本宮市","本宮立石","","Motomiya-shi","Motomiya Tateishi",""]],
	"9691116":[[7,"本宮市","本宮弁天","","Motomiya-shi","Motomiya Benten",""]],
	"9691117":[[7,"本宮市","本宮鹿ノ子田","","Motomiya-shi","Motomiya Kanokoda",""]],
	"9691118":[[7,"本宮市","本宮下台","","Motomiya-shi","Motomiya Shimodai",""]],
	"9691119":[[7,"本宮市","本宮柳ノ内","","Motomiya-shi","Motomiya Yanaginochi",""]],
	"9691121":[[7,"本宮市","本宮舘ノ越","","Motomiya-shi","Motomiya Tatenokoshi",""]],
	"9691122":[[7,"本宮市","本宮大町","","Motomiya-shi","Motomiya Daimachi",""]],
	"9691123":[[7,"本宮市","本宮東町","","Motomiya-shi","Motomiya Higashimachi",""],[7,"本宮市","本宮東町裏","","Motomiya-shi","Motomiya Higashimachiura",""]],
	"9691124":[[7,"本宮市","本宮仲町","","Motomiya-shi","Motomiya Nakamachi",""]],
	"9691125":[[7,"本宮市","本宮荒町","","Motomiya-shi","Motomiya Aramachi",""]],
	"9691126":[[7,"本宮市","本宮馬場","","Motomiya-shi","Motomiya Baba",""]],
	"9691127":[[7,"本宮市","本宮鉄砲町","","Motomiya-shi","Motomiya Teppomachi",""]],
	"9691128":[[7,"本宮市","本宮舘町","","Motomiya-shi","Motomiya Tatemachi",""]],
	"9691129":[[7,"本宮市","本宮鍛冶免","","Motomiya-shi","Motomiya Kajimen",""],[7,"本宮市","本宮矢来","","Motomiya-shi","Motomiya Yarai",""]],
	"9691131":[[7,"本宮市","本宮南町裡","","Motomiya-shi","Motomiya Minamimachiura",""]],
	"9691132":[[7,"本宮市","本宮下町","","Motomiya-shi","Motomiya Shimomachi",""]],
	"9691133":[[7,"本宮市","本宮中條","","Motomiya-shi","Motomiya Nakajo",""]],
	"9691134":[[7,"本宮市","本宮上町","","Motomiya-shi","Motomiya Kamimachi",""]],
	"9691135":[[7,"本宮市","本宮土樋","","Motomiya-shi","Motomiya Tsuchidoi",""],[7,"本宮市","本宮蛭田","","Motomiya-shi","Motomiya Hiruta",""]],
	"9691136":[[7,"本宮市","本宮九縄","","Motomiya-shi","Motomiya Kunawa",""]],
	"9691137":[[7,"本宮市","本宮太郎丸","","Motomiya-shi","Motomiya Taromaru",""]],
	"9691138":[[7,"本宮市","本宮鳴瀬","","Motomiya-shi","Motomiya Naruse",""]],
	"9691139":[[7,"本宮市","本宮石塚","","Motomiya-shi","Motomiya Ishizuka",""]],
	"9691141":[[7,"本宮市","本宮兼谷","","Motomiya-shi","Motomiya Kanaya",""]],
	"9691142":[[7,"本宮市","本宮兼谷平","","Motomiya-shi","Motomiya Kanayadaira",""]],
	"9691143":[[7,"本宮市","本宮山田","","Motomiya-shi","Motomiya Yamada",""]],
	"9691144":[[7,"本宮市","本宮大森","","Motomiya-shi","Motomiya Omori",""]],
	"9691145":[[7,"本宮市","本宮葭ヶ入","","Motomiya-shi","Motomiya Yoshigairi",""]],
	"9691146":[[7,"本宮市","本宮南山神","","Motomiya-shi","Motomiya Minamiyamakami",""]],
	"9691147":[[7,"本宮市","本宮花町","","Motomiya-shi","Motomiya Hanamachi",""]],
	"9691148":[[7,"本宮市","本宮栄田","","Motomiya-shi","Motomiya Sakaeda",""]],
	"9691149":[[7,"本宮市","本宮万世","","Motomiya-shi","Motomiya Bansei",""]],
	"9691151":[[7,"本宮市","本宮千代田","","Motomiya-shi","Motomiya Chiyoda",""]],
	"9691152":[[7,"本宮市","本宮上千束","","Motomiya-shi","Motomiya Kamisenzoku",""],[7,"本宮市","本宮千束","","Motomiya-shi","Motomiya Senzoku",""]],
	"9691153":[[7,"本宮市","本宮塩田入","","Motomiya-shi","Motomiya Shiodairi",""]],
	"9691154":[[7,"本宮市","本宮塩田","","Motomiya-shi","Motomiya Shioda",""]],
	"9691155":[[7,"本宮市","本宮懸鉄","","Motomiya-shi","Motomiya Kankane",""],[7,"本宮市","本宮反町","","Motomiya-shi","Motomiya Sorimachi",""],[7,"本宮市","本宮雲雀田","","Motomiya-shi","Motomiya Hibarita",""],[7,"本宮市","本宮舞台","","Motomiya-shi","Motomiya Butai",""]],
	"9691156":[[7,"本宮市","本宮諏訪","","Motomiya-shi","Motomiya Suwa",""],[7,"本宮市","本宮鍋田","","Motomiya-shi","Motomiya Nabeta",""]],
	"9691157":[[7,"本宮市","本宮瀬樋内","","Motomiya-shi","Motomiya Sebiuchi",""],[7,"本宮市","本宮田中","","Motomiya-shi","Motomiya Tanaka",""]],
	"9691158":[[7,"本宮市","本宮天ヶ","","Motomiya-shi","Motomiya Amaga",""],[7,"本宮市","本宮蛇ノ鼻","","Motomiya-shi","Motomiya Janohana",""],[7,"本宮市","本宮平井","","Motomiya-shi","Motomiya Hirai",""]],
	"9691159":[[7,"本宮市","本宮小幡","","Motomiya-shi","Motomiya Obata",""],[7,"本宮市","本宮小籏北","","Motomiya-shi","Motomiya Obatakita",""],[7,"本宮市","本宮広町","","Motomiya-shi","Motomiya Hiromachi",""]],
	"9691161":[[7,"本宮市","本宮欠下","","Motomiya-shi","Motomiya Gakeshita",""]],
	"9691162":[[7,"本宮市","本宮北川原田","","Motomiya-shi","Motomiya Kitakawaharada",""],[7,"本宮市","本宮南河原田","","Motomiya-shi","Motomiya Minamikawaharada",""]],
	"9691163":[[7,"本宮市","本宮白川","","Motomiya-shi","Motomiya Shirakawa",""]],
	"9691164":[[7,"本宮市","本宮戸崎","","Motomiya-shi","Motomiya Tosaki",""]],
	"9691165":[[7,"本宮市","本宮中台","","Motomiya-shi","Motomiya Nakadai",""]],
	"9691166":[[7,"本宮市","本宮近江内","","Motomiya-shi","Motomiya Omiuchi",""]],
	"9691167":[[7,"本宮市","本宮北山神","","Motomiya-shi","Motomiya Kitayamanokami",""],[7,"本宮市","本宮道屋敷","","Motomiya-shi","Motomiya Doyashiki",""]],
	"9691168":[[7,"本宮市","本宮一ッ屋","","Motomiya-shi","Motomiya Hitotsuya",""]],
	"9691169":[[7,"本宮市","本宮小原田","","Motomiya-shi","Motomiya Koharada",""]],
	"9691171":[[7,"本宮市","本宮樋ノ口","","Motomiya-shi","Motomiya Toinokuchi",""]],
	"9691172":[[7,"本宮市","本宮北ノ内","","Motomiya-shi","Motomiya Kitanochi",""]],
	"9691173":[[7,"本宮市","本宮中野","","Motomiya-shi","Motomiya Nakano",""],[7,"本宮市","本宮中野後","","Motomiya-shi","Motomiya Nakanoshiro",""]],
	"9691174":[[7,"本宮市","本宮南ノ内","","Motomiya-shi","Motomiya Minaminochi",""]],
	"9691175":[[7,"本宮市","本宮竹花","","Motomiya-shi","Motomiya Takenohana",""],[7,"本宮市","本宮名郷","","Motomiya-shi","Motomiya Nago",""],[7,"本宮市","本宮名郷脇","","Motomiya-shi","Motomiya Nagowaki",""]],
	"9691176":[[7,"本宮市","本宮赤坂","","Motomiya-shi","Motomiya Akasaka",""],[7,"本宮市","本宮地蔵堂","","Motomiya-shi","Motomiya Jizodo",""]],
	"9691201":[[7,"本宮市","稲沢","","Motomiya-shi","Inazawa",""]],
	"9691202":[[7,"本宮市","松沢","","Motomiya-shi","Matsuzawa",""]],
	"9691203":[[7,"本宮市","白岩","","Motomiya-shi","Shiraiwa",""]],
	"9691204":[[7,"本宮市","糠沢","","Motomiya-shi","Nukazawa",""]],
	"9691205":[[7,"本宮市","和田","","Motomiya-shi","Wada",""]],
	"9691206":[[7,"本宮市","長屋","","Motomiya-shi","Nagaya",""]],
	"9691300":[[7,"安達郡大玉村","","","Otama-mura, Adachi-gun","",""]],
	"9691301":[[7,"安達郡大玉村","大山","","Otama-mura, Adachi-gun","Oyama",""]],
	"9691302":[[7,"安達郡大玉村","玉井","","Otama-mura, Adachi-gun","Tamanoi",""]],
	"9691401":[[7,"二本松市","吉倉","","Nihommatsu-shi","Yoshikura",""]],
	"9691402":[[7,"二本松市","米沢","","Nihommatsu-shi","Yonazawa",""]],
	"9691403":[[7,"二本松市","渋川","","Nihommatsu-shi","Shibukawa",""]],
	"9691404":[[7,"二本松市","油井","","Nihommatsu-shi","Yui",""]],
	"9691405":[[7,"二本松市","智恵子の森","","Nihommatsu-shi","Chiekonomori",""]],
	"9691511":[[7,"二本松市","下川崎","","Nihommatsu-shi","Shimokawasaki",""]],
	"9691512":[[7,"二本松市","上川崎","","Nihommatsu-shi","Kamikawasaki",""]],
	"9691513":[[7,"二本松市","小沢","","Nihommatsu-shi","Ozawa",""]],
	"9691600":[[7,"伊達郡桑折町","","","Kori-machi, Date-gun","",""]],
	"9691601":[[7,"伊達郡桑折町","北町","","Kori-machi, Date-gun","Kitamachi",""]],
	"9691602":[[7,"伊達郡桑折町","町裏","","Kori-machi, Date-gun","Machiura",""]],
	"9691603":[[7,"伊達郡桑折町","上町","","Kori-machi, Date-gun","Uwamachi",""]],
	"9691604":[[7,"伊達郡桑折町","堰下","","Kori-machi, Date-gun","Sekishita",""]],
	"9691605":[[7,"伊達郡桑折町","堰合","","Kori-machi, Date-gun","Sekiai",""]],
	"9691606":[[7,"伊達郡桑折町","東段","","Kori-machi, Date-gun","Higashidan",""]],
	"9691607":[[7,"伊達郡桑折町","西段","","Kori-machi, Date-gun","Nishidan",""]],
	"9691608":[[7,"伊達郡桑折町","芝堤","","Kori-machi, Date-gun","Shibatsutsumi",""]],
	"9691611":[[7,"伊達郡桑折町","東大隅","","Kori-machi, Date-gun","Higashiosumi",""]],
	"9691612":[[7,"伊達郡桑折町","西大隅","","Kori-machi, Date-gun","Nishiosumi",""]],
	"9691613":[[7,"伊達郡桑折町","桑島","","Kori-machi, Date-gun","Kuwajima",""]],
	"9691614":[[7,"伊達郡桑折町","本町","","Kori-machi, Date-gun","Motomachi",""]],
	"9691615":[[7,"伊達郡桑折町","沢","","Kori-machi, Date-gun","Sawa",""]],
	"9691616":[[7,"伊達郡桑折町","舘","","Kori-machi, Date-gun","Tate",""]],
	"9691617":[[7,"伊達郡桑折町","陣屋","","Kori-machi, Date-gun","Jinya",""]],
	"9691618":[[7,"伊達郡桑折町","庫場","","Kori-machi, Date-gun","Kuraba",""]],
	"9691619":[[7,"伊達郡桑折町","仮屋","","Kori-machi, Date-gun","Kariya",""]],
	"9691621":[[7,"伊達郡桑折町","道場前","","Kori-machi, Date-gun","Dojomae",""]],
	"9691622":[[7,"伊達郡桑折町","南町","","Kori-machi, Date-gun","Minamimachi",""]],
	"9691623":[[7,"伊達郡桑折町","和尚堂","","Kori-machi, Date-gun","Oshodo",""]],
	"9691624":[[7,"伊達郡桑折町","新和町","","Kori-machi, Date-gun","Shinwacho",""]],
	"9691625":[[7,"伊達郡桑折町","新吉町","","Kori-machi, Date-gun","Shinyoshicho",""]],
	"9691626":[[7,"伊達郡桑折町","寺坂","","Kori-machi, Date-gun","Terasaka",""]],
	"9691627":[[7,"伊達郡桑折町","諏訪","","Kori-machi, Date-gun","Suwa",""]],
	"9691628":[[7,"伊達郡桑折町","新町","","Kori-machi, Date-gun","Shimmachi",""]],
	"9691629":[[7,"伊達郡桑折町","西町","","Kori-machi, Date-gun","Nishimachi",""]],
	"9691631":[[7,"伊達郡桑折町","白銀","","Kori-machi, Date-gun","Shirogane",""],[7,"伊達郡桑折町","薮内","","Kori-machi, Date-gun","Yabuchi",""]],
	"9691632":[[7,"伊達郡桑折町","田植","","Kori-machi, Date-gun","Taue",""]],
	"9691633":[[7,"伊達郡桑折町","赤坂","","Kori-machi, Date-gun","Akasaka",""],[7,"伊達郡桑折町","一里壇","","Kori-machi, Date-gun","Ichiridan",""],[7,"伊達郡桑折町","界","","Kori-machi, Date-gun","Sakai",""]],
	"9691634":[[7,"伊達郡桑折町","落合","","Kori-machi, Date-gun","Ochiai",""],[7,"伊達郡桑折町","杉ノ前","","Kori-machi, Date-gun","Suginomae",""],[7,"伊達郡桑折町","砂子沢","","Kori-machi, Date-gun","Sunagozawa",""]],
	"9691635":[[7,"伊達郡桑折町","狐崎","","Kori-machi, Date-gun","Kitsunezaki",""],[7,"伊達郡桑折町","東八串","","Kori-machi, Date-gun","Higashiyakushi",""]],
	"9691641":[[7,"伊達郡桑折町","南半田","","Kori-machi, Date-gun","Minamihanda",""]],
	"9691642":[[7,"伊達郡桑折町","北半田","","Kori-machi, Date-gun","Kitahanda",""]],
	"9691643":[[7,"伊達郡桑折町","谷地","","Kori-machi, Date-gun","Yaji",""]],
	"9691651":[[7,"伊達郡桑折町","万正寺","","Kori-machi, Date-gun","Manshoji",""]],
	"9691652":[[7,"伊達郡桑折町","成田","","Kori-machi, Date-gun","Narita",""]],
	"9691653":[[7,"伊達郡桑折町","松原","","Kori-machi, Date-gun","Matsubara",""]],
	"9691654":[[7,"伊達郡桑折町","平沢","","Kori-machi, Date-gun","Hirasawa",""]],
	"9691661":[[7,"伊達郡桑折町","上郡","","Kori-machi, Date-gun","Kamigori",""]],
	"9691662":[[7,"伊達郡桑折町","下郡","","Kori-machi, Date-gun","Shimogori",""]],
	"9691663":[[7,"伊達郡桑折町","伊達崎","","Kori-machi, Date-gun","Danzaki",""]],
	"9691700":[[7,"伊達郡国見町","","","Kunimi-machi, Date-gun","",""]],
	"9691701":[[7,"伊達郡国見町","石母田","","Kunimi-machi, Date-gun","Ishimoda",""]],
	"9691711":[[7,"伊達郡国見町","貝田","","Kunimi-machi, Date-gun","Kaida",""]],
	"9691712":[[7,"伊達郡国見町","光明寺","","Kunimi-machi, Date-gun","Komyoji",""]],
	"9691713":[[7,"伊達郡国見町","大木戸","","Kunimi-machi, Date-gun","Okido",""]],
	"9691714":[[7,"伊達郡国見町","高城","","Kunimi-machi, Date-gun","Takagi",""]],
	"9691721":[[7,"伊達郡国見町","川内","","Kunimi-machi, Date-gun","Kawauchi",""]],
	"9691722":[[7,"伊達郡国見町","西大枝","","Kunimi-machi, Date-gun","Nishioeda",""]],
	"9691731":[[7,"伊達郡国見町","森山","","Kunimi-machi, Date-gun","Moriyama",""]],
	"9691741":[[7,"伊達郡国見町","徳江","","Kunimi-machi, Date-gun","Tokue",""]],
	"9691751":[[7,"伊達郡国見町","塚野目","","Kunimi-machi, Date-gun","Tsukanome",""]],
	"9691761":[[7,"伊達郡国見町","藤田","","Kunimi-machi, Date-gun","Fujita",""]],
	"9691771":[[7,"伊達郡国見町","山崎","","Kunimi-machi, Date-gun","Yamazaki",""]],
	"9691780":[[7,"伊達郡国見町","新内谷","","Kunimi-machi, Date-gun","Shinuchiya",""]],
	"9691781":[[7,"伊達郡国見町","内谷","","Kunimi-machi, Date-gun","Uchiya",""]],
	"9691782":[[7,"伊達郡国見町","泉田","","Kunimi-machi, Date-gun","Izumida",""]],
	"9691783":[[7,"伊達郡国見町","鳥取","","Kunimi-machi, Date-gun","Tottori",""]],
	"9691784":[[7,"伊達郡国見町","小坂","","Kunimi-machi, Date-gun","Kosaka",""]],
	"9691785":[[7,"伊達郡国見町","板橋南","","Kunimi-machi, Date-gun","Itabashiminami",""]],
	"9691786":[[7,"伊達郡国見町","新泉田","","Kunimi-machi, Date-gun","Shinizumida",""]],
	"9691787":[[7,"伊達郡国見町","新小坂","","Kunimi-machi, Date-gun","Shinkosaka",""]],
	"9691788":[[7,"伊達郡国見町","小坂南","","Kunimi-machi, Date-gun","Kosakaminami",""]],
	"9691789":[[7,"伊達郡国見町","新鳥取","","Kunimi-machi, Date-gun","Shintottori",""]],
	"9692271":[[7,"耶麻郡猪苗代町","中小松","","Inawashiro-machi, Yama-gun","Nakakomatsu",""]],
	"9692272":[[7,"耶麻郡猪苗代町","金田","","Inawashiro-machi, Yama-gun","Kaneda",""]],
	"9692273":[[7,"耶麻郡猪苗代町","関都","","Inawashiro-machi, Yama-gun","Sekito",""]],
	"9692274":[[7,"耶麻郡猪苗代町","壺楊","","Inawashiro-machi, Yama-gun","Tsuboyo",""]],
	"9692275":[[7,"耶麻郡猪苗代町","山潟","","Inawashiro-machi, Yama-gun","Yamagata",""]],
	"9692661":[[7,"耶麻郡猪苗代町","三郷","","Inawashiro-machi, Yama-gun","Misato",""]],
	"9692662":[[7,"耶麻郡猪苗代町","八幡","","Inawashiro-machi, Yama-gun","Yahata",""]],
	"9692663":[[7,"耶麻郡猪苗代町","川桁","","Inawashiro-machi, Yama-gun","Kawageta",""]],
	"9692701":[[7,"耶麻郡北塩原村","檜原","","Kitashiobara-mura, Yama-gun","Hibara",""],[7,"耶麻郡北塩原村","五色沼、甚九郎山、曽原山、寺沢山、","","Kitashiobara-mura, Yama-gun","Goshikinuma.jinkuroyama.soharayama.",""]],
	"9692751":[[7,"耶麻郡猪苗代町","若宮","","Inawashiro-machi, Yama-gun","Wakamiya",""]],
	"9692752":[[7,"耶麻郡猪苗代町","蚕養","","Inawashiro-machi, Yama-gun","Kogai",""]],
	"9693100":[[7,"耶麻郡猪苗代町","","","Inawashiro-machi, Yama-gun","",""]],
	"9693101":[[7,"耶麻郡猪苗代町","家ノ前","","Inawashiro-machi, Yama-gun","Ienomae",""],[7,"耶麻郡猪苗代町","上ノ山","","Inawashiro-machi, Yama-gun","Uenoyama",""],[7,"耶麻郡猪苗代町","大谷地","","Inawashiro-machi, Yama-gun","Oyachi",""],[7,"耶麻郡猪苗代町","欠上り","","Inawashiro-machi, Yama-gun","Kakeagari",""],[7,"耶麻郡猪苗代町","北ノ林","","Inawashiro-machi, Yama-gun","Kitanohayashi",""],[7,"耶麻郡猪苗代町","行人壇","","Inawashiro-machi, Yama-gun","Gyonindan",""],[7,"耶麻郡猪苗代町","グミ沢原","","Inawashiro-machi, Yama-gun","Gumizawahara",""],[7,"耶麻郡猪苗代町","渋谷","","Inawashiro-machi, Yama-gun","Shibutani",""],[7,"耶麻郡猪苗代町","清水","","Inawashiro-machi, Yama-gun","Shimizu",""],[7,"耶麻郡猪苗代町","清水端","","Inawashiro-machi, Yama-gun","Shimizubata",""],[7,"耶麻郡猪苗代町","下辺沢","","Inawashiro-machi, Yama-gun","Shimohenzawa",""],[7,"耶麻郡猪苗代町","菖蒲田","","Inawashiro-machi, Yama-gun","Shobuda",""],[7,"耶麻郡猪苗代町","新堀田東","","Inawashiro-machi, Yama-gun","Shimboritahigashi",""],[7,"耶麻郡猪苗代町","新堀西","","Inawashiro-machi, Yama-gun","Shimborinishi",""],[7,"耶麻郡猪苗代町","堰間上","","Inawashiro-machi, Yama-gun","Sekimaue",""],[7,"耶麻郡猪苗代町","芹沢","","Inawashiro-machi, Yama-gun","Serisawa",""],[7,"耶麻郡猪苗代町","土湯沢山","","Inawashiro-machi, Yama-gun","Tsuchiyusawayama",""],[7,"耶麻郡猪苗代町","土手間","","Inawashiro-machi, Yama-gun","Dotema",""],[7,"耶麻郡猪苗代町","中道西","","Inawashiro-machi, Yama-gun","Nakamichinishi",""],[7,"耶麻郡猪苗代町","長坂","","Inawashiro-machi, Yama-gun","Nagasaka",""],[7,"耶麻郡猪苗代町","沼ノ倉","","Inawashiro-machi, Yama-gun","Numanokura",""],[7,"耶麻郡猪苗代町","琵琶沢原","","Inawashiro-machi, Yama-gun","Biwasawahara",""],[7,"耶麻郡猪苗代町","辺沢","","Inawashiro-machi, Yama-gun","Henzawa",""],[7,"耶麻郡猪苗代町","程塚","","Inawashiro-machi, Yama-gun","Hodozuka",""],[7,"耶麻郡猪苗代町","三ツ屋","","Inawashiro-machi, Yama-gun","Mitsuya",""],[7,"耶麻郡猪苗代町","村中","","Inawashiro-machi, Yama-gun","Muranaka",""],[7,"耶麻郡猪苗代町","村北","","Inawashiro-machi, Yama-gun","Murakita",""],[7,"耶麻郡猪苗代町","山神原","","Inawashiro-machi, Yama-gun","Yamakamihara",""]],
	"9693102":[[7,"耶麻郡猪苗代町","右近山","","Inawashiro-machi, Yama-gun","Ukonyama",""],[7,"耶麻郡猪苗代町","西峰","","Inawashiro-machi, Yama-gun","Nishimine",""],[7,"耶麻郡猪苗代町","猫石山","","Inawashiro-machi, Yama-gun","Nekoishiyama",""],[7,"耶麻郡猪苗代町","葉山","","Inawashiro-machi, Yama-gun","Hayama",""],[7,"耶麻郡猪苗代町","雛草","","Inawashiro-machi, Yama-gun","Hinakusa",""],[7,"耶麻郡猪苗代町","見禰","","Inawashiro-machi, Yama-gun","Mine",""],[7,"耶麻郡猪苗代町","見禰山","","Inawashiro-machi, Yama-gun","Mineyama",""]],
	"9693103":[[7,"耶麻郡猪苗代町","鹿野境","","Inawashiro-machi, Yama-gun","Kanozakai",""],[7,"耶麻郡猪苗代町","上村前","","Inawashiro-machi, Yama-gun","Kamimuramae",""],[7,"耶麻郡猪苗代町","上村東","","Inawashiro-machi, Yama-gun","Kamimurahigashi",""],[7,"耶麻郡猪苗代町","桐木沢","","Inawashiro-machi, Yama-gun","Kirinokizawa",""],[7,"耶麻郡猪苗代町","五輪原","","Inawashiro-machi, Yama-gun","Gorimpara",""],[7,"耶麻郡猪苗代町","諏訪前","","Inawashiro-machi, Yama-gun","Suwamae",""],[7,"耶麻郡猪苗代町","諏訪東","","Inawashiro-machi, Yama-gun","Suwahigashi",""],[7,"耶麻郡猪苗代町","諏訪西","","Inawashiro-machi, Yama-gun","Suwanishi",""],[7,"耶麻郡猪苗代町","禰次","","Inawashiro-machi, Yama-gun","Netsugi",""],[7,"耶麻郡猪苗代町","ハノ木沢","","Inawashiro-machi, Yama-gun","Hanokizawa",""],[7,"耶麻郡猪苗代町","林崎","","Inawashiro-machi, Yama-gun","Hayashizaki",""],[7,"耶麻郡猪苗代町","町島田","","Inawashiro-machi, Yama-gun","Machishimada",""]],
	"9693111":[[7,"耶麻郡猪苗代町","雷","","Inawashiro-machi, Yama-gun","Ikazuchi",""],[7,"耶麻郡猪苗代町","出雲壇","","Inawashiro-machi, Yama-gun","Izumodan",""],[7,"耶麻郡猪苗代町","板橋北","","Inawashiro-machi, Yama-gun","Itabashikita",""],[7,"耶麻郡猪苗代町","太田","","Inawashiro-machi, Yama-gun","Ota",""],[7,"耶麻郡猪苗代町","太田西","","Inawashiro-machi, Yama-gun","Otanishi",""],[7,"耶麻郡猪苗代町","小黒川","","Inawashiro-machi, Yama-gun","Ogurogawa",""],[7,"耶麻郡猪苗代町","窪田","","Inawashiro-machi, Yama-gun","Kubota",""],[7,"耶麻郡猪苗代町","窪ノ内","","Inawashiro-machi, Yama-gun","Kubonochi",""],[7,"耶麻郡猪苗代町","窪南","","Inawashiro-machi, Yama-gun","Kubominami",""],[7,"耶麻郡猪苗代町","御三壇","","Inawashiro-machi, Yama-gun","Gosandan",""],[7,"耶麻郡猪苗代町","五百苅","","Inawashiro-machi, Yama-gun","Gohyakugari",""],[7,"耶麻郡猪苗代町","猿壇","","Inawashiro-machi, Yama-gun","Sarudan",""],[7,"耶麻郡猪苗代町","二丁田","","Inawashiro-machi, Yama-gun","Nichoda",""],[7,"耶麻郡猪苗代町","沼田","","Inawashiro-machi, Yama-gun","Numata",""],[7,"耶麻郡猪苗代町","東町裏","","Inawashiro-machi, Yama-gun","Higashimachiura",""],[7,"耶麻郡猪苗代町","明円","","Inawashiro-machi, Yama-gun","Myoen",""],[7,"耶麻郡猪苗代町","村東下","","Inawashiro-machi, Yama-gun","Murahigashishita",""],[7,"耶麻郡猪苗代町","村東","","Inawashiro-machi, Yama-gun","Murahigashi",""]],
	"9693112":[[7,"耶麻郡猪苗代町","堤","","Inawashiro-machi, Yama-gun","Tsutsumi",""],[7,"耶麻郡猪苗代町","寺後","","Inawashiro-machi, Yama-gun","Terago",""],[7,"耶麻郡猪苗代町","中町","","Inawashiro-machi, Yama-gun","Nakamachi",""],[7,"耶麻郡猪苗代町","馬場","","Inawashiro-machi, Yama-gun","Baba",""],[7,"耶麻郡猪苗代町","弁才天西","","Inawashiro-machi, Yama-gun","Benzaitennishi",""]],
	"9693113":[[7,"耶麻郡猪苗代町","大道西","","Inawashiro-machi, Yama-gun","Omichinishi",""],[7,"耶麻郡猪苗代町","北半坂","","Inawashiro-machi, Yama-gun","Kitahanzaka",""],[7,"耶麻郡猪苗代町","新地","","Inawashiro-machi, Yama-gun","Shinchi",""],[7,"耶麻郡猪苗代町","茶園","","Inawashiro-machi, Yama-gun","Chaen",""],[7,"耶麻郡猪苗代町","堤下","","Inawashiro-machi, Yama-gun","Tsutsumishita",""],[7,"耶麻郡猪苗代町","堤北","","Inawashiro-machi, Yama-gun","Tsutsumikita",""],[7,"耶麻郡猪苗代町","鶴峰西","","Inawashiro-machi, Yama-gun","Tsuruminenishi",""],[7,"耶麻郡猪苗代町","樋場","","Inawashiro-machi, Yama-gun","Toiba",""],[7,"耶麻郡猪苗代町","樋場道下","","Inawashiro-machi, Yama-gun","Toibamichishita",""],[7,"耶麻郡猪苗代町","並杉西","","Inawashiro-machi, Yama-gun","Namisuginishi",""],[7,"耶麻郡猪苗代町","土町","","Inawashiro-machi, Yama-gun","Hanimachi",""],[7,"耶麻郡猪苗代町","土町西裡","","Inawashiro-machi, Yama-gun","Hanimachinishiura",""],[7,"耶麻郡猪苗代町","土町南","","Inawashiro-machi, Yama-gun","Hanimachiminami",""],[7,"耶麻郡猪苗代町","半坂","","Inawashiro-machi, Yama-gun","Hanzaka",""],[7,"耶麻郡猪苗代町","町西","","Inawashiro-machi, Yama-gun","Machinishi",""],[7,"耶麻郡猪苗代町","南半坂","","Inawashiro-machi, Yama-gun","Minamihanzaka",""]],
	"9693121":[[7,"耶麻郡猪苗代町","芦原","","Inawashiro-machi, Yama-gun","Ashihara",""],[7,"耶麻郡猪苗代町","裏町","","Inawashiro-machi, Yama-gun","Uramachi",""],[7,"耶麻郡猪苗代町","オヒテ川","","Inawashiro-machi, Yama-gun","Ohitekawa",""],[7,"耶麻郡猪苗代町","上ザル田","","Inawashiro-machi, Yama-gun","Kamizaruta",""],[7,"耶麻郡猪苗代町","津金沢","","Inawashiro-machi, Yama-gun","Tsuganesawa",""],[7,"耶麻郡猪苗代町","寺東","","Inawashiro-machi, Yama-gun","Terahigashi",""],[7,"耶麻郡猪苗代町","梨木西","","Inawashiro-machi, Yama-gun","Nashinokinishi",""],[7,"耶麻郡猪苗代町","町東","","Inawashiro-machi, Yama-gun","Machihigashi",""],[7,"耶麻郡猪苗代町","横まくり","","Inawashiro-machi, Yama-gun","Yokomakuri",""],[7,"耶麻郡猪苗代町","横マクリ","","Inawashiro-machi, Yama-gun","Yokomakuri",""]],
	"9693122":[[7,"耶麻郡猪苗代町","新町","","Inawashiro-machi, Yama-gun","Aramachi",""],[7,"耶麻郡猪苗代町","カキ田","","Inawashiro-machi, Yama-gun","Kakita",""],[7,"耶麻郡猪苗代町","ガギ田","","Inawashiro-machi, Yama-gun","Gagita",""],[7,"耶麻郡猪苗代町","坂下","","Inawashiro-machi, Yama-gun","Sakashita",""],[7,"耶麻郡猪苗代町","塚田","","Inawashiro-machi, Yama-gun","Tsukata",""],[7,"耶麻郡猪苗代町","町尻","","Inawashiro-machi, Yama-gun","Machijiri",""],[7,"耶麻郡猪苗代町","本町","","Inawashiro-machi, Yama-gun","Motomachi",""]],
	"9693123":[[7,"耶麻郡猪苗代町","古城跡","","Inawashiro-machi, Yama-gun","Kojoato",""],[7,"耶麻郡猪苗代町","古城町","","Inawashiro-machi, Yama-gun","Kojomachi",""],[7,"耶麻郡猪苗代町","城南","","Inawashiro-machi, Yama-gun","Shirominami",""],[7,"耶麻郡猪苗代町","鶴田","","Inawashiro-machi, Yama-gun","Tsuruta",""]],
	"9693131":[[7,"耶麻郡猪苗代町","今泉","","Inawashiro-machi, Yama-gun","Imaizumi",""],[7,"耶麻郡猪苗代町","上屋敷","","Inawashiro-machi, Yama-gun","Kamiyashiki",""],[7,"耶麻郡猪苗代町","下園","","Inawashiro-machi, Yama-gun","Shimozono",""],[7,"耶麻郡猪苗代町","新堀向","","Inawashiro-machi, Yama-gun","Shimborimukai",""],[7,"耶麻郡猪苗代町","西舘","","Inawashiro-machi, Yama-gun","Nishidate",""],[7,"耶麻郡猪苗代町","東谷地","","Inawashiro-machi, Yama-gun","Higashiyachi",""],[7,"耶麻郡猪苗代町","村南","","Inawashiro-machi, Yama-gun","Muraminami",""]],
	"9693132":[[7,"耶麻郡猪苗代町","堅田","","Inawashiro-machi, Yama-gun","Katada",""]],
	"9693133":[[7,"耶麻郡猪苗代町","千代田","","Inawashiro-machi, Yama-gun","Chiyoda",""]],
	"9693141":[[7,"耶麻郡猪苗代町","磐里","","Inawashiro-machi, Yama-gun","Iwasato",""],[7,"耶麻郡猪苗代町","六角","","Inawashiro-machi, Yama-gun","Rokkaku",""]],
	"9693281":[[7,"耶麻郡猪苗代町","西葉山","","Inawashiro-machi, Yama-gun","Nishihayama",""]],
	"9693282":[[7,"耶麻郡猪苗代町","酸奨沢","","Inawashiro-machi, Yama-gun","Sanshozawa",""]],
	"9693283":[[7,"耶麻郡猪苗代町","長田","","Inawashiro-machi, Yama-gun","Osada",""]],
	"9693284":[[7,"耶麻郡猪苗代町","三ツ和","","Inawashiro-machi, Yama-gun","Mitsuwa",""]],
	"9693285":[[7,"耶麻郡猪苗代町","翁沢","","Inawashiro-machi, Yama-gun","Okinazawa",""]],
	"9693286":[[7,"耶麻郡猪苗代町","磐根","","Inawashiro-machi, Yama-gun","Iwane",""]],
	"9693287":[[7,"耶麻郡猪苗代町","不動","","Inawashiro-machi, Yama-gun","Fudo",""]],
	"9693288":[[7,"耶麻郡猪苗代町","綿場","","Inawashiro-machi, Yama-gun","Wataba",""]],
	"9693300":[[7,"耶麻郡磐梯町","","","Bandai-machi, Yama-gun","",""]],
	"9693301":[[7,"耶麻郡磐梯町","磐梯","","Bandai-machi, Yama-gun","Bandai",""]],
	"9693302":[[7,"耶麻郡磐梯町","更科","","Bandai-machi, Yama-gun","Sarashina",""]],
	"9693303":[[7,"耶麻郡磐梯町","赤枝","","Bandai-machi, Yama-gun","Akaeda",""]],
	"9693304":[[7,"耶麻郡磐梯町","大谷","","Bandai-machi, Yama-gun","Otani",""]],
	"9693401":[[7,"会津若松市","河東町岡田","","Aizuwakamatsu-shi","Kawahigashimachi Okada",""]],
	"9693402":[[7,"会津若松市","河東町福島","","Aizuwakamatsu-shi","Kawahigashimachi Fukushima",""]],
	"9693411":[[7,"会津若松市","河東町大田原","","Aizuwakamatsu-shi","Kawahigashimachi Otawara",""]],
	"9693412":[[7,"会津若松市","河東町代田","","Aizuwakamatsu-shi","Kawahigashimachi Yoda",""]],
	"9693421":[[7,"会津若松市","河東町熊野堂","","Aizuwakamatsu-shi","Kawahigashimachi Kumanodo",""]],
	"9693422":[[7,"会津若松市","河東町広野","","Aizuwakamatsu-shi","Kawahigashimachi Koya",""]],
	"9693431":[[7,"会津若松市","河東町東長原","","Aizuwakamatsu-shi","Kawahigashimachi Higashinagahara",""]],
	"9693441":[[7,"会津若松市","河東町南高野","","Aizuwakamatsu-shi","Kawahigashimachi Minamikoya",""]],
	"9693451":[[7,"会津若松市","河東町八田","","Aizuwakamatsu-shi","Kawahigashimachi Hatta",""]],
	"9693461":[[7,"会津若松市","河東町浅山","","Aizuwakamatsu-shi","Kawahigashimachi Asayama",""]],
	"9693462":[[7,"会津若松市","河東町金田","","Aizuwakamatsu-shi","Kawahigashimachi Kaneda",""]],
	"9693463":[[7,"会津若松市","河東町倉橋","","Aizuwakamatsu-shi","Kawahigashimachi Kurahashi",""]],
	"9693464":[[7,"会津若松市","河東町工業団地","","Aizuwakamatsu-shi","Kawahigashimachi Kogyodanchi",""]],
	"9693471":[[7,"会津若松市","河東町広田","","Aizuwakamatsu-shi","Kawahigashimachi Hirota",""]],
	"9693481":[[7,"会津若松市","河東町郡山","","Aizuwakamatsu-shi","Kawahigashimachi Koriyama",""]],
	"9693482":[[7,"会津若松市","河東町谷沢","","Aizuwakamatsu-shi","Kawahigashimachi Tanisawa",""]],
	"9693500":[[7,"河沼郡湯川村","","","Yugawa-mura, Kawanuma-gun","",""]],
	"9693501":[[7,"喜多方市","塩川町三吉","","Kitakata-shi","Shiokawamachi Miyoshi",""]],
	"9693502":[[7,"喜多方市","塩川町常世","","Kitakata-shi","Shiokawamachi Tokoyo",""]],
	"9693503":[[7,"喜多方市","塩川町五合","","Kitakata-shi","Shiokawamachi Gogo",""]],
	"9693504":[[7,"喜多方市","塩川町中屋沢","","Kitakata-shi","Shiokawamachi Nakayazawa",""]],
	"9693505":[[7,"喜多方市","塩川町金橋","","Kitakata-shi","Shiokawamachi Kanahashi",""]],
	"9693506":[[7,"喜多方市","塩川町窪","","Kitakata-shi","Shiokawamachi Kubo",""]],
	"9693511":[[7,"喜多方市","塩川町町北","","Kitakata-shi","Shiokawamachi Machikita",""]],
	"9693512":[[7,"喜多方市","塩川町東栄町","","Kitakata-shi","Shiokawamachi Higashisakaemachi",""]],
	"9693513":[[7,"喜多方市","塩川町中町","","Kitakata-shi","Shiokawamachi Nakamachi",""]],
	"9693514":[[7,"喜多方市","塩川町新町","","Kitakata-shi","Shiokawamachi Aramachi",""]],
	"9693515":[[7,"喜多方市","塩川町米沢町","","Kitakata-shi","Shiokawamachi Yonezawacho",""]],
	"9693521":[[7,"喜多方市","塩川町岡ノ前","","Kitakata-shi","Shiokawamachi Okanomae",""],[7,"喜多方市","塩川町東岡","","Kitakata-shi","Shiokawamachi Higashioka",""],[7,"喜多方市","塩川町身神","","Kitakata-shi","Shiokawamachi Mikami",""]],
	"9693522":[[7,"喜多方市","塩川町新丁","","Kitakata-shi","Shiokawamachi Shincho",""]],
	"9693523":[[7,"喜多方市","塩川町石橋","","Kitakata-shi","Shiokawamachi Ishibashi",""],[7,"喜多方市","塩川町反町","","Kitakata-shi","Shiokawamachi Soricho",""]],
	"9693524":[[7,"喜多方市","塩川町清水岸","","Kitakata-shi","Shiokawamachi Shimizugishi",""],[7,"喜多方市","塩川町竹ノ花","","Kitakata-shi","Shiokawamachi Takenohana",""],[7,"喜多方市","塩川町舘ノ内","","Kitakata-shi","Shiokawamachi Tatenochi",""]],
	"9693525":[[7,"喜多方市","塩川町黄金田","","Kitakata-shi","Shiokawamachi Koganeda",""],[7,"喜多方市","塩川町諏訪前","","Kitakata-shi","Shiokawamachi Suwamae",""]],
	"9693526":[[7,"喜多方市","塩川町諏訪町","","Kitakata-shi","Shiokawamachi Suwacho",""]],
	"9693527":[[7,"喜多方市","塩川町御殿場","","Kitakata-shi","Shiokawamachi Gotemba",""]],
	"9693528":[[7,"喜多方市","塩川町諏訪北","","Kitakata-shi","Shiokawamachi Suwakita",""]],
	"9693531":[[7,"喜多方市","塩川町新井田谷地","","Kitakata-shi","Shiokawamachi Niidayaji",""]],
	"9693532":[[7,"喜多方市","塩川町大在家","","Kitakata-shi","Shiokawamachi Ozaike",""],[7,"喜多方市","塩川町経塚","","Kitakata-shi","Shiokawamachi Kyozuka",""],[7,"喜多方市","塩川町小府根","","Kitakata-shi","Shiokawamachi Kofune",""],[7,"喜多方市","塩川町高道","","Kitakata-shi","Shiokawamachi Takamichi",""],[7,"喜多方市","塩川町藤ノ木","","Kitakata-shi","Shiokawamachi Fujinoki",""]],
	"9693533":[[7,"喜多方市","塩川町新江木","","Kitakata-shi","Shiokawamachi Nieki",""]],
	"9693534":[[7,"喜多方市","塩川町遠田","","Kitakata-shi","Shiokawamachi Tota",""],[7,"喜多方市","塩川町西ノ新田","","Kitakata-shi","Shiokawamachi Nishinoshinden",""]],
	"9693535":[[7,"喜多方市","塩川町会知","","Kitakata-shi","Shiokawamachi Kaichi",""]],
	"9693536":[[7,"喜多方市","塩川町大田木","","Kitakata-shi","Shiokawamachi Otaki",""]],
	"9693537":[[7,"喜多方市","塩川町四奈川","","Kitakata-shi","Shiokawamachi Shinagawa",""]],
	"9693538":[[7,"喜多方市","塩川町天沼","","Kitakata-shi","Shiokawamachi Amanuma",""]],
	"9693539":[[7,"喜多方市","塩川町源太屋敷","","Kitakata-shi","Shiokawamachi Gendayashiki",""],[7,"喜多方市","塩川町吉沖","","Kitakata-shi","Shiokawamachi Yoshioki",""]],
	"9693541":[[7,"河沼郡湯川村","浜崎","","Yugawa-mura, Kawanuma-gun","Hamasaki",""]],
	"9693542":[[7,"河沼郡湯川村","湊","","Yugawa-mura, Kawanuma-gun","Minato",""]],
	"9693543":[[7,"河沼郡湯川村","笈川","","Yugawa-mura, Kawanuma-gun","Oikawa",""]],
	"9693544":[[7,"河沼郡湯川村","清水田","","Yugawa-mura, Kawanuma-gun","Shimizuda",""]],
	"9693545":[[7,"河沼郡湯川村","桜町","","Yugawa-mura, Kawanuma-gun","Sakuramachi",""]],
	"9693546":[[7,"河沼郡湯川村","美田園","","Yugawa-mura, Kawanuma-gun","Mitazono",""]],
	"9693551":[[7,"河沼郡湯川村","堂畑","","Yugawa-mura, Kawanuma-gun","Dobatake",""]],
	"9693552":[[7,"河沼郡湯川村","三川","","Yugawa-mura, Kawanuma-gun","Mikawa",""]],
	"9693553":[[7,"河沼郡湯川村","田川","","Yugawa-mura, Kawanuma-gun","Tagawa",""]],
	"9693554":[[7,"河沼郡湯川村","熊ノ目","","Yugawa-mura, Kawanuma-gun","Kumanome",""]],
	"9693555":[[7,"河沼郡湯川村","佐野目","","Yugawa-mura, Kawanuma-gun","Sanome",""]],
	"9693556":[[7,"河沼郡湯川村","勝常","","Yugawa-mura, Kawanuma-gun","Shojo",""]],
	"9694101":[[7,"喜多方市","山都町小舟寺","","Kitakata-shi","Yamatomachi Kofunaji",""]],
	"9694102":[[7,"喜多方市","山都町一川","","Kitakata-shi","Yamatomachi Ichikawa",""]],
	"9694103":[[7,"喜多方市","山都町木幡","","Kitakata-shi","Yamatomachi Kohata",""]],
	"9694104":[[7,"喜多方市","山都町蓬莱","","Kitakata-shi","Yamatomachi Horai",""]],
	"9694105":[[7,"喜多方市","山都町三津合","","Kitakata-shi","Yamatomachi Mitsuai",""]],
	"9694106":[[7,"喜多方市","山都町朝倉","","Kitakata-shi","Yamatomachi Asakura",""]],
	"9694107":[[7,"喜多方市","山都町相川","","Kitakata-shi","Yamatomachi Aikawa",""]],
	"9694108":[[7,"喜多方市","山都町一ノ木","","Kitakata-shi","Yamatomachi Ichinoki",""]],
	"9694109":[[7,"喜多方市","山都町早稲谷","","Kitakata-shi","Yamatomachi Wasetani",""]],
	"9694111":[[7,"喜多方市","山都町蔵ノ後","","Kitakata-shi","Yamatomachi Kuranoshiro",""]],
	"9694112":[[7,"喜多方市","山都町上ノ原道東","","Kitakata-shi","Yamatomachi Uenoharamichihigashi",""]],
	"9694113":[[7,"喜多方市","山都町上ノ原道西","","Kitakata-shi","Yamatomachi Uenoharamichinishi",""]],
	"9694114":[[7,"喜多方市","山都町小山","","Kitakata-shi","Yamatomachi Koyama",""]],
	"9694115":[[7,"喜多方市","山都町五十苅","","Kitakata-shi","Yamatomachi Gojukari",""]],
	"9694116":[[7,"喜多方市","山都町清水上","","Kitakata-shi","Yamatomachi Shimizue",""]],
	"9694117":[[7,"喜多方市","山都町清水尻","","Kitakata-shi","Yamatomachi Shimizujiri",""]],
	"9694118":[[7,"喜多方市","山都町古屋敷","","Kitakata-shi","Yamatomachi Furuyashiki",""]],
	"9694119":[[7,"喜多方市","山都町江戸塚","","Kitakata-shi","Yamatomachi Edotsuka",""]],
	"9694121":[[7,"喜多方市","山都町太田","","Kitakata-shi","Yamatomachi Ota",""]],
	"9694122":[[7,"喜多方市","山都町木曽","","Kitakata-shi","Yamatomachi Kiso",""]],
	"9694123":[[7,"喜多方市","山都町中新田","","Kitakata-shi","Yamatomachi Nakashinden",""]],
	"9694124":[[7,"喜多方市","山都町墓ノ後","","Kitakata-shi","Yamatomachi Hakanoato",""]],
	"9694125":[[7,"喜多方市","山都町弥左エ門田","","Kitakata-shi","Yamatomachi Yazaemonden",""]],
	"9694126":[[7,"喜多方市","山都町馬放場","","Kitakata-shi","Yamatomachi Umahanashiba",""]],
	"9694127":[[7,"喜多方市","山都町久祢花","","Kitakata-shi","Yamatomachi Kuyabana",""]],
	"9694131":[[7,"喜多方市","山都町広野","","Kitakata-shi","Yamatomachi Hirono",""]],
	"9694132":[[7,"喜多方市","山都町三ノ宮","","Kitakata-shi","Yamatomachi Sannomiya",""]],
	"9694133":[[7,"喜多方市","山都町広葎田","","Kitakata-shi","Yamatomachi Hiromukuroda",""]],
	"9694134":[[7,"喜多方市","山都町葎田","","Kitakata-shi","Yamatomachi Mukuroda",""]],
	"9694135":[[7,"喜多方市","山都町広中新田","","Kitakata-shi","Yamatomachi Hironakashinden",""]],
	"9694136":[[7,"喜多方市","山都町町尻","","Kitakata-shi","Yamatomachi Machijiri",""]],
	"9694137":[[7,"喜多方市","山都町中野","","Kitakata-shi","Yamatomachi Nakano",""]],
	"9694138":[[7,"喜多方市","山都町蛇崩","","Kitakata-shi","Yamatomachi Jakuzure",""]],
	"9694139":[[7,"喜多方市","山都町北松ノ前","","Kitakata-shi","Yamatomachi Kitamatsunomae",""]],
	"9694140":[[7,"喜多方市","山都町石打場下","","Kitakata-shi","Yamatomachi Ishiuchibashita",""]],
	"9694141":[[7,"喜多方市","山都町田向","","Kitakata-shi","Yamatomachi Tamukai",""]],
	"9694142":[[7,"喜多方市","山都町七十苅","","Kitakata-shi","Yamatomachi Nanajugari",""]],
	"9694143":[[7,"喜多方市","山都町沢田","","Kitakata-shi","Yamatomachi Sawata",""]],
	"9694144":[[7,"喜多方市","山都町殿戸","","Kitakata-shi","Yamatomachi Tonoto",""]],
	"9694145":[[7,"喜多方市","山都町西原","","Kitakata-shi","Yamatomachi Nishihara",""]],
	"9694146":[[7,"喜多方市","山都町広古屋敷","","Kitakata-shi","Yamatomachi Hirokoyashiki",""]],
	"9694147":[[7,"喜多方市","山都町石堀古","","Kitakata-shi","Yamatomachi Ishibotsuko",""]],
	"9694148":[[7,"喜多方市","山都町岩渕","","Kitakata-shi","Yamatomachi Iwabuchi",""]],
	"9694149":[[7,"喜多方市","山都町谷地","","Kitakata-shi","Yamatomachi Yachi",""]],
	"9694151":[[7,"喜多方市","山都町大山中","","Kitakata-shi","Yamatomachi Oyamanaka",""]],
	"9694152":[[7,"喜多方市","山都町上ノ山平","","Kitakata-shi","Yamatomachi Uenoyamataira",""]],
	"9694153":[[7,"喜多方市","山都町下殿戸","","Kitakata-shi","Yamatomachi Shimotonoto",""]],
	"9694154":[[7,"喜多方市","山都町舘原","","Kitakata-shi","Yamatomachi Tatenohara",""]],
	"9694155":[[7,"喜多方市","山都町入海","","Kitakata-shi","Yamatomachi Iriumi",""]],
	"9694156":[[7,"喜多方市","山都町西川","","Kitakata-shi","Yamatomachi Nishikawa",""]],
	"9694157":[[7,"喜多方市","山都町小松","","Kitakata-shi","Yamatomachi Komatsu",""]],
	"9694161":[[7,"喜多方市","山都町中石打場","","Kitakata-shi","Yamatomachi Nakaishiuchiba",""]],
	"9694162":[[7,"喜多方市","山都町上新田","","Kitakata-shi","Yamatomachi Kamishinden",""]],
	"9694163":[[7,"喜多方市","山都町下石打場","","Kitakata-shi","Yamatomachi Shimoishiuchiba",""]],
	"9694164":[[7,"喜多方市","山都町上石打場","","Kitakata-shi","Yamatomachi Kamiishiuchiba",""]],
	"9694165":[[7,"喜多方市","山都町三ツ山","","Kitakata-shi","Yamatomachi Mitsuyama",""]],
	"9694166":[[7,"喜多方市","山都町沢尻","","Kitakata-shi","Yamatomachi Sawajiri",""]],
	"9694167":[[7,"喜多方市","山都町大林","","Kitakata-shi","Yamatomachi Obayashi",""]],
	"9694301":[[7,"喜多方市","高郷町上郷","","Kitakata-shi","Takasatomachi Kamigo",""]],
	"9694302":[[7,"喜多方市","高郷町峯","","Kitakata-shi","Takasatomachi Mine",""]],
	"9694303":[[7,"喜多方市","高郷町揚津","","Kitakata-shi","Takasatomachi Agatsu",""]],
	"9694304":[[7,"喜多方市","高郷町磐見","","Kitakata-shi","Takasatomachi Iwami",""]],
	"9694311":[[7,"喜多方市","高郷町西羽賀","","Kitakata-shi","Takasatomachi Nishihaga",""]],
	"9694312":[[7,"喜多方市","高郷町池ノ原","","Kitakata-shi","Takasatomachi Ikenohara",""]],
	"9694313":[[7,"喜多方市","高郷町塩坪","","Kitakata-shi","Takasatomachi Shiotsubo",""]],
	"9694314":[[7,"喜多方市","高郷町川井","","Kitakata-shi","Takasatomachi Kawai",""]],
	"9694315":[[7,"喜多方市","高郷町夏井","","Kitakata-shi","Takasatomachi Natsui",""]],
	"9694316":[[7,"喜多方市","高郷町大田賀","","Kitakata-shi","Takasatomachi Otaga",""]],
	"9694400":[[7,"耶麻郡西会津町","","","Nishiaizu-machi, Yama-gun","",""]],
	"9694401":[[7,"耶麻郡西会津町","登世島","","Nishiaizu-machi, Yama-gun","Tosejima",""]],
	"9694402":[[7,"耶麻郡西会津町","尾野本","","Nishiaizu-machi, Yama-gun","Onomoto",""]],
	"9694403":[[7,"耶麻郡西会津町","束松","","Nishiaizu-machi, Yama-gun","Tabanematsu",""]],
	"9694404":[[7,"耶麻郡西会津町","睦合","","Nishiaizu-machi, Yama-gun","Mutsuai",""]],
	"9694405":[[7,"耶麻郡西会津町","下谷","","Nishiaizu-machi, Yama-gun","Shitatani",""]],
	"9694406":[[7,"耶麻郡西会津町","野沢","","Nishiaizu-machi, Yama-gun","Nozawa",""]],
	"9694511":[[7,"耶麻郡西会津町","群岡","","Nishiaizu-machi, Yama-gun","Muraoka",""]],
	"9694512":[[7,"耶麻郡西会津町","上野尻","","Nishiaizu-machi, Yama-gun","Kaminojiri",""]],
	"9694513":[[7,"耶麻郡西会津町","宝坂屋敷","","Nishiaizu-machi, Yama-gun","Hosaka Yashiki",""]],
	"9694514":[[7,"耶麻郡西会津町","宝坂宝坂","","Nishiaizu-machi, Yama-gun","Hosaka Hosaka",""]],
	"9694515":[[7,"耶麻郡西会津町","下野尻","","Nishiaizu-machi, Yama-gun","Shimonojiri",""]],
	"9694621":[[7,"耶麻郡西会津町","新郷冨士","","Nishiaizu-machi, Yama-gun","Shingo Fuji",""]],
	"9694622":[[7,"耶麻郡西会津町","新郷笹川","","Nishiaizu-machi, Yama-gun","Shingo Sasagawa",""]],
	"9694623":[[7,"耶麻郡西会津町","新郷豊洲","","Nishiaizu-machi, Yama-gun","Shingo Toyosu",""]],
	"9694624":[[7,"耶麻郡西会津町","新郷三河","","Nishiaizu-machi, Yama-gun","Shingo Mikawa",""]],
	"9694731":[[7,"耶麻郡西会津町","奥川飯根","","Nishiaizu-machi, Yama-gun","Okugawa Iine",""]],
	"9694732":[[7,"耶麻郡西会津町","奥川飯沢","","Nishiaizu-machi, Yama-gun","Okugawa Iizawa",""]],
	"9694733":[[7,"耶麻郡西会津町","奥川大綱木","","Nishiaizu-machi, Yama-gun","Okugawa Otsunagi",""]],
	"9694734":[[7,"耶麻郡西会津町","奥川飯里","","Nishiaizu-machi, Yama-gun","Okugawa Iisato",""]],
	"9694735":[[7,"耶麻郡西会津町","奥川豊島","","Nishiaizu-machi, Yama-gun","Okugawa Toyoshima",""]],
	"9694736":[[7,"耶麻郡西会津町","奥川元島","","Nishiaizu-machi, Yama-gun","Okugawa Motoshima",""]],
	"9694737":[[7,"耶麻郡西会津町","奥川高陽根","","Nishiaizu-machi, Yama-gun","Okugawa Kayane",""]],
	"9695111":[[7,"会津若松市","大戸町石村","","Aizuwakamatsu-shi","Otomachi Ishimura",""]],
	"9695112":[[7,"会津若松市","大戸町下雨屋","","Aizuwakamatsu-shi","Otomachi Shimoamaya",""]],
	"9695113":[[7,"会津若松市","大戸町宮内","","Aizuwakamatsu-shi","Otomachi Miyauchi",""]],
	"9695114":[[7,"会津若松市","大戸町上雨屋","","Aizuwakamatsu-shi","Otomachi Kamiamaya",""]],
	"9695121":[[7,"会津若松市","大戸町上三寄南原","","Aizuwakamatsu-shi","Otomachi Kamimiyoriminamihara",""]],
	"9695122":[[7,"会津若松市","大戸町上三寄乙","","Aizuwakamatsu-shi","Otomachi Kamimiyoriotsu",""],[7,"会津若松市","大戸町上三寄香塩","","Aizuwakamatsu-shi","Otomachi Kamimiyorikashu",""]],
	"9695123":[[7,"会津若松市","大戸町上三寄大豆田","","Aizuwakamatsu-shi","Otomachi Kamimiyoriomameta",""],[7,"会津若松市","大戸町上三寄丙","","Aizuwakamatsu-shi","Otomachi Kamimiyorihei",""]],
	"9695131":[[7,"会津若松市","大戸町高川","","Aizuwakamatsu-shi","Otomachi Takagawa",""]],
	"9695132":[[7,"会津若松市","大戸町上小塩","","Aizuwakamatsu-shi","Otomachi Kamioshu",""]],
	"9695133":[[7,"会津若松市","大戸町大川","","Aizuwakamatsu-shi","Otomachi Okawa",""]],
	"9695141":[[7,"会津若松市","大戸町小谷川端","","Aizuwakamatsu-shi","Otomachi Oyakawabata",""]],
	"9695142":[[7,"会津若松市","大戸町小谷坂下","","Aizuwakamatsu-shi","Otomachi Oyasakanoshita",""]],
	"9695143":[[7,"会津若松市","大戸町小谷原","","Aizuwakamatsu-shi","Otomachi Oyahara",""]],
	"9695144":[[7,"会津若松市","大戸町小谷西村","","Aizuwakamatsu-shi","Otomachi Oyanishimura",""]],
	"9695145":[[7,"会津若松市","大戸町小谷平沢","","Aizuwakamatsu-shi","Otomachi Oyahirasawa",""]],
	"9695146":[[7,"会津若松市","大戸町小谷湯ノ平","","Aizuwakamatsu-shi","Otomachi Oyayunodaira",""]],
	"9695147":[[7,"会津若松市","大戸町芦牧","","Aizuwakamatsu-shi","Otomachi Ashinomaki",""]],
	"9695201":[[7,"南会津郡下郷町","高陦","","Shimogo-machi, Minamiaizu-gun","Takashima",""]],
	"9695202":[[7,"南会津郡下郷町","枝松","","Shimogo-machi, Minamiaizu-gun","Edamatsu",""]],
	"9695203":[[7,"南会津郡下郷町","白岩","","Shimogo-machi, Minamiaizu-gun","Shiraiwa",""]],
	"9695204":[[7,"南会津郡下郷町","弥五島","","Shimogo-machi, Minamiaizu-gun","Yagoshima",""]],
	"9695205":[[7,"南会津郡下郷町","大沢","","Shimogo-machi, Minamiaizu-gun","Osawa",""]],
	"9695206":[[7,"南会津郡下郷町","湯野上","","Shimogo-machi, Minamiaizu-gun","Yunokami",""]],
	"9695207":[[7,"南会津郡下郷町","大内","","Shimogo-machi, Minamiaizu-gun","Ouchi",""]],
	"9695208":[[7,"南会津郡下郷町","小沼崎","","Shimogo-machi, Minamiaizu-gun","Onumazaki",""]],
	"9695300":[[7,"南会津郡下郷町","","","Shimogo-machi, Minamiaizu-gun","",""]],
	"9695311":[[7,"南会津郡下郷町","豊成","","Shimogo-machi, Minamiaizu-gun","Toyonari",""]],
	"9695312":[[7,"南会津郡下郷町","戸赤","","Shimogo-machi, Minamiaizu-gun","Toaka",""]],
	"9695313":[[7,"南会津郡下郷町","原","","Shimogo-machi, Minamiaizu-gun","Hara",""]],
	"9695314":[[7,"南会津郡下郷町","日影","","Shimogo-machi, Minamiaizu-gun","Hikage",""]],
	"9695315":[[7,"南会津郡下郷町","荒石","","Shimogo-machi, Minamiaizu-gun","Araishi",""]],
	"9695316":[[7,"南会津郡下郷町","石井","","Shimogo-machi, Minamiaizu-gun","Ishii",""]],
	"9695317":[[7,"南会津郡下郷町","志源行","","Shimogo-machi, Minamiaizu-gun","Shigengyo",""]],
	"9695318":[[7,"南会津郡下郷町","磯上","","Shimogo-machi, Minamiaizu-gun","Isogami",""]],
	"9695321":[[7,"南会津郡下郷町","沢口","","Shimogo-machi, Minamiaizu-gun","Sawaguchi",""]],
	"9695322":[[7,"南会津郡下郷町","領毛","","Shimogo-machi, Minamiaizu-gun","Ryoge",""]],
	"9695323":[[7,"南会津郡下郷町","桑取火","","Shimogo-machi, Minamiaizu-gun","Kuwatobi",""]],
	"9695324":[[7,"南会津郡下郷町","安張","","Shimogo-machi, Minamiaizu-gun","Yasuhari",""]],
	"9695325":[[7,"南会津郡下郷町","中山","","Shimogo-machi, Minamiaizu-gun","Nakayama",""]],
	"9695326":[[7,"南会津郡下郷町","栄富","","Shimogo-machi, Minamiaizu-gun","Eitomi",""]],
	"9695331":[[7,"南会津郡下郷町","澳田","","Shimogo-machi, Minamiaizu-gun","Ikuta",""]],
	"9695332":[[7,"南会津郡下郷町","中妻","","Shimogo-machi, Minamiaizu-gun","Nakazuma",""]],
	"9695333":[[7,"南会津郡下郷町","合川","","Shimogo-machi, Minamiaizu-gun","Aikawa",""]],
	"9695334":[[7,"南会津郡下郷町","大松川","","Shimogo-machi, Minamiaizu-gun","Omatsukawa",""]],
	"9695335":[[7,"南会津郡下郷町","南倉沢","","Shimogo-machi, Minamiaizu-gun","Nagurasawa",""]],
	"9695341":[[7,"南会津郡下郷町","野際新田","","Shimogo-machi, Minamiaizu-gun","Nogiwashinden",""]],
	"9695342":[[7,"南会津郡下郷町","音金","","Shimogo-machi, Minamiaizu-gun","Otokane",""]],
	"9695343":[[7,"南会津郡下郷町","落合","","Shimogo-machi, Minamiaizu-gun","Ochiai",""]],
	"9695344":[[7,"南会津郡下郷町","沢田","","Shimogo-machi, Minamiaizu-gun","Sawada",""]],
	"9695345":[[7,"南会津郡下郷町","塩生","","Shimogo-machi, Minamiaizu-gun","Shiono",""]],
	"9696001":[[7,"会津若松市","北会津町天満","","Aizuwakamatsu-shi","Kitaaizumachi Temman",""]],
	"9696002":[[7,"会津若松市","北会津町麻生新田","","Aizuwakamatsu-shi","Kitaaizumachi Asoshinden",""]],
	"9696003":[[7,"会津若松市","北会津町西麻生","","Aizuwakamatsu-shi","Kitaaizumachi Nishiaso",""]],
	"9696004":[[7,"会津若松市","北会津町古麻生","","Aizuwakamatsu-shi","Kitaaizumachi Furuaso",""]],
	"9696005":[[7,"会津若松市","北会津町松野","","Aizuwakamatsu-shi","Kitaaizumachi Matsuno",""]],
	"9696006":[[7,"会津若松市","北会津町新在家","","Aizuwakamatsu-shi","Kitaaizumachi Shinzaike",""]],
	"9696007":[[7,"会津若松市","北会津町北後庵","","Aizuwakamatsu-shi","Kitaaizumachi Kitagoan",""]],
	"9696008":[[7,"会津若松市","北会津町大島","","Aizuwakamatsu-shi","Kitaaizumachi Oshima",""]],
	"9696011":[[7,"会津若松市","北会津町西後庵","","Aizuwakamatsu-shi","Kitaaizumachi Nishigoan",""]],
	"9696012":[[7,"会津若松市","北会津町金屋","","Aizuwakamatsu-shi","Kitaaizumachi Kanaya",""]],
	"9696013":[[7,"会津若松市","北会津町下野","","Aizuwakamatsu-shi","Kitaaizumachi Shimono",""]],
	"9696015":[[7,"会津若松市","北会津町水季の里","","Aizuwakamatsu-shi","Kitaaizumachi Mizukinosato",""]],
	"9696021":[[7,"大沼郡会津美里町","舘ノ廻甲","","Aizumisato-machi, Onuma-gun","Tatenomawariko",""]],
	"9696022":[[7,"大沼郡会津美里町","大道上甲","","Aizumisato-machi, Onuma-gun","Omichikamiko",""]],
	"9696023":[[7,"大沼郡会津美里町","近右エ門田","","Aizumisato-machi, Onuma-gun","Konuemonden",""]],
	"9696024":[[7,"大沼郡会津美里町","川原町北甲","","Aizumisato-machi, Onuma-gun","Kawarachokitako",""]],
	"9696025":[[7,"大沼郡会津美里町","権現堂甲","","Aizumisato-machi, Onuma-gun","Gongendoko",""]],
	"9696026":[[7,"大沼郡会津美里町","本郷前川原甲","","Aizumisato-machi, Onuma-gun","Hongomaekawaharako",""]],
	"9696027":[[7,"大沼郡会津美里町","荒井甲","","Aizumisato-machi, Onuma-gun","Araiko",""]],
	"9696028":[[7,"大沼郡会津美里町","旱泥甲","","Aizumisato-machi, Onuma-gun","Hidoroko",""]],
	"9696029":[[7,"大沼郡会津美里町","三本松甲","","Aizumisato-machi, Onuma-gun","Sambommatsuko",""]],
	"9696031":[[7,"大沼郡会津美里町","広面","","Aizumisato-machi, Onuma-gun","Hirozura",""]],
	"9696032":[[7,"大沼郡会津美里町","竹原","","Aizumisato-machi, Onuma-gun","Takehara",""]],
	"9696033":[[7,"大沼郡会津美里町","堰向","","Aizumisato-machi, Onuma-gun","Sekimukai",""]],
	"9696034":[[7,"大沼郡会津美里町","堰向甲","","Aizumisato-machi, Onuma-gun","Sekimukaiko",""]],
	"9696035":[[7,"大沼郡会津美里町","中樋","","Aizumisato-machi, Onuma-gun","Nakatoi",""]],
	"9696036":[[7,"大沼郡会津美里町","上野川原","","Aizumisato-machi, Onuma-gun","Uenokawara",""]],
	"9696037":[[7,"大沼郡会津美里町","家西甲","","Aizumisato-machi, Onuma-gun","Ienishiko",""]],
	"9696038":[[7,"大沼郡会津美里町","御用地甲","","Aizumisato-machi, Onuma-gun","Goyochiko",""]],
	"9696041":[[7,"大沼郡会津美里町","川原町","","Aizumisato-machi, Onuma-gun","Kawaracho",""]],
	"9696042":[[7,"大沼郡会津美里町","瀬戸町甲","","Aizumisato-machi, Onuma-gun","Setomachiko",""]],
	"9696043":[[7,"大沼郡会津美里町","松原際甲","","Aizumisato-machi, Onuma-gun","Matsubaragiwako",""]],
	"9696044":[[7,"大沼郡会津美里町","瀬戸屋前","","Aizumisato-machi, Onuma-gun","Setoyamae",""]],
	"9696045":[[7,"大沼郡会津美里町","北浦甲","","Aizumisato-machi, Onuma-gun","Kitaurako",""]],
	"9696046":[[7,"大沼郡会津美里町","石切畑甲","","Aizumisato-machi, Onuma-gun","Ishikiribatako",""]],
	"9696047":[[7,"大沼郡会津美里町","北川原甲","","Aizumisato-machi, Onuma-gun","Kitagawarako",""]],
	"9696051":[[7,"大沼郡会津美里町","思堀","","Aizumisato-machi, Onuma-gun","Omoibori",""]],
	"9696052":[[7,"大沼郡会津美里町","黒川","","Aizumisato-machi, Onuma-gun","Kurokawa",""]],
	"9696053":[[7,"大沼郡会津美里町","仲塚甲","","Aizumisato-machi, Onuma-gun","Nakazukako",""]],
	"9696054":[[7,"大沼郡会津美里町","惣印南","","Aizumisato-machi, Onuma-gun","Soimminami",""]],
	"9696055":[[7,"大沼郡会津美里町","惣印甲","","Aizumisato-machi, Onuma-gun","Soinko",""]],
	"9696056":[[7,"大沼郡会津美里町","惣印東","","Aizumisato-machi, Onuma-gun","Soinhigashi",""]],
	"9696057":[[7,"大沼郡会津美里町","大川端甲","","Aizumisato-machi, Onuma-gun","Okawabatako",""]],
	"9696058":[[7,"大沼郡会津美里町","的場甲","","Aizumisato-machi, Onuma-gun","Matobako",""]],
	"9696059":[[7,"大沼郡会津美里町","六日町甲","","Aizumisato-machi, Onuma-gun","Muikamachiko",""]],
	"9696061":[[7,"大沼郡会津美里町","上町甲","","Aizumisato-machi, Onuma-gun","Uwamachiko",""]],
	"9696062":[[7,"大沼郡会津美里町","御用地","","Aizumisato-machi, Onuma-gun","Goyochi",""]],
	"9696063":[[7,"大沼郡会津美里町","御用地跡甲","","Aizumisato-machi, Onuma-gun","Goyochiatoko",""]],
	"9696064":[[7,"大沼郡会津美里町","向川原","","Aizumisato-machi, Onuma-gun","Mukaigawara",""]],
	"9696065":[[7,"大沼郡会津美里町","本郷入口道上甲","","Aizumisato-machi, Onuma-gun","Hongoiriguchimichiueko",""]],
	"9696066":[[7,"大沼郡会津美里町","本郷入口中道上甲","","Aizumisato-machi, Onuma-gun","Hongoiriguchinakamichiueko",""]],
	"9696067":[[7,"大沼郡会津美里町","梁場上甲","","Aizumisato-machi, Onuma-gun","Yanabakamiko",""]],
	"9696068":[[7,"大沼郡会津美里町","車川原甲","","Aizumisato-machi, Onuma-gun","Kurumagawarako",""]],
	"9696069":[[7,"大沼郡会津美里町","船場甲","","Aizumisato-machi, Onuma-gun","Funabako",""]],
	"9696071":[[7,"大沼郡会津美里町","本郷上","","Aizumisato-machi, Onuma-gun","Hongokami",""]],
	"9696072":[[7,"大沼郡会津美里町","真々川甲","","Aizumisato-machi, Onuma-gun","Mamakawako",""]],
	"9696073":[[7,"大沼郡会津美里町","寺ノ前甲","","Aizumisato-machi, Onuma-gun","Teranomaeko",""]],
	"9696074":[[7,"大沼郡会津美里町","中道下甲","","Aizumisato-machi, Onuma-gun","Nakamichishitako",""]],
	"9696075":[[7,"大沼郡会津美里町","本郷道東","","Aizumisato-machi, Onuma-gun","Hongomichihigashi",""]],
	"9696076":[[7,"大沼郡会津美里町","本郷道東甲","","Aizumisato-machi, Onuma-gun","Hongomichihigashiko",""]],
	"9696077":[[7,"大沼郡会津美里町","東谷地甲","","Aizumisato-machi, Onuma-gun","Higashiyachiko",""]],
	"9696078":[[7,"大沼郡会津美里町","蛭ケ窪","","Aizumisato-machi, Onuma-gun","Hirugakubo",""]],
	"9696079":[[7,"大沼郡会津美里町","三日町甲","","Aizumisato-machi, Onuma-gun","Mikkamachiko",""]],
	"9696081":[[7,"大沼郡会津美里町","三日町上","","Aizumisato-machi, Onuma-gun","Mikkamachiue",""]],
	"9696082":[[7,"大沼郡会津美里町","三日町上甲","","Aizumisato-machi, Onuma-gun","Mikkamachiueko",""]],
	"9696083":[[7,"大沼郡会津美里町","三日町道上甲","","Aizumisato-machi, Onuma-gun","Mikkamachimichiueko",""]],
	"9696084":[[7,"大沼郡会津美里町","本郷高田町甲","","Aizumisato-machi, Onuma-gun","Hongotakadamachiko",""]],
	"9696085":[[7,"大沼郡会津美里町","西谷地","","Aizumisato-machi, Onuma-gun","Nishiyachi",""]],
	"9696086":[[7,"大沼郡会津美里町","西谷地甲","","Aizumisato-machi, Onuma-gun","Nishiyachiko",""]],
	"9696087":[[7,"大沼郡会津美里町","本郷道西","","Aizumisato-machi, Onuma-gun","Hongomichinishi",""]],
	"9696101":[[7,"大沼郡会津美里町","駅前","","Aizumisato-machi, Onuma-gun","Ekimae",""]],
	"9696102":[[7,"大沼郡会津美里町","思堀向","","Aizumisato-machi, Onuma-gun","Omoiborimukai",""]],
	"9696103":[[7,"大沼郡会津美里町","上村北","","Aizumisato-machi, Onuma-gun","Kamimurakita",""]],
	"9696104":[[7,"大沼郡会津美里町","上村西道上","","Aizumisato-machi, Onuma-gun","Kamimuranishimichikami",""],[7,"大沼郡会津美里町","上村西道下","","Aizumisato-machi, Onuma-gun","Kamimuranishimichishita",""]],
	"9696105":[[7,"大沼郡会津美里町","上村東","","Aizumisato-machi, Onuma-gun","Kamimurahigashi",""],[7,"大沼郡会津美里町","上村南","","Aizumisato-machi, Onuma-gun","Kamimuraminami",""]],
	"9696106":[[7,"大沼郡会津美里町","黒川内","","Aizumisato-machi, Onuma-gun","Kurokawauchi",""]],
	"9696107":[[7,"大沼郡会津美里町","新用地","","Aizumisato-machi, Onuma-gun","Shinyochi",""]],
	"9696108":[[7,"大沼郡会津美里町","堰下","","Aizumisato-machi, Onuma-gun","Sekishita",""]],
	"9696109":[[7,"大沼郡会津美里町","宗頤町","","Aizumisato-machi, Onuma-gun","Soemmachi",""]],
	"9696111":[[7,"大沼郡会津美里町","家西","","Aizumisato-machi, Onuma-gun","Ienishi",""]],
	"9696112":[[7,"大沼郡会津美里町","家東甲","","Aizumisato-machi, Onuma-gun","Iehigashiko",""]],
	"9696113":[[7,"大沼郡会津美里町","車川原","","Aizumisato-machi, Onuma-gun","Kurumagawara",""]],
	"9696114":[[7,"大沼郡会津美里町","御用地跡","","Aizumisato-machi, Onuma-gun","Goyochiato",""]],
	"9696115":[[7,"大沼郡会津美里町","新町","","Aizumisato-machi, Onuma-gun","Shincho",""]],
	"9696116":[[7,"大沼郡会津美里町","瀬戸町","","Aizumisato-machi, Onuma-gun","Setomachi",""]],
	"9696117":[[7,"大沼郡会津美里町","本郷入口道上","","Aizumisato-machi, Onuma-gun","Hongoirikuchimichikami",""]],
	"9696118":[[7,"大沼郡会津美里町","仲塚","","Aizumisato-machi, Onuma-gun","Nakatsuka",""],[7,"大沼郡会津美里町","向川原甲","","Aizumisato-machi, Onuma-gun","Mukaikawaharako",""]],
	"9696119":[[7,"大沼郡会津美里町","梁場上","","Aizumisato-machi, Onuma-gun","Yanabakami",""]],
	"9696121":[[7,"大沼郡会津美里町","延命寺前","","Aizumisato-machi, Onuma-gun","Emmeijimae",""]],
	"9696122":[[7,"大沼郡会津美里町","寺ノ前","","Aizumisato-machi, Onuma-gun","Teranomae",""]],
	"9696123":[[7,"大沼郡会津美里町","中道下","","Aizumisato-machi, Onuma-gun","Nakamichishita",""]],
	"9696124":[[7,"大沼郡会津美里町","東谷地","","Aizumisato-machi, Onuma-gun","Higashiyachi",""]],
	"9696125":[[7,"大沼郡会津美里町","本郷","","Aizumisato-machi, Onuma-gun","Hongo",""]],
	"9696126":[[7,"大沼郡会津美里町","本郷甲","","Aizumisato-machi, Onuma-gun","Hongoko",""]],
	"9696127":[[7,"大沼郡会津美里町","本郷上甲","","Aizumisato-machi, Onuma-gun","Hongokamiko",""]],
	"9696128":[[7,"大沼郡会津美里町","真々川","","Aizumisato-machi, Onuma-gun","Mamakawa",""]],
	"9696129":[[7,"大沼郡会津美里町","本郷道西甲","","Aizumisato-machi, Onuma-gun","Hongomichinishiko",""]],
	"9696131":[[7,"大沼郡会津美里町","大石","","Aizumisato-machi, Onuma-gun","Oishi",""]],
	"9696132":[[7,"大沼郡会津美里町","本郷高田町","","Aizumisato-machi, Onuma-gun","Hongotakadamachi",""]],
	"9696133":[[7,"大沼郡会津美里町","船場","","Aizumisato-machi, Onuma-gun","Funaba",""]],
	"9696134":[[7,"大沼郡会津美里町","三日町","","Aizumisato-machi, Onuma-gun","Mikkamachi",""]],
	"9696135":[[7,"大沼郡会津美里町","穂馬","","Aizumisato-machi, Onuma-gun","Homa",""]],
	"9696141":[[7,"大沼郡会津美里町","大八郷","","Aizumisato-machi, Onuma-gun","Ohachigo",""]],
	"9696142":[[7,"大沼郡会津美里町","村上","","Aizumisato-machi, Onuma-gun","Murakami",""]],
	"9696143":[[7,"大沼郡会津美里町","氷玉","","Aizumisato-machi, Onuma-gun","Hidama",""]],
	"9696144":[[7,"大沼郡会津美里町","福重岡","","Aizumisato-machi, Onuma-gun","Fukueoka",""]],
	"9696145":[[7,"大沼郡会津美里町","山南","","Aizumisato-machi, Onuma-gun","Yamaminami",""]],
	"9696146":[[7,"大沼郡会津美里町","横堀下","","Aizumisato-machi, Onuma-gun","Yokoborishita",""]],
	"9696151":[[7,"大沼郡会津美里町","石切畑","","Aizumisato-machi, Onuma-gun","Ishikiribatake",""]],
	"9696152":[[7,"大沼郡会津美里町","川原町甲","","Aizumisato-machi, Onuma-gun","Kawarachoko",""]],
	"9696154":[[7,"大沼郡会津美里町","北浦","","Aizumisato-machi, Onuma-gun","Kitaura",""]],
	"9696155":[[7,"大沼郡会津美里町","北川原","","Aizumisato-machi, Onuma-gun","Kitagawara",""]],
	"9696156":[[7,"大沼郡会津美里町","瀬戸屋前甲","","Aizumisato-machi, Onuma-gun","Setoyamaeko",""]],
	"9696157":[[7,"大沼郡会津美里町","本屋敷","","Aizumisato-machi, Onuma-gun","Motoyashiki",""]],
	"9696158":[[7,"大沼郡会津美里町","松原際","","Aizumisato-machi, Onuma-gun","Matsubarakiwa",""]],
	"9696159":[[7,"大沼郡会津美里町","川原町北","","Aizumisato-machi, Onuma-gun","Kawaharachokita",""]],
	"9696161":[[7,"大沼郡会津美里町","荒井前","","Aizumisato-machi, Onuma-gun","Araimae",""]],
	"9696162":[[7,"大沼郡会津美里町","杉","","Aizumisato-machi, Onuma-gun","Sugi",""]],
	"9696163":[[7,"大沼郡会津美里町","黒沢","","Aizumisato-machi, Onuma-gun","Kurosawa",""]],
	"9696164":[[7,"大沼郡会津美里町","本郷道上","","Aizumisato-machi, Onuma-gun","Hongomichikami",""]],
	"9696165":[[7,"大沼郡会津美里町","山道下","","Aizumisato-machi, Onuma-gun","Yamamichishita",""]],
	"9696166":[[7,"大沼郡会津美里町","下川原","","Aizumisato-machi, Onuma-gun","Shimogawara",""]],
	"9696171":[[7,"大沼郡会津美里町","荒井","","Aizumisato-machi, Onuma-gun","Arai",""]],
	"9696172":[[7,"大沼郡会津美里町","本郷村西","","Aizumisato-machi, Onuma-gun","Hongomuranishi",""]],
	"9696173":[[7,"大沼郡会津美里町","大道上","","Aizumisato-machi, Onuma-gun","Omichikami",""]],
	"9696174":[[7,"大沼郡会津美里町","権現堂","","Aizumisato-machi, Onuma-gun","Gongendo",""]],
	"9696175":[[7,"大沼郡会津美里町","舘ノ廻","","Aizumisato-machi, Onuma-gun","Tatenomawari",""]],
	"9696176":[[7,"大沼郡会津美里町","旱泥","","Aizumisato-machi, Onuma-gun","Hidoro",""]],
	"9696177":[[7,"大沼郡会津美里町","本郷前川原","","Aizumisato-machi, Onuma-gun","Hongomaekawahara",""]],
	"9696180":[[7,"会津若松市","北会津町両堂","","Aizuwakamatsu-shi","Kitaaizumachi Ryodo",""]],
	"9696182":[[7,"会津若松市","北会津町柏原","","Aizuwakamatsu-shi","Kitaaizumachi Kashiwabara",""]],
	"9696183":[[7,"会津若松市","北会津町上米塚","","Aizuwakamatsu-shi","Kitaaizumachi Kamiyonezuka",""]],
	"9696184":[[7,"会津若松市","北会津町三本松","","Aizuwakamatsu-shi","Kitaaizumachi Sambommatsu",""]],
	"9696185":[[7,"会津若松市","北会津町下米塚","","Aizuwakamatsu-shi","Kitaaizumachi Shimoyonezuka",""]],
	"9696186":[[7,"会津若松市","北会津町古館","","Aizuwakamatsu-shi","Kitaaizumachi Furudate",""]],
	"9696188":[[7,"会津若松市","北会津町東小松","","Aizuwakamatsu-shi","Kitaaizumachi Higashikomatsu",""]],
	"9696189":[[7,"会津若松市","北会津町小松","","Aizuwakamatsu-shi","Kitaaizumachi Komatsu",""]],
	"9696200":[[7,"大沼郡会津美里町","","","Aizumisato-machi, Onuma-gun","",""]],
	"9696201":[[7,"大沼郡会津美里町","安田","","Aizumisato-machi, Onuma-gun","Yasuda",""],[7,"大沼郡会津美里町","安田乙","","Aizumisato-machi, Onuma-gun","Yasudaotsu",""]],
	"9696202":[[7,"大沼郡会津美里町","高田村東","","Aizumisato-machi, Onuma-gun","Takadamurahigashi",""],[7,"大沼郡会津美里町","村前","","Aizumisato-machi, Onuma-gun","Muramae",""]],
	"9696203":[[7,"大沼郡会津美里町","高田前川原","","Aizumisato-machi, Onuma-gun","Takadamaekawahara",""],[7,"大沼郡会津美里町","水戸","","Aizumisato-machi, Onuma-gun","Mito",""]],
	"9696204":[[7,"大沼郡会津美里町","台ノ下","","Aizumisato-machi, Onuma-gun","Dainoshita",""],[7,"大沼郡会津美里町","宮ノ腰","","Aizumisato-machi, Onuma-gun","Miyanokoshi",""]],
	"9696205":[[7,"大沼郡会津美里町","御田","","Aizumisato-machi, Onuma-gun","Onta",""]],
	"9696206":[[7,"大沼郡会津美里町","家ノ下","","Aizumisato-machi, Onuma-gun","Ienoshita",""],[7,"大沼郡会津美里町","坂ノ下道上","","Aizumisato-machi, Onuma-gun","Sakanoshitamichiue",""],[7,"大沼郡会津美里町","坂ノ下道下","","Aizumisato-machi, Onuma-gun","Sakanoshitamichishita",""],[7,"大沼郡会津美里町","坂ノ下道下甲","","Aizumisato-machi, Onuma-gun","Sakanoshitamichishitako",""],[7,"大沼郡会津美里町","佐布川","","Aizumisato-machi, Onuma-gun","Sabukawa",""],[7,"大沼郡会津美里町","高田中川原道下","","Aizumisato-machi, Onuma-gun","Takadanakagawaramichishita",""],[7,"大沼郡会津美里町","松木田","","Aizumisato-machi, Onuma-gun","Matsukida",""],[7,"大沼郡会津美里町","葭添","","Aizumisato-machi, Onuma-gun","Yoshizoe",""]],
	"9696207":[[7,"大沼郡会津美里町","宮里","","Aizumisato-machi, Onuma-gun","Miyazato",""]],
	"9696211":[[7,"大沼郡会津美里町","橋丸","","Aizumisato-machi, Onuma-gun","Hashimaru",""]],
	"9696212":[[7,"大沼郡会津美里町","藤家館","","Aizumisato-machi, Onuma-gun","Fujiietate",""]],
	"9696213":[[7,"大沼郡会津美里町","勝原","","Aizumisato-machi, Onuma-gun","Katsuhara",""]],
	"9696214":[[7,"大沼郡会津美里町","冨川","","Aizumisato-machi, Onuma-gun","Tomikawa",""]],
	"9696215":[[7,"大沼郡会津美里町","下堀","","Aizumisato-machi, Onuma-gun","Shimohori",""]],
	"9696221":[[7,"大沼郡会津美里町","旭館端","","Aizumisato-machi, Onuma-gun","Asahitatehata",""]],
	"9696222":[[7,"大沼郡会津美里町","旭市川","","Aizumisato-machi, Onuma-gun","Asahiichikawa",""]],
	"9696223":[[7,"大沼郡会津美里町","旭寺入","","Aizumisato-machi, Onuma-gun","Asahiterairi",""]],
	"9696224":[[7,"大沼郡会津美里町","旭無量","","Aizumisato-machi, Onuma-gun","Asahimuryo",""]],
	"9696225":[[7,"大沼郡会津美里町","旭三寄","","Aizumisato-machi, Onuma-gun","Asahimiyose",""]],
	"9696226":[[7,"大沼郡会津美里町","旭杉原","","Aizumisato-machi, Onuma-gun","Asahisugihara",""]],
	"9696231":[[7,"大沼郡会津美里町","尾岐窪","","Aizumisato-machi, Onuma-gun","Omatakubo",""]],
	"9696232":[[7,"大沼郡会津美里町","東尾岐","","Aizumisato-machi, Onuma-gun","Higashiomata",""]],
	"9696241":[[7,"大沼郡会津美里町","吉田","","Aizumisato-machi, Onuma-gun","Yoshida",""]],
	"9696242":[[7,"大沼郡会津美里町","大室","","Aizumisato-machi, Onuma-gun","Omuro",""]],
	"9696243":[[7,"大沼郡会津美里町","宮川","","Aizumisato-machi, Onuma-gun","Miyakawa",""]],
	"9696244":[[7,"大沼郡会津美里町","西尾","","Aizumisato-machi, Onuma-gun","Nishio",""]],
	"9696245":[[7,"大沼郡会津美里町","西本","","Aizumisato-machi, Onuma-gun","Nishimoto",""]],
	"9696251":[[7,"大沼郡会津美里町","永井野","","Aizumisato-machi, Onuma-gun","Nagaino",""]],
	"9696252":[[7,"大沼郡会津美里町","松岸","","Aizumisato-machi, Onuma-gun","Matsukishi",""]],
	"9696253":[[7,"大沼郡会津美里町","杉屋","","Aizumisato-machi, Onuma-gun","Sugiya",""]],
	"9696254":[[7,"大沼郡会津美里町","荻窪","","Aizumisato-machi, Onuma-gun","Ogikubo",""]],
	"9696255":[[7,"大沼郡会津美里町","松沢","","Aizumisato-machi, Onuma-gun","Matsuzawa",""]],
	"9696256":[[7,"大沼郡会津美里町","上戸原","","Aizumisato-machi, Onuma-gun","Jodohara",""]],
	"9696261":[[7,"大沼郡会津美里町","内川原","","Aizumisato-machi, Onuma-gun","Uchikawara",""],[7,"大沼郡会津美里町","梅ノ木","","Aizumisato-machi, Onuma-gun","Umenoki",""],[7,"大沼郡会津美里町","権現宮","","Aizumisato-machi, Onuma-gun","Gongemmiya",""],[7,"大沼郡会津美里町","権現宮甲","","Aizumisato-machi, Onuma-gun","Gongemmiyako",""],[7,"大沼郡会津美里町","権現宮南","","Aizumisato-machi, Onuma-gun","Gongemmiyaminami",""],[7,"大沼郡会津美里町","権現宮南甲","","Aizumisato-machi, Onuma-gun","Gongemmiyaminamiko",""],[7,"大沼郡会津美里町","高田道上","","Aizumisato-machi, Onuma-gun","Takadamichiue",""],[7,"大沼郡会津美里町","地尻","","Aizumisato-machi, Onuma-gun","Chijiri",""],[7,"大沼郡会津美里町","東川原","","Aizumisato-machi, Onuma-gun","Higashikawara",""]],
	"9696262":[[7,"大沼郡会津美里町","鹿島","","Aizumisato-machi, Onuma-gun","Kashima",""],[7,"大沼郡会津美里町","観音北","","Aizumisato-machi, Onuma-gun","Kannonkita",""],[7,"大沼郡会津美里町","外川原","","Aizumisato-machi, Onuma-gun","Sotokawara",""],[7,"大沼郡会津美里町","外川原甲","","Aizumisato-machi, Onuma-gun","Sotokawarako",""],[7,"大沼郡会津美里町","法憧寺北","","Aizumisato-machi, Onuma-gun","Hodojikita",""],[7,"大沼郡会津美里町","法憧寺北甲","","Aizumisato-machi, Onuma-gun","Hodojikitako",""],[7,"大沼郡会津美里町","法憧寺東","","Aizumisato-machi, Onuma-gun","Hodojihigashi",""],[7,"大沼郡会津美里町","法憧寺南","","Aizumisato-machi, Onuma-gun","Hodojiminami",""],[7,"大沼郡会津美里町","法憧寺南甲","","Aizumisato-machi, Onuma-gun","Hodojiminamiko",""]],
	"9696263":[[7,"大沼郡会津美里町","清竜寺北","","Aizumisato-machi, Onuma-gun","Seiryujikita",""],[7,"大沼郡会津美里町","宮北","","Aizumisato-machi, Onuma-gun","Miyakita",""],[7,"大沼郡会津美里町","宮林","","Aizumisato-machi, Onuma-gun","Miyabayashi",""],[7,"大沼郡会津美里町","宮林甲","","Aizumisato-machi, Onuma-gun","Miyabayashiko",""],[7,"大沼郡会津美里町","文珠西","","Aizumisato-machi, Onuma-gun","Monjunishi",""],[7,"大沼郡会津美里町","文珠東","","Aizumisato-machi, Onuma-gun","Monjuhigashi",""]],
	"9696264":[[7,"大沼郡会津美里町","高田","","Aizumisato-machi, Onuma-gun","Takada",""],[7,"大沼郡会津美里町","高田乙","","Aizumisato-machi, Onuma-gun","Takadaotsu",""],[7,"大沼郡会津美里町","高田甲","","Aizumisato-machi, Onuma-gun","Takadako",""]],
	"9696265":[[7,"大沼郡会津美里町","漆原北","","Aizumisato-machi, Onuma-gun","Urushiwarakita",""],[7,"大沼郡会津美里町","御蔵南","","Aizumisato-machi, Onuma-gun","Okuraminami",""],[7,"大沼郡会津美里町","川添","","Aizumisato-machi, Onuma-gun","Kawazoe",""],[7,"大沼郡会津美里町","館南","","Aizumisato-machi, Onuma-gun","Tateminami",""],[7,"大沼郡会津美里町","長光寺南","","Aizumisato-machi, Onuma-gun","Chokojiminami",""],[7,"大沼郡会津美里町","六地蔵","","Aizumisato-machi, Onuma-gun","Rokujizo",""]],
	"9696266":[[7,"大沼郡会津美里町","油田","","Aizumisato-machi, Onuma-gun","Aburaden",""],[7,"大沼郡会津美里町","新丁屋敷","","Aizumisato-machi, Onuma-gun","Shinchoyashiki",""],[7,"大沼郡会津美里町","館ノ越","","Aizumisato-machi, Onuma-gun","Tatenokoshi",""],[7,"大沼郡会津美里町","西裏屋敷添","","Aizumisato-machi, Onuma-gun","Nishiurayashikizoe",""],[7,"大沼郡会津美里町","布才地","","Aizumisato-machi, Onuma-gun","Fusaichi",""],[7,"大沼郡会津美里町","竜興寺北","","Aizumisato-machi, Onuma-gun","Ryukojikita",""]],
	"9696267":[[7,"大沼郡会津美里町","新丁西","","Aizumisato-machi, Onuma-gun","Shinchonishi",""],[7,"大沼郡会津美里町","西裏","","Aizumisato-machi, Onuma-gun","Nishiura",""]],
	"9696268":[[7,"大沼郡会津美里町","谷地","","Aizumisato-machi, Onuma-gun","Yachi",""],[7,"大沼郡会津美里町","谷地前","","Aizumisato-machi, Onuma-gun","Yachimae",""],[7,"大沼郡会津美里町","柳台","","Aizumisato-machi, Onuma-gun","Yanagidai",""],[7,"大沼郡会津美里町","柳台甲","","Aizumisato-machi, Onuma-gun","Yanagidaiko",""]],
	"9696271":[[7,"大沼郡会津美里町","寺崎","","Aizumisato-machi, Onuma-gun","Terasaki",""],[7,"大沼郡会津美里町","沼ノ上","","Aizumisato-machi, Onuma-gun","Numanoe",""]],
	"9696272":[[7,"大沼郡会津美里町","赤留","","Aizumisato-machi, Onuma-gun","Akaru",""]],
	"9696273":[[7,"大沼郡会津美里町","八木沢","","Aizumisato-machi, Onuma-gun","Yagisawa",""]],
	"9696274":[[7,"大沼郡会津美里町","雀林","","Aizumisato-machi, Onuma-gun","Suzumebayashi",""]],
	"9696301":[[7,"大沼郡会津美里町","杉甲","","Aizumisato-machi, Onuma-gun","Sugiko",""]],
	"9696302":[[7,"大沼郡会津美里町","山道下甲","","Aizumisato-machi, Onuma-gun","Yamamichishitako",""]],
	"9696303":[[7,"大沼郡会津美里町","山道上","","Aizumisato-machi, Onuma-gun","Yamamichikami",""]],
	"9696304":[[7,"大沼郡会津美里町","黒沢甲","","Aizumisato-machi, Onuma-gun","Kurosawako",""]],
	"9696305":[[7,"大沼郡会津美里町","延命寺前甲","","Aizumisato-machi, Onuma-gun","Emmeijimaeko",""]],
	"9696306":[[7,"大沼郡会津美里町","延命寺前乙","","Aizumisato-machi, Onuma-gun","Emmeijimaeotsu",""]],
	"9696307":[[7,"大沼郡会津美里町","石田甲","","Aizumisato-machi, Onuma-gun","Ishidako",""]],
	"9696311":[[7,"大沼郡会津美里町","清水台","","Aizumisato-machi, Onuma-gun","Shimizudai",""]],
	"9696312":[[7,"大沼郡会津美里町","清水台甲","","Aizumisato-machi, Onuma-gun","Shimizudaiko",""]],
	"9696313":[[7,"大沼郡会津美里町","下川原甲","","Aizumisato-machi, Onuma-gun","Shimokawarako",""]],
	"9696314":[[7,"大沼郡会津美里町","清水川甲","","Aizumisato-machi, Onuma-gun","Shimizukawako",""]],
	"9696315":[[7,"大沼郡会津美里町","蛇ノ宮甲","","Aizumisato-machi, Onuma-gun","Hebinomiyako",""]],
	"9696316":[[7,"大沼郡会津美里町","北原","","Aizumisato-machi, Onuma-gun","Kitahara",""]],
	"9696317":[[7,"大沼郡会津美里町","北原甲","","Aizumisato-machi, Onuma-gun","Kitaharako",""]],
	"9696318":[[7,"大沼郡会津美里町","北原乙","","Aizumisato-machi, Onuma-gun","Kitaharaotsu",""]],
	"9696321":[[7,"大沼郡会津美里町","丸山北","","Aizumisato-machi, Onuma-gun","Maruyamakita",""]],
	"9696322":[[7,"大沼郡会津美里町","丸山北甲","","Aizumisato-machi, Onuma-gun","Maruyamakitako",""]],
	"9696323":[[7,"大沼郡会津美里町","丸山","","Aizumisato-machi, Onuma-gun","Maruyama",""]],
	"9696324":[[7,"大沼郡会津美里町","丸山乙","","Aizumisato-machi, Onuma-gun","Maruyamaotsu",""]],
	"9696325":[[7,"大沼郡会津美里町","宮後","","Aizumisato-machi, Onuma-gun","Miyago",""]],
	"9696326":[[7,"大沼郡会津美里町","宮後甲","","Aizumisato-machi, Onuma-gun","Miyagoko",""]],
	"9696327":[[7,"大沼郡会津美里町","宮後乙","","Aizumisato-machi, Onuma-gun","Miyagotsu",""]],
	"9696328":[[7,"大沼郡会津美里町","山南乙","","Aizumisato-machi, Onuma-gun","Yamaminamiotsu",""]],
	"9696331":[[7,"大沼郡会津美里町","本郷村西甲","","Aizumisato-machi, Onuma-gun","Hongomuranishiko",""]],
	"9696332":[[7,"大沼郡会津美里町","本郷村西乙","","Aizumisato-machi, Onuma-gun","Hongomuranishiotsu",""]],
	"9696333":[[7,"大沼郡会津美里町","大八郷乙","","Aizumisato-machi, Onuma-gun","Ohachigootsu",""]],
	"9696334":[[7,"大沼郡会津美里町","本郷村東乙","","Aizumisato-machi, Onuma-gun","Hongomurahigashiotsu",""]],
	"9696335":[[7,"大沼郡会津美里町","村上乙","","Aizumisato-machi, Onuma-gun","Murakamiotsu",""]],
	"9696336":[[7,"大沼郡会津美里町","本郷千苅","","Aizumisato-machi, Onuma-gun","Hongosengari",""]],
	"9696337":[[7,"大沼郡会津美里町","本郷千苅乙","","Aizumisato-machi, Onuma-gun","Hongosengariotsu",""]],
	"9696338":[[7,"大沼郡会津美里町","橋本乙","","Aizumisato-machi, Onuma-gun","Hashimototsu",""]],
	"9696341":[[7,"大沼郡会津美里町","横堀下乙","","Aizumisato-machi, Onuma-gun","Yokoborishitaotsu",""]],
	"9696342":[[7,"大沼郡会津美里町","倉田","","Aizumisato-machi, Onuma-gun","Kurata",""]],
	"9696343":[[7,"大沼郡会津美里町","沖田","","Aizumisato-machi, Onuma-gun","Okita",""]],
	"9696351":[[7,"大沼郡会津美里町","穴田","","Aizumisato-machi, Onuma-gun","Anada",""]],
	"9696352":[[7,"大沼郡会津美里町","穴田乙","","Aizumisato-machi, Onuma-gun","Anadaotsu",""]],
	"9696353":[[7,"大沼郡会津美里町","堂ノ前","","Aizumisato-machi, Onuma-gun","Donomae",""]],
	"9696354":[[7,"大沼郡会津美里町","堂ノ前甲","","Aizumisato-machi, Onuma-gun","Donomaeko",""]],
	"9696355":[[7,"大沼郡会津美里町","西沖","","Aizumisato-machi, Onuma-gun","Nishioki",""]],
	"9696356":[[7,"大沼郡会津美里町","稗田乙","","Aizumisato-machi, Onuma-gun","Hiedaotsu",""]],
	"9696401":[[7,"大沼郡会津美里町","和田目","","Aizumisato-machi, Onuma-gun","Wadame",""]],
	"9696402":[[7,"大沼郡会津美里町","新屋敷","","Aizumisato-machi, Onuma-gun","Shinyashiki",""]],
	"9696403":[[7,"大沼郡会津美里町","鶴野辺","","Aizumisato-machi, Onuma-gun","Tsurunobe",""]],
	"9696404":[[7,"大沼郡会津美里町","境野","","Aizumisato-machi, Onuma-gun","Sakaino",""]],
	"9696405":[[7,"大沼郡会津美里町","米田","","Aizumisato-machi, Onuma-gun","Yoneta",""]],
	"9696406":[[7,"大沼郡会津美里町","佐賀瀬川","","Aizumisato-machi, Onuma-gun","Sakasegawa",""]],
	"9696407":[[7,"大沼郡会津美里町","上平","","Aizumisato-machi, Onuma-gun","Uwadaira",""]],
	"9696408":[[7,"大沼郡会津美里町","沼田","","Aizumisato-machi, Onuma-gun","Numata",""]],
	"9696409":[[7,"大沼郡会津美里町","小沢","","Aizumisato-machi, Onuma-gun","Ozawa",""]],
	"9696411":[[7,"大沼郡会津美里町","立石田","","Aizumisato-machi, Onuma-gun","Tachiishida",""]],
	"9696500":[[7,"河沼郡会津坂下町","","","Aizubange-machi, Kawanuma-gun","",""]],
	"9696501":[[7,"河沼郡会津坂下町","長井","","Aizubange-machi, Kawanuma-gun","Nagai",""]],
	"9696502":[[7,"河沼郡会津坂下町","津尻","","Aizubange-machi, Kawanuma-gun","Tsujiri",""]],
	"9696503":[[7,"河沼郡会津坂下町","宇内","","Aizubange-machi, Kawanuma-gun","Unai",""]],
	"9696504":[[7,"河沼郡会津坂下町","八日沢","","Aizubange-machi, Kawanuma-gun","Yokazawa",""]],
	"9696505":[[7,"河沼郡会津坂下町","新舘","","Aizubange-machi, Kawanuma-gun","Niidate",""]],
	"9696506":[[7,"河沼郡会津坂下町","見明","","Aizubange-machi, Kawanuma-gun","Mimyo",""]],
	"9696507":[[7,"河沼郡会津坂下町","大上","","Aizubange-machi, Kawanuma-gun","Okami",""]],
	"9696511":[[7,"河沼郡会津坂下町","青木","","Aizubange-machi, Kawanuma-gun","Aoki",""]],
	"9696512":[[7,"河沼郡会津坂下町","沼越","","Aizubange-machi, Kawanuma-gun","Numakoshi",""]],
	"9696513":[[7,"河沼郡会津坂下町","立川","","Aizubange-machi, Kawanuma-gun","Tachikawa",""]],
	"9696514":[[7,"河沼郡会津坂下町","五香","","Aizubange-machi, Kawanuma-gun","Goka",""]],
	"9696515":[[7,"河沼郡会津坂下町","福原前","","Aizubange-machi, Kawanuma-gun","Fukuharamae",""]],
	"9696516":[[7,"河沼郡会津坂下町","中泉","","Aizubange-machi, Kawanuma-gun","Nakaizumi",""]],
	"9696517":[[7,"河沼郡会津坂下町","合川","","Aizubange-machi, Kawanuma-gun","Aikawa",""]],
	"9696518":[[7,"河沼郡会津坂下町","青津","","Aizubange-machi, Kawanuma-gun","Aozu",""]],
	"9696519":[[7,"河沼郡会津坂下町","御池田","","Aizubange-machi, Kawanuma-gun","Oikeda",""],[7,"河沼郡会津坂下町","三谷","","Aizubange-machi, Kawanuma-gun","Mitani",""]],
	"9696521":[[7,"河沼郡会津坂下町","金上","","Aizubange-machi, Kawanuma-gun","Kanagami",""]],
	"9696522":[[7,"河沼郡会津坂下町","宮古","","Aizubange-machi, Kawanuma-gun","Miyako",""]],
	"9696523":[[7,"河沼郡会津坂下町","海老細","","Aizubange-machi, Kawanuma-gun","Ebisai",""]],
	"9696524":[[7,"河沼郡会津坂下町","束原","","Aizubange-machi, Kawanuma-gun","Tsukahara",""]],
	"9696525":[[7,"河沼郡会津坂下町","開津","","Aizubange-machi, Kawanuma-gun","Kaizu",""]],
	"9696526":[[7,"河沼郡会津坂下町","五ノ併","","Aizubange-machi, Kawanuma-gun","Gonohei",""]],
	"9696527":[[7,"河沼郡会津坂下町","福原","","Aizubange-machi, Kawanuma-gun","Fukuhara",""]],
	"9696528":[[7,"河沼郡会津坂下町","新開津","","Aizubange-machi, Kawanuma-gun","Shinkaizu",""]],
	"9696531":[[7,"河沼郡会津坂下町","上口","","Aizubange-machi, Kawanuma-gun","Joguchi",""],[7,"河沼郡会津坂下町","東上口甲","","Aizubange-machi, Kawanuma-gun","Higashijoguchiko",""]],
	"9696532":[[7,"河沼郡会津坂下町","東川前丙","","Aizubange-machi, Kawanuma-gun","Higashikawamaehei",""],[7,"河沼郡会津坂下町","道下丙","","Aizubange-machi, Kawanuma-gun","Michishitahei",""]],
	"9696533":[[7,"河沼郡会津坂下町","上ノ台乙","","Aizubange-machi, Kawanuma-gun","Kaminodaiotsu",""],[7,"河沼郡会津坂下町","台ノ下","","Aizubange-machi, Kawanuma-gun","Dainoshita",""]],
	"9696534":[[7,"河沼郡会津坂下町","小川原","","Aizubange-machi, Kawanuma-gun","Ogawahara",""],[7,"河沼郡会津坂下町","北小川原乙","","Aizubange-machi, Kawanuma-gun","Kitaogawaharaotsu",""],[7,"河沼郡会津坂下町","原道東甲","","Aizubange-machi, Kawanuma-gun","Haramichihigashiko",""]],
	"9696535":[[7,"河沼郡会津坂下町","家ノ前乙","","Aizubange-machi, Kawanuma-gun","Ienomaeotsu",""],[7,"河沼郡会津坂下町","東屋敷添乙","","Aizubange-machi, Kawanuma-gun","Higashiyashikizoeotsu",""]],
	"9696536":[[7,"河沼郡会津坂下町","市中一番甲","","Aizubange-machi, Kawanuma-gun","Ichinaka1-banko",""]],
	"9696537":[[7,"河沼郡会津坂下町","戌亥乙","","Aizubange-machi, Kawanuma-gun","Inuiotsu",""],[7,"河沼郡会津坂下町","西ノ宮乙","","Aizubange-machi, Kawanuma-gun","Nishinomiyaotsu",""]],
	"9696538":[[7,"河沼郡会津坂下町","姥ケ下乙","","Aizubange-machi, Kawanuma-gun","Ubagashitaotsu",""],[7,"河沼郡会津坂下町","上窪道北乙","","Aizubange-machi, Kawanuma-gun","Kamikubomichikitaotsu",""],[7,"河沼郡会津坂下町","上沼ノ上丙","","Aizubange-machi, Kawanuma-gun","Kaminumanoehei",""]],
	"9696539":[[7,"河沼郡会津坂下町","古市乙","","Aizubange-machi, Kawanuma-gun","Furuichiotsu",""]],
	"9696541":[[7,"河沼郡会津坂下町","上四十石甲","","Aizubange-machi, Kawanuma-gun","Kamishijutsukokuko",""],[7,"河沼郡会津坂下町","四十石","","Aizubange-machi, Kawanuma-gun","Shijutsukoku",""]],
	"9696542":[[7,"河沼郡会津坂下町","光明寺東甲","","Aizubange-machi, Kawanuma-gun","Komyojihigashiko",""],[7,"河沼郡会津坂下町","古屋敷甲","","Aizubange-machi, Kawanuma-gun","Furuyashikiko",""]],
	"9696543":[[7,"河沼郡会津坂下町","市中二番甲","","Aizubange-machi, Kawanuma-gun","Ichinaka2-banko",""]],
	"9696544":[[7,"河沼郡会津坂下町","大堀川西甲","","Aizubange-machi, Kawanuma-gun","Ohorikawanishiko",""],[7,"河沼郡会津坂下町","東南町裏甲","","Aizubange-machi, Kawanuma-gun","Tonammachiurako",""]],
	"9696545":[[7,"河沼郡会津坂下町","五反田","","Aizubange-machi, Kawanuma-gun","Gotanda",""]],
	"9696546":[[7,"河沼郡会津坂下町","曲田","","Aizubange-machi, Kawanuma-gun","Magarida",""]],
	"9696547":[[7,"河沼郡会津坂下町","市中三番甲","","Aizubange-machi, Kawanuma-gun","Ichinaka3-banko",""]],
	"9696548":[[7,"河沼郡会津坂下町","茶屋町甲","","Aizubange-machi, Kawanuma-gun","Chayamachiko",""]],
	"9696549":[[7,"河沼郡会津坂下町","古町川尻","","Aizubange-machi, Kawanuma-gun","Furumachikawajiri",""]],
	"9696551":[[7,"河沼郡会津坂下町","舘ノ下","","Aizubange-machi, Kawanuma-gun","Tatenoshita",""]],
	"9696552":[[7,"河沼郡会津坂下町","舘ノ内甲","","Aizubange-machi, Kawanuma-gun","Tatenochiko",""]],
	"9696553":[[7,"河沼郡会津坂下町","石田","","Aizubange-machi, Kawanuma-gun","Ishida",""],[7,"河沼郡会津坂下町","西南町裏甲","","Aizubange-machi, Kawanuma-gun","Seinammachiurako",""]],
	"9696554":[[7,"河沼郡会津坂下町","松ノ目","","Aizubange-machi, Kawanuma-gun","Matsunome",""]],
	"9696555":[[7,"河沼郡会津坂下町","沢ノ目","","Aizubange-machi, Kawanuma-gun","Sawanome",""]],
	"9696556":[[7,"河沼郡会津坂下町","北逆水甲","","Aizubange-machi, Kawanuma-gun","Kitasakamizuko",""],[7,"河沼郡会津坂下町","逆水","","Aizubange-machi, Kawanuma-gun","Sakamizu",""]],
	"9696557":[[7,"河沼郡会津坂下町","市中四番甲","","Aizubange-machi, Kawanuma-gun","Ichinaka4-banko",""]],
	"9696561":[[7,"河沼郡会津坂下町","大道","","Aizubange-machi, Kawanuma-gun","Daido",""]],
	"9696562":[[7,"河沼郡会津坂下町","一丁田甲","","Aizubange-machi, Kawanuma-gun","Itchodako",""],[7,"河沼郡会津坂下町","中岡甲","","Aizubange-machi, Kawanuma-gun","Nakaokako",""]],
	"9696563":[[7,"河沼郡会津坂下町","市中新町甲","","Aizubange-machi, Kawanuma-gun","Ichinakashinchoko",""]],
	"9696564":[[7,"河沼郡会津坂下町","中岩田","","Aizubange-machi, Kawanuma-gun","Nakaiwata",""]],
	"9696565":[[7,"河沼郡会津坂下町","惣六","","Aizubange-machi, Kawanuma-gun","Soroku",""]],
	"9696566":[[7,"河沼郡会津坂下町","稲荷塚","","Aizubange-machi, Kawanuma-gun","Inarizuka",""]],
	"9696567":[[7,"河沼郡会津坂下町","沼田甲","","Aizubange-machi, Kawanuma-gun","Numatako",""]],
	"9696571":[[7,"河沼郡会津坂下町","白狐","","Aizubange-machi, Kawanuma-gun","Byakko",""]],
	"9696572":[[7,"河沼郡会津坂下町","羽林","","Aizubange-machi, Kawanuma-gun","Habayashi",""]],
	"9696573":[[7,"河沼郡会津坂下町","大沖","","Aizubange-machi, Kawanuma-gun","Ooki",""]],
	"9696574":[[7,"河沼郡会津坂下町","樋島","","Aizubange-machi, Kawanuma-gun","Toishima",""]],
	"9696575":[[7,"河沼郡会津坂下町","勝大","","Aizubange-machi, Kawanuma-gun","Katsuo",""]],
	"9696576":[[7,"河沼郡会津坂下町","牛川","","Aizubange-machi, Kawanuma-gun","Ushikawa",""]],
	"9696581":[[7,"河沼郡会津坂下町","片門","","Aizubange-machi, Kawanuma-gun","Katakado",""]],
	"9696582":[[7,"河沼郡会津坂下町","高寺","","Aizubange-machi, Kawanuma-gun","Takatera",""]],
	"9696583":[[7,"河沼郡会津坂下町","気多宮","","Aizubange-machi, Kawanuma-gun","Ketanomiya",""]],
	"9696584":[[7,"河沼郡会津坂下町","塔寺","","Aizubange-machi, Kawanuma-gun","Todera",""]],
	"9696585":[[7,"河沼郡会津坂下町","船杉","","Aizubange-machi, Kawanuma-gun","Funasugi",""]],
	"9696586":[[7,"河沼郡会津坂下町","坂本","","Aizubange-machi, Kawanuma-gun","Sakamoto",""]],
	"9696587":[[7,"河沼郡会津坂下町","束松","","Aizubange-machi, Kawanuma-gun","Tabanematsu",""]],
	"9697200":[[7,"河沼郡柳津町","","","Yanaizu-machi, Kawanuma-gun","",""]],
	"9697201":[[7,"河沼郡柳津町","柳津","","Yanaizu-machi, Kawanuma-gun","Yanaizu",""]],
	"9697202":[[7,"河沼郡柳津町","大柳","","Yanaizu-machi, Kawanuma-gun","Oryu",""]],
	"9697203":[[7,"河沼郡柳津町","軽井沢","","Yanaizu-machi, Kawanuma-gun","Karuizawa",""]],
	"9697204":[[7,"河沼郡柳津町","猪倉野","","Yanaizu-machi, Kawanuma-gun","Ikurano",""]],
	"9697205":[[7,"河沼郡柳津町","郷戸","","Yanaizu-machi, Kawanuma-gun","Godo",""]],
	"9697206":[[7,"河沼郡柳津町","飯谷","","Yanaizu-machi, Kawanuma-gun","Iitani",""]],
	"9697207":[[7,"河沼郡柳津町","小椿","","Yanaizu-machi, Kawanuma-gun","Kotsubaki",""]],
	"9697208":[[7,"河沼郡柳津町","藤","","Yanaizu-machi, Kawanuma-gun","Fuji",""]],
	"9697209":[[7,"河沼郡柳津町","細八","","Yanaizu-machi, Kawanuma-gun","Hosohachi",""]],
	"9697311":[[7,"河沼郡柳津町","湯八木沢","","Yanaizu-machi, Kawanuma-gun","Yuyagisawa",""]],
	"9697312":[[7,"河沼郡柳津町","久保田","","Yanaizu-machi, Kawanuma-gun","Kubota",""]],
	"9697313":[[7,"河沼郡柳津町","五畳敷","","Yanaizu-machi, Kawanuma-gun","Gojojiki",""]],
	"9697314":[[7,"河沼郡柳津町","牧沢","","Yanaizu-machi, Kawanuma-gun","Makizawa",""]],
	"9697315":[[7,"河沼郡柳津町","四つ谷","","Yanaizu-machi, Kawanuma-gun","Yotsuya",""]],
	"9697321":[[7,"河沼郡柳津町","砂子原","","Yanaizu-machi, Kawanuma-gun","Sunakohara",""]],
	"9697322":[[7,"河沼郡柳津町","黒沢","","Yanaizu-machi, Kawanuma-gun","Kurosawa",""]],
	"9697323":[[7,"河沼郡柳津町","芋小屋","","Yanaizu-machi, Kawanuma-gun","Imogoya",""]],
	"9697324":[[7,"河沼郡柳津町","胄中","","Yanaizu-machi, Kawanuma-gun","Kabuchu",""]],
	"9697325":[[7,"河沼郡柳津町","大成沢","","Yanaizu-machi, Kawanuma-gun","Onarisawa",""]],
	"9697326":[[7,"河沼郡柳津町","琵琶首","","Yanaizu-machi, Kawanuma-gun","Biwakubi",""]],
	"9697401":[[7,"大沼郡三島町","西方","","Mishima-machi, Onuma-gun","Nishikata",""]],
	"9697402":[[7,"大沼郡三島町","名入","","Mishima-machi, Onuma-gun","Nairi",""]],
	"9697403":[[7,"大沼郡三島町","小山","","Mishima-machi, Onuma-gun","Koyama",""]],
	"9697404":[[7,"大沼郡三島町","高清水","","Mishima-machi, Onuma-gun","Takashimizu",""]],
	"9697405":[[7,"大沼郡三島町","滝原","","Mishima-machi, Onuma-gun","Takibara",""]],
	"9697406":[[7,"大沼郡三島町","早戸","","Mishima-machi, Onuma-gun","Hayato",""]],
	"9697407":[[7,"大沼郡三島町","大石田","","Mishima-machi, Onuma-gun","Oishida",""]],
	"9697413":[[7,"大沼郡三島町","桧原","","Mishima-machi, Onuma-gun","Hinohara",""]],
	"9697500":[[7,"大沼郡三島町","","","Mishima-machi, Onuma-gun","",""]],
	"9697511":[[7,"大沼郡三島町","宮下","","Mishima-machi, Onuma-gun","Miyashita",""]],
	"9697512":[[7,"大沼郡三島町","桑原","","Mishima-machi, Onuma-gun","Kuwanohara",""]],
	"9697513":[[7,"大沼郡三島町","桧原","","Mishima-machi, Onuma-gun","Hinohara",""]],
	"9697514":[[7,"大沼郡三島町","滝谷","","Mishima-machi, Onuma-gun","Takiya",""]],
	"9697515":[[7,"大沼郡三島町","川井","","Mishima-machi, Onuma-gun","Kawai",""]],
	"9697516":[[7,"大沼郡三島町","大登","","Mishima-machi, Onuma-gun","Onobori",""]],
	"9697517":[[7,"大沼郡三島町","大谷","","Mishima-machi, Onuma-gun","Otani",""]],
	"9697518":[[7,"大沼郡三島町","浅岐","","Mishima-machi, Onuma-gun","Asamata",""]],
	"9697519":[[7,"大沼郡三島町","間方","","Mishima-machi, Onuma-gun","Magata",""]]
})
