zipdata({
	"6000000":[[26,"京都市下京区","","","Shimogyo-ku, Kyoto-shi","",""]],
	"6008001":[[26,"京都市下京区","真町","","Shimogyo-ku, Kyoto-shi","Shincho",""]],
	"6008002":[[26,"京都市下京区","御旅町","","Shimogyo-ku, Kyoto-shi","Otabicho",""]],
	"6008003":[[26,"京都市下京区","御旅宮本町","","Shimogyo-ku, Kyoto-shi","Otabimiyamotocho",""]],
	"6008004":[[26,"京都市下京区","奈良物町","","Shimogyo-ku, Kyoto-shi","Naramonocho",""]],
	"6008005":[[26,"京都市下京区","立売東町","","Shimogyo-ku, Kyoto-shi","Tachiuri Higashicho",""]],
	"6008006":[[26,"京都市下京区","立売中之町","","Shimogyo-ku, Kyoto-shi","Tachiuri Nakanocho",""]],
	"6008007":[[26,"京都市下京区","立売西町","","Shimogyo-ku, Kyoto-shi","Tachiuri Nishimachi",""]],
	"6008008":[[26,"京都市下京区","長刀鉾町","","Shimogyo-ku, Kyoto-shi","Naginatabokocho",""]],
	"6008009":[[26,"京都市下京区","函谷鉾町","","Shimogyo-ku, Kyoto-shi","Kankobokocho",""]],
	"6008011":[[26,"京都市下京区","橋本町","","Shimogyo-ku, Kyoto-shi","Hashimotocho",""]],
	"6008012":[[26,"京都市下京区","斎藤町","","Shimogyo-ku, Kyoto-shi","Saitocho",""]],
	"6008013":[[26,"京都市下京区","天王町","","Shimogyo-ku, Kyoto-shi","Tennocho",""]],
	"6008014":[[26,"京都市下京区","和泉屋町","","Shimogyo-ku, Kyoto-shi","Izumiyacho",""]],
	"6008015":[[26,"京都市下京区","美濃屋町","","Shimogyo-ku, Kyoto-shi","Minoyacho",""]],
	"6008016":[[26,"京都市下京区","材木町","","Shimogyo-ku, Kyoto-shi","Zaimokucho",""]],
	"6008017":[[26,"京都市下京区","下材木町","","Shimogyo-ku, Kyoto-shi","Shimozaimokucho",""]],
	"6008018":[[26,"京都市下京区","市之町","","Shimogyo-ku, Kyoto-shi","Ichinocho",""]],
	"6008019":[[26,"京都市下京区","船頭町","","Shimogyo-ku, Kyoto-shi","Sendocho",""]],
	"6008020":[[26,"京都市下京区","御影堂前町","","Shimogyo-ku, Kyoto-shi","Mikagedomaecho",""]],
	"6008021":[[26,"京都市下京区","順風町","","Shimogyo-ku, Kyoto-shi","Jumpucho",""]],
	"6008022":[[26,"京都市下京区","稲荷町","","Shimogyo-ku, Kyoto-shi","Inaricho",""]],
	"6008023":[[26,"京都市下京区","富永町","","Shimogyo-ku, Kyoto-shi","Tominagacho",""],[26,"京都市下京区","光寺下る、河原町通松原上る、河原町","","Shimogyo-ku, Kyoto-shi","Tominagacho",""],[26,"京都市下京区","仏光寺通河原町西入）","","Shimogyo-ku, Kyoto-shi","Tominagacho",""]],
	"6008024":[[26,"京都市下京区","天満町","","Shimogyo-ku, Kyoto-shi","Temmacho",""]],
	"6008025":[[26,"京都市下京区","清水町","","Shimogyo-ku, Kyoto-shi","Shimizucho",""],[26,"京都市下京区","下る、西木屋町通松原上る）","","Shimogyo-ku, Kyoto-shi","Shimizucho",""]],
	"6008026":[[26,"京都市下京区","松川町","","Shimogyo-ku, Kyoto-shi","Matsukawacho",""]],
	"6008027":[[26,"京都市下京区","難波町","","Shimogyo-ku, Kyoto-shi","Nambacho",""]],
	"6008028":[[26,"京都市下京区","植松町","","Shimogyo-ku, Kyoto-shi","Uematsucho",""],[26,"京都市下京区","下る、寺町通万寿寺上る、松原通寺町","","Shimogyo-ku, Kyoto-shi","Uematsucho",""],[26,"京都市下京区","西入、万寿寺通寺町西入）","","Shimogyo-ku, Kyoto-shi","Uematsucho",""]],
	"6008029":[[26,"京都市下京区","西橋詰町","","Shimogyo-ku, Kyoto-shi","Nishihashizumecho",""]],
	"6008031":[[26,"京都市下京区","貞安前之町","","Shimogyo-ku, Kyoto-shi","Teiammaenocho",""]],
	"6008032":[[26,"京都市下京区","中之町","","Shimogyo-ku, Kyoto-shi","Nakanocho",""],[26,"京都市下京区","入、仏光寺通寺町東入）","","Shimogyo-ku, Kyoto-shi","Nakanocho",""]],
	"6008033":[[26,"京都市下京区","恵美須之町","","Shimogyo-ku, Kyoto-shi","Ebisunocho",""]],
	"6008034":[[26,"京都市下京区","幸竹町","","Shimogyo-ku, Kyoto-shi","Kotakecho",""]],
	"6008035":[[26,"京都市下京区","京極町","","Shimogyo-ku, Kyoto-shi","Kyogokucho",""]],
	"6008036":[[26,"京都市下京区","茶磨屋町","","Shimogyo-ku, Kyoto-shi","Chamayacho",""]],
	"6008037":[[26,"京都市下京区","丸屋町","","Shimogyo-ku, Kyoto-shi","Maruyacho",""]],
	"6008038":[[26,"京都市下京区","足袋屋町","","Shimogyo-ku, Kyoto-shi","Tabiyacho",""]],
	"6008039":[[26,"京都市下京区","大寿町","","Shimogyo-ku, Kyoto-shi","Daizucho",""]],
	"6008040":[[26,"京都市下京区","安土町","","Shimogyo-ku, Kyoto-shi","Azuchicho",""]],
	"6008041":[[26,"京都市下京区","八文字町","","Shimogyo-ku, Kyoto-shi","Hachimonjicho",""]],
	"6008042":[[26,"京都市下京区","俵屋町","","Shimogyo-ku, Kyoto-shi","Tawarayacho",""]],
	"6008043":[[26,"京都市下京区","大黒町","","Shimogyo-ku, Kyoto-shi","Daikokucho",""],[26,"京都市下京区","寺町西入、仏光寺通麩屋町東入）","","Shimogyo-ku, Kyoto-shi","Daikokucho",""]],
	"6008044":[[26,"京都市下京区","橘町","","Shimogyo-ku, Kyoto-shi","Tachibanacho",""],[26,"京都市下京区","西入、高辻通御幸町東入）","","Shimogyo-ku, Kyoto-shi","Tachibanacho",""]],
	"6008045":[[26,"京都市下京区","茶磨屋町","","Shimogyo-ku, Kyoto-shi","Chamayacho",""]],
	"6008046":[[26,"京都市下京区","桝屋町","","Shimogyo-ku, Kyoto-shi","Masuyacho",""]],
	"6008047":[[26,"京都市下京区","石不動之町","","Shimogyo-ku, Kyoto-shi","Ishifudonocho",""]],
	"6008048":[[26,"京都市下京区","須浜町","","Shimogyo-ku, Kyoto-shi","Subamacho",""]],
	"6008049":[[26,"京都市下京区","堅田町","","Shimogyo-ku, Kyoto-shi","Katadacho",""]],
	"6008050":[[26,"京都市下京区","堅田町","","Shimogyo-ku, Kyoto-shi","Katadacho",""]],
	"6008051":[[26,"京都市下京区","徳正寺町","","Shimogyo-ku, Kyoto-shi","Tokushojicho",""]],
	"6008052":[[26,"京都市下京区","塩屋町","","Shimogyo-ku, Kyoto-shi","Shioyacho",""],[26,"京都市下京区","麩屋町西入、綾小路通柳馬場東入、富","","Shimogyo-ku, Kyoto-shi","Shioyacho",""],[26,"京都市下京区","る、麩屋町通綾小路下る）","","Shimogyo-ku, Kyoto-shi","Shioyacho",""]],
	"6008053":[[26,"京都市下京区","塗師屋町","","Shimogyo-ku, Kyoto-shi","Nushiyacho",""]],
	"6008054":[[26,"京都市下京区","仏光寺東町","","Shimogyo-ku, Kyoto-shi","Bukkoji Higashimachi",""]],
	"6008055":[[26,"京都市下京区","鍋屋町","","Shimogyo-ku, Kyoto-shi","Nabeyacho",""]],
	"6008056":[[26,"京都市下京区","雁金町","","Shimogyo-ku, Kyoto-shi","Kariganecho",""]],
	"6008057":[[26,"京都市下京区","鍵屋町","","Shimogyo-ku, Kyoto-shi","Kagiyacho",""],[26,"京都市下京区","下る、麩屋町通松原上る）","","Shimogyo-ku, Kyoto-shi","Kagiyacho",""]],
	"6008058":[[26,"京都市下京区","上鱗形町","","Shimogyo-ku, Kyoto-shi","Kamiurokogatacho",""]],
	"6008059":[[26,"京都市下京区","下鱗形町","","Shimogyo-ku, Kyoto-shi","Shimorokogatacho",""]],
	"6008060":[[26,"京都市下京区","雁金町","","Shimogyo-ku, Kyoto-shi","Kariganecho",""]],
	"6008061":[[26,"京都市下京区","筋屋町","","Shimogyo-ku, Kyoto-shi","Sujiyacho",""]],
	"6008062":[[26,"京都市下京区","恵美須屋町","","Shimogyo-ku, Kyoto-shi","Ebisuyacho",""]],
	"6008063":[[26,"京都市下京区","松原中之町","","Shimogyo-ku, Kyoto-shi","Matsubaranakanocho",""]],
	"6008064":[[26,"京都市下京区","本上神明町","","Shimogyo-ku, Kyoto-shi","Motokamishimmeicho",""]],
	"6008065":[[26,"京都市下京区","本神明町","","Shimogyo-ku, Kyoto-shi","Motoshimmeicho",""]],
	"6008066":[[26,"京都市下京区","柏屋町","","Shimogyo-ku, Kyoto-shi","Kashiwayacho",""]],
	"6008067":[[26,"京都市下京区","堅田町","","Shimogyo-ku, Kyoto-shi","Katadacho",""],[26,"京都市下京区","馬場西入、万寿寺通柳馬場東入、柳馬","","Shimogyo-ku, Kyoto-shi","Katadacho",""]],
	"6008068":[[26,"京都市下京区","忠庵町","","Shimogyo-ku, Kyoto-shi","Chuancho",""]],
	"6008069":[[26,"京都市下京区","吉文字町","","Shimogyo-ku, Kyoto-shi","Kichimonjicho",""],[26,"京都市下京区","下る、柳馬場通松原上る）","","Shimogyo-ku, Kyoto-shi","Kichimonjicho",""]],
	"6008070":[[26,"京都市下京区","俵屋町","","Shimogyo-ku, Kyoto-shi","Tawarayacho",""],[26,"京都市下京区","入、五条通堺町上る）","","Shimogyo-ku, Kyoto-shi","Tawarayacho",""]],
	"6008071":[[26,"京都市下京区","相之町","","Shimogyo-ku, Kyoto-shi","Ainocho",""]],
	"6008072":[[26,"京都市下京区","綾材木町","","Shimogyo-ku, Kyoto-shi","Ayazaimokucho",""]],
	"6008073":[[26,"京都市下京区","永原町","","Shimogyo-ku, Kyoto-shi","Nagaharacho",""]],
	"6008074":[[26,"京都市下京区","東前町","","Shimogyo-ku, Kyoto-shi","Higashimaecho",""]],
	"6008075":[[26,"京都市下京区","万里小路町","","Shimogyo-ku, Kyoto-shi","Marikojicho",""]],
	"6008076":[[26,"京都市下京区","泉正寺町","","Shimogyo-ku, Kyoto-shi","Senshojicho",""]],
	"6008077":[[26,"京都市下京区","夕顔町","","Shimogyo-ku, Kyoto-shi","Yugaocho",""]],
	"6008078":[[26,"京都市下京区","杉屋町","","Shimogyo-ku, Kyoto-shi","Sugiyacho",""]],
	"6008079":[[26,"京都市下京区","鍛冶屋町","","Shimogyo-ku, Kyoto-shi","Kajiyacho",""]],
	"6008081":[[26,"京都市下京区","小石町","","Shimogyo-ku, Kyoto-shi","Koishicho",""]],
	"6008082":[[26,"京都市下京区","高材木町","","Shimogyo-ku, Kyoto-shi","Takazaimokucho",""]],
	"6008083":[[26,"京都市下京区","西前町","","Shimogyo-ku, Kyoto-shi","Nishimaecho",""]],
	"6008084":[[26,"京都市下京区","新開町","","Shimogyo-ku, Kyoto-shi","Shinkaicho",""]],
	"6008085":[[26,"京都市下京区","葛籠屋町","","Shimogyo-ku, Kyoto-shi","Tsuzurayacho",""]],
	"6008086":[[26,"京都市下京区","本燈籠町","","Shimogyo-ku, Kyoto-shi","Hontorocho",""]],
	"6008087":[[26,"京都市下京区","樋之下町","","Shimogyo-ku, Kyoto-shi","Hinoshitacho",""]],
	"6008088":[[26,"京都市下京区","官社殿町","","Shimogyo-ku, Kyoto-shi","Kanshadencho",""]],
	"6008089":[[26,"京都市下京区","堅田町","","Shimogyo-ku, Kyoto-shi","Katadacho",""]],
	"6008090":[[26,"京都市下京区","竹屋之町","","Shimogyo-ku, Kyoto-shi","Takeyanocho",""]],
	"6008091":[[26,"京都市下京区","元悪王子町","","Shimogyo-ku, Kyoto-shi","Motoakuojicho",""]],
	"6008092":[[26,"京都市下京区","神明町","","Shimogyo-ku, Kyoto-shi","Shimmeicho",""]],
	"6008093":[[26,"京都市下京区","竹屋町","","Shimogyo-ku, Kyoto-shi","Takeyacho",""]],
	"6008094":[[26,"京都市下京区","仏光寺西町","","Shimogyo-ku, Kyoto-shi","Bukkoji Nishimachi",""]],
	"6008095":[[26,"京都市下京区","扇酒屋町","","Shimogyo-ku, Kyoto-shi","Ogisakayacho",""]],
	"6008096":[[26,"京都市下京区","高橋町","","Shimogyo-ku, Kyoto-shi","Takahashicho",""]],
	"6008097":[[26,"京都市下京区","三軒町","","Shimogyo-ku, Kyoto-shi","Sangencho",""]],
	"6008098":[[26,"京都市下京区","稲荷町","","Shimogyo-ku, Kyoto-shi","Inaricho",""],[26,"京都市下京区","入、高辻通間之町東入、高辻通東洞院","","Shimogyo-ku, Kyoto-shi","Inaricho",""]],
	"6008099":[[26,"京都市下京区","上柳町","","Shimogyo-ku, Kyoto-shi","Kamiyanagicho",""],[26,"京都市下京区","仏光寺通東洞院西入）","","Shimogyo-ku, Kyoto-shi","Kamiyanagicho",""]],
	"6008101":[[26,"京都市下京区","御影堂町","","Shimogyo-ku, Kyoto-shi","Mieidocho",""]],
	"6008102":[[26,"京都市下京区","本覚寺前町","","Shimogyo-ku, Kyoto-shi","Hongakujimaecho",""]],
	"6008103":[[26,"京都市下京区","塩竈町","","Shimogyo-ku, Kyoto-shi","Shiogamacho",""]],
	"6008104":[[26,"京都市下京区","万寿寺町","","Shimogyo-ku, Kyoto-shi","Manjujicho",""]],
	"6008105":[[26,"京都市下京区","松屋町","","Shimogyo-ku, Kyoto-shi","Matsuyacho",""]],
	"6008106":[[26,"京都市下京区","醍醐町","","Shimogyo-ku, Kyoto-shi","Daigocho",""]],
	"6008107":[[26,"京都市下京区","東錺屋町","","Shimogyo-ku, Kyoto-shi","Higashikazariyacho",""]],
	"6008108":[[26,"京都市下京区","西錺屋町","","Shimogyo-ku, Kyoto-shi","Nishikazariyacho",""]],
	"6008109":[[26,"京都市下京区","平屋町","","Shimogyo-ku, Kyoto-shi","Hirayacho",""]],
	"6008110":[[26,"京都市下京区","南橋詰町","","Shimogyo-ku, Kyoto-shi","Minamihashizumecho",""]],
	"6008111":[[26,"京都市下京区","都市町","","Shimogyo-ku, Kyoto-shi","Toichicho",""]],
	"6008112":[[26,"京都市下京区","八ツ柳町","","Shimogyo-ku, Kyoto-shi","Yatsuyanagicho",""]],
	"6008113":[[26,"京都市下京区","波止土濃町","","Shimogyo-ku, Kyoto-shi","Hashidonocho",""]],
	"6008114":[[26,"京都市下京区","早尾町","","Shimogyo-ku, Kyoto-shi","Hayaocho",""]],
	"6008115":[[26,"京都市下京区","岩滝町","","Shimogyo-ku, Kyoto-shi","Iwatakicho",""]],
	"6008116":[[26,"京都市下京区","聖真子町","","Shimogyo-ku, Kyoto-shi","Shoshinjicho",""]],
	"6008117":[[26,"京都市下京区","南京極町","","Shimogyo-ku, Kyoto-shi","Minamikyogokucho",""]],
	"6008118":[[26,"京都市下京区","平居町","","Shimogyo-ku, Kyoto-shi","Hiraicho",""]],
	"6008119":[[26,"京都市下京区","本塩竈町","","Shimogyo-ku, Kyoto-shi","Motoshiogamacho",""]],
	"6008120":[[26,"京都市下京区","若宮町","","Shimogyo-ku, Kyoto-shi","Wakamiyacho",""],[26,"京都市下京区","町通上枳殻馬場上る、河原町通上ノ口","","Shimogyo-ku, Kyoto-shi","Wakamiyacho",""]],
	"6008121":[[26,"京都市下京区","菊屋町","","Shimogyo-ku, Kyoto-shi","Kikuyacho",""],[26,"京都市下京区","茂川筋上ノ口下る、上ノ口通二ノ宮西","","Shimogyo-ku, Kyoto-shi","Kikuyacho",""]],
	"6008122":[[26,"京都市下京区","平岡町","","Shimogyo-ku, Kyoto-shi","Hiraokacho",""]],
	"6008123":[[26,"京都市下京区","高宮町","","Shimogyo-ku, Kyoto-shi","Takamiyacho",""]],
	"6008124":[[26,"京都市下京区","富松町","","Shimogyo-ku, Kyoto-shi","Tomimatsucho",""]],
	"6008125":[[26,"京都市下京区","富浜町","","Shimogyo-ku, Kyoto-shi","Tomihamacho",""]],
	"6008126":[[26,"京都市下京区","鍵屋町","","Shimogyo-ku, Kyoto-shi","Kagiyacho",""],[26,"京都市下京区","入、木屋町通正面上る、正面通二ノ宮","","Shimogyo-ku, Kyoto-shi","Kagiyacho",""],[26,"京都市下京区","通正面上る）","","Shimogyo-ku, Kyoto-shi","Kagiyacho",""]],
	"6008127":[[26,"京都市下京区","梅湊町","","Shimogyo-ku, Kyoto-shi","Umeminatocho",""]],
	"6008128":[[26,"京都市下京区","大工町","","Shimogyo-ku, Kyoto-shi","Daikucho",""],[26,"京都市下京区","土手町東入、上ノ口通西木屋町西入、","","Shimogyo-ku, Kyoto-shi","Daikucho",""],[26,"京都市下京区","下る、河原町通六条下る、土手町通上","","Shimogyo-ku, Kyoto-shi","Daikucho",""],[26,"京都市下京区","通河原町東入）","","Shimogyo-ku, Kyoto-shi","Daikucho",""]],
	"6008129":[[26,"京都市下京区","溜池町","","Shimogyo-ku, Kyoto-shi","Tameikecho",""]],
	"6008130":[[26,"京都市下京区","紺屋町","","Shimogyo-ku, Kyoto-shi","Konyacho",""]],
	"6008131":[[26,"京都市下京区","上二之宮町","","Shimogyo-ku, Kyoto-shi","Kamininomiyacho",""]],
	"6008132":[[26,"京都市下京区","下二之宮町","","Shimogyo-ku, Kyoto-shi","Shimoninomiyacho",""]],
	"6008133":[[26,"京都市下京区","稲荷町","","Shimogyo-ku, Kyoto-shi","Inaricho",""]],
	"6008134":[[26,"京都市下京区","山王町","","Shimogyo-ku, Kyoto-shi","Sannocho",""],[26,"京都市下京区","西入、正面通三ノ宮東入、正面通二ノ","","Shimogyo-ku, Kyoto-shi","Sannocho",""]],
	"6008135":[[26,"京都市下京区","上三之宮町","","Shimogyo-ku, Kyoto-shi","Kamisannomiyacho",""]],
	"6008136":[[26,"京都市下京区","下三之宮町","","Shimogyo-ku, Kyoto-shi","Shimosannomiyacho",""]],
	"6008137":[[26,"京都市下京区","十禅師町","","Shimogyo-ku, Kyoto-shi","Juzenjicho",""]],
	"6008138":[[26,"京都市下京区","大宮町","","Shimogyo-ku, Kyoto-shi","Omiyacho",""]],
	"6008139":[[26,"京都市下京区","八王子町","","Shimogyo-ku, Kyoto-shi","Hachiojicho",""]],
	"6008141":[[26,"京都市下京区","新日吉町","","Shimogyo-ku, Kyoto-shi","Shinhiyoshicho",""]],
	"6008142":[[26,"京都市下京区","納屋町","","Shimogyo-ku, Kyoto-shi","Nayacho",""]],
	"6008143":[[26,"京都市下京区","住吉町","","Shimogyo-ku, Kyoto-shi","Sumiyoshicho",""],[26,"京都市下京区","場通河原町西入、下珠数屋町通高倉東","","Shimogyo-ku, Kyoto-shi","Sumiyoshicho",""]],
	"6008144":[[26,"京都市下京区","塩屋町","","Shimogyo-ku, Kyoto-shi","Shioyacho",""],[26,"京都市下京区","殻馬場通河原町西入下る）","","Shimogyo-ku, Kyoto-shi","Shioyacho",""]],
	"6008145":[[26,"京都市下京区","皆山町","","Shimogyo-ku, Kyoto-shi","Kaizancho",""]],
	"6008146":[[26,"京都市下京区","材木町","","Shimogyo-ku, Kyoto-shi","Zaimokucho",""],[26,"京都市下京区","る、河原町通七条下る、七条通間之町","","Shimogyo-ku, Kyoto-shi","Zaimokucho",""],[26,"京都市下京区","入、七条通河原町東入、七条通高倉西","","Shimogyo-ku, Kyoto-shi","Zaimokucho",""],[26,"京都市下京区","西入、七条通東洞院東入、高倉通七条","","Shimogyo-ku, Kyoto-shi","Zaimokucho",""],[26,"京都市下京区","上る、東洞院通七条下る、柳馬場通七","","Shimogyo-ku, Kyoto-shi","Zaimokucho",""]],
	"6008147":[[26,"京都市下京区","堀詰町","","Shimogyo-ku, Kyoto-shi","Horizumecho",""]],
	"6008148":[[26,"京都市下京区","飴屋町","","Shimogyo-ku, Kyoto-shi","Ameyacho",""]],
	"6008149":[[26,"京都市下京区","粉川町","","Shimogyo-ku, Kyoto-shi","Kogawacho",""]],
	"6008150":[[26,"京都市下京区","上珠数屋町","","Shimogyo-ku, Kyoto-shi","Kamijuzuyacho",""]],
	"6008151":[[26,"京都市下京区","打越町","","Shimogyo-ku, Kyoto-shi","Uchikoshicho",""]],
	"6008152":[[26,"京都市下京区","筒金町","","Shimogyo-ku, Kyoto-shi","Tsutsuganecho",""]],
	"6008153":[[26,"京都市下京区","廿人講町","","Shimogyo-ku, Kyoto-shi","Nijuninkocho",""]],
	"6008154":[[26,"京都市下京区","榎木町","","Shimogyo-ku, Kyoto-shi","Enokicho",""]],
	"6008155":[[26,"京都市下京区","西玉水町","","Shimogyo-ku, Kyoto-shi","Nishitamamizucho",""]],
	"6008156":[[26,"京都市下京区","笹屋町","","Shimogyo-ku, Kyoto-shi","Sasayacho",""]],
	"6008157":[[26,"京都市下京区","橘町","","Shimogyo-ku, Kyoto-shi","Tachibanacho",""]],
	"6008158":[[26,"京都市下京区","卓屋町","","Shimogyo-ku, Kyoto-shi","Shokuyacho",""]],
	"6008159":[[26,"京都市下京区","亀町","","Shimogyo-ku, Kyoto-shi","Kamemachi",""]],
	"6008160":[[26,"京都市下京区","西魚屋町","","Shimogyo-ku, Kyoto-shi","Nishiuoyacho",""]],
	"6008161":[[26,"京都市下京区","大黒町","","Shimogyo-ku, Kyoto-shi","Daikokucho",""],[26,"京都市下京区","入、室町通鍵屋町上る、室町通楊梅上","","Shimogyo-ku, Kyoto-shi","Daikokucho",""]],
	"6008162":[[26,"京都市下京区","堺町","","Shimogyo-ku, Kyoto-shi","Sakaicho",""],[26,"京都市下京区","る、的場通室町西入、的場通室町東入","","Shimogyo-ku, Kyoto-shi","Sakaicho",""],[26,"京都市下京区","上る、室町通的場上る）","","Shimogyo-ku, Kyoto-shi","Sakaicho",""]],
	"6008163":[[26,"京都市下京区","下諏訪町","","Shimogyo-ku, Kyoto-shi","Shimosuwancho",""]],
	"6008164":[[26,"京都市下京区","上柳町","","Shimogyo-ku, Kyoto-shi","Kamiyanagicho",""],[26,"京都市下京区","る、六条通烏丸西入、六条通諏訪町西","","Shimogyo-ku, Kyoto-shi","Kamiyanagicho",""],[26,"京都市下京区","東入）","","Shimogyo-ku, Kyoto-shi","Kamiyanagicho",""]],
	"6008165":[[26,"京都市下京区","下柳町","","Shimogyo-ku, Kyoto-shi","Shimoyanagicho",""]],
	"6008166":[[26,"京都市下京区","乾町","","Shimogyo-ku, Kyoto-shi","Inuicho",""]],
	"6008167":[[26,"京都市下京区","常葉町","","Shimogyo-ku, Kyoto-shi","Tokiwacho",""]],
	"6008168":[[26,"京都市下京区","八百屋町","","Shimogyo-ku, Kyoto-shi","Yaoyacho",""],[26,"京都市下京区","る、六条通新町東入下る、六条通室町","","Shimogyo-ku, Kyoto-shi","Yaoyacho",""]],
	"6008169":[[26,"京都市下京区","東魚屋町","","Shimogyo-ku, Kyoto-shi","Higashiuoyacho",""]],
	"6008170":[[26,"京都市下京区","上諏訪町","","Shimogyo-ku, Kyoto-shi","Kamisuwancho",""]],
	"6008171":[[26,"京都市下京区","上平野町","","Shimogyo-ku, Kyoto-shi","Kamihiranocho",""]],
	"6008172":[[26,"京都市下京区","下平野町","","Shimogyo-ku, Kyoto-shi","Shimohiranocho",""]],
	"6008173":[[26,"京都市下京区","仏具屋町","","Shimogyo-ku, Kyoto-shi","Butsuguyacho",""],[26,"京都市下京区","六条上る、不明門通六条下る、花屋町","","Shimogyo-ku, Kyoto-shi","Butsuguyacho",""],[26,"京都市下京区","屋町通不明門東入、六条通不明門西入","","Shimogyo-ku, Kyoto-shi","Butsuguyacho",""],[26,"京都市下京区","入、六条通東洞院西入）","","Shimogyo-ku, Kyoto-shi","Butsuguyacho",""]],
	"6008174":[[26,"京都市下京区","高槻町","","Shimogyo-ku, Kyoto-shi","Takatsukicho",""]],
	"6008175":[[26,"京都市下京区","烏丸","","Shimogyo-ku, Kyoto-shi","Karasuma",""]],
	"6008176":[[26,"京都市下京区","北町","","Shimogyo-ku, Kyoto-shi","Kitamachi",""]],
	"6008177":[[26,"京都市下京区","大坂町","","Shimogyo-ku, Kyoto-shi","Osakacho",""]],
	"6008178":[[26,"京都市下京区","鍵屋町","","Shimogyo-ku, Kyoto-shi","Kagiyacho",""],[26,"京都市下京区","町東入、諏訪町通鍵屋町上る、諏訪町","","Shimogyo-ku, Kyoto-shi","Kagiyacho",""]],
	"6008179":[[26,"京都市下京区","横諏訪町","","Shimogyo-ku, Kyoto-shi","Yokosuwancho",""]],
	"6008180":[[26,"京都市下京区","下万寿寺町","","Shimogyo-ku, Kyoto-shi","Shimomanjujicho",""]],
	"6008181":[[26,"京都市下京区","大津町","","Shimogyo-ku, Kyoto-shi","Otsucho",""]],
	"6008182":[[26,"京都市下京区","塗師屋町","","Shimogyo-ku, Kyoto-shi","Nushiyacho",""],[26,"京都市下京区","六条上る、下坂通間之町西入、下坂通","","Shimogyo-ku, Kyoto-shi","Nushiyacho",""],[26,"京都市下京区","通間之町東入、六条通高倉西入、六条","","Shimogyo-ku, Kyoto-shi","Nushiyacho",""]],
	"6008183":[[26,"京都市下京区","夷之町","","Shimogyo-ku, Kyoto-shi","Ebisunocho",""],[26,"京都市下京区","六条下る、花屋町通間之町西入、花屋","","Shimogyo-ku, Kyoto-shi","Ebisunocho",""],[26,"京都市下京区","六条通間之町西入、六条通間之町東入","","Shimogyo-ku, Kyoto-shi","Ebisunocho",""]],
	"6008184":[[26,"京都市下京区","天神町","","Shimogyo-ku, Kyoto-shi","Tenjincho",""]],
	"6008185":[[26,"京都市下京区","花屋町","","Shimogyo-ku, Kyoto-shi","Hanayacho",""],[26,"京都市下京区","上珠数屋町通東洞院東入、東洞院通上","","Shimogyo-ku, Kyoto-shi","Hanayacho",""]],
	"6008186":[[26,"京都市下京区","富田町","","Shimogyo-ku, Kyoto-shi","Tomitacho",""]],
	"6008187":[[26,"京都市下京区","橋詰町","","Shimogyo-ku, Kyoto-shi","Hashizumecho",""]],
	"6008188":[[26,"京都市下京区","和泉町","","Shimogyo-ku, Kyoto-shi","Izumicho",""]],
	"6008189":[[26,"京都市下京区","福島町","","Shimogyo-ku, Kyoto-shi","Fukushimacho",""]],
	"6008190":[[26,"京都市下京区","東玉水町","","Shimogyo-ku, Kyoto-shi","Higashitamamizucho",""]],
	"6008191":[[26,"京都市下京区","堺町","","Shimogyo-ku, Kyoto-shi","Sakaimachi",""]],
	"6008192":[[26,"京都市下京区","富屋町","","Shimogyo-ku, Kyoto-shi","Tomiyacho",""]],
	"6008193":[[26,"京都市下京区","骨屋町","","Shimogyo-ku, Kyoto-shi","Honeyacho",""]],
	"6008194":[[26,"京都市下京区","栄町","","Shimogyo-ku, Kyoto-shi","Sakaecho",""]],
	"6008195":[[26,"京都市下京区","升屋町","","Shimogyo-ku, Kyoto-shi","Masuyacho",""]],
	"6008196":[[26,"京都市下京区","八軒町","","Shimogyo-ku, Kyoto-shi","Hachikencho",""]],
	"6008197":[[26,"京都市下京区","唐物町","","Shimogyo-ku, Kyoto-shi","Karamonocho",""]],
	"6008198":[[26,"京都市下京区","若松町","","Shimogyo-ku, Kyoto-shi","Wakamatsucho",""]],
	"6008199":[[26,"京都市下京区","万屋町","","Shimogyo-ku, Kyoto-shi","Yorozuyacho",""]],
	"6008201":[[26,"京都市下京区","若宮町","","Shimogyo-ku, Kyoto-shi","Wakamiyacho",""],[26,"京都市下京区","る東入、三ノ宮通七条下る、須原通七","","Shimogyo-ku, Kyoto-shi","Wakamiyacho",""],[26,"京都市下京区","西入、七条通加茂川筋西入下る）","","Shimogyo-ku, Kyoto-shi","Wakamiyacho",""]],
	"6008202":[[26,"京都市下京区","川端町","","Shimogyo-ku, Kyoto-shi","Kawabatacho",""]],
	"6008203":[[26,"京都市下京区","屋形町","","Shimogyo-ku, Kyoto-shi","Yakatacho",""]],
	"6008204":[[26,"京都市下京区","東之町","","Shimogyo-ku, Kyoto-shi","Higashinocho",""]],
	"6008205":[[26,"京都市下京区","西之町","","Shimogyo-ku, Kyoto-shi","Nishinocho",""]],
	"6008206":[[26,"京都市下京区","下之町","","Shimogyo-ku, Kyoto-shi","Shimonocho",""]],
	"6008207":[[26,"京都市下京区","上之町","","Shimogyo-ku, Kyoto-shi","Kaminocho",""]],
	"6008208":[[26,"京都市下京区","小稲荷町","","Shimogyo-ku, Kyoto-shi","Koinaricho",""]],
	"6008209":[[26,"京都市下京区","郷之町","","Shimogyo-ku, Kyoto-shi","Gonocho",""]],
	"6008210":[[26,"京都市下京区","桜木町","","Shimogyo-ku, Kyoto-shi","Sakuragicho",""]],
	"6008211":[[26,"京都市下京区","真苧屋町","","Shimogyo-ku, Kyoto-shi","Maoyacho",""]],
	"6008212":[[26,"京都市下京区","塩小路町","","Shimogyo-ku, Kyoto-shi","Shiokojicho",""]],
	"6008213":[[26,"京都市下京区","東塩小路向畑町","","Shimogyo-ku, Kyoto-shi","Higashishiokoji Mukaihatacho",""]],
	"6008214":[[26,"京都市下京区","東塩小路高倉町","","Shimogyo-ku, Kyoto-shi","Higashishiokoji Takakuracho",""]],
	"6008215":[[26,"京都市下京区","東塩小路釜殿町","","Shimogyo-ku, Kyoto-shi","Higashishiokoji Kamadonocho",""]],
	"6008216":[[26,"京都市下京区","東塩小路町","","Shimogyo-ku, Kyoto-shi","Higashishiokojicho",""]],
	"6008217":[[26,"京都市下京区","東境町","","Shimogyo-ku, Kyoto-shi","Higashisakaicho",""]],
	"6008218":[[26,"京都市下京区","西境町","","Shimogyo-ku, Kyoto-shi","Nishisakaicho",""]],
	"6008219":[[26,"京都市下京区","中居町","","Shimogyo-ku, Kyoto-shi","Nakaicho",""]],
	"6008221":[[26,"京都市下京区","高雄町","","Shimogyo-ku, Kyoto-shi","Takaocho",""]],
	"6008222":[[26,"京都市下京区","文覚町","","Shimogyo-ku, Kyoto-shi","Mongakucho",""]],
	"6008223":[[26,"京都市下京区","大黒町","","Shimogyo-ku, Kyoto-shi","Daikokucho",""],[26,"京都市下京区","入、下魚棚通油小路東入、下魚棚通西","","Shimogyo-ku, Kyoto-shi","Daikokucho",""],[26,"京都市下京区","筋通七条下る、東中筋通下魚棚下る）","","Shimogyo-ku, Kyoto-shi","Daikokucho",""]],
	"6008224":[[26,"京都市下京区","東町","","Shimogyo-ku, Kyoto-shi","Higashicho",""]],
	"6008225":[[26,"京都市下京区","東大工町","","Shimogyo-ku, Kyoto-shi","Higashidaikucho",""]],
	"6008226":[[26,"京都市下京区","土橋町","","Shimogyo-ku, Kyoto-shi","Tsuchihashicho",""]],
	"6008227":[[26,"京都市下京区","菱屋町","","Shimogyo-ku, Kyoto-shi","Hishiyacho",""]],
	"6008228":[[26,"京都市下京区","北小路町","","Shimogyo-ku, Kyoto-shi","Kitakojicho",""]],
	"6008229":[[26,"京都市下京区","米屋町","","Shimogyo-ku, Kyoto-shi","Komeyacho",""]],
	"6008231":[[26,"京都市下京区","油小路町","","Shimogyo-ku, Kyoto-shi","Aburanokojicho",""]],
	"6008232":[[26,"京都市下京区","南町","","Shimogyo-ku, Kyoto-shi","Minamimachi",""]],
	"6008233":[[26,"京都市下京区","北不動堂町","","Shimogyo-ku, Kyoto-shi","Kitafudondocho",""]],
	"6008234":[[26,"京都市下京区","南不動堂町","","Shimogyo-ku, Kyoto-shi","Minamifudondocho",""]],
	"6008235":[[26,"京都市下京区","東油小路町","","Shimogyo-ku, Kyoto-shi","Higashiaburanokojicho",""]],
	"6008236":[[26,"京都市下京区","西油小路町","","Shimogyo-ku, Kyoto-shi","Nishiaburanokojicho",""]],
	"6008237":[[26,"京都市下京区","松明町","","Shimogyo-ku, Kyoto-shi","Taimatsucho",""]],
	"6008238":[[26,"京都市下京区","御方紺屋町","","Shimogyo-ku, Kyoto-shi","Mikatakonyacho",""]],
	"6008239":[[26,"京都市下京区","鎌屋町","","Shimogyo-ku, Kyoto-shi","Kamayacho",""]],
	"6008241":[[26,"京都市下京区","志水町","","Shimogyo-ku, Kyoto-shi","Shimizucho",""]],
	"6008242":[[26,"京都市下京区","上夷町","","Shimogyo-ku, Kyoto-shi","Kamiebisucho",""]],
	"6008243":[[26,"京都市下京区","南夷町","","Shimogyo-ku, Kyoto-shi","Minamiebisucho",""]],
	"6008244":[[26,"京都市下京区","坊門中之町","","Shimogyo-ku, Kyoto-shi","Bomonnakanocho",""]],
	"6008245":[[26,"京都市下京区","古御旅町","","Shimogyo-ku, Kyoto-shi","Furuotabicho",""]],
	"6008246":[[26,"京都市下京区","垣ケ内町","","Shimogyo-ku, Kyoto-shi","Kakigauchicho",""]],
	"6008247":[[26,"京都市下京区","八条坊門町","","Shimogyo-ku, Kyoto-shi","Hachijobomoncho",""]],
	"6008248":[[26,"京都市下京区","上中之町","","Shimogyo-ku, Kyoto-shi","Kaminakanocho",""]],
	"6008249":[[26,"京都市下京区","下糀屋町","","Shimogyo-ku, Kyoto-shi","Shimokojiyacho",""]],
	"6008251":[[26,"京都市下京区","南八百屋町","","Shimogyo-ku, Kyoto-shi","Minamiyaoyacho",""]],
	"6008252":[[26,"京都市下京区","川端町","","Shimogyo-ku, Kyoto-shi","Kawabatacho",""]],
	"6008253":[[26,"京都市下京区","木津屋町","","Shimogyo-ku, Kyoto-shi","Kizuyacho",""]],
	"6008254":[[26,"京都市下京区","伊勢松町","","Shimogyo-ku, Kyoto-shi","Isematsucho",""]],
	"6008255":[[26,"京都市下京区","清水町","","Shimogyo-ku, Kyoto-shi","Shimizucho",""],[26,"京都市下京区","橋下る、堀川通塩小路西入）","","Shimogyo-ku, Kyoto-shi","Shimizucho",""]],
	"6008256":[[26,"京都市下京区","松本町","","Shimogyo-ku, Kyoto-shi","Matsumotocho",""]],
	"6008257":[[26,"京都市下京区","三軒替地町","","Shimogyo-ku, Kyoto-shi","Sangengaechicho",""]],
	"6008258":[[26,"京都市下京区","金換町","","Shimogyo-ku, Kyoto-shi","Kanegaecho",""]],
	"6008259":[[26,"京都市下京区","上糀屋町","","Shimogyo-ku, Kyoto-shi","Kamikojiyacho",""]],
	"6008261":[[26,"京都市下京区","花園町","","Shimogyo-ku, Kyoto-shi","Hanazonocho",""]],
	"6008262":[[26,"京都市下京区","八百屋町","","Shimogyo-ku, Kyoto-shi","Yaoyacho",""],[26,"京都市下京区","入、七条通堀川西入下る、東堀川通七","","Shimogyo-ku, Kyoto-shi","Yaoyacho",""]],
	"6008263":[[26,"京都市下京区","下魚棚","","Shimogyo-ku, Kyoto-shi","Shimoonotana",""]],
	"6008264":[[26,"京都市下京区","樽屋町","","Shimogyo-ku, Kyoto-shi","Taruyacho",""]],
	"6008265":[[26,"京都市下京区","徹宝町","","Shimogyo-ku, Kyoto-shi","Teppocho",""]],
	"6008266":[[26,"京都市下京区","上之町","","Shimogyo-ku, Kyoto-shi","Kaminocho",""],[26,"京都市下京区","る、木津屋橋通大宮東入、下魚棚通大","","Shimogyo-ku, Kyoto-shi","Kaminocho",""]],
	"6008267":[[26,"京都市下京区","御器屋町","","Shimogyo-ku, Kyoto-shi","Gokiyacho",""]],
	"6008268":[[26,"京都市下京区","大工町","","Shimogyo-ku, Kyoto-shi","Daikucho",""],[26,"京都市下京区","条通猪熊西入、七条通大宮東入、下魚","","Shimogyo-ku, Kyoto-shi","Daikucho",""],[26,"京都市下京区","下魚棚通大宮東入下る、下魚棚通黒門","","Shimogyo-ku, Kyoto-shi","Daikucho",""]],
	"6008269":[[26,"京都市下京区","西八百屋町","","Shimogyo-ku, Kyoto-shi","Nishiyaoyacho",""]],
	"6008301":[[26,"京都市下京区","上柳町","","Shimogyo-ku, Kyoto-shi","Kamiyanagicho",""],[26,"京都市下京区","上る、楊梅通室町西入）","","Shimogyo-ku, Kyoto-shi","Kamiyanagicho",""]],
	"6008302":[[26,"京都市下京区","蛭子町","","Shimogyo-ku, Kyoto-shi","Ebisucho",""]],
	"6008303":[[26,"京都市下京区","銭屋町","","Shimogyo-ku, Kyoto-shi","Zeniyacho",""]],
	"6008304":[[26,"京都市下京区","艮町","","Shimogyo-ku, Kyoto-shi","Ushitoracho",""]],
	"6008305":[[26,"京都市下京区","東若松町","","Shimogyo-ku, Kyoto-shi","Higashiwakamatsucho",""]],
	"6008306":[[26,"京都市下京区","平野町","","Shimogyo-ku, Kyoto-shi","Hiranocho",""]],
	"6008307":[[26,"京都市下京区","辰巳町","","Shimogyo-ku, Kyoto-shi","Tatsumicho",""]],
	"6008308":[[26,"京都市下京区","新シ町","","Shimogyo-ku, Kyoto-shi","Atarashicho",""]],
	"6008310":[[26,"京都市下京区","夷之町","","Shimogyo-ku, Kyoto-shi","Ebisunocho",""],[26,"京都市下京区","入、七条通西洞院東入、新町通七条上","","Shimogyo-ku, Kyoto-shi","Ebisunocho",""],[26,"京都市下京区","東入、西洞院通七条上る）","","Shimogyo-ku, Kyoto-shi","Ebisunocho",""]],
	"6008311":[[26,"京都市下京区","毘沙門町","","Shimogyo-ku, Kyoto-shi","Bishamoncho",""]],
	"6008312":[[26,"京都市下京区","上錫屋町","","Shimogyo-ku, Kyoto-shi","Kamisuzuyacho",""]],
	"6008313":[[26,"京都市下京区","上若宮町","","Shimogyo-ku, Kyoto-shi","Kamiwakamiyacho",""]],
	"6008314":[[26,"京都市下京区","若宮町","","Shimogyo-ku, Kyoto-shi","Wakamiyacho",""],[26,"京都市下京区","町西入、六条通西洞院東入、六条通若","","Shimogyo-ku, Kyoto-shi","Wakamiyacho",""],[26,"京都市下京区","新花屋町上る、若宮通新花屋町下る、","","Shimogyo-ku, Kyoto-shi","Wakamiyacho",""],[26,"京都市下京区","宮通六条下る）","","Shimogyo-ku, Kyoto-shi","Wakamiyacho",""]],
	"6008315":[[26,"京都市下京区","東松屋町","","Shimogyo-ku, Kyoto-shi","Higashimatsuyacho",""]],
	"6008316":[[26,"京都市下京区","四本松町","","Shimogyo-ku, Kyoto-shi","Shihommatsucho",""]],
	"6008317":[[26,"京都市下京区","鍵屋町","","Shimogyo-ku, Kyoto-shi","Kagiyacho",""],[26,"京都市下京区","西入、若宮通正面下る、若宮通北小路","","Shimogyo-ku, Kyoto-shi","Kagiyacho",""]],
	"6008318":[[26,"京都市下京区","井筒町","","Shimogyo-ku, Kyoto-shi","Izutsucho",""]],
	"6008319":[[26,"京都市下京区","竹屋町","","Shimogyo-ku, Kyoto-shi","Takeyacho",""]],
	"6008320":[[26,"京都市下京区","福本町","","Shimogyo-ku, Kyoto-shi","Fukumotocho",""]],
	"6008321":[[26,"京都市下京区","八百屋町","","Shimogyo-ku, Kyoto-shi","Yaoyacho",""],[26,"京都市下京区","入、楊梅通若宮西入）","","Shimogyo-ku, Kyoto-shi","Yaoyacho",""]],
	"6008322":[[26,"京都市下京区","小柳町","","Shimogyo-ku, Kyoto-shi","Koyanagicho",""]],
	"6008323":[[26,"京都市下京区","金屋町","","Shimogyo-ku, Kyoto-shi","Kanayacho",""]],
	"6008324":[[26,"京都市下京区","東側町","","Shimogyo-ku, Kyoto-shi","Higashigawacho",""]],
	"6008325":[[26,"京都市下京区","西側町","","Shimogyo-ku, Kyoto-shi","Nishigawacho",""]],
	"6008326":[[26,"京都市下京区","西松屋町","","Shimogyo-ku, Kyoto-shi","Nishimatsuyacho",""]],
	"6008327":[[26,"京都市下京区","西洞院町","","Shimogyo-ku, Kyoto-shi","Nishinotoincho",""]],
	"6008328":[[26,"京都市下京区","蛭子水町","","Shimogyo-ku, Kyoto-shi","Ebisumizucho",""]],
	"6008329":[[26,"京都市下京区","鍛冶屋町","","Shimogyo-ku, Kyoto-shi","Kajiyacho",""],[26,"京都市下京区","北小路上る、西洞院通正面下る）","","Shimogyo-ku, Kyoto-shi","Kajiyacho",""]],
	"6008331":[[26,"京都市下京区","金東横町","","Shimogyo-ku, Kyoto-shi","Kintoyokocho",""]],
	"6008332":[[26,"京都市下京区","中金仏町","","Shimogyo-ku, Kyoto-shi","Nakakanabutsucho",""]],
	"6008333":[[26,"京都市下京区","卜味金仏町","","Shimogyo-ku, Kyoto-shi","Bokumikanabutsucho",""]],
	"6008334":[[26,"京都市下京区","西若松町","","Shimogyo-ku, Kyoto-shi","Nishiwakamatsucho",""]],
	"6008335":[[26,"京都市下京区","住吉町","","Shimogyo-ku, Kyoto-shi","Sumiyoshicho",""]],
	"6008336":[[26,"京都市下京区","元日町","","Shimogyo-ku, Kyoto-shi","Ganjitsucho",""]],
	"6008337":[[26,"京都市下京区","佐女牛井町","","Shimogyo-ku, Kyoto-shi","Samegaicho",""]],
	"6008338":[[26,"京都市下京区","泉水町","","Shimogyo-ku, Kyoto-shi","Sensuicho",""]],
	"6008340":[[26,"京都市下京区","花屋町","","Shimogyo-ku, Kyoto-shi","Hanayacho",""]],
	"6008341":[[26,"京都市下京区","学林町","","Shimogyo-ku, Kyoto-shi","Gakurincho",""]],
	"6008342":[[26,"京都市下京区","山川町","","Shimogyo-ku, Kyoto-shi","Yamakawacho",""]],
	"6008343":[[26,"京都市下京区","植松町","","Shimogyo-ku, Kyoto-shi","Uematsucho",""]],
	"6008344":[[26,"京都市下京区","柳町","","Shimogyo-ku, Kyoto-shi","Yanagicho",""]],
	"6008345":[[26,"京都市下京区","紅葉町","","Shimogyo-ku, Kyoto-shi","Momijicho",""]],
	"6008346":[[26,"京都市下京区","玉本町","","Shimogyo-ku, Kyoto-shi","Tamamotocho",""]],
	"6008347":[[26,"京都市下京区","仏具屋町","","Shimogyo-ku, Kyoto-shi","Butsuguyacho",""],[26,"京都市下京区","東入、花屋町通油小路東入）","","Shimogyo-ku, Kyoto-shi","Butsuguyacho",""]],
	"6008348":[[26,"京都市下京区","珠数屋町","","Shimogyo-ku, Kyoto-shi","Juzuyacho",""]],
	"6008349":[[26,"京都市下京区","堺町","","Shimogyo-ku, Kyoto-shi","Sakaicho",""]],
	"6008351":[[26,"京都市下京区","富永町","","Shimogyo-ku, Kyoto-shi","Tominagacho",""],[26,"京都市下京区","辻通岩上西入、高辻通岩上東入、高辻","","Shimogyo-ku, Kyoto-shi","Tominagacho",""]],
	"6008352":[[26,"京都市下京区","吉文字町","","Shimogyo-ku, Kyoto-shi","Kichimonjicho",""]],
	"6008353":[[26,"京都市下京区","高辻猪熊町","","Shimogyo-ku, Kyoto-shi","Takatsuji Inokumacho",""]],
	"6008354":[[26,"京都市下京区","十文字町","","Shimogyo-ku, Kyoto-shi","Jumonjicho",""]],
	"6008355":[[26,"京都市下京区","来迎堂町","","Shimogyo-ku, Kyoto-shi","Raikodocho",""]],
	"6008356":[[26,"京都市下京区","北門前町","","Shimogyo-ku, Kyoto-shi","Kitamonzencho",""]],
	"6008357":[[26,"京都市下京区","柿本町","","Shimogyo-ku, Kyoto-shi","Kakimotocho",""]],
	"6008358":[[26,"京都市下京区","門前町","","Shimogyo-ku, Kyoto-shi","Monzencho",""]],
	"6008359":[[26,"京都市下京区","丸屋町","","Shimogyo-ku, Kyoto-shi","Maruyacho",""],[26,"京都市下京区","入、綾小路通黒門東入、猪熊通綾小路","","Shimogyo-ku, Kyoto-shi","Maruyacho",""],[26,"京都市下京区","路下る）","","Shimogyo-ku, Kyoto-shi","Maruyacho",""]],
	"6008361":[[26,"京都市下京区","堀之上町","","Shimogyo-ku, Kyoto-shi","Horinogamicho",""]],
	"6008362":[[26,"京都市下京区","中堂寺前町","","Shimogyo-ku, Kyoto-shi","Chudoji Maecho",""]],
	"6008363":[[26,"京都市下京区","大宮","","Shimogyo-ku, Kyoto-shi","Omiya",""]],
	"6008364":[[26,"京都市下京区","突抜","","Shimogyo-ku, Kyoto-shi","Tsukinuke",""]],
	"6008365":[[26,"京都市下京区","丹波街道町","","Shimogyo-ku, Kyoto-shi","Tambakaidocho",""]],
	"6008371":[[26,"京都市下京区","西門前町","","Shimogyo-ku, Kyoto-shi","Nishimonzencho",""]],
	"6008372":[[26,"京都市下京区","南門前町","","Shimogyo-ku, Kyoto-shi","Minamimonzencho",""]],
	"6008373":[[26,"京都市下京区","下五条町","","Shimogyo-ku, Kyoto-shi","Shimogojocho",""]],
	"6008374":[[26,"京都市下京区","藪之内町","","Shimogyo-ku, Kyoto-shi","Yabunochicho",""]],
	"6008375":[[26,"京都市下京区","下長福寺町","","Shimogyo-ku, Kyoto-shi","Shimochofukujicho",""]],
	"6008376":[[26,"京都市下京区","上長福寺町","","Shimogyo-ku, Kyoto-shi","Kamichofukujicho",""]],
	"6008377":[[26,"京都市下京区","上五条町","","Shimogyo-ku, Kyoto-shi","Kamigojocho",""]],
	"6008381":[[26,"京都市下京区","下り松町","","Shimogyo-ku, Kyoto-shi","Sagarimatsucho",""]],
	"6008382":[[26,"京都市下京区","塩屋町","","Shimogyo-ku, Kyoto-shi","Shioyacho",""]],
	"6008383":[[26,"京都市下京区","綾大宮町","","Shimogyo-ku, Kyoto-shi","Ayaomiyacho",""]],
	"6008384":[[26,"京都市下京区","今大黒町","","Shimogyo-ku, Kyoto-shi","Imadaikokucho",""]],
	"6008385":[[26,"京都市下京区","五坊大宮町","","Shimogyo-ku, Kyoto-shi","Goboomiyacho",""]],
	"6008386":[[26,"京都市下京区","杉蛭子町","","Shimogyo-ku, Kyoto-shi","Sugiebisucho",""]],
	"6008387":[[26,"京都市下京区","高辻大宮町","","Shimogyo-ku, Kyoto-shi","Takatsuji Omiyacho",""]],
	"6008388":[[26,"京都市下京区","坊門町","","Shimogyo-ku, Kyoto-shi","Bomoncho",""]],
	"6008389":[[26,"京都市下京区","四条大宮町","","Shimogyo-ku, Kyoto-shi","Shijo Omiyacho",""]],
	"6008390":[[26,"京都市下京区","松本町","","Shimogyo-ku, Kyoto-shi","Matsumotocho",""]],
	"6008391":[[26,"京都市下京区","佐竹町","","Shimogyo-ku, Kyoto-shi","Satakecho",""]],
	"6008392":[[26,"京都市下京区","妙満寺町","","Shimogyo-ku, Kyoto-shi","Myomanjicho",""]],
	"6008393":[[26,"京都市下京区","雁金町","","Shimogyo-ku, Kyoto-shi","Kariganecho",""]],
	"6008394":[[26,"京都市下京区","晒屋町","","Shimogyo-ku, Kyoto-shi","Sarashiyacho",""]],
	"6008395":[[26,"京都市下京区","徳屋町","","Shimogyo-ku, Kyoto-shi","Tokuyacho",""]],
	"6008396":[[26,"京都市下京区","槌屋町","","Shimogyo-ku, Kyoto-shi","Tsuchiyacho",""]],
	"6008397":[[26,"京都市下京区","西田町","","Shimogyo-ku, Kyoto-shi","Nishidacho",""]],
	"6008398":[[26,"京都市下京区","瀬戸屋町","","Shimogyo-ku, Kyoto-shi","Setoyacho",""]],
	"6008399":[[26,"京都市下京区","丸屋町","","Shimogyo-ku, Kyoto-shi","Maruyacho",""],[26,"京都市下京区","面下る、北小路通堀川東入、堀川通北","","Shimogyo-ku, Kyoto-shi","Maruyacho",""]],
	"6008401":[[26,"京都市下京区","燈籠町","","Shimogyo-ku, Kyoto-shi","Torocho",""]],
	"6008402":[[26,"京都市下京区","大江町","","Shimogyo-ku, Kyoto-shi","Oecho",""]],
	"6008403":[[26,"京都市下京区","吉水町","","Shimogyo-ku, Kyoto-shi","Yoshimizucho",""]],
	"6008404":[[26,"京都市下京区","福田寺町","","Shimogyo-ku, Kyoto-shi","Fukudenjicho",""]],
	"6008405":[[26,"京都市下京区","万寿寺中之町","","Shimogyo-ku, Kyoto-shi","Manjujinakanocho",""]],
	"6008406":[[26,"京都市下京区","亀屋町","","Shimogyo-ku, Kyoto-shi","Kameyacho",""]],
	"6008407":[[26,"京都市下京区","朝妻町","","Shimogyo-ku, Kyoto-shi","Asazumacho",""]],
	"6008408":[[26,"京都市下京区","深草町","","Shimogyo-ku, Kyoto-shi","Fukakusacho",""]],
	"6008409":[[26,"京都市下京区","玉屋町","","Shimogyo-ku, Kyoto-shi","Tamayacho",""]],
	"6008410":[[26,"京都市下京区","悪王子町","","Shimogyo-ku, Kyoto-shi","Akuojicho",""]],
	"6008411":[[26,"京都市下京区","水銀屋町","","Shimogyo-ku, Kyoto-shi","Suiginyacho",""]],
	"6008412":[[26,"京都市下京区","二帖半敷町","","Shimogyo-ku, Kyoto-shi","Nijohanjikicho",""]],
	"6008413":[[26,"京都市下京区","大政所町","","Shimogyo-ku, Kyoto-shi","Omandokorocho",""]],
	"6008414":[[26,"京都市下京区","匂天神町","","Shimogyo-ku, Kyoto-shi","Nioitenjincho",""]],
	"6008415":[[26,"京都市下京区","因幡堂町","","Shimogyo-ku, Kyoto-shi","Inabadocho",""]],
	"6008416":[[26,"京都市下京区","薬師前町","","Shimogyo-ku, Kyoto-shi","Yakushimaecho",""]],
	"6008417":[[26,"京都市下京区","俊成町","","Shimogyo-ku, Kyoto-shi","Shunzeicho",""]],
	"6008418":[[26,"京都市下京区","五条烏丸町","","Shimogyo-ku, Kyoto-shi","Gojokarasumacho",""]],
	"6008419":[[26,"京都市下京区","大堀町","","Shimogyo-ku, Kyoto-shi","Oboricho",""]],
	"6008420":[[26,"京都市下京区","高砂町","","Shimogyo-ku, Kyoto-shi","Takasagocho",""]],
	"6008421":[[26,"京都市下京区","童侍者町","","Shimogyo-ku, Kyoto-shi","Dojishacho",""]],
	"6008422":[[26,"京都市下京区","白楽天町","","Shimogyo-ku, Kyoto-shi","Hakurakutencho",""]],
	"6008423":[[26,"京都市下京区","釘隠町","","Shimogyo-ku, Kyoto-shi","Kugikakushicho",""]],
	"6008424":[[26,"京都市下京区","山王町","","Shimogyo-ku, Kyoto-shi","Sannocho",""]],
	"6008425":[[26,"京都市下京区","骨屋町","","Shimogyo-ku, Kyoto-shi","Honeyacho",""]],
	"6008426":[[26,"京都市下京区","小島町","","Shimogyo-ku, Kyoto-shi","Kojimacho",""]],
	"6008427":[[26,"京都市下京区","玉津島町","","Shimogyo-ku, Kyoto-shi","Tamatsushimacho",""]],
	"6008428":[[26,"京都市下京区","弁財天町","","Shimogyo-ku, Kyoto-shi","Benzaitencho",""]],
	"6008429":[[26,"京都市下京区","御供石町","","Shimogyo-ku, Kyoto-shi","Gokuishicho",""]],
	"6008430":[[26,"京都市下京区","小田原町","","Shimogyo-ku, Kyoto-shi","Odawaracho",""]],
	"6008431":[[26,"京都市下京区","善長寺町","","Shimogyo-ku, Kyoto-shi","Zenchojicho",""]],
	"6008432":[[26,"京都市下京区","糸屋町","","Shimogyo-ku, Kyoto-shi","Itoyacho",""]],
	"6008433":[[26,"京都市下京区","繁昌町","","Shimogyo-ku, Kyoto-shi","Hanjocho",""]],
	"6008434":[[26,"京都市下京区","高辻町","","Shimogyo-ku, Kyoto-shi","Takatsujicho",""]],
	"6008435":[[26,"京都市下京区","中野之町","","Shimogyo-ku, Kyoto-shi","Nakanonocho",""]],
	"6008436":[[26,"京都市下京区","元両替町","","Shimogyo-ku, Kyoto-shi","Motoryogaecho",""]],
	"6008437":[[26,"京都市下京区","徳万町","","Shimogyo-ku, Kyoto-shi","Tokumancho",""]],
	"6008438":[[26,"京都市下京区","長刀切町","","Shimogyo-ku, Kyoto-shi","Naginatagiricho",""]],
	"6008439":[[26,"京都市下京区","坂東屋町","","Shimogyo-ku, Kyoto-shi","Bantoyacho",""]],
	"6008440":[[26,"京都市下京区","材木町","","Shimogyo-ku, Kyoto-shi","Zaimokucho",""],[26,"京都市下京区","万寿寺通新町東入）","","Shimogyo-ku, Kyoto-shi","Zaimokucho",""]],
	"6008441":[[26,"京都市下京区","四条町","","Shimogyo-ku, Kyoto-shi","Shijocho",""]],
	"6008442":[[26,"京都市下京区","矢田町","","Shimogyo-ku, Kyoto-shi","Yadacho",""]],
	"6008443":[[26,"京都市下京区","船鉾町","","Shimogyo-ku, Kyoto-shi","Funebokocho",""]],
	"6008444":[[26,"京都市下京区","菅大臣町","","Shimogyo-ku, Kyoto-shi","Kandaijincho",""]],
	"6008445":[[26,"京都市下京区","岩戸山町","","Shimogyo-ku, Kyoto-shi","Iwatoyamacho",""]],
	"6008446":[[26,"京都市下京区","堀之内町","","Shimogyo-ku, Kyoto-shi","Horinochicho",""]],
	"6008447":[[26,"京都市下京区","御影町","","Shimogyo-ku, Kyoto-shi","Mikagecho",""]],
	"6008448":[[26,"京都市下京区","藪下町","","Shimogyo-ku, Kyoto-shi","Yabushitacho",""]],
	"6008449":[[26,"京都市下京区","富永町","","Shimogyo-ku, Kyoto-shi","Tominagacho",""],[26,"京都市下京区","万寿寺通新町東入）","","Shimogyo-ku, Kyoto-shi","Tominagacho",""]],
	"6008451":[[26,"京都市下京区","亀屋町","","Shimogyo-ku, Kyoto-shi","Kameyacho",""]],
	"6008452":[[26,"京都市下京区","永倉町","","Shimogyo-ku, Kyoto-shi","Nagakuracho",""]],
	"6008453":[[26,"京都市下京区","月見町","","Shimogyo-ku, Kyoto-shi","Tsukimicho",""]],
	"6008454":[[26,"京都市下京区","布屋町","","Shimogyo-ku, Kyoto-shi","Nunoyacho",""]],
	"6008455":[[26,"京都市下京区","八幡町","","Shimogyo-ku, Kyoto-shi","Yawatacho",""]],
	"6008456":[[26,"京都市下京区","天使突抜","","Shimogyo-ku, Kyoto-shi","Tenshitsukinuke",""]],
	"6008457":[[26,"京都市下京区","上金仏町","","Shimogyo-ku, Kyoto-shi","Kamikanabutsucho",""]],
	"6008458":[[26,"京都市下京区","樋口町","","Shimogyo-ku, Kyoto-shi","Higuchicho",""]],
	"6008459":[[26,"京都市下京区","天神前町","","Shimogyo-ku, Kyoto-shi","Tenjimmaecho",""]],
	"6008460":[[26,"京都市下京区","荒神町","","Shimogyo-ku, Kyoto-shi","Kojincho",""]],
	"6008461":[[26,"京都市下京区","木賊山町","","Shimogyo-ku, Kyoto-shi","Tokusayamacho",""]],
	"6008462":[[26,"京都市下京区","本柳水町","","Shimogyo-ku, Kyoto-shi","Honryusuicho",""]],
	"6008463":[[26,"京都市下京区","永養寺町","","Shimogyo-ku, Kyoto-shi","Eiyojicho",""]],
	"6008464":[[26,"京都市下京区","菊屋町","","Shimogyo-ku, Kyoto-shi","Kikuyacho",""],[26,"京都市下京区","下る、若宮通松原上る）","","Shimogyo-ku, Kyoto-shi","Kikuyacho",""]],
	"6008465":[[26,"京都市下京区","高辻西洞院町","","Shimogyo-ku, Kyoto-shi","Takatsuji Nishinotoincho",""]],
	"6008466":[[26,"京都市下京区","舟屋町","","Shimogyo-ku, Kyoto-shi","Funayacho",""]],
	"6008467":[[26,"京都市下京区","麓町","","Shimogyo-ku, Kyoto-shi","Fumotocho",""]],
	"6008468":[[26,"京都市下京区","住吉町","","Shimogyo-ku, Kyoto-shi","Sumiyoshicho",""],[26,"京都市下京区","通新花屋町下る、西中筋通花屋町上る","","Shimogyo-ku, Kyoto-shi","Sumiyoshicho",""],[26,"京都市下京区","入、堀川通新花屋町上る、堀川通新花","","Shimogyo-ku, Kyoto-shi","Sumiyoshicho",""],[26,"京都市下京区","下る）","","Shimogyo-ku, Kyoto-shi","Sumiyoshicho",""]],
	"6008469":[[26,"京都市下京区","太子山町","","Shimogyo-ku, Kyoto-shi","Taishiyamacho",""]],
	"6008471":[[26,"京都市下京区","新釜座町","","Shimogyo-ku, Kyoto-shi","Shinkamanzacho",""]],
	"6008472":[[26,"京都市下京区","妙伝寺町","","Shimogyo-ku, Kyoto-shi","Myodenjicho",""]],
	"6008473":[[26,"京都市下京区","芦刈山町","","Shimogyo-ku, Kyoto-shi","Ashikariyamacho",""]],
	"6008474":[[26,"京都市下京区","綾西洞院町","","Shimogyo-ku, Kyoto-shi","Ayanishinotoincho",""]],
	"6008475":[[26,"京都市下京区","風早町","","Shimogyo-ku, Kyoto-shi","Kazahayacho",""]],
	"6008476":[[26,"京都市下京区","喜吉町","","Shimogyo-ku, Kyoto-shi","Kiyoshicho",""]],
	"6008477":[[26,"京都市下京区","要法寺町","","Shimogyo-ku, Kyoto-shi","Yohojicho",""]],
	"6008478":[[26,"京都市下京区","西綾小路西半町","","Shimogyo-ku, Kyoto-shi","Nishiayanokoji Nishihancho",""]],
	"6008479":[[26,"京都市下京区","西綾小路東半町","","Shimogyo-ku, Kyoto-shi","Nishiayanokoji Higashihancho",""]],
	"6008480":[[26,"京都市下京区","小泉町","","Shimogyo-ku, Kyoto-shi","Koizumicho",""]],
	"6008481":[[26,"京都市下京区","四条堀川町","","Shimogyo-ku, Kyoto-shi","Shijo Horikawacho",""]],
	"6008482":[[26,"京都市下京区","綾堀川町","","Shimogyo-ku, Kyoto-shi","Ayahorikawacho",""]],
	"6008483":[[26,"京都市下京区","吉水町","","Shimogyo-ku, Kyoto-shi","Yoshimizucho",""],[26,"京都市下京区","上る、東堀川通仏光寺下る、仏光寺通","","Shimogyo-ku, Kyoto-shi","Yoshimizucho",""]],
	"6008484":[[26,"京都市下京区","西高辻町","","Shimogyo-ku, Kyoto-shi","Nishitakatsujicho",""]],
	"6008485":[[26,"京都市下京区","五軒町","","Shimogyo-ku, Kyoto-shi","Gokencho",""]],
	"6008486":[[26,"京都市下京区","高辻堀川町","","Shimogyo-ku, Kyoto-shi","Takatsuji Horikawacho",""]],
	"6008487":[[26,"京都市下京区","橘町","","Shimogyo-ku, Kyoto-shi","Tachibanacho",""],[26,"京都市下京区","入、松原通醒ケ井西入、松原通醒ケ井","","Shimogyo-ku, Kyoto-shi","Tachibanacho",""],[26,"京都市下京区","川東入）","","Shimogyo-ku, Kyoto-shi","Tachibanacho",""]],
	"6008488":[[26,"京都市下京区","篠屋町","","Shimogyo-ku, Kyoto-shi","Sasayacho",""]],
	"6008489":[[26,"京都市下京区","橋橘町","","Shimogyo-ku, Kyoto-shi","Hashitachibanacho",""]],
	"6008490":[[26,"京都市下京区","立中町","","Shimogyo-ku, Kyoto-shi","Tatsunakacho",""]],
	"6008491":[[26,"京都市下京区","鶏鉾町","","Shimogyo-ku, Kyoto-shi","Niwatoribokocho",""]],
	"6008492":[[26,"京都市下京区","月鉾町","","Shimogyo-ku, Kyoto-shi","Tsukihokocho",""]],
	"6008493":[[26,"京都市下京区","郭巨山町","","Shimogyo-ku, Kyoto-shi","Katsukyoyamacho",""]],
	"6008494":[[26,"京都市下京区","傘鉾町","","Shimogyo-ku, Kyoto-shi","Kasabokocho",""]],
	"6008495":[[26,"京都市下京区","藤本寄町","","Shimogyo-ku, Kyoto-shi","Fujimotoyoricho",""]],
	"6008496":[[26,"京都市下京区","石井筒町","","Shimogyo-ku, Kyoto-shi","Ishiizutsucho",""]],
	"6008497":[[26,"京都市下京区","高野堂町","","Shimogyo-ku, Kyoto-shi","Koyadocho",""]],
	"6008498":[[26,"京都市下京区","柏屋町","","Shimogyo-ku, Kyoto-shi","Kashiwayacho",""],[26,"京都市下京区","東入、四条通東堀川東入、四条通堀川","","Shimogyo-ku, Kyoto-shi","Kashiwayacho",""]],
	"6008499":[[26,"京都市下京区","唐津屋町","","Shimogyo-ku, Kyoto-shi","Karatsuyacho",""]],
	"6008801":[[26,"京都市下京区","中堂寺西寺町","","Shimogyo-ku, Kyoto-shi","Chudoji Nishideracho",""]],
	"6008802":[[26,"京都市下京区","中堂寺櫛笥町","","Shimogyo-ku, Kyoto-shi","Chudoji Kushigecho",""]],
	"6008803":[[26,"京都市下京区","中堂寺薮ノ内町","","Shimogyo-ku, Kyoto-shi","Chudoji Yabunochicho",""]],
	"6008804":[[26,"京都市下京区","中堂寺前田町","","Shimogyo-ku, Kyoto-shi","Chudoji Maedacho",""]],
	"6008805":[[26,"京都市下京区","中堂寺鍵田町","","Shimogyo-ku, Kyoto-shi","Chudoji Kagitacho",""]],
	"6008806":[[26,"京都市下京区","中堂寺壬生川町","","Shimogyo-ku, Kyoto-shi","Chudoji Mibugawacho",""]],
	"6008807":[[26,"京都市下京区","中堂寺命婦町","","Shimogyo-ku, Kyoto-shi","Chudoji Myobucho",""]],
	"6008811":[[26,"京都市下京区","中堂寺坊城町","","Shimogyo-ku, Kyoto-shi","Chudoji Bojocho",""]],
	"6008812":[[26,"京都市下京区","中堂寺北町","","Shimogyo-ku, Kyoto-shi","Chudoji Kitamachi",""]],
	"6008813":[[26,"京都市下京区","中堂寺南町","","Shimogyo-ku, Kyoto-shi","Chudoji Minamimachi",""]],
	"6008814":[[26,"京都市下京区","中堂寺庄ノ内町","","Shimogyo-ku, Kyoto-shi","Chudoji Shonochicho",""]],
	"6008815":[[26,"京都市下京区","中堂寺粟田町","","Shimogyo-ku, Kyoto-shi","Chudoji Awatacho",""]],
	"6008816":[[26,"京都市下京区","西新屋敷中堂寺町","","Shimogyo-ku, Kyoto-shi","Nishishinyashikichudojicho",""]],
	"6008821":[[26,"京都市下京区","小坂町","","Shimogyo-ku, Kyoto-shi","Kosakacho",""]],
	"6008822":[[26,"京都市下京区","裏片町","","Shimogyo-ku, Kyoto-shi","Urakatacho",""]],
	"6008823":[[26,"京都市下京区","薬園町","","Shimogyo-ku, Kyoto-shi","Yakuencho",""]],
	"6008824":[[26,"京都市下京区","二人司町","","Shimogyo-ku, Kyoto-shi","Ninintsukasacho",""]],
	"6008825":[[26,"京都市下京区","西新屋敷中之町","","Shimogyo-ku, Kyoto-shi","Nishishinyashikinakanocho",""]],
	"6008826":[[26,"京都市下京区","西新屋敷上之町","","Shimogyo-ku, Kyoto-shi","Nishishinyashikikaminocho",""]],
	"6008827":[[26,"京都市下京区","西新屋敷太夫町","","Shimogyo-ku, Kyoto-shi","Nishishinyashikitayucho",""]],
	"6008828":[[26,"京都市下京区","西新屋敷揚屋町","","Shimogyo-ku, Kyoto-shi","Nishishinyashikiageyacho",""]],
	"6008829":[[26,"京都市下京区","西新屋敷下之町","","Shimogyo-ku, Kyoto-shi","Nishishinyashikishimonocho",""]],
	"6008831":[[26,"京都市下京区","花畑町","","Shimogyo-ku, Kyoto-shi","Hanabatakecho",""]],
	"6008832":[[26,"京都市下京区","諏訪開町","","Shimogyo-ku, Kyoto-shi","Suwabirakicho",""]],
	"6008833":[[26,"京都市下京区","西酢屋町","","Shimogyo-ku, Kyoto-shi","Nishisuyacho",""]],
	"6008834":[[26,"京都市下京区","和気町","","Shimogyo-ku, Kyoto-shi","Wakicho",""]],
	"6008835":[[26,"京都市下京区","観喜寺町","","Shimogyo-ku, Kyoto-shi","Kankijicho",""]],
	"6008836":[[26,"京都市下京区","八条坊門町","","Shimogyo-ku, Kyoto-shi","Hachijobomoncho",""]],
	"6008837":[[26,"京都市下京区","夷馬場町","","Shimogyo-ku, Kyoto-shi","Ebisunobambacho",""]],
	"6008841":[[26,"京都市下京区","朱雀正会町","","Shimogyo-ku, Kyoto-shi","Sujaku Shokaicho",""]],
	"6008842":[[26,"京都市下京区","朱雀堂ノ口町","","Shimogyo-ku, Kyoto-shi","Sujaku Donokuchicho",""]],
	"6008843":[[26,"京都市下京区","朱雀内畑町","","Shimogyo-ku, Kyoto-shi","Sujaku Uchihatacho",""]],
	"6008844":[[26,"京都市下京区","朱雀裏畑町","","Shimogyo-ku, Kyoto-shi","Sujaku Urahatacho",""]],
	"6008845":[[26,"京都市下京区","朱雀北ノ口町","","Shimogyo-ku, Kyoto-shi","Sujaku Kitanokuchicho",""]],
	"6008846":[[26,"京都市下京区","朱雀宝蔵町","","Shimogyo-ku, Kyoto-shi","Sujaku Hozocho",""]],
	"6008847":[[26,"京都市下京区","朱雀分木町","","Shimogyo-ku, Kyoto-shi","Sujaku Bunkicho",""]],
	"6008851":[[26,"京都市下京区","梅小路頭町","","Shimogyo-ku, Kyoto-shi","Umekoji Kashiracho",""]],
	"6008852":[[26,"京都市下京区","梅小路東中町","","Shimogyo-ku, Kyoto-shi","Umekoji Higashinakamachi",""]],
	"6008853":[[26,"京都市下京区","梅小路高畑町","","Shimogyo-ku, Kyoto-shi","Umekoji Takahatacho",""]],
	"6008854":[[26,"京都市下京区","梅小路西中町","","Shimogyo-ku, Kyoto-shi","Umekoji Nishinakamachi",""]],
	"6008855":[[26,"京都市下京区","梅小路石橋町","","Shimogyo-ku, Kyoto-shi","Umekoji Ishibashicho",""]],
	"6008856":[[26,"京都市下京区","梅小路本町","","Shimogyo-ku, Kyoto-shi","Umekoji Hommachi",""]],
	"6008857":[[26,"京都市下京区","梅小路東町","","Shimogyo-ku, Kyoto-shi","Umekoji Higashimachi",""]],
	"6008861":[[26,"京都市下京区","七条御所ノ内北町","","Shimogyo-ku, Kyoto-shi","Shichijogoshonochi Kitamachi",""]],
	"6008862":[[26,"京都市下京区","七条御所ノ内中町","","Shimogyo-ku, Kyoto-shi","Shichijogoshonochi Nakamachi",""]],
	"6008863":[[26,"京都市下京区","七条御所ノ内本町","","Shimogyo-ku, Kyoto-shi","Shichijogoshonochi Hommachi",""]],
	"6008864":[[26,"京都市下京区","七条御所ノ内南町","","Shimogyo-ku, Kyoto-shi","Shichijogoshonochi Minamimachi",""]],
	"6008865":[[26,"京都市下京区","七条御所ノ内西町","","Shimogyo-ku, Kyoto-shi","Shichijogoshonochi Nishimachi",""]],
	"6008871":[[26,"京都市下京区","西七条北東野町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Kitahigashinocho",""]],
	"6008872":[[26,"京都市下京区","西七条南東野町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Minamihigashinocho",""]],
	"6008873":[[26,"京都市下京区","西七条東久保町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Higashikubocho",""]],
	"6008874":[[26,"京都市下京区","西七条西久保町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Nishikubocho",""]],
	"6008875":[[26,"京都市下京区","西七条石井町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Ishiicho",""]],
	"6008876":[[26,"京都市下京区","西七条南中野町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Minaminakanocho",""]],
	"6008877":[[26,"京都市下京区","西七条南西野町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Minaminishinocho",""]],
	"6008878":[[26,"京都市下京区","西七条北西野町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Kitanishinocho",""]],
	"6008879":[[26,"京都市下京区","西七条中野町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Nakanocho",""]],
	"6008881":[[26,"京都市下京区","西七条掛越町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Kakegoshicho",""]],
	"6008882":[[26,"京都市下京区","西七条比輪田町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Hiwadacho",""]],
	"6008883":[[26,"京都市下京区","西七条北衣田町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Kitakinutacho",""]],
	"6008884":[[26,"京都市下京区","西七条南衣田町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Minamikinutacho",""]],
	"6008885":[[26,"京都市下京区","西七条南月読町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Minamitsukiyomicho",""]],
	"6008886":[[26,"京都市下京区","西七条北月読町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Kitatsukiyomicho",""]],
	"6008887":[[26,"京都市下京区","西七条名倉町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Nakuracho",""]],
	"6008888":[[26,"京都市下京区","西七条八幡町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Yawatacho",""]],
	"6008891":[[26,"京都市下京区","西七条東八反田町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Higashihattandacho",""]],
	"6008892":[[26,"京都市下京区","西七条西八反田町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Nishihattandacho",""]],
	"6008893":[[26,"京都市下京区","西七条御領町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Goryocho",""]],
	"6008894":[[26,"京都市下京区","西七条市部町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Ichibecho",""]],
	"6008895":[[26,"京都市下京区","西七条東石ケ坪町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Higashiishigatsubocho",""]],
	"6008896":[[26,"京都市下京区","西七条西石ケ坪町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Nishiishigatsubocho",""]],
	"6008897":[[26,"京都市下京区","西七条御前田町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Ommaedacho",""]],
	"6008898":[[26,"京都市下京区","西七条東御前田町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Higashiommaedacho",""]],
	"6008899":[[26,"京都市下京区","西七条赤社町","","Shimogyo-ku, Kyoto-shi","Nishishichijo Akayashirocho",""]]
})
