zipdata({
	"7780000":[[36,"三好市","","","Miyoshi-shi","",""]],
	"7780001":[[36,"三好市","池田町ウエノ","","Miyoshi-shi","Ikedacho Ueno",""]],
	"7780002":[[36,"三好市","池田町マチ","","Miyoshi-shi","Ikedacho Machi",""]],
	"7780003":[[36,"三好市","池田町サラダ","","Miyoshi-shi","Ikedacho Sarada",""]],
	"7780004":[[36,"三好市","池田町シンマチ","","Miyoshi-shi","Ikedacho Shimmachi",""]],
	"7780005":[[36,"三好市","池田町シマ","","Miyoshi-shi","Ikedacho Shima",""]],
	"7780006":[[36,"三好市","池田町トウゲ","","Miyoshi-shi","Ikedacho Toge",""]],
	"7780007":[[36,"三好市","池田町ヤマダ","","Miyoshi-shi","Ikedacho Yamada",""]],
	"7780008":[[36,"三好市","池田町クヤウジ","","Miyoshi-shi","Ikedacho Kuyauji",""]],
	"7780009":[[36,"三好市","池田町ヤサン","","Miyoshi-shi","Ikedacho Yasan",""]],
	"7780010":[[36,"三好市","池田町ウエマツ","","Miyoshi-shi","Ikedacho Uematsu",""]],
	"7780011":[[36,"三好市","池田町ハヤシ","","Miyoshi-shi","Ikedacho Hayashi",""]],
	"7780012":[[36,"三好市","池田町イケミナミ","","Miyoshi-shi","Ikedacho Ikeminami",""]],
	"7780013":[[36,"三好市","池田町シンヤマ","","Miyoshi-shi","Ikedacho Shinyama",""]],
	"7780014":[[36,"三好市","池田町イタノ","","Miyoshi-shi","Ikedacho Itano",""]],
	"7780020":[[36,"三好市","池田町州津","","Miyoshi-shi","Ikedacho Shuzu",""]],
	"7780031":[[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""]],
	"7780032":[[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""],[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama ",""]],
	"7780040":[[36,"三好市","池田町西山","","Miyoshi-shi","Ikedacho Nishiyama",""]],
	"7780101":[[36,"三好市","西祖谷山村一宇","","Miyoshi-shi","Nishiiyayamamura Ichiu",""],[36,"三好市","西祖谷山村尾井ノ内","","Miyoshi-shi","Nishiiyayamamura Oinochi",""],[36,"三好市","西祖谷山村重末","","Miyoshi-shi","Nishiiyayamamura Shigesue",""],[36,"三好市","西祖谷山村田ノ内","","Miyoshi-shi","Nishiiyayamamura Tanochi",""],[36,"三好市","西祖谷山村戸ノ谷","","Miyoshi-shi","Nishiiyayamamura Tonotani",""],[36,"三好市","西祖谷山村眠谷","","Miyoshi-shi","Nishiiyayamamura Nemuridani",""],[36,"三好市","西祖谷山村冥地","","Miyoshi-shi","Nishiiyayamamura Myoji",""]],
	"7780102":[[36,"三好市","西祖谷山村今久保","","Miyoshi-shi","Nishiiyayamamura Imakubo",""],[36,"三好市","西祖谷山村閑定","","Miyoshi-shi","Nishiiyayamamura Kanjo",""],[36,"三好市","西祖谷山村善徳","","Miyoshi-shi","Nishiiyayamamura Zentoku",""],[36,"三好市","西祖谷山村中尾","","Miyoshi-shi","Nishiiyayamamura Nakao",""]],
	"7780103":[[36,"三好市","西祖谷山村有瀬","","Miyoshi-shi","Nishiiyayamamura Aruse",""]],
	"7780104":[[36,"三好市","西祖谷山村吾橋","","Miyoshi-shi","Nishiiyayamamura Ahashi",""],[36,"三好市","西祖谷山村榎","","Miyoshi-shi","Nishiiyayamamura Enoki",""],[36,"三好市","西祖谷山村上吾橋","","Miyoshi-shi","Nishiiyayamamura Kamiahashi",""],[36,"三好市","西祖谷山村下吾橋","","Miyoshi-shi","Nishiiyayamamura Shimoahashi",""],[36,"三好市","西祖谷山村土日浦","","Miyoshi-shi","Nishiiyayamamura Tsuchihiura",""],[36,"三好市","西祖谷山村東山","","Miyoshi-shi","Nishiiyayamamura Higashiyama",""],[36,"三好市","西祖谷山村南山","","Miyoshi-shi","Nishiiyayamamura Minamiyama",""]],
	"7780105":[[36,"三好市","西祖谷山村後山","","Miyoshi-shi","Nishiiyayamamura Ushiroyama",""],[36,"三好市","西祖谷山村後山西","","Miyoshi-shi","Nishiiyayamamura Ushiroyamanishi",""],[36,"三好市","西祖谷山村後山向","","Miyoshi-shi","Nishiiyayamamura Ushiroyamamukai",""],[36,"三好市","西祖谷山村徳善","","Miyoshi-shi","Nishiiyayamamura Tokuzen",""],[36,"三好市","西祖谷山村徳善北","","Miyoshi-shi","Nishiiyayamamura Tokuzenkita",""],[36,"三好市","西祖谷山村徳善西","","Miyoshi-shi","Nishiiyayamamura Tokuzennishi",""],[36,"三好市","西祖谷山村西岡","","Miyoshi-shi","Nishiiyayamamura Nishioka",""],[36,"三好市","西祖谷山村東西岡","","Miyoshi-shi","Nishiiyayamamura Higashinishioka",""]],
	"7780165":[[36,"三好市","池田町松尾","","Miyoshi-shi","Ikedacho Matsuo",""]],
	"7780201":[[36,"三好市","東祖谷菅生","","Miyoshi-shi","Higashiiya Sugeoi",""],[36,"三好市","東祖谷見ノ越","","Miyoshi-shi","Higashiiya Minokoshi",""]],
	"7780202":[[36,"三好市","東祖谷落合","","Miyoshi-shi","Higashiiya Ochiai",""],[36,"三好市","東祖谷久保","","Miyoshi-shi","Higashiiya Kubo",""]],
	"7780203":[[36,"三好市","東祖谷奥の井","","Miyoshi-shi","Higashiiya Okunoi",""],[36,"三好市","東祖谷釜ケ谷","","Miyoshi-shi","Higashiiya Kamagatani",""],[36,"三好市","東祖谷九鬼","","Miyoshi-shi","Higashiiya Kuki",""],[36,"三好市","東祖谷栗枝渡","","Miyoshi-shi","Higashiiya Kurisudo",""],[36,"三好市","東祖谷下瀬","","Miyoshi-shi","Higashiiya Shimose",""],[36,"三好市","東祖谷中上","","Miyoshi-shi","Higashiiya Nakaue",""],[36,"三好市","東祖谷西山","","Miyoshi-shi","Higashiiya Nishiyama",""],[36,"三好市","東祖谷林","","Miyoshi-shi","Higashiiya Hayashi",""]],
	"7780204":[[36,"三好市","東祖谷大枝","","Miyoshi-shi","Higashiiya Oeda",""],[36,"三好市","東祖谷大西","","Miyoshi-shi","Higashiiya Onishi",""],[36,"三好市","東祖谷京上","","Miyoshi-shi","Higashiiya Kyojo",""],[36,"三好市","東祖谷若林","","Miyoshi-shi","Higashiiya Wakabayashi",""]],
	"7780205":[[36,"三好市","東祖谷阿佐","","Miyoshi-shi","Higashiiya Asa",""],[36,"三好市","東祖谷小川","","Miyoshi-shi","Higashiiya Ogawa",""],[36,"三好市","東祖谷樫尾","","Miyoshi-shi","Higashiiya Kashio",""],[36,"三好市","東祖谷古味","","Miyoshi-shi","Higashiiya Komi",""],[36,"三好市","東祖谷新居屋","","Miyoshi-shi","Higashiiya Niiya",""],[36,"三好市","東祖谷麦生土","","Miyoshi-shi","Higashiiya Mujuto",""],[36,"三好市","東祖谷元井","","Miyoshi-shi","Higashiiya Mottoi",""]],
	"7780206":[[36,"三好市","東祖谷今井","","Miyoshi-shi","Higashiiya Imai",""],[36,"三好市","東祖谷小島","","Miyoshi-shi","Higashiiya Oshima",""],[36,"三好市","東祖谷佐野","","Miyoshi-shi","Higashiiya Sano",""],[36,"三好市","東祖谷高野","","Miyoshi-shi","Higashiiya Takano",""],[36,"三好市","東祖谷釣井","","Miyoshi-shi","Higashiiya Tsurui",""],[36,"三好市","東祖谷和田","","Miyoshi-shi","Higashiiya Wada",""]],
	"7785251":[[36,"三好市","池田町白地","","Miyoshi-shi","Ikedacho Hakuchi",""]],
	"7785252":[[36,"三好市","池田町馬路","","Miyoshi-shi","Ikedacho Umaji",""]],
	"7785253":[[36,"三好市","池田町佐野","","Miyoshi-shi","Ikedacho Sano",""]],
	"7785254":[[36,"三好市","山城町佐連","","Miyoshi-shi","Yamashirocho Sare ",""]]
})
