zipdata({
	"7710101":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710102":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710103":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710104":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710105":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710106":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710111":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710112":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710113":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710114":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710115":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710116":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710117":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710121":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710122":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710123":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710124":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710125":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710126":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710127":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710128":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710129":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710130":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710131":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710132":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710133":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710134":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710135":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710136":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710137":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710138":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710139":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710141":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710142":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710143":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710144":[[36,"徳島市","川内町","","Tokushima-shi","Kawauchicho",""]],
	"7710200":[[36,"板野郡松茂町","","","Matsushige-cho, Itano-gun","",""],[36,"板野郡北島町","","","Kitajima-cho, Itano-gun","",""]],
	"7710201":[[36,"板野郡北島町","北村","","Kitajima-cho, Itano-gun","Kitamura",""]],
	"7710202":[[36,"板野郡北島町","太郎八須","","Kitajima-cho, Itano-gun","Tarohachizu",""]],
	"7710203":[[36,"板野郡北島町","中村","","Kitajima-cho, Itano-gun","Nakamura",""]],
	"7710204":[[36,"板野郡北島町","鯛浜","","Kitajima-cho, Itano-gun","Tainohama",""]],
	"7710205":[[36,"板野郡北島町","江尻","","Kitajima-cho, Itano-gun","Ejiri",""]],
	"7710206":[[36,"板野郡北島町","高房","","Kitajima-cho, Itano-gun","Takabo",""]],
	"7710207":[[36,"板野郡北島町","新喜来","","Kitajima-cho, Itano-gun","Shinkirai",""]],
	"7710211":[[36,"板野郡松茂町","長岸","","Matsushige-cho, Itano-gun","Nagagishi",""]],
	"7710212":[[36,"板野郡松茂町","中喜来","","Matsushige-cho, Itano-gun","Nakagirai",""]],
	"7710213":[[36,"板野郡松茂町","豊久","","Matsushige-cho, Itano-gun","Toyohisa",""]],
	"7710214":[[36,"板野郡松茂町","満穂","","Matsushige-cho, Itano-gun","Mitsuho",""]],
	"7710215":[[36,"板野郡松茂町","豊岡","","Matsushige-cho, Itano-gun","Toyoka",""]],
	"7710216":[[36,"板野郡松茂町","長原","","Matsushige-cho, Itano-gun","Nagahara",""]],
	"7710217":[[36,"板野郡松茂町","豊中","","Matsushige-cho, Itano-gun","Toyonaka",""]],
	"7710218":[[36,"板野郡松茂町","住吉","","Matsushige-cho, Itano-gun","Sumiyoshi",""]],
	"7710219":[[36,"板野郡松茂町","笹木野","","Matsushige-cho, Itano-gun","Sasagino",""]],
	"7710220":[[36,"板野郡松茂町","広島","","Matsushige-cho, Itano-gun","Hiroshima",""]],
	"7710360":[[36,"鳴門市","瀬戸町明神","","Naruto-shi","Setochoakinokami",""]],
	"7710361":[[36,"鳴門市","瀬戸町堂浦","","Naruto-shi","Setochodonora",""]],
	"7710362":[[36,"鳴門市","瀬戸町北泊","","Naruto-shi","Setochokitadomari",""]],
	"7710363":[[36,"鳴門市","瀬戸町湊谷","","Naruto-shi","Setochominatodani",""]],
	"7710364":[[36,"鳴門市","瀬戸町北泊","","Naruto-shi","Setochokitadomari",""]],
	"7710365":[[36,"鳴門市","瀬戸町小島田","","Naruto-shi","Setochokoshimada",""]],
	"7710366":[[36,"鳴門市","瀬戸町中島田","","Naruto-shi","Setochonakashimada",""]],
	"7710367":[[36,"鳴門市","瀬戸町大島田","","Naruto-shi","Setochooshimada",""]],
	"7710368":[[36,"鳴門市","瀬戸町室","","Naruto-shi","Setochomuro",""]],
	"7710369":[[36,"鳴門市","瀬戸町撫佐","","Naruto-shi","Setochomusa",""]],
	"7710371":[[36,"鳴門市","北灘町櫛木","","Naruto-shi","Kitanadachokushiki",""]],
	"7710372":[[36,"鳴門市","北灘町粟田","","Naruto-shi","Kitanadachoawata",""]],
	"7710373":[[36,"鳴門市","北灘町大浦","","Naruto-shi","Kitanadachooura",""]],
	"7710374":[[36,"鳴門市","北灘町宿毛谷","","Naruto-shi","Kitanadachoshukumodani",""]],
	"7710375":[[36,"鳴門市","北灘町鳥ケ丸","","Naruto-shi","Kitanadachotorigamaru",""]],
	"7710376":[[36,"鳴門市","北灘町折野","","Naruto-shi","Kitanadachoorino",""]],
	"7710377":[[36,"鳴門市","北灘町大須","","Naruto-shi","Kitanadachoozu",""]],
	"7710378":[[36,"鳴門市","北灘町碁浦","","Naruto-shi","Kitanadachogonora",""]],
	"7711151":[[36,"徳島市","応神町古川","","Tokushima-shi","Ojinchofurukawa",""]],
	"7711152":[[36,"徳島市","応神町中原","","Tokushima-shi","Ojinchonakahara",""]],
	"7711153":[[36,"徳島市","応神町吉成","","Tokushima-shi","Ojinchoyoshinari",""]],
	"7711154":[[36,"徳島市","応神町東貞方","","Tokushima-shi","Ojinchohigashisadakata",""]],
	"7711155":[[36,"徳島市","応神町西貞方","","Tokushima-shi","Ojinchonishisadakata",""]],
	"7711156":[[36,"徳島市","応神町応神産業団地","","Tokushima-shi","Ojinchoojinsangyodanchi",""]],
	"7711200":[[36,"板野郡藍住町","","","Aizumi-cho, Itano-gun","",""]],
	"7711201":[[36,"板野郡藍住町","奥野","","Aizumi-cho, Itano-gun","Okuno",""]],
	"7711202":[[36,"板野郡藍住町","奥野","","Aizumi-cho, Itano-gun","Okuno",""],[36,"板野郡藍住町","奥野","","Aizumi-cho, Itano-gun","Okuno",""],[36,"板野郡藍住町","奥野","","Aizumi-cho, Itano-gun","Okuno",""],[36,"板野郡藍住町","奥野","","Aizumi-cho, Itano-gun","Okuno",""]],
	"7711203":[[36,"板野郡藍住町","奥野","","Aizumi-cho, Itano-gun","Okuno",""]],
	"7711210":[[36,"板野郡藍住町","徳命","","Aizumi-cho, Itano-gun","Tokumei",""]],
	"7711211":[[36,"板野郡藍住町","徳命","","Aizumi-cho, Itano-gun","Tokumei",""],[36,"板野郡藍住町","徳命","","Aizumi-cho, Itano-gun","Tokumei",""]],
	"7711212":[[36,"板野郡藍住町","徳命","","Aizumi-cho, Itano-gun","Tokumei",""],[36,"板野郡藍住町","徳命","","Aizumi-cho, Itano-gun","Tokumei",""]],
	"7711220":[[36,"板野郡藍住町","東中富","","Aizumi-cho, Itano-gun","Higashinakatomi",""]],
	"7711221":[[36,"板野郡藍住町","東中富","","Aizumi-cho, Itano-gun","Higashinakatomi",""]],
	"7711222":[[36,"板野郡藍住町","東中富","","Aizumi-cho, Itano-gun","Higashinakatomi",""]],
	"7711223":[[36,"板野郡藍住町","東中富","","Aizumi-cho, Itano-gun","Higashinakatomi",""],[36,"板野郡藍住町","東中富","","Aizumi-cho, Itano-gun","Higashinakatomi",""]],
	"7711224":[[36,"板野郡藍住町","東中富","","Aizumi-cho, Itano-gun","Higashinakatomi",""],[36,"板野郡藍住町","東中富","","Aizumi-cho, Itano-gun","Higashinakatomi",""],[36,"板野郡藍住町","東中富","","Aizumi-cho, Itano-gun","Higashinakatomi",""],[36,"板野郡藍住町","東中富","","Aizumi-cho, Itano-gun","Higashinakatomi",""],[36,"板野郡藍住町","東中富","","Aizumi-cho, Itano-gun","Higashinakatomi",""],[36,"板野郡藍住町","東中富","","Aizumi-cho, Itano-gun","Higashinakatomi",""]],
	"7711230":[[36,"板野郡藍住町","富吉","","Aizumi-cho, Itano-gun","Tomiyoshi",""]],
	"7711231":[[36,"板野郡藍住町","富吉","","Aizumi-cho, Itano-gun","Tomiyoshi",""],[36,"板野郡藍住町","富吉","","Aizumi-cho, Itano-gun","Tomiyoshi",""],[36,"板野郡藍住町","富吉","","Aizumi-cho, Itano-gun","Tomiyoshi",""]],
	"7711232":[[36,"板野郡藍住町","富吉","","Aizumi-cho, Itano-gun","Tomiyoshi",""],[36,"板野郡藍住町","富吉","","Aizumi-cho, Itano-gun","Tomiyoshi",""]],
	"7711240":[[36,"板野郡藍住町","乙瀬","","Aizumi-cho, Itano-gun","Otoze",""]],
	"7711250":[[36,"板野郡藍住町","矢上","","Aizumi-cho, Itano-gun","Yakami",""]],
	"7711251":[[36,"板野郡藍住町","矢上","","Aizumi-cho, Itano-gun","Yakami",""],[36,"板野郡藍住町","矢上","","Aizumi-cho, Itano-gun","Yakami",""]],
	"7711252":[[36,"板野郡藍住町","矢上","","Aizumi-cho, Itano-gun","Yakami",""],[36,"板野郡藍住町","矢上","","Aizumi-cho, Itano-gun","Yakami",""]],
	"7711253":[[36,"板野郡藍住町","矢上","","Aizumi-cho, Itano-gun","Yakami",""],[36,"板野郡藍住町","矢上","","Aizumi-cho, Itano-gun","Yakami",""]],
	"7711260":[[36,"板野郡藍住町","笠木","","Aizumi-cho, Itano-gun","Kasagi",""]],
	"7711261":[[36,"板野郡藍住町","笠木","","Aizumi-cho, Itano-gun","Kasagi",""]],
	"7711262":[[36,"板野郡藍住町","笠木","","Aizumi-cho, Itano-gun","Kasagi",""],[36,"板野郡藍住町","笠木","","Aizumi-cho, Itano-gun","Kasagi",""]],
	"7711264":[[36,"板野郡藍住町","住吉","","Aizumi-cho, Itano-gun","Sumiyoshi",""]],
	"7711265":[[36,"板野郡藍住町","住吉","","Aizumi-cho, Itano-gun","Sumiyoshi",""],[36,"板野郡藍住町","住吉","","Aizumi-cho, Itano-gun","Sumiyoshi",""],[36,"板野郡藍住町","住吉","","Aizumi-cho, Itano-gun","Sumiyoshi",""]],
	"7711266":[[36,"板野郡藍住町","住吉","","Aizumi-cho, Itano-gun","Sumiyoshi",""],[36,"板野郡藍住町","住吉","","Aizumi-cho, Itano-gun","Sumiyoshi",""]],
	"7711267":[[36,"板野郡藍住町","住吉","","Aizumi-cho, Itano-gun","Sumiyoshi",""],[36,"板野郡藍住町","住吉","","Aizumi-cho, Itano-gun","Sumiyoshi",""]],
	"7711270":[[36,"板野郡藍住町","勝瑞","","Aizumi-cho, Itano-gun","Shozui",""]],
	"7711271":[[36,"板野郡藍住町","勝瑞","","Aizumi-cho, Itano-gun","Shozui",""]],
	"7711272":[[36,"板野郡藍住町","勝瑞","","Aizumi-cho, Itano-gun","Shozui",""]],
	"7711273":[[36,"板野郡藍住町","勝瑞","","Aizumi-cho, Itano-gun","Shozui",""],[36,"板野郡藍住町","勝瑞","","Aizumi-cho, Itano-gun","Shozui",""]],
	"7711300":[[36,"板野郡上板町","","","Kamiita-cho, Itano-gun","",""]],
	"7711301":[[36,"板野郡上板町","鍛冶屋原","","Kamiita-cho, Itano-gun","Kajiyabara",""]],
	"7711302":[[36,"板野郡上板町","七條","","Kamiita-cho, Itano-gun","Shichijo",""]],
	"7711310":[[36,"板野郡上板町","泉谷","","Kamiita-cho, Itano-gun","Izumidani",""]],
	"7711311":[[36,"板野郡上板町","引野","","Kamiita-cho, Itano-gun","Hikino",""]],
	"7711320":[[36,"板野郡上板町","神宅","","Kamiita-cho, Itano-gun","Kanyake",""]],
	"7711330":[[36,"板野郡上板町","西分","","Kamiita-cho, Itano-gun","Nishibun",""]],
	"7711341":[[36,"板野郡上板町","第十新田","","Kamiita-cho, Itano-gun","Daijushinden",""]],
	"7711342":[[36,"板野郡上板町","佐藤塚","","Kamiita-cho, Itano-gun","Satozuka",""]],
	"7711343":[[36,"板野郡上板町","椎本","","Kamiita-cho, Itano-gun","Shiinomoto",""]],
	"7711344":[[36,"板野郡上板町","下六條","","Kamiita-cho, Itano-gun","Shimorokujo",""]],
	"7711345":[[36,"板野郡上板町","上六條","","Kamiita-cho, Itano-gun","Kamirokujo",""]],
	"7711346":[[36,"板野郡上板町","高磯","","Kamiita-cho, Itano-gun","Takaiso",""]],
	"7711347":[[36,"板野郡上板町","高瀬","","Kamiita-cho, Itano-gun","Takase",""]],
	"7711350":[[36,"板野郡上板町","瀬部","","Kamiita-cho, Itano-gun","Sebe",""]],
	"7711401":[[36,"阿波市","吉野町柿原","","Awa-shi","Yoshinocho Kakihara",""]],
	"7711402":[[36,"阿波市","吉野町西条","","Awa-shi","Yoshinocho Saijo",""]],
	"7711403":[[36,"阿波市","吉野町五条","","Awa-shi","Yoshinocho Gojo",""]],
	"7711501":[[36,"阿波市","土成町秋月","","Awa-shi","Donaricho Akizuki",""]],
	"7711502":[[36,"阿波市","土成町水田","","Awa-shi","Donaricho Mizuta",""]],
	"7711503":[[36,"阿波市","土成町浦池","","Awa-shi","Donaricho Uranoike",""]],
	"7711504":[[36,"阿波市","土成町成当","","Awa-shi","Donaricho Narito",""]],
	"7711505":[[36,"阿波市","土成町郡","","Awa-shi","Donaricho Kori",""]],
	"7711506":[[36,"阿波市","土成町土成","","Awa-shi","Donaricho Donari",""]],
	"7711507":[[36,"阿波市","土成町吉田","","Awa-shi","Donaricho Yoshida",""]],
	"7711508":[[36,"阿波市","土成町宮川内","","Awa-shi","Donaricho Miyagawauchi",""]],
	"7711509":[[36,"阿波市","土成町高尾","","Awa-shi","Donaricho Takao",""]],
	"7711601":[[36,"阿波市","市場町市場","","Awa-shi","Ichibacho Ichiba",""]],
	"7711602":[[36,"阿波市","市場町市場","","Awa-shi","Ichibacho Ichiba",""]],
	"7711603":[[36,"阿波市","市場町市場","","Awa-shi","Ichibacho Ichiba",""]],
	"7711604":[[36,"阿波市","市場町市場","","Awa-shi","Ichibacho Ichiba",""]],
	"7711610":[[36,"阿波市","市場町香美","","Awa-shi","Ichibacho Kagami",""]],
	"7711611":[[36,"阿波市","市場町香美","","Awa-shi","Ichibacho Kagami",""]],
	"7711612":[[36,"阿波市","市場町上喜来","","Awa-shi","Ichibacho Kamigirai",""]],
	"7711613":[[36,"阿波市","市場町大俣","","Awa-shi","Ichibacho Omata",""]],
	"7711614":[[36,"阿波市","市場町犬墓","","Awa-shi","Ichibacho Inunohaka",""]],
	"7711615":[[36,"阿波市","市場町大影","","Awa-shi","Ichibacho Okage",""]],
	"7711616":[[36,"阿波市","市場町日開谷","","Awa-shi","Ichibacho Higaidani",""]],
	"7711621":[[36,"阿波市","市場町尾開","","Awa-shi","Ichibacho Obari",""]],
	"7711622":[[36,"阿波市","市場町興崎","","Awa-shi","Ichibacho Kozaki",""]],
	"7711623":[[36,"阿波市","市場町切幡","","Awa-shi","Ichibacho Kirihata",""]],
	"7711624":[[36,"阿波市","市場町山野上","","Awa-shi","Ichibacho Yamanoe",""]],
	"7711625":[[36,"阿波市","市場町八幡","","Awa-shi","Ichibacho Yawata",""]],
	"7711626":[[36,"阿波市","市場町伊月","","Awa-shi","Ichibacho Itsuki",""]],
	"7711627":[[36,"阿波市","市場町大野島","","Awa-shi","Ichibacho Onojima",""]],
	"7711700":[[36,"阿波市","","","Awa-shi","",""]],
	"7711701":[[36,"阿波市","阿波町伊沢市","","Awa-shi","Awacho Isawaichi",""],[36,"阿波市","阿波町王地","","Awa-shi","Awacho Oji",""],[36,"阿波市","阿波町王地南","","Awa-shi","Awacho Ojiminami",""],[36,"阿波市","阿波町大坪","","Awa-shi","Awacho Otsubo",""],[36,"阿波市","阿波町大原","","Awa-shi","Awacho Ohara",""],[36,"阿波市","阿波町大道南","","Awa-shi","Awacho Omichiminami",""],[36,"阿波市","阿波町勝命","","Awa-shi","Awacho Katsumyo",""],[36,"阿波市","阿波町勝命北","","Awa-shi","Awacho Katsumyokita",""],[36,"阿波市","阿波町庚申原","","Awa-shi","Awacho Koshimbara",""],[36,"阿波市","阿波町下喜来","","Awa-shi","Awacho Shimogirai",""],[36,"阿波市","阿波町下喜来南","","Awa-shi","Awacho Shimogiraiminami",""],[36,"阿波市","阿波町新開","","Awa-shi","Awacho Shimbari",""],[36,"阿波市","阿波町清原","","Awa-shi","Awacho Seibara",""],[36,"阿波市","阿波町谷島","","Awa-shi","Awacho Tanijima",""],[36,"阿波市","阿波町谷島北","","Awa-shi","Awacho Tanijimakita",""],[36,"阿波市","阿波町西清原","","Awa-shi","Awacho Nishiseibara",""],[36,"阿波市","阿波町平川原北","","Awa-shi","Awacho Heigawarakita",""],[36,"阿波市","阿波町平川原南","","Awa-shi","Awacho Heigawaraminami",""],[36,"阿波市","阿波町南谷島","","Awa-shi","Awacho Minamitanijima",""]],
	"7711702":[[36,"阿波市","阿波町伊勢","","Awa-shi","Awacho Ise",""],[36,"阿波市","阿波町井出口","","Awa-shi","Awacho Ideguchi",""],[36,"阿波市","阿波町稲荷","","Awa-shi","Awacho Inari",""],[36,"阿波市","阿波町大久保","","Awa-shi","Awacho Okubo",""],[36,"阿波市","阿波町柏谷左右","","Awa-shi","Awacho Kashiwadanisayu",""],[36,"阿波市","阿波町川添","","Awa-shi","Awacho Kawazoe",""],[36,"阿波市","阿波町北ノ名","","Awa-shi","Awacho Kitanomyo",""],[36,"阿波市","阿波町山王","","Awa-shi","Awacho Sanno",""],[36,"阿波市","阿波町四歩一","","Awa-shi","Awacho Shibuichi",""],[36,"阿波市","阿波町下原","","Awa-shi","Awacho Shimobara",""],[36,"阿波市","阿波町大次郎","","Awa-shi","Awacho Daijiro",""],[36,"阿波市","阿波町谷口","","Awa-shi","Awacho Taniguchi",""],[36,"阿波市","阿波町寺サコ","","Awa-shi","Awacho Terasako",""],[36,"阿波市","阿波町天西山","","Awa-shi","Awacho Tensaizan",""],[36,"阿波市","阿波町西ノ岡","","Awa-shi","Awacho Nishinoka",""],[36,"阿波市","阿波町野神","","Awa-shi","Awacho Nogami",""],[36,"阿波市","阿波町久原","","Awa-shi","Awacho Hisahara",""],[36,"阿波市","阿波町本町","","Awa-shi","Awacho Hommachi",""],[36,"阿波市","阿波町本安","","Awa-shi","Awacho Honyasu",""],[36,"阿波市","阿波町森沢","","Awa-shi","Awacho Morisawa",""],[36,"阿波市","阿波町安政","","Awa-shi","Awacho Yasumasa",""],[36,"阿波市","阿波町山尻","","Awa-shi","Awacho Yamajiri",""],[36,"阿波市","阿波町早田","","Awa-shi","Awacho Wasada",""]],
	"7711703":[[36,"阿波市","阿波町伊沢田","","Awa-shi","Awacho Isawada",""],[36,"阿波市","阿波町大道北","","Awa-shi","Awacho Omichikita",""],[36,"阿波市","阿波町岡地","","Awa-shi","Awacho Okaji",""],[36,"阿波市","阿波町北柴生","","Awa-shi","Awacho Kitashibo",""],[36,"阿波市","阿波町北原","","Awa-shi","Awacho Kitabara",""],[36,"阿波市","阿波町真福寺","","Awa-shi","Awacho Shimpukuji",""],[36,"阿波市","阿波町綱懸","","Awa-shi","Awacho Tsunakake",""],[36,"阿波市","阿波町東条","","Awa-shi","Awacho Tojo",""],[36,"阿波市","阿波町中原","","Awa-shi","Awacho Nakahara",""],[36,"阿波市","阿波町西柴生","","Awa-shi","Awacho Nishishibo",""],[36,"阿波市","阿波町西原","","Awa-shi","Awacho Nishibara",""],[36,"阿波市","阿波町東柴生","","Awa-shi","Awacho Higashishibo",""],[36,"阿波市","阿波町東原","","Awa-shi","Awacho Higashibara",""],[36,"阿波市","阿波町前島","","Awa-shi","Awacho Maejima",""],[36,"阿波市","阿波町丸山","","Awa-shi","Awacho Maruyama",""],[36,"阿波市","阿波町南柴生","","Awa-shi","Awacho Minamishibo",""]],
	"7711704":[[36,"阿波市","阿波町伊沢谷東縁","","Awa-shi","Awacho Isawadanihigashiberi",""],[36,"阿波市","阿波町糸下","","Awa-shi","Awacho Itoga",""],[36,"阿波市","阿波町芋場","","Awa-shi","Awacho Imoba",""],[36,"阿波市","阿波町梅ノ木原","","Awa-shi","Awacho Umenokibara",""],[36,"阿波市","阿波町梅ノ東","","Awa-shi","Awacho Umenohigashi",""],[36,"阿波市","阿波町小倉","","Awa-shi","Awacho Ogura",""],[36,"阿波市","阿波町亀底","","Awa-shi","Awacho Kamezoko",""],[36,"阿波市","阿波町北久保","","Awa-shi","Awacho Kitakubo",""],[36,"阿波市","阿波町北五味知","","Awa-shi","Awacho Kitagomijiri",""],[36,"阿波市","阿波町北正広","","Awa-shi","Awacho Kitamasahiro",""],[36,"阿波市","阿波町立割","","Awa-shi","Awacho Tatewari",""],[36,"阿波市","阿波町西正広","","Awa-shi","Awacho Nishimasahiro",""],[36,"阿波市","阿波町八丁原","","Awa-shi","Awacho Hatchobara",""],[36,"阿波市","阿波町東正広","","Awa-shi","Awacho Higashimasahiro",""],[36,"阿波市","阿波町引地","","Awa-shi","Awacho Hikichi",""],[36,"阿波市","阿波町広野","","Awa-shi","Awacho Hirono",""],[36,"阿波市","阿波町真重","","Awa-shi","Awacho Mashige",""],[36,"阿波市","阿波町南五味知","","Awa-shi","Awacho Minamigomijiri",""],[36,"阿波市","阿波町元町","","Awa-shi","Awacho Motomachi",""],[36,"阿波市","阿波町山ノ神","","Awa-shi","Awacho Yamanokami",""]],
	"7711705":[[36,"阿波市","阿波町赤坂","","Awa-shi","Awacho Akasaka",""],[36,"阿波市","阿波町医王寺","","Awa-shi","Awacho Ioji",""],[36,"阿波市","阿波町居屋敷","","Awa-shi","Awacho Iyashiki",""],[36,"阿波市","阿波町梅川内","","Awa-shi","Awacho Umekawauchi",""],[36,"阿波市","阿波町王子川","","Awa-shi","Awacho Ojigawa",""],[36,"阿波市","阿波町川久保","","Awa-shi","Awacho Kawakubo",""],[36,"阿波市","阿波町北整理","","Awa-shi","Awacho Kitaseiri",""],[36,"阿波市","阿波町北山","","Awa-shi","Awacho Kitayama",""],[36,"阿波市","阿波町五明","","Awa-shi","Awacho Gomyo",""],[36,"阿波市","阿波町桜ノ岡","","Awa-shi","Awacho Sakuranoka",""],[36,"阿波市","阿波町寒風","","Awa-shi","Awacho Samukaze",""],[36,"阿波市","阿波町十善地","","Awa-shi","Awacho Juzenji",""],[36,"阿波市","阿波町善地","","Awa-shi","Awacho Zenji",""],[36,"阿波市","阿波町高垣","","Awa-shi","Awacho Takagaki",""],[36,"阿波市","阿波町栩ケ窪","","Awa-shi","Awacho Tochigakubo",""],[36,"阿波市","阿波町馬場","","Awa-shi","Awacho Baba",""],[36,"阿波市","阿波町日吉谷","","Awa-shi","Awacho Hiyoshidani",""],[36,"阿波市","阿波町松川内","","Awa-shi","Awacho Matsukawauchi",""]],
	"7711706":[[36,"阿波市","阿波町岩津","","Awa-shi","Awacho Iwazu",""],[36,"阿波市","阿波町植桜","","Awa-shi","Awacho Uezakura",""],[36,"阿波市","阿波町乙岩津","","Awa-shi","Awacho Otsuiwazu",""],[36,"阿波市","阿波町北岡","","Awa-shi","Awacho Kitaoka",""],[36,"阿波市","阿波町北西谷","","Awa-shi","Awacho Kitanishidani",""],[36,"阿波市","阿波町三本柳","","Awa-shi","Awacho Sambonyanagi",""],[36,"阿波市","阿波町中川原","","Awa-shi","Awacho Nakagawahara",""],[36,"阿波市","阿波町中坪","","Awa-shi","Awacho Nakatsubo",""],[36,"阿波市","阿波町中長峰","","Awa-shi","Awacho Nakanagamine",""],[36,"阿波市","阿波町西島","","Awa-shi","Awacho Nishijima",""],[36,"阿波市","阿波町西整理","","Awa-shi","Awacho Nishiseiri",""],[36,"阿波市","阿波町西長峰","","Awa-shi","Awacho Nishinagamine",""],[36,"阿波市","阿波町西林","","Awa-shi","Awacho Nishibayashi",""],[36,"阿波市","阿波町東川原","","Awa-shi","Awacho Higashikawahara",""],[36,"阿波市","阿波町東島","","Awa-shi","Awacho Higashijima",""],[36,"阿波市","阿波町東整理","","Awa-shi","Awacho Higashiseiri",""],[36,"阿波市","阿波町東長峰","","Awa-shi","Awacho Higashinagamine",""],[36,"阿波市","阿波町東村","","Awa-shi","Awacho Higashimura",""],[36,"阿波市","阿波町南川原","","Awa-shi","Awacho Minamikawahara",""],[36,"阿波市","阿波町南整理","","Awa-shi","Awacho Minamiseiri",""],[36,"阿波市","阿波町南西谷","","Awa-shi","Awacho Minaminishidani",""]],
	"7711714":[[36,"阿波市","市場町犬墓","","Awa-shi","Ichibacho Inunohaka",""]],
	"7712101":[[36,"美馬市","美馬町","","Mima-shi","Mimacho",""]],
	"7712102":[[36,"美馬市","美馬町","","Mima-shi","Mimacho",""],[36,"美馬市","川ノ上、観音、栗林、黒砂、狙ケ内、","","Mima-shi","Kawanoe.kannon.kuribayashi.kurosuna",""],[36,"美馬市","惣田、外墓、滝ノ上、立見山、田ノ岡","","Mima-shi","Soda.sotobaka.takinoe.tatsumiyama.t",""],[36,"美馬市","西浦、西ノ谷、野田ノ井、橋谷、場シ","","Mima-shi","Nishiura.nishinotani.notanoi.hashid",""],[36,"美馬市","水ノ岡、味噌ケ久保、道ノ上、宮ノ岡","","Mima-shi","Mizunoka.misogakubo.michinoe.miyano",""],[36,"美馬市","山橋谷、横尾）","","Mima-shi","Yamahashidani.yoko)",""]],
	"7712103":[[36,"美馬市","美馬町","","Mima-shi","Mimacho",""],[36,"美馬市","露口、中沼田、中野、夏弥喜、ナロヲ","","Mima-shi","Tsuyuguchi.nakanumada.nakano.natsuy",""],[36,"美馬市","坊ケ谷、水久保、宗ノ分、屋内）","","Mima-shi","Bogatani.mizukubo.munenobun.yanai)",""]],
	"7712104":[[36,"美馬市","美馬町","","Mima-shi","Mimacho",""],[36,"美馬市","谷頭、玉振前、チゲジ、天神東、轟、","","Mima-shi","Tanigashira.tamafurimae.chigeji.ten",""],[36,"美馬市","ノリコヘ、橋本、東岸ノ下、東段、東","","Mima-shi","Norikohe.hashinomoto.higashikishino",""],[36,"美馬市","宗重、薬師）","","Mima-shi","Muneshige.yakushi)",""]],
	"7712105":[[36,"美馬市","美馬町","","Mima-shi","Mimacho",""],[36,"美馬市","北土ケ久保、喜入道、滝宮、土ケ久保","","Mima-shi","Kitatsuchigakubo.kinyudo.takinomiya",""]],
	"7712106":[[36,"美馬市","美馬町","","Mima-shi","Mimacho",""],[36,"美馬市","喜来市、里平野、下突出、谷ヨリ西、","","Mima-shi","Kiraiichi.satohirano.shimotsukidash",""],[36,"美馬市","西荒川、沼田島、東荒川、南荒川、南","","Mima-shi","Nishiarakawa.numadajima.higashiarak",""]],
	"7712107":[[36,"美馬市","美馬町","","Mima-shi","Mimacho",""],[36,"美馬市","谷口、栂尾、突落、中尾、中耕地、中","","Mima-shi","Taniguchi.tsugao.tsukiotoshi.nakao.",""],[36,"美馬市","西宮ノ上、東宮ノ上、細野、前田、松","","Mima-shi","Nishimiyanoe.higashimiyanoe.hosono.",""],[36,"美馬市","山夏蕨、吉水）","","Mima-shi","Yamanatsuwarabi.yoshimizu)",""]],
	"7712301":[[36,"三好市","三野町清水","","Miyoshi-shi","Minocho Shimizu",""]],
	"7712302":[[36,"三好市","三野町加茂野宮","","Miyoshi-shi","Minocho Kamonomiya",""]],
	"7712303":[[36,"三好市","三野町勢力","","Miyoshi-shi","Minocho Seiriki",""]],
	"7712304":[[36,"三好市","三野町芝生","","Miyoshi-shi","Minocho Shibo",""]],
	"7712305":[[36,"三好市","三野町太刀野","","Miyoshi-shi","Minocho Tachino",""]],
	"7712306":[[36,"三好市","三野町太刀野山","","Miyoshi-shi","Minocho Tachinoyama",""]],
	"7712501":[[36,"三好郡東みよし町","昼間","","Higashimiyoshi-cho, Miyoshi-gun","Hiruma",""]],
	"7712502":[[36,"三好郡東みよし町","足代","","Higashimiyoshi-cho, Miyoshi-gun","Ashiro",""]],
	"7712503":[[36,"三好郡東みよし町","東山","","Higashimiyoshi-cho, Miyoshi-gun","Higashiyama",""]],
	"7713200":[[36,"名西郡神山町","","","Kamiyama-cho, Myozai-gun","",""]],
	"7713201":[[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""]],
	"7713202":[[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""],[36,"名西郡神山町","阿野","","Kamiyama-cho, Myozai-gun","Ano",""]],
	"7713203":[[36,"名西郡神山町","鬼籠野","","Kamiyama-cho, Myozai-gun","Orono",""]],
	"7713310":[[36,"名西郡神山町","神領","","Kamiyama-cho, Myozai-gun","Jinryo",""]],
	"7713311":[[36,"名西郡神山町","神領","","Kamiyama-cho, Myozai-gun","Jinryo",""],[36,"名西郡神山町","神領","","Kamiyama-cho, Myozai-gun","Jinryo",""],[36,"名西郡神山町","神領","","Kamiyama-cho, Myozai-gun","Jinryo",""],[36,"名西郡神山町","神領","","Kamiyama-cho, Myozai-gun","Jinryo",""],[36,"名西郡神山町","神領","","Kamiyama-cho, Myozai-gun","Jinryo",""],[36,"名西郡神山町","神領","","Kamiyama-cho, Myozai-gun","Jinryo",""],[36,"名西郡神山町","神領","","Kamiyama-cho, Myozai-gun","Jinryo",""]],
	"7713421":[[36,"名西郡神山町","下分","","Kamiyama-cho, Myozai-gun","Shimobun",""]],
	"7713422":[[36,"名西郡神山町","上分","","Kamiyama-cho, Myozai-gun","Kamibun",""]],
	"7714100":[[36,"名東郡佐那河内村","","","Sanagochi-son, Myodo-gun","",""]],
	"7714101":[[36,"名東郡佐那河内村","下","","Sanagochi-son, Myodo-gun","Shimo",""]],
	"7714102":[[36,"名東郡佐那河内村","上","","Sanagochi-son, Myodo-gun","Kami",""]],
	"7714261":[[36,"徳島市","丈六町","","Tokushima-shi","Jorokucho",""]],
	"7714262":[[36,"徳島市","丈六町","","Tokushima-shi","Jorokucho",""]],
	"7714263":[[36,"徳島市","丈六町","","Tokushima-shi","Jorokucho",""]],
	"7714264":[[36,"徳島市","多家良町","","Tokushima-shi","Takaracho",""]],
	"7714265":[[36,"徳島市","飯谷町","","Tokushima-shi","Iitanicho",""]],
	"7714266":[[36,"徳島市","八多町","","Tokushima-shi","Hatacho",""]],
	"7714267":[[36,"徳島市","渋野町","","Tokushima-shi","Shibunocho",""]],
	"7714300":[[36,"勝浦郡勝浦町","","","Katsura-cho, Katsura-gun","",""]],
	"7714301":[[36,"勝浦郡勝浦町","沼江","","Katsura-cho, Katsura-gun","Nue",""]],
	"7714302":[[36,"勝浦郡勝浦町","中角","","Katsura-cho, Katsura-gun","Nakatsuno",""]],
	"7714303":[[36,"勝浦郡勝浦町","生名","","Katsura-cho, Katsura-gun","Ikuna",""]],
	"7714304":[[36,"勝浦郡勝浦町","星谷","","Katsura-cho, Katsura-gun","Hoshitani",""]],
	"7714305":[[36,"勝浦郡勝浦町","久国","","Katsura-cho, Katsura-gun","Hisakuni",""]],
	"7714306":[[36,"勝浦郡勝浦町","棚野","","Katsura-cho, Katsura-gun","Tanano",""]],
	"7714307":[[36,"勝浦郡勝浦町","三渓","","Katsura-cho, Katsura-gun","Mitani",""]],
	"7714308":[[36,"勝浦郡勝浦町","坂本","","Katsura-cho, Katsura-gun","Sakamoto",""]],
	"7714500":[[36,"勝浦郡上勝町","","","Kamikatsu-cho, Katsura-gun","",""]],
	"7714501":[[36,"勝浦郡上勝町","福原","","Kamikatsu-cho, Katsura-gun","Fukuhara",""]],
	"7714502":[[36,"勝浦郡上勝町","旭","","Kamikatsu-cho, Katsura-gun","Asahi",""]],
	"7714503":[[36,"勝浦郡上勝町","生実","","Kamikatsu-cho, Katsura-gun","Ikumi",""]],
	"7714504":[[36,"勝浦郡上勝町","傍示","","Kamikatsu-cho, Katsura-gun","Hoji",""]],
	"7714505":[[36,"勝浦郡上勝町","正木","","Kamikatsu-cho, Katsura-gun","Masaki",""]],
	"7715170":[[36,"阿南市","楠根町","","Anan-shi","Kusunecho",""]],
	"7715171":[[36,"阿南市","熊谷町","","Anan-shi","Kumadanicho",""]],
	"7715172":[[36,"阿南市","吉井町","","Anan-shi","Yoshiicho",""]],
	"7715173":[[36,"阿南市","加茂町","","Anan-shi","Kamocho",""]],
	"7715174":[[36,"阿南市","水井町","","Anan-shi","Suiicho",""]],
	"7715175":[[36,"阿南市","細野町","","Anan-shi","Hosonocho",""]],
	"7715176":[[36,"阿南市","大田井町","","Anan-shi","Otaicho",""]],
	"7715177":[[36,"阿南市","大井町","","Anan-shi","Oicho",""]],
	"7715178":[[36,"阿南市","十八女町","","Anan-shi","Sakaricho",""]],
	"7715179":[[36,"阿南市","深瀬町","","Anan-shi","Fukasecho",""]],
	"7715200":[[36,"那賀郡那賀町","","","Naka-cho, Naka-gun","",""]],
	"7715201":[[36,"那賀郡那賀町","和食","","Naka-cho, Naka-gun","Wajiki",""]],
	"7715202":[[36,"那賀郡那賀町","土佐","","Naka-cho, Naka-gun","Tosa",""]],
	"7715203":[[36,"那賀郡那賀町","和食郷","","Naka-cho, Naka-gun","Wajikigo",""]],
	"7715204":[[36,"那賀郡那賀町","中山","","Naka-cho, Naka-gun","Nakayama",""]],
	"7715205":[[36,"那賀郡那賀町","百合谷","","Naka-cho, Naka-gun","Momaedani",""]],
	"7715206":[[36,"那賀郡那賀町","百合","","Naka-cho, Naka-gun","Momae",""]],
	"7715207":[[36,"那賀郡那賀町","阿井","","Naka-cho, Naka-gun","Ai",""]],
	"7715208":[[36,"那賀郡那賀町","仁宇","","Naka-cho, Naka-gun","Niu",""]],
	"7715209":[[36,"那賀郡那賀町","小仁宇","","Naka-cho, Naka-gun","Koniu",""]],
	"7715320":[[36,"那賀郡那賀町","榎谷","","Naka-cho, Naka-gun","Enokidani",""]],
	"7715321":[[36,"那賀郡那賀町","馬路","","Naka-cho, Naka-gun","Umaji",""]],
	"7715322":[[36,"那賀郡那賀町","谷内","","Naka-cho, Naka-gun","Taniuchi",""]],
	"7715323":[[36,"那賀郡那賀町","相名","","Naka-cho, Naka-gun","Aina",""]],
	"7715324":[[36,"那賀郡那賀町","井ノ谷","","Naka-cho, Naka-gun","Inotani",""]],
	"7715325":[[36,"那賀郡那賀町","平野","","Naka-cho, Naka-gun","Hirano",""]],
	"7715326":[[36,"那賀郡那賀町","内山","","Naka-cho, Naka-gun","Uchiyama",""]],
	"7715327":[[36,"那賀郡那賀町","西納","","Naka-cho, Naka-gun","Nishino",""]],
	"7715328":[[36,"那賀郡那賀町","請ノ谷","","Naka-cho, Naka-gun","Ukenotani",""]],
	"7715329":[[36,"那賀郡那賀町","竹ケ谷","","Naka-cho, Naka-gun","Takegatani",""]],
	"7715401":[[36,"那賀郡那賀町","朝生","","Naka-cho, Naka-gun","Aso",""]],
	"7715402":[[36,"那賀郡那賀町","簗ノ上","","Naka-cho, Naka-gun","Yananoe",""]],
	"7715403":[[36,"那賀郡那賀町","鮎川","","Naka-cho, Naka-gun","Aikawa",""]],
	"7715404":[[36,"那賀郡那賀町","牛輪","","Naka-cho, Naka-gun","Ushiwa",""]],
	"7715405":[[36,"那賀郡那賀町","入野","","Naka-cho, Naka-gun","Irino",""]],
	"7715406":[[36,"那賀郡那賀町","延野","","Naka-cho, Naka-gun","Nobuno",""]],
	"7715407":[[36,"那賀郡那賀町","雄","","Naka-cho, Naka-gun","Ondori",""]],
	"7715408":[[36,"那賀郡那賀町","吉野","","Naka-cho, Naka-gun","Yoshino",""]],
	"7715409":[[36,"那賀郡那賀町","鉢","","Naka-cho, Naka-gun","Hachi",""]],
	"7715410":[[36,"那賀郡那賀町","大久保","","Naka-cho, Naka-gun","Okubo",""]],
	"7715411":[[36,"那賀郡那賀町","横石","","Naka-cho, Naka-gun","Yokoishi",""]],
	"7715412":[[36,"那賀郡那賀町","朴野","","Naka-cho, Naka-gun","Hono",""]],
	"7715413":[[36,"那賀郡那賀町","蔭谷","","Naka-cho, Naka-gun","Kagedani",""]],
	"7715501":[[36,"那賀郡那賀町","音谷","","Naka-cho, Naka-gun","Ondani",""]],
	"7715502":[[36,"那賀郡那賀町","桜谷","","Naka-cho, Naka-gun","Sakuradani",""]],
	"7715503":[[36,"那賀郡那賀町","小浜","","Naka-cho, Naka-gun","Kohama",""]],
	"7715504":[[36,"那賀郡那賀町","臼ケ谷","","Naka-cho, Naka-gun","Usugatani",""]],
	"7715505":[[36,"那賀郡那賀町","長安","","Naka-cho, Naka-gun","Nagayasu",""]],
	"7715506":[[36,"那賀郡那賀町","桧曽根","","Naka-cho, Naka-gun","Hisone",""]],
	"7715507":[[36,"那賀郡那賀町","菖蒲","","Naka-cho, Naka-gun","Shobu",""]],
	"7715508":[[36,"那賀郡那賀町","東尾","","Naka-cho, Naka-gun","Higashio",""]],
	"7715511":[[36,"那賀郡那賀町","水崎","","Naka-cho, Naka-gun","Misaki",""]],
	"7715512":[[36,"那賀郡那賀町","小計","","Naka-cho, Naka-gun","Kobakari",""]],
	"7715513":[[36,"那賀郡那賀町","古屋","","Naka-cho, Naka-gun","Furuya",""]],
	"7715514":[[36,"那賀郡那賀町","深森","","Naka-cho, Naka-gun","Fukamori",""]],
	"7715515":[[36,"那賀郡那賀町","川俣","","Naka-cho, Naka-gun","Kawamata",""]],
	"7715516":[[36,"那賀郡那賀町","大戸","","Naka-cho, Naka-gun","Oto",""]],
	"7715517":[[36,"那賀郡那賀町","日真","","Naka-cho, Naka-gun","Hima",""]],
	"7715518":[[36,"那賀郡那賀町","拝宮","","Naka-cho, Naka-gun","Haigyu",""]],
	"7715531":[[36,"那賀郡那賀町","日浦","","Naka-cho, Naka-gun","Hiura",""]],
	"7715532":[[36,"那賀郡那賀町","花瀬","","Naka-cho, Naka-gun","Hanaze",""]],
	"7716101":[[36,"那賀郡那賀町","阿津江","","Naka-cho, Naka-gun","Azue",""]],
	"7716102":[[36,"那賀郡那賀町","木頭名","","Naka-cho, Naka-gun","Kitomyo",""]],
	"7716103":[[36,"那賀郡那賀町","出羽","","Naka-cho, Naka-gun","Izuriha",""]],
	"7716104":[[36,"那賀郡那賀町","当山","","Naka-cho, Naka-gun","Toyama",""]],
	"7716105":[[36,"那賀郡那賀町","木頭","","Naka-cho, Naka-gun","Kito",""]],
	"7716106":[[36,"那賀郡那賀町","坂州","","Naka-cho, Naka-gun","Sakashu",""]],
	"7716107":[[36,"那賀郡那賀町","掛盤","","Naka-cho, Naka-gun","Kakeban",""]],
	"7716111":[[36,"那賀郡那賀町","小泉","","Naka-cho, Naka-gun","Koizumi",""]],
	"7716112":[[36,"那賀郡那賀町","高野","","Naka-cho, Naka-gun","Takano",""]],
	"7716113":[[36,"那賀郡那賀町","寺内","","Naka-cho, Naka-gun","Terauchi",""]],
	"7716114":[[36,"那賀郡那賀町","沢谷","","Naka-cho, Naka-gun","Sawadani",""]],
	"7716115":[[36,"那賀郡那賀町","小畠","","Naka-cho, Naka-gun","Obatake",""]],
	"7716116":[[36,"那賀郡那賀町","横谷","","Naka-cho, Naka-gun","Yokodani",""]],
	"7716117":[[36,"那賀郡那賀町","川成","","Naka-cho, Naka-gun","Kawanari",""]],
	"7716118":[[36,"那賀郡那賀町","岩倉","","Naka-cho, Naka-gun","Iwakura",""]],
	"7716321":[[36,"那賀郡那賀町","平谷","","Naka-cho, Naka-gun","Hiradani",""]],
	"7716322":[[36,"那賀郡那賀町","大殿","","Naka-cho, Naka-gun","Otono",""]],
	"7716323":[[36,"那賀郡那賀町","白石","","Naka-cho, Naka-gun","Shiraishi",""]],
	"7716324":[[36,"那賀郡那賀町","御所谷","","Naka-cho, Naka-gun","Goshodani",""]],
	"7716325":[[36,"那賀郡那賀町","丈ケ谷","","Naka-cho, Naka-gun","Jogatani",""]],
	"7716326":[[36,"那賀郡那賀町","府殿","","Naka-cho, Naka-gun","Fudono",""]],
	"7716327":[[36,"那賀郡那賀町","成瀬","","Naka-cho, Naka-gun","Naruse",""]],
	"7716328":[[36,"那賀郡那賀町","海川","","Naka-cho, Naka-gun","Kaikawa",""]],
	"7716401":[[36,"那賀郡那賀町","木頭助","","Naka-cho, Naka-gun","Kito Suke",""]],
	"7716402":[[36,"那賀郡那賀町","木頭出原","","Naka-cho, Naka-gun","Kito Izuhara",""]],
	"7716403":[[36,"那賀郡那賀町","木頭和無田","","Naka-cho, Naka-gun","Kito Wamuda",""]],
	"7716404":[[36,"那賀郡那賀町","木頭南宇","","Naka-cho, Naka-gun","Kito Minamiu",""]],
	"7716405":[[36,"那賀郡那賀町","木頭西宇","","Naka-cho, Naka-gun","Kito Nishiu",""]],
	"7716511":[[36,"那賀郡那賀町","木頭折宇","","Naka-cho, Naka-gun","Kito Oriu",""]],
	"7716512":[[36,"那賀郡那賀町","木頭北川","","Naka-cho, Naka-gun","Kito Kitagawa",""]]
})
