zipdata({
	"0390100":[[2,"三戸郡三戸町","","","Sannohe-machi, Sannohe-gun","",""],[2,"三戸郡南部町","","","Nambu-cho, Sannohe-gun","",""]],
	"0390101":[[2,"三戸郡南部町","玉掛","","Nambu-cho, Sannohe-gun","Tamakake",""]],
	"0390102":[[2,"三戸郡南部町","赤石","","Nambu-cho, Sannohe-gun","Akaishi",""]],
	"0390103":[[2,"三戸郡南部町","大向","","Nambu-cho, Sannohe-gun","Omukai",""]],
	"0390104":[[2,"三戸郡南部町","小向","","Nambu-cho, Sannohe-gun","Komukai",""]],
	"0390105":[[2,"三戸郡南部町","沖田面","","Nambu-cho, Sannohe-gun","Okitaomote",""]],
	"0390106":[[2,"三戸郡南部町","相内","","Nambu-cho, Sannohe-gun","Ainai",""]],
	"0390111":[[2,"三戸郡三戸町","泉山","","Sannohe-machi, Sannohe-gun","Izumiyama",""]],
	"0390112":[[2,"三戸郡三戸町","梅内","","Sannohe-machi, Sannohe-gun","Umenai",""]],
	"0390113":[[2,"三戸郡三戸町","目時","","Sannohe-machi, Sannohe-gun","Metoki",""]],
	"0390121":[[2,"三戸郡三戸町","豊川","","Sannohe-machi, Sannohe-gun","Toyokawa",""]],
	"0390122":[[2,"三戸郡三戸町","斗内","","Sannohe-machi, Sannohe-gun","Tonai",""]],
	"0390131":[[2,"三戸郡三戸町","二日町","","Sannohe-machi, Sannohe-gun","Futsukamachi",""]],
	"0390132":[[2,"三戸郡三戸町","在府小路町","","Sannohe-machi, Sannohe-gun","Zaifukojimachi",""]],
	"0390133":[[2,"三戸郡三戸町","馬喰町","","Sannohe-machi, Sannohe-gun","Bakuromachi",""]],
	"0390134":[[2,"三戸郡三戸町","同心町","","Sannohe-machi, Sannohe-gun","Doshincho",""]],
	"0390135":[[2,"三戸郡三戸町","八日町","","Sannohe-machi, Sannohe-gun","Yokamachi",""]],
	"0390141":[[2,"三戸郡三戸町","川守田","","Sannohe-machi, Sannohe-gun","Kawamorita",""]],
	"0390142":[[2,"三戸郡三戸町","久慈町","","Sannohe-machi, Sannohe-gun","Kujimachi",""]],
	"0390143":[[2,"三戸郡三戸町","川守田町","","Sannohe-machi, Sannohe-gun","Kawamoritamachi",""]],
	"0390144":[[2,"三戸郡三戸町","六日町","","Sannohe-machi, Sannohe-gun","Muikamachi",""]],
	"0390200":[[2,"三戸郡田子町","","","Takko-machi, Sannohe-gun","",""]],
	"0390201":[[2,"三戸郡田子町","田子","","Takko-machi, Sannohe-gun","Takko",""]],
	"0390202":[[2,"三戸郡田子町","相米","","Takko-machi, Sannohe-gun","Somai",""]],
	"0390311":[[2,"三戸郡田子町","原","","Takko-machi, Sannohe-gun","Hara",""]],
	"0390312":[[2,"三戸郡田子町","石亀","","Takko-machi, Sannohe-gun","Ishigame",""]],
	"0390313":[[2,"三戸郡田子町","茂市","","Takko-machi, Sannohe-gun","Moichi",""]],
	"0390314":[[2,"三戸郡田子町","遠瀬","","Takko-machi, Sannohe-gun","Tose",""]],
	"0390315":[[2,"三戸郡田子町","夏坂","","Takko-machi, Sannohe-gun","Natsusaka",""]],
	"0390316":[[2,"三戸郡田子町","関","","Takko-machi, Sannohe-gun","Seki",""]],
	"0390317":[[2,"三戸郡田子町","山口","","Takko-machi, Sannohe-gun","Yamaguchi",""]],
	"0390451":[[2,"三戸郡三戸町","蛇沼","","Sannohe-machi, Sannohe-gun","Januma",""]],
	"0390452":[[2,"三戸郡三戸町","袴田","","Sannohe-machi, Sannohe-gun","Hakamada",""]],
	"0390453":[[2,"三戸郡三戸町","貝守","","Sannohe-machi, Sannohe-gun","Kaimori",""]],
	"0390501":[[2,"三戸郡南部町","上名久井","","Nambu-cho, Sannohe-gun","Kaminakui",""]],
	"0390502":[[2,"三戸郡南部町","下名久井","","Nambu-cho, Sannohe-gun","Shimonakui",""]],
	"0390503":[[2,"三戸郡南部町","平","","Nambu-cho, Sannohe-gun","Taira",""]],
	"0390504":[[2,"三戸郡南部町","鳥舌内","","Nambu-cho, Sannohe-gun","Choshitanai",""]],
	"0390505":[[2,"三戸郡南部町","鳥谷","","Nambu-cho, Sannohe-gun","Toya",""]],
	"0390506":[[2,"三戸郡南部町","法光寺","","Nambu-cho, Sannohe-gun","Hokoji",""]],
	"0390507":[[2,"三戸郡南部町","高瀬","","Nambu-cho, Sannohe-gun","Takase",""]],
	"0390606":[[2,"三戸郡南部町","相内","","Nambu-cho, Sannohe-gun","Ainai",""]],
	"0390611":[[2,"三戸郡南部町","斗賀","","Nambu-cho, Sannohe-gun","Toga",""]],
	"0390612":[[2,"三戸郡南部町","剣吉","","Nambu-cho, Sannohe-gun","Kenyoshi",""]],
	"0390613":[[2,"三戸郡南部町","森越","","Nambu-cho, Sannohe-gun","Morikoshi",""]],
	"0390614":[[2,"三戸郡南部町","虎渡","","Nambu-cho, Sannohe-gun","Torato",""]],
	"0390801":[[2,"三戸郡南部町","片岸","","Nambu-cho, Sannohe-gun","Katagishi",""]],
	"0390802":[[2,"三戸郡南部町","苫米地","","Nambu-cho, Sannohe-gun","Tomabechi",""]],
	"0390803":[[2,"三戸郡南部町","麦沢","","Nambu-cho, Sannohe-gun","Mugisawa",""]],
	"0390804":[[2,"三戸郡南部町","高橋","","Nambu-cho, Sannohe-gun","Takahashi",""]],
	"0390805":[[2,"三戸郡南部町","小泉","","Nambu-cho, Sannohe-gun","Koizumi",""]],
	"0390811":[[2,"三戸郡南部町","法師岡","","Nambu-cho, Sannohe-gun","Hoshioka",""]],
	"0390812":[[2,"三戸郡南部町","椛木","","Nambu-cho, Sannohe-gun","Kabaki",""]],
	"0390813":[[2,"三戸郡南部町","杉沢","","Nambu-cho, Sannohe-gun","Sugisawa",""]],
	"0390814":[[2,"三戸郡南部町","埖渡","","Nambu-cho, Sannohe-gun","Gomiwatari",""]],
	"0390815":[[2,"三戸郡南部町","福田","","Nambu-cho, Sannohe-gun","Fukuda",""]],
	"0391101":[[2,"八戸市","尻内町","","Hachinohe-shi","Shiriuchimachi",""]],
	"0391102":[[2,"八戸市","一番町","","Hachinohe-shi","Ichibancho",""]],
	"0391103":[[2,"八戸市","長苗代","","Hachinohe-shi","Naganawashiro",""]],
	"0391104":[[2,"八戸市","田面木","","Hachinohe-shi","Tamonoki",""]],
	"0391105":[[2,"八戸市","八幡","","Hachinohe-shi","Yawata",""]],
	"0391106":[[2,"八戸市","坂牛","","Hachinohe-shi","Sakaushi",""]],
	"0391107":[[2,"八戸市","櫛引","","Hachinohe-shi","Kushibiki",""]],
	"0391108":[[2,"八戸市","上野","","Hachinohe-shi","Uwano",""]],
	"0391109":[[2,"八戸市","豊崎町","","Hachinohe-shi","Toyosakimachi",""]],
	"0391111":[[2,"八戸市","東白山台","","Hachinohe-shi","Higashihakusandai",""]],
	"0391112":[[2,"八戸市","南白山台","","Hachinohe-shi","Minamihakusandai",""]],
	"0391113":[[2,"八戸市","西白山台","","Hachinohe-shi","Nishihakusandai",""]],
	"0391114":[[2,"八戸市","北白山台","","Hachinohe-shi","Kitahakusandai",""]],
	"0391121":[[2,"八戸市","卸センター","","Hachinohe-shi","Oroshisenta",""]],
	"0391160":[[2,"八戸市","小田","","Hachinohe-shi","Koda",""]],
	"0391161":[[2,"八戸市","河原木","","Hachinohe-shi","Kawaragi",""]],
	"0391162":[[2,"八戸市","豊洲","","Hachinohe-shi","Toyosu",""]],
	"0391163":[[2,"八戸市","高州","","Hachinohe-shi","Takasu",""]],
	"0391164":[[2,"八戸市","下長","","Hachinohe-shi","Shimonaga",""]],
	"0391165":[[2,"八戸市","石堂","","Hachinohe-shi","Ishido",""]],
	"0391166":[[2,"八戸市","根城","","Hachinohe-shi","Nejo",""]],
	"0391167":[[2,"八戸市","沢里","","Hachinohe-shi","Sawasato",""]],
	"0391168":[[2,"八戸市","八太郎","","Hachinohe-shi","Hattaro",""]],
	"0391169":[[2,"八戸市","日計","","Hachinohe-shi","Hibakari",""]],
	"0391200":[[2,"三戸郡階上町","","","Hashikami-cho, Sannohe-gun","",""]],
	"0391201":[[2,"三戸郡階上町","道仏","","Hashikami-cho, Sannohe-gun","Dobutsu",""]],
	"0391202":[[2,"三戸郡階上町","赤保内","","Hashikami-cho, Sannohe-gun","Akabonai",""]],
	"0391203":[[2,"三戸郡階上町","鳥屋部","","Hashikami-cho, Sannohe-gun","Toyabe",""]],
	"0391204":[[2,"三戸郡階上町","平内","","Hashikami-cho, Sannohe-gun","Hiranai",""]],
	"0391205":[[2,"三戸郡階上町","晴山沢","","Hashikami-cho, Sannohe-gun","Hareyamasawa",""]],
	"0391206":[[2,"三戸郡階上町","田代","","Hashikami-cho, Sannohe-gun","Tashiro",""]],
	"0391207":[[2,"三戸郡階上町","金山沢","","Hashikami-cho, Sannohe-gun","Kaneyamasawa",""]],
	"0391208":[[2,"三戸郡階上町","角柄折","","Hashikami-cho, Sannohe-gun","Tsunogaraori",""]],
	"0391211":[[2,"三戸郡階上町","蒼前東","","Hashikami-cho, Sannohe-gun","Sozenhigashi",""]],
	"0391212":[[2,"三戸郡階上町","蒼前西","","Hashikami-cho, Sannohe-gun","Sozennishi",""]],
	"0391500":[[2,"三戸郡五戸町","","","Gonohe-machi, Sannohe-gun","",""]],
	"0391501":[[2,"三戸郡五戸町","上市川","","Gonohe-machi, Sannohe-gun","Kamiichikawa",""]],
	"0391502":[[2,"三戸郡五戸町","切谷内","","Gonohe-machi, Sannohe-gun","Kiriyanai",""]],
	"0391503":[[2,"三戸郡五戸町","大久保","","Gonohe-machi, Sannohe-gun","Okubo",""],[2,"三戸郡五戸町","佐野上谷地","","Gonohe-machi, Sannohe-gun","Sanokamiyachi",""],[2,"三戸郡五戸町","鮫ノ口","","Gonohe-machi, Sannohe-gun","Samenokuchi",""]],
	"0391504":[[2,"三戸郡五戸町","兎内","","Gonohe-machi, Sannohe-gun","Usaginai",""],[2,"三戸郡五戸町","兎内上保土沢","","Gonohe-machi, Sannohe-gun","Usaginaikamihotozawa",""],[2,"三戸郡五戸町","兎内下保土沢","","Gonohe-machi, Sannohe-gun","Usaginaishimohotozawa",""],[2,"三戸郡五戸町","兎内下川原","","Gonohe-machi, Sannohe-gun","Usaginaishimokawara",""],[2,"三戸郡五戸町","兎内下谷地","","Gonohe-machi, Sannohe-gun","Usaginaishimoyachi",""],[2,"三戸郡五戸町","上兎内","","Gonohe-machi, Sannohe-gun","Kamiusaginai",""]],
	"0391505":[[2,"三戸郡五戸町","石仏","","Gonohe-machi, Sannohe-gun","Ishibotoke",""],[2,"三戸郡五戸町","石仏上川原","","Gonohe-machi, Sannohe-gun","Ishibotokekamikawara",""],[2,"三戸郡五戸町","石仏下川原","","Gonohe-machi, Sannohe-gun","Ishibotokeshimokawara",""],[2,"三戸郡五戸町","石仏前","","Gonohe-machi, Sannohe-gun","Ishibotokemae",""]],
	"0391506":[[2,"三戸郡五戸町","熊野林","","Gonohe-machi, Sannohe-gun","Kumanobayashi",""],[2,"三戸郡五戸町","熊野林後","","Gonohe-machi, Sannohe-gun","Kumanobayashiushiro",""],[2,"三戸郡五戸町","熊野林前","","Gonohe-machi, Sannohe-gun","Kumanobayashimae",""]],
	"0391507":[[2,"三戸郡五戸町","蛯川後","","Gonohe-machi, Sannohe-gun","Ebikawaushiro",""],[2,"三戸郡五戸町","蛯川前川原","","Gonohe-machi, Sannohe-gun","Ebikawamaekawara",""],[2,"三戸郡五戸町","蛯川村","","Gonohe-machi, Sannohe-gun","Ebikawamura",""],[2,"三戸郡五戸町","上谷地","","Gonohe-machi, Sannohe-gun","Kamiyachi",""],[2,"三戸郡五戸町","中森","","Gonohe-machi, Sannohe-gun","Nakamori",""]],
	"0391508":[[2,"三戸郡五戸町","赤川","","Gonohe-machi, Sannohe-gun","Akagawa",""],[2,"三戸郡五戸町","赤川前","","Gonohe-machi, Sannohe-gun","Akagawamae",""],[2,"三戸郡五戸町","上新道","","Gonohe-machi, Sannohe-gun","Kamishimmichi",""],[2,"三戸郡五戸町","下新道","","Gonohe-machi, Sannohe-gun","Shimoshimmichi",""],[2,"三戸郡五戸町","土取場","","Gonohe-machi, Sannohe-gun","Tsuchitoriba",""],[2,"三戸郡五戸町","中寄","","Gonohe-machi, Sannohe-gun","Nakayori",""]],
	"0391511":[[2,"三戸郡五戸町","鍜冶屋窪","","Gonohe-machi, Sannohe-gun","Kajiyakubo",""],[2,"三戸郡五戸町","鍜冶屋窪上ミ","","Gonohe-machi, Sannohe-gun","Kajiyakubokami",""],[2,"三戸郡五戸町","鍜冶屋敷","","Gonohe-machi, Sannohe-gun","Kajiyashiki",""],[2,"三戸郡五戸町","丁塚","","Gonohe-machi, Sannohe-gun","Chozuka",""]],
	"0391512":[[2,"三戸郡五戸町","西ノ沢","","Gonohe-machi, Sannohe-gun","Nishinosawa",""]],
	"0391513":[[2,"三戸郡五戸町","古館","","Gonohe-machi, Sannohe-gun","Furudate",""],[2,"三戸郡五戸町","古館向","","Gonohe-machi, Sannohe-gun","Furudatemukai",""],[2,"三戸郡五戸町","古館向川原","","Gonohe-machi, Sannohe-gun","Furudatemukaikawara",""],[2,"三戸郡五戸町","古館脇","","Gonohe-machi, Sannohe-gun","Furudatewaki",""]],
	"0391514":[[2,"三戸郡五戸町","下中崎","","Gonohe-machi, Sannohe-gun","Shimonakasaki",""],[2,"三戸郡五戸町","中崎","","Gonohe-machi, Sannohe-gun","Nakazaki",""]],
	"0391515":[[2,"三戸郡五戸町","熊ノ沢","","Gonohe-machi, Sannohe-gun","Kumanosawa",""],[2,"三戸郡五戸町","熊ノ沢頭","","Gonohe-machi, Sannohe-gun","Kumanosawagashira",""],[2,"三戸郡五戸町","治郎左エ門長根","","Gonohe-machi, Sannohe-gun","Jirozaemonnagane",""]],
	"0391516":[[2,"三戸郡五戸町","市川道十文字","","Gonohe-machi, Sannohe-gun","Ichikawamichijumonji",""]],
	"0391517":[[2,"三戸郡五戸町","沢向","","Gonohe-machi, Sannohe-gun","Sawamukai",""]],
	"0391518":[[2,"三戸郡五戸町","下モ沢向","","Gonohe-machi, Sannohe-gun","Shimosawamukai",""]],
	"0391519":[[2,"三戸郡五戸町","天満","","Gonohe-machi, Sannohe-gun","Temman",""],[2,"三戸郡五戸町","天満後","","Gonohe-machi, Sannohe-gun","Temmanushiro",""],[2,"三戸郡五戸町","天満下川原","","Gonohe-machi, Sannohe-gun","Temmanshimokawara",""]],
	"0391521":[[2,"三戸郡五戸町","五百窪","","Gonohe-machi, Sannohe-gun","Iokubo",""],[2,"三戸郡五戸町","泉窪","","Gonohe-machi, Sannohe-gun","Izumikubo",""],[2,"三戸郡五戸町","大渡","","Gonohe-machi, Sannohe-gun","Owatari",""],[2,"三戸郡五戸町","大渡道ノ下","","Gonohe-machi, Sannohe-gun","Owatarimichinoshimo",""],[2,"三戸郡五戸町","久蔵窪","","Gonohe-machi, Sannohe-gun","Kyuzokubo",""]],
	"0391522":[[2,"三戸郡五戸町","小渡","","Gonohe-machi, Sannohe-gun","Kowatari",""],[2,"三戸郡五戸町","小渡頭","","Gonohe-machi, Sannohe-gun","Kowatarigashira",""],[2,"三戸郡五戸町","徳良窪","","Gonohe-machi, Sannohe-gun","Tokurakubo",""],[2,"三戸郡五戸町","苗代沢","","Gonohe-machi, Sannohe-gun","Nashirozawa",""]],
	"0391523":[[2,"三戸郡五戸町","上保土沢","","Gonohe-machi, Sannohe-gun","Kamihotozawa",""],[2,"三戸郡五戸町","下保土沢","","Gonohe-machi, Sannohe-gun","Shimohotozawa",""],[2,"三戸郡五戸町","新蔵長根","","Gonohe-machi, Sannohe-gun","Shinzonagane",""]],
	"0391524":[[2,"三戸郡五戸町","豊間内","","Gonohe-machi, Sannohe-gun","Toyomanai",""]],
	"0391525":[[2,"三戸郡五戸町","地蔵岱","","Gonohe-machi, Sannohe-gun","Jizotai",""]],
	"0391526":[[2,"三戸郡五戸町","上長下","","Gonohe-machi, Sannohe-gun","Kaminagashita",""],[2,"三戸郡五戸町","下長下","","Gonohe-machi, Sannohe-gun","Shimonagashita",""],[2,"三戸郡五戸町","惣林橋","","Gonohe-machi, Sannohe-gun","Sorimbashi",""]],
	"0391527":[[2,"三戸郡五戸町","扇田","","Gonohe-machi, Sannohe-gun","Ogida",""]],
	"0391528":[[2,"三戸郡五戸町","浅水","","Gonohe-machi, Sannohe-gun","Asamizu",""]],
	"0391529":[[2,"三戸郡五戸町","手倉橋","","Gonohe-machi, Sannohe-gun","Tegurabashi",""]],
	"0391531":[[2,"三戸郡五戸町","狐森","","Gonohe-machi, Sannohe-gun","Kitsunemori",""],[2,"三戸郡五戸町","狐森北","","Gonohe-machi, Sannohe-gun","Kitsunemorikita",""]],
	"0391532":[[2,"三戸郡五戸町","観音堂","","Gonohe-machi, Sannohe-gun","Kannondo",""]],
	"0391533":[[2,"三戸郡五戸町","上大町","","Gonohe-machi, Sannohe-gun","Kamiomachi",""],[2,"三戸郡五戸町","野月","","Gonohe-machi, Sannohe-gun","Nozuki",""]],
	"0391534":[[2,"三戸郡五戸町","荒町","","Gonohe-machi, Sannohe-gun","Aramachi",""]],
	"0391535":[[2,"三戸郡五戸町","新丁","","Gonohe-machi, Sannohe-gun","Shincho",""]],
	"0391536":[[2,"三戸郡五戸町","愛宕後","","Gonohe-machi, Sannohe-gun","Atagoshiro",""],[2,"三戸郡五戸町","愛宕下タ","","Gonohe-machi, Sannohe-gun","Atagoshita",""],[2,"三戸郡五戸町","愛宕丁","","Gonohe-machi, Sannohe-gun","Atagocho",""]],
	"0391537":[[2,"三戸郡五戸町","ウルエ長根","","Gonohe-machi, Sannohe-gun","Uruenagane",""],[2,"三戸郡五戸町","ウルエ長根下","","Gonohe-machi, Sannohe-gun","Uruenaganeshita",""],[2,"三戸郡五戸町","追分","","Gonohe-machi, Sannohe-gun","Oiwake",""],[2,"三戸郡五戸町","二本柳","","Gonohe-machi, Sannohe-gun","Nihonyanagi",""],[2,"三戸郡五戸町","二本柳向","","Gonohe-machi, Sannohe-gun","Nihonyanagimukai",""]],
	"0391538":[[2,"三戸郡五戸町","塚無岱","","Gonohe-machi, Sannohe-gun","Tsukanashitai",""],[2,"三戸郡五戸町","古街道長根","","Gonohe-machi, Sannohe-gun","Furukaidonagane",""]],
	"0391539":[[2,"三戸郡五戸町","石沢境","","Gonohe-machi, Sannohe-gun","Ishizawasakai",""],[2,"三戸郡五戸町","中ノ沢","","Gonohe-machi, Sannohe-gun","Nakanosawa",""],[2,"三戸郡五戸町","中ノ沢西張","","Gonohe-machi, Sannohe-gun","Nakanosawanishihari",""]],
	"0391541":[[2,"三戸郡五戸町","新田窪","","Gonohe-machi, Sannohe-gun","Shindenkubo",""]],
	"0391542":[[2,"三戸郡五戸町","中道","","Gonohe-machi, Sannohe-gun","Nakamichi",""],[2,"三戸郡五戸町","中道十文字","","Gonohe-machi, Sannohe-gun","Nakamichijumonji",""]],
	"0391543":[[2,"三戸郡五戸町","竹原","","Gonohe-machi, Sannohe-gun","Takehara",""]],
	"0391544":[[2,"三戸郡五戸町","二階平","","Gonohe-machi, Sannohe-gun","Nikaidaira",""],[2,"三戸郡五戸町","二階平下タ","","Gonohe-machi, Sannohe-gun","Nikaidairashita",""]],
	"0391545":[[2,"三戸郡五戸町","正場沢","","Gonohe-machi, Sannohe-gun","Shobasawa",""],[2,"三戸郡五戸町","正場沢長根","","Gonohe-machi, Sannohe-gun","Shobasawanagane",""]],
	"0391546":[[2,"三戸郡五戸町","下タノ沢","","Gonohe-machi, Sannohe-gun","Shitanosawa",""],[2,"三戸郡五戸町","下タノ沢頭","","Gonohe-machi, Sannohe-gun","Shitanosawagashira",""],[2,"三戸郡五戸町","土井頭","","Gonohe-machi, Sannohe-gun","Doigashira",""]],
	"0391547":[[2,"三戸郡五戸町","神明後","","Gonohe-machi, Sannohe-gun","Shimmeiushiro",""]],
	"0391548":[[2,"三戸郡五戸町","新町","","Gonohe-machi, Sannohe-gun","Shimmachi",""]],
	"0391551":[[2,"三戸郡五戸町","上新井田","","Gonohe-machi, Sannohe-gun","Kaminiida",""],[2,"三戸郡五戸町","上新井田前","","Gonohe-machi, Sannohe-gun","Kaminiidamae",""]],
	"0391552":[[2,"三戸郡五戸町","姥堤","","Gonohe-machi, Sannohe-gun","Ubazutsumi",""],[2,"三戸郡五戸町","上高田","","Gonohe-machi, Sannohe-gun","Kamitakada",""],[2,"三戸郡五戸町","筒口川原","","Gonohe-machi, Sannohe-gun","Doguchikawara",""],[2,"三戸郡五戸町","中高田","","Gonohe-machi, Sannohe-gun","Nakatakada",""]],
	"0391553":[[2,"三戸郡五戸町","川原町下裏","","Gonohe-machi, Sannohe-gun","Kawaramachishimora",""],[2,"三戸郡五戸町","川原町西裏","","Gonohe-machi, Sannohe-gun","Kawaramachinishiura",""]],
	"0391554":[[2,"三戸郡五戸町","川原町","","Gonohe-machi, Sannohe-gun","Kawaramachi",""],[2,"三戸郡五戸町","川原町裏","","Gonohe-machi, Sannohe-gun","Kawaramachiura",""],[2,"三戸郡五戸町","傳兵ヱ丁","","Gonohe-machi, Sannohe-gun","Dembeecho",""]],
	"0391555":[[2,"三戸郡五戸町","下高田","","Gonohe-machi, Sannohe-gun","Shimotakada",""],[2,"三戸郡五戸町","古堂","","Gonohe-machi, Sannohe-gun","Furudo",""],[2,"三戸郡五戸町","古堂後","","Gonohe-machi, Sannohe-gun","Furudoushiro",""]],
	"0391556":[[2,"三戸郡五戸町","油出","","Gonohe-machi, Sannohe-gun","Aburade",""]],
	"0391557":[[2,"三戸郡五戸町","上川原","","Gonohe-machi, Sannohe-gun","Kamikawara",""],[2,"三戸郡五戸町","八景","","Gonohe-machi, Sannohe-gun","Hakkei",""]],
	"0391558":[[2,"三戸郡五戸町","沢","","Gonohe-machi, Sannohe-gun","Sawa",""],[2,"三戸郡五戸町","館","","Gonohe-machi, Sannohe-gun","Tate",""],[2,"三戸郡五戸町","博労町","","Gonohe-machi, Sannohe-gun","Bakuromachi",""],[2,"三戸郡五戸町","堀合","","Gonohe-machi, Sannohe-gun","Horiai",""]],
	"0391559":[[2,"三戸郡五戸町","下大町","","Gonohe-machi, Sannohe-gun","Shimoomachi",""],[2,"三戸郡五戸町","横丁","","Gonohe-machi, Sannohe-gun","Yokocho",""]],
	"0391561":[[2,"三戸郡五戸町","赤坂","","Gonohe-machi, Sannohe-gun","Akasaka",""],[2,"三戸郡五戸町","越掛沢","","Gonohe-machi, Sannohe-gun","Koshikakezawa",""],[2,"三戸郡五戸町","越掛沢前","","Gonohe-machi, Sannohe-gun","Koshikakezawamae",""],[2,"三戸郡五戸町","越掛沢道下モ","","Gonohe-machi, Sannohe-gun","Koshikakezawamichinoshimo",""]],
	"0391562":[[2,"三戸郡五戸町","鹿内","","Gonohe-machi, Sannohe-gun","Shikanai",""],[2,"三戸郡五戸町","鹿内沖","","Gonohe-machi, Sannohe-gun","Shikanaioki",""],[2,"三戸郡五戸町","鹿内下モ","","Gonohe-machi, Sannohe-gun","Shikanaishimo",""],[2,"三戸郡五戸町","鹿内前","","Gonohe-machi, Sannohe-gun","Shikanaimae",""],[2,"三戸郡五戸町","白山","","Gonohe-machi, Sannohe-gun","Hakusan",""],[2,"三戸郡五戸町","白山前","","Gonohe-machi, Sannohe-gun","Hakusammae",""]],
	"0391563":[[2,"三戸郡五戸町","岡谷地","","Gonohe-machi, Sannohe-gun","Okayachi",""],[2,"三戸郡五戸町","毛無森","","Gonohe-machi, Sannohe-gun","Kenashimori",""],[2,"三戸郡五戸町","大学沢","","Gonohe-machi, Sannohe-gun","Daigakuzawa",""],[2,"三戸郡五戸町","大学沢向","","Gonohe-machi, Sannohe-gun","Daigakuzawamukai",""],[2,"三戸郡五戸町","大工窪","","Gonohe-machi, Sannohe-gun","Daikukubo",""],[2,"三戸郡五戸町","平佐窪","","Gonohe-machi, Sannohe-gun","Heisakubo",""]],
	"0391564":[[2,"三戸郡五戸町","古館下川原","","Gonohe-machi, Sannohe-gun","Furudateshimokawara",""],[2,"三戸郡五戸町","六角","","Gonohe-machi, Sannohe-gun","Rokkaku",""]],
	"0391565":[[2,"三戸郡五戸町","下新井田","","Gonohe-machi, Sannohe-gun","Shimoniida",""],[2,"三戸郡五戸町","下新井田前","","Gonohe-machi, Sannohe-gun","Shimoniidamae",""],[2,"三戸郡五戸町","花道川原","","Gonohe-machi, Sannohe-gun","Hanamichikawara",""]],
	"0391566":[[2,"三戸郡五戸町","幸ノ神","","Gonohe-machi, Sannohe-gun","Sainokami",""],[2,"三戸郡五戸町","幸ノ神前","","Gonohe-machi, Sannohe-gun","Sainokamimae",""]],
	"0391567":[[2,"三戸郡五戸町","上大平楽","","Gonohe-machi, Sannohe-gun","Kamitaiheiraku",""],[2,"三戸郡五戸町","下大平楽","","Gonohe-machi, Sannohe-gun","Shimotaiheiraku",""]],
	"0391568":[[2,"三戸郡五戸町","銀杏木","","Gonohe-machi, Sannohe-gun","Ichonoki",""],[2,"三戸郡五戸町","銀杏木前","","Gonohe-machi, Sannohe-gun","Ichonokimae",""],[2,"三戸郡五戸町","一本木","","Gonohe-machi, Sannohe-gun","Ippongi",""],[2,"三戸郡五戸町","一本木前","","Gonohe-machi, Sannohe-gun","Ippongimae",""],[2,"三戸郡五戸町","應田","","Gonohe-machi, Sannohe-gun","Oda",""],[2,"三戸郡五戸町","傘松","","Gonohe-machi, Sannohe-gun","Karakasamatsu",""],[2,"三戸郡五戸町","傘松前","","Gonohe-machi, Sannohe-gun","Karakasamatsumae",""]],
	"0391569":[[2,"三戸郡五戸町","根岸","","Gonohe-machi, Sannohe-gun","Negishi",""],[2,"三戸郡五戸町","虫追塚前","","Gonohe-machi, Sannohe-gun","Mushioizukamae",""]],
	"0391701":[[2,"三戸郡五戸町","倉石石沢","","Gonohe-machi, Sannohe-gun","Kuraishi Ishizawa",""]],
	"0391702":[[2,"三戸郡五戸町","倉石中市","","Gonohe-machi, Sannohe-gun","Kuraishi Nakaichi",""]],
	"0391703":[[2,"三戸郡五戸町","倉石又重","","Gonohe-machi, Sannohe-gun","Kuraishi Matashige",""]],
	"0391800":[[2,"三戸郡新郷村","","","Shingo-mura, Sannohe-gun","",""]],
	"0391801":[[2,"三戸郡新郷村","戸来","","Shingo-mura, Sannohe-gun","Herai",""]],
	"0391802":[[2,"三戸郡新郷村","西越","","Shingo-mura, Sannohe-gun","Saigoshi",""]],
	"0392102":[[2,"上北郡おいらせ町","豊栄","","Oirase-cho, Kamikita-gun","Toyosakae",""]],
	"0392111":[[2,"上北郡おいらせ町","西後谷地","","Oirase-cho, Kamikita-gun","Nishiushiroyachi",""]],
	"0392112":[[2,"上北郡おいらせ町","中野平","","Oirase-cho, Kamikita-gun","Nakanotai",""]],
	"0392113":[[2,"上北郡おいらせ町","犬毛谷地","","Oirase-cho, Kamikita-gun","Inukeyachi",""]],
	"0392114":[[2,"上北郡おいらせ町","高田","","Oirase-cho, Kamikita-gun","Takada",""]],
	"0392115":[[2,"上北郡おいらせ町","菜飯","","Oirase-cho, Kamikita-gun","Nameshi",""]],
	"0392116":[[2,"上北郡おいらせ町","秋堂","","Oirase-cho, Kamikita-gun","Akido",""]],
	"0392117":[[2,"上北郡おいらせ町","川端","","Oirase-cho, Kamikita-gun","Kawabata",""]],
	"0392118":[[2,"上北郡おいらせ町","彦七川原","","Oirase-cho, Kamikita-gun","Hikoshichigawara",""]],
	"0392121":[[2,"上北郡おいらせ町","下境","","Oirase-cho, Kamikita-gun","Shimosakai",""]],
	"0392122":[[2,"上北郡おいらせ町","沼小屋","","Oirase-cho, Kamikita-gun","Numakoya",""]],
	"0392123":[[2,"上北郡おいらせ町","西下谷地","","Oirase-cho, Kamikita-gun","Nishishimoyachi",""]],
	"0392124":[[2,"上北郡おいらせ町","境田","","Oirase-cho, Kamikita-gun","Sakaida",""]],
	"0392125":[[2,"上北郡おいらせ町","三本木","","Oirase-cho, Kamikita-gun","Sambongi",""]],
	"0392126":[[2,"上北郡おいらせ町","間木","","Oirase-cho, Kamikita-gun","Magi",""]],
	"0392127":[[2,"上北郡おいらせ町","木崎","","Oirase-cho, Kamikita-gun","Kizaki",""]],
	"0392128":[[2,"上北郡おいらせ町","染屋","","Oirase-cho, Kamikita-gun","Someya",""]],
	"0392129":[[2,"上北郡おいらせ町","中平下長根山","","Oirase-cho, Kamikita-gun","Nakataishimonaganeyama",""]],
	"0392131":[[2,"上北郡おいらせ町","向川原","","Oirase-cho, Kamikita-gun","Mukaikawara",""]],
	"0392132":[[2,"上北郡おいらせ町","西前川原","","Oirase-cho, Kamikita-gun","Nishimaekawara",""]],
	"0392133":[[2,"上北郡おいらせ町","上川原","","Oirase-cho, Kamikita-gun","Kamikawara",""]],
	"0392134":[[2,"上北郡おいらせ町","馳下り","","Oirase-cho, Kamikita-gun","Hasekudari",""]],
	"0392135":[[2,"上北郡おいらせ町","立蛇","","Oirase-cho, Kamikita-gun","Tachija",""]],
	"0392136":[[2,"上北郡おいらせ町","中下田","","Oirase-cho, Kamikita-gun","Nakashimoda",""]],
	"0392141":[[2,"上北郡おいらせ町","明土","","Oirase-cho, Kamikita-gun","Akedo",""]],
	"0392142":[[2,"上北郡おいらせ町","小前谷地","","Oirase-cho, Kamikita-gun","Komaeyachi",""]],
	"0392143":[[2,"上北郡おいらせ町","上水下","","Oirase-cho, Kamikita-gun","Josuishita",""]],
	"0392144":[[2,"上北郡おいらせ町","丈の端","","Oirase-cho, Kamikita-gun","Takenohashi",""]],
	"0392145":[[2,"上北郡おいらせ町","上谷地","","Oirase-cho, Kamikita-gun","Kamiyachi",""]],
	"0392146":[[2,"上北郡おいらせ町","中谷地","","Oirase-cho, Kamikita-gun","Nakayachi",""]],
	"0392147":[[2,"上北郡おいらせ町","赤田前","","Oirase-cho, Kamikita-gun","Akadamae",""]],
	"0392151":[[2,"上北郡おいらせ町","向山","","Oirase-cho, Kamikita-gun","Mukaiyama",""]],
	"0392152":[[2,"上北郡おいらせ町","向山東","","Oirase-cho, Kamikita-gun","Mukaiyamahigashi",""]],
	"0392153":[[2,"上北郡おいらせ町","山崎","","Oirase-cho, Kamikita-gun","Yamazaki",""]],
	"0392154":[[2,"上北郡おいらせ町","豊原","","Oirase-cho, Kamikita-gun","Toyohara",""]],
	"0392155":[[2,"上北郡おいらせ町","木ノ下西","","Oirase-cho, Kamikita-gun","Kinoshitanishi",""]],
	"0392156":[[2,"上北郡おいらせ町","木ノ下南","","Oirase-cho, Kamikita-gun","Kinoshitaminami",""]],
	"0392157":[[2,"上北郡おいらせ町","木ノ下東","","Oirase-cho, Kamikita-gun","Kinoshitahigashi",""]],
	"0392158":[[2,"上北郡おいらせ町","向山南","","Oirase-cho, Kamikita-gun","Mukaiyamaminami",""]],
	"0392161":[[2,"上北郡おいらせ町","西下川原","","Oirase-cho, Kamikita-gun","Nishishimokawara",""]],
	"0392162":[[2,"上北郡おいらせ町","南下田","","Oirase-cho, Kamikita-gun","Minamishimoda",""]],
	"0392163":[[2,"上北郡おいらせ町","館越","","Oirase-cho, Kamikita-gun","Tategoshi",""]],
	"0392164":[[2,"上北郡おいらせ町","神明前","","Oirase-cho, Kamikita-gun","Shimmeimae",""]],
	"0392165":[[2,"上北郡おいらせ町","阿光坊","","Oirase-cho, Kamikita-gun","Akobo",""]],
	"0392171":[[2,"上北郡おいらせ町","新敷","","Oirase-cho, Kamikita-gun","Nishiki",""]],
	"0392172":[[2,"上北郡おいらせ町","洗平","","Oirase-cho, Kamikita-gun","Araidai",""]],
	"0392173":[[2,"上北郡おいらせ町","瓢","","Oirase-cho, Kamikita-gun","Fukube",""]],
	"0392180":[[2,"上北郡おいらせ町","住吉","","Oirase-cho, Kamikita-gun","Sumiyoshi",""]],
	"0392181":[[2,"上北郡おいらせ町","古間木山","","Oirase-cho, Kamikita-gun","Furumagiyama",""]],
	"0392182":[[2,"上北郡おいらせ町","鶉久保","","Oirase-cho, Kamikita-gun","Uzurakubo",""]],
	"0392183":[[2,"上北郡おいらせ町","鶉久保山","","Oirase-cho, Kamikita-gun","Uzurakuboyama",""]],
	"0392184":[[2,"上北郡おいらせ町","浜道","","Oirase-cho, Kamikita-gun","Hamamichi",""]],
	"0392185":[[2,"上北郡おいらせ町","上久保","","Oirase-cho, Kamikita-gun","Kamikubo",""]],
	"0392186":[[2,"上北郡おいらせ町","北下田","","Oirase-cho, Kamikita-gun","Kitashimoda",""]],
	"0392187":[[2,"上北郡おいらせ町","緑ケ丘","","Oirase-cho, Kamikita-gun","Midorigaoka",""]],
	"0392188":[[2,"上北郡おいらせ町","若葉","","Oirase-cho, Kamikita-gun","Wakaba",""]],
	"0392189":[[2,"上北郡おいらせ町","青葉","","Oirase-cho, Kamikita-gun","Aoba",""]],
	"0392200":[[2,"上北郡おいらせ町","","","Oirase-cho, Kamikita-gun","",""]],
	"0392201":[[2,"上北郡おいらせ町","二川目","","Oirase-cho, Kamikita-gun","Futakawame",""]],
	"0392202":[[2,"上北郡おいらせ町","向平","","Oirase-cho, Kamikita-gun","Mukaitai",""]],
	"0392203":[[2,"上北郡おいらせ町","一川目","","Oirase-cho, Kamikita-gun","Hitokawame",""]],
	"0392204":[[2,"上北郡おいらせ町","深沢","","Oirase-cho, Kamikita-gun","Fukasawa",""]],
	"0392205":[[2,"上北郡おいらせ町","深沢平","","Oirase-cho, Kamikita-gun","Fukasawatai",""]],
	"0392206":[[2,"上北郡おいらせ町","松原","","Oirase-cho, Kamikita-gun","Matsubara",""]],
	"0392211":[[2,"上北郡おいらせ町","新田","","Oirase-cho, Kamikita-gun","Shinden",""]],
	"0392212":[[2,"上北郡おいらせ町","東下川原","","Oirase-cho, Kamikita-gun","Higashishimokawara",""]],
	"0392213":[[2,"上北郡おいらせ町","堀ノ内","","Oirase-cho, Kamikita-gun","Horinochi",""]],
	"0392214":[[2,"上北郡おいらせ町","東前川原","","Oirase-cho, Kamikita-gun","Higashimaekawara",""]],
	"0392215":[[2,"上北郡おいらせ町","下屋敷","","Oirase-cho, Kamikita-gun","Shimoyashiki",""]],
	"0392216":[[2,"上北郡おいらせ町","後田","","Oirase-cho, Kamikita-gun","Ushiroda",""]],
	"0392217":[[2,"上北郡おいらせ町","牛込平","","Oirase-cho, Kamikita-gun","Ushigometai",""]],
	"0392221":[[2,"上北郡おいらせ町","上前田","","Oirase-cho, Kamikita-gun","Kamimaeda",""]],
	"0392222":[[2,"上北郡おいらせ町","下前田","","Oirase-cho, Kamikita-gun","Shimomaeda",""]],
	"0392223":[[2,"上北郡おいらせ町","苗平谷地","","Oirase-cho, Kamikita-gun","Naehirayachi",""]],
	"0392224":[[2,"上北郡おいらせ町","下明堂","","Oirase-cho, Kamikita-gun","Shimoakedo",""]],
	"0392225":[[2,"上北郡おいらせ町","上明堂","","Oirase-cho, Kamikita-gun","Kamiakedo",""]],
	"0392226":[[2,"上北郡おいらせ町","新助川原","","Oirase-cho, Kamikita-gun","Shinsukekawara",""]],
	"0392231":[[2,"上北郡おいらせ町","東下谷地","","Oirase-cho, Kamikita-gun","Higashishimoyachi",""]],
	"0392232":[[2,"上北郡おいらせ町","東後谷地","","Oirase-cho, Kamikita-gun","Higashiushiroyachi",""]],
	"0392233":[[2,"上北郡おいらせ町","沼端","","Oirase-cho, Kamikita-gun","Numahata",""]],
	"0392234":[[2,"上北郡おいらせ町","堤田","","Oirase-cho, Kamikita-gun","Tsutsumida",""]],
	"0392235":[[2,"上北郡おいらせ町","千刈田","","Oirase-cho, Kamikita-gun","Sengarida",""]],
	"0392236":[[2,"上北郡おいらせ町","洋光台","","Oirase-cho, Kamikita-gun","Yokodai",""]],
	"0392241":[[2,"八戸市","市川町","","Hachinohe-shi","Ichikawamachi",""]],
	"0392242":[[2,"八戸市","多賀台","","Hachinohe-shi","Tagadai",""]],
	"0392243":[[2,"八戸市","松ケ丘","","Hachinohe-shi","Matsugaoka",""]],
	"0392245":[[2,"八戸市","北インター工業団地","","Hachinohe-shi","Kitaintakogyodanchi",""]],
	"0392246":[[2,"八戸市","桔梗野工業団地","","Hachinohe-shi","Kikyonokogyodanchi",""]],
	"0392251":[[2,"上北郡おいらせ町","向坂","","Oirase-cho, Kamikita-gun","Mukaisaka",""]],
	"0392252":[[2,"上北郡おいらせ町","黒坂谷地","","Oirase-cho, Kamikita-gun","Kurosakayachi",""]],
	"0392253":[[2,"上北郡おいらせ町","獺野","","Oirase-cho, Kamikita-gun","Usono",""]],
	"0392254":[[2,"上北郡おいらせ町","苗振谷地","","Oirase-cho, Kamikita-gun","Naefuriyachi",""]],
	"0392255":[[2,"上北郡おいらせ町","土取","","Oirase-cho, Kamikita-gun","Tsuchitori",""]],
	"0392300":[[2,"上北郡六戸町","","","Rokunohe-machi, Kamikita-gun","",""]],
	"0392302":[[2,"三戸郡五戸町","切谷内","","Gonohe-machi, Sannohe-gun","Kiriyanai",""]],
	"0392311":[[2,"上北郡六戸町","上吉田","","Rokunohe-machi, Kamikita-gun","Kamiyoshita",""]],
	"0392312":[[2,"上北郡六戸町","下吉田","","Rokunohe-machi, Kamikita-gun","Shimoyoshita",""]],
	"0392313":[[2,"上北郡六戸町","鶴喰","","Rokunohe-machi, Kamikita-gun","Tsurubami",""]],
	"0392314":[[2,"上北郡六戸町","小平","","Rokunohe-machi, Kamikita-gun","Kodaira",""]],
	"0392315":[[2,"上北郡六戸町","柳町","","Rokunohe-machi, Kamikita-gun","Yanagimachi",""]],
	"0392371":[[2,"上北郡六戸町","犬落瀬","","Rokunohe-machi, Kamikita-gun","Inuotose",""]],
	"0392372":[[2,"上北郡六戸町","折茂","","Rokunohe-machi, Kamikita-gun","Orimo",""]],
	"0392401":[[2,"上北郡東北町","上野","","Tohoku-machi, Kamikita-gun","Uwano",""]],
	"0392402":[[2,"上北郡東北町","大浦","","Tohoku-machi, Kamikita-gun","Oura",""]],
	"0392403":[[2,"上北郡東北町","新舘","","Tohoku-machi, Kamikita-gun","Niidate",""]],
	"0392404":[[2,"上北郡東北町","上北北","","Tohoku-machi, Kamikita-gun","Kamikitakita",""]],
	"0392405":[[2,"上北郡東北町","上北南","","Tohoku-machi, Kamikita-gun","Kamikitaminami",""]],
	"0392406":[[2,"上北郡東北町","旭北","","Tohoku-machi, Kamikita-gun","Asahikita",""]],
	"0392407":[[2,"上北郡東北町","旭南","","Tohoku-machi, Kamikita-gun","Asahiminami",""]],
	"0392500":[[2,"上北郡七戸町","","","Shichinohe-machi, Kamikita-gun","",""]],
	"0392501":[[2,"上北郡七戸町","荒熊内","","Shichinohe-machi, Kamikita-gun","Arakumanai",""]],
	"0392502":[[2,"上北郡七戸町","大沢","","Shichinohe-machi, Kamikita-gun","Osawa",""]],
	"0392503":[[2,"上北郡七戸町","豊間内","","Shichinohe-machi, Kamikita-gun","Toyomanai",""]],
	"0392504":[[2,"上北郡七戸町","寒水","","Shichinohe-machi, Kamikita-gun","Hiyamizu",""]],
	"0392505":[[2,"上北郡七戸町","立野頭","","Shichinohe-machi, Kamikita-gun","Tatenogashira",""]],
	"0392506":[[2,"上北郡七戸町","膝森","","Shichinohe-machi, Kamikita-gun","Hizamori",""]],
	"0392507":[[2,"上北郡七戸町","えぞ花","","Shichinohe-machi, Kamikita-gun","Ezobana",""]],
	"0392508":[[2,"上北郡七戸町","大池","","Shichinohe-machi, Kamikita-gun","Oike",""]],
	"0392511":[[2,"上北郡七戸町","笊田川久保","","Shichinohe-machi, Kamikita-gun","Zarutakawakubo",""]],
	"0392512":[[2,"上北郡七戸町","笊田","","Shichinohe-machi, Kamikita-gun","Zaruta",""]],
	"0392513":[[2,"上北郡七戸町","東槻木","","Shichinohe-machi, Kamikita-gun","Higashitsukinoki",""]],
	"0392514":[[2,"上北郡七戸町","太田野","","Shichinohe-machi, Kamikita-gun","Otano",""]],
	"0392515":[[2,"上北郡七戸町","蒼前","","Shichinohe-machi, Kamikita-gun","Sozen",""]],
	"0392516":[[2,"上北郡七戸町","舘野","","Shichinohe-machi, Kamikita-gun","Tateno",""]],
	"0392517":[[2,"上北郡七戸町","夏焼","","Shichinohe-machi, Kamikita-gun","Natsuyaki",""]],
	"0392518":[[2,"上北郡七戸町","天神林","","Shichinohe-machi, Kamikita-gun","Tenjimbayashi",""]],
	"0392521":[[2,"上北郡七戸町","天王","","Shichinohe-machi, Kamikita-gun","Tenno",""]],
	"0392522":[[2,"上北郡七戸町","倉越","","Shichinohe-machi, Kamikita-gun","Kurakoshi",""]],
	"0392523":[[2,"上北郡七戸町","影津内","","Shichinohe-machi, Kamikita-gun","Kagetsunai",""]],
	"0392524":[[2,"上北郡七戸町","寺裏","","Shichinohe-machi, Kamikita-gun","Teraura",""]],
	"0392525":[[2,"上北郡七戸町","七戸","","Shichinohe-machi, Kamikita-gun","Shichinohe",""]],
	"0392526":[[2,"上北郡七戸町","上町野","","Shichinohe-machi, Kamikita-gun","Uwamachino",""]],
	"0392527":[[2,"上北郡七戸町","町","","Shichinohe-machi, Kamikita-gun","Machi",""]],
	"0392531":[[2,"上北郡七戸町","太田","","Shichinohe-machi, Kamikita-gun","Ota",""]],
	"0392532":[[2,"上北郡七戸町","大林","","Shichinohe-machi, Kamikita-gun","Obayashi",""]],
	"0392533":[[2,"上北郡七戸町","川去","","Shichinohe-machi, Kamikita-gun","Kawasari",""]],
	"0392534":[[2,"上北郡七戸町","荒屋","","Shichinohe-machi, Kamikita-gun","Araya",""]],
	"0392535":[[2,"上北郡七戸町","沼ノ沢","","Shichinohe-machi, Kamikita-gun","Numanosawa",""]],
	"0392536":[[2,"上北郡七戸町","野佐掛","","Shichinohe-machi, Kamikita-gun","Nosakake",""]],
	"0392537":[[2,"上北郡七戸町","賽ノ神","","Shichinohe-machi, Kamikita-gun","Sainokami",""]],
	"0392538":[[2,"上北郡七戸町","寺下","","Shichinohe-machi, Kamikita-gun","Terashita",""]],
	"0392539":[[2,"上北郡七戸町","中村","","Shichinohe-machi, Kamikita-gun","Nakamura",""]],
	"0392541":[[2,"上北郡七戸町","都平","","Shichinohe-machi, Kamikita-gun","Miyakotai",""]],
	"0392542":[[2,"上北郡七戸町","萩ノ沢","","Shichinohe-machi, Kamikita-gun","Haginosawa",""]],
	"0392543":[[2,"上北郡七戸町","有田沢","","Shichinohe-machi, Kamikita-gun","Aritasawa",""]],
	"0392544":[[2,"上北郡七戸町","八栗平","","Shichinohe-machi, Kamikita-gun","Hakkuritai",""]],
	"0392545":[[2,"上北郡七戸町","別曽","","Shichinohe-machi, Kamikita-gun","Besso",""]],
	"0392546":[[2,"上北郡七戸町","清水頭","","Shichinohe-machi, Kamikita-gun","Shimizukashira",""]],
	"0392547":[[2,"上北郡七戸町","矢倉","","Shichinohe-machi, Kamikita-gun","Yagura",""]],
	"0392548":[[2,"上北郡七戸町","見町","","Shichinohe-machi, Kamikita-gun","Mirumachi",""]],
	"0392549":[[2,"上北郡七戸町","下見町","","Shichinohe-machi, Kamikita-gun","Shimomirumachi",""]],
	"0392551":[[2,"上北郡七戸町","薬師平","","Shichinohe-machi, Kamikita-gun","Yakushitai",""]],
	"0392552":[[2,"上北郡七戸町","鶴打田","","Shichinohe-machi, Kamikita-gun","Tsuruchita",""]],
	"0392553":[[2,"上北郡七戸町","八尺堂","","Shichinohe-machi, Kamikita-gun","Hasshakudo",""]],
	"0392554":[[2,"上北郡七戸町","中岫","","Shichinohe-machi, Kamikita-gun","Nakaguki",""]],
	"0392555":[[2,"上北郡七戸町","前田","","Shichinohe-machi, Kamikita-gun","Maeda",""]],
	"0392556":[[2,"上北郡七戸町","西槻木","","Shichinohe-machi, Kamikita-gun","Nishitsukinoki",""]],
	"0392557":[[2,"上北郡七戸町","西野","","Shichinohe-machi, Kamikita-gun","Seino",""]],
	"0392558":[[2,"上北郡七戸町","高屋敷","","Shichinohe-machi, Kamikita-gun","Takayashiki",""]],
	"0392559":[[2,"上北郡七戸町","山屋","","Shichinohe-machi, Kamikita-gun","Yamaya",""]],
	"0392561":[[2,"上北郡七戸町","銀南木","","Shichinohe-machi, Kamikita-gun","Ichonoki",""]],
	"0392562":[[2,"上北郡七戸町","倉岡","","Shichinohe-machi, Kamikita-gun","Kuraoka",""]],
	"0392563":[[2,"上北郡七戸町","向平","","Shichinohe-machi, Kamikita-gun","Mukaitai",""]],
	"0392564":[[2,"上北郡七戸町","古屋敷","","Shichinohe-machi, Kamikita-gun","Furuyashiki",""]],
	"0392565":[[2,"上北郡七戸町","治部袋","","Shichinohe-machi, Kamikita-gun","Jimba",""]],
	"0392566":[[2,"上北郡七戸町","放森","","Shichinohe-machi, Kamikita-gun","Hanatsumori",""]],
	"0392567":[[2,"上北郡七戸町","鶴児平","","Shichinohe-machi, Kamikita-gun","Tsurunokotai",""]],
	"0392568":[[2,"上北郡七戸町","左組","","Shichinohe-machi, Kamikita-gun","Sagumi",""]],
	"0392569":[[2,"上北郡七戸町","馬門川原","","Shichinohe-machi, Kamikita-gun","Makadogawara",""]],
	"0392571":[[2,"上北郡七戸町","蛇坂","","Shichinohe-machi, Kamikita-gun","Hebisaka",""]],
	"0392572":[[2,"上北郡七戸町","城ノ後","","Shichinohe-machi, Kamikita-gun","Shironoato",""]],
	"0392573":[[2,"上北郡七戸町","野続","","Shichinohe-machi, Kamikita-gun","Notsuzuki",""]],
	"0392574":[[2,"上北郡七戸町","宇道坂","","Shichinohe-machi, Kamikita-gun","Udozaka",""]],
	"0392575":[[2,"上北郡七戸町","作田","","Shichinohe-machi, Kamikita-gun","Sakuta",""]],
	"0392576":[[2,"上北郡七戸町","桜田","","Shichinohe-machi, Kamikita-gun","Sakurada",""]],
	"0392577":[[2,"上北郡七戸町","鍛治林","","Shichinohe-machi, Kamikita-gun","Kajibayashi",""]],
	"0392578":[[2,"上北郡七戸町","貝ノ口","","Shichinohe-machi, Kamikita-gun","Kainokuchi",""]],
	"0392579":[[2,"上北郡七戸町","十役野","","Shichinohe-machi, Kamikita-gun","Toyakuno",""]],
	"0392581":[[2,"上北郡七戸町","東上川原","","Shichinohe-machi, Kamikita-gun","Higashikamikawara",""]],
	"0392582":[[2,"上北郡七戸町","西上川原","","Shichinohe-machi, Kamikita-gun","Nishikamikawara",""]],
	"0392583":[[2,"上北郡七戸町","前川原","","Shichinohe-machi, Kamikita-gun","Maekawara",""]],
	"0392584":[[2,"上北郡七戸町","後川原","","Shichinohe-machi, Kamikita-gun","Ushirokawara",""]],
	"0392585":[[2,"上北郡七戸町","上ノ山","","Shichinohe-machi, Kamikita-gun","Uenoyama",""]],
	"0392586":[[2,"上北郡七戸町","海内","","Shichinohe-machi, Kamikita-gun","Uminai",""]],
	"0392587":[[2,"上北郡七戸町","上屋田","","Shichinohe-machi, Kamikita-gun","Ueyada",""]],
	"0392588":[[2,"上北郡七戸町","和田下","","Shichinohe-machi, Kamikita-gun","Wadashimo",""]],
	"0392589":[[2,"上北郡七戸町","和田","","Shichinohe-machi, Kamikita-gun","Wada",""]],
	"0392600":[[2,"上北郡東北町","","","Tohoku-machi, Kamikita-gun","",""]],
	"0392601":[[2,"上北郡東北町","ガス平","","Tohoku-machi, Kamikita-gun","Gasutai",""]],
	"0392602":[[2,"上北郡東北町","五十嵐","","Tohoku-machi, Kamikita-gun","Igarashi",""],[2,"上北郡東北町","細津橋ノ上","","Tohoku-machi, Kamikita-gun","Hosotsuhashinokami",""]],
	"0392603":[[2,"上北郡東北町","横沢山","","Tohoku-machi, Kamikita-gun","Yokosawayama",""]],
	"0392604":[[2,"上北郡東北町","空久保","","Tohoku-machi, Kamikita-gun","Akikubo",""],[2,"上北郡東北町","饅頭長根","","Tohoku-machi, Kamikita-gun","Manjunagane",""],[2,"上北郡東北町","水流","","Tohoku-machi, Kamikita-gun","Mizunagare",""],[2,"上北郡東北町","横沢","","Tohoku-machi, Kamikita-gun","Yokosawa",""],[2,"上北郡東北町","横沢頭","","Tohoku-machi, Kamikita-gun","Yokosawagashira",""]],
	"0392605":[[2,"上北郡東北町","淋代","","Tohoku-machi, Kamikita-gun","Sabishiro",""],[2,"上北郡東北町","高森","","Tohoku-machi, Kamikita-gun","Takamori",""]],
	"0392606":[[2,"上北郡東北町","数牛","","Tohoku-machi, Kamikita-gun","Kasoshi",""],[2,"上北郡東北町","谷地頭","","Tohoku-machi, Kamikita-gun","Yajigashira",""]],
	"0392607":[[2,"上北郡東北町","姥沢","","Tohoku-machi, Kamikita-gun","Ubasawa",""]],
	"0392611":[[2,"上北郡東北町","中村道ノ上","","Tohoku-machi, Kamikita-gun","Nakamura Michinokami",""],[2,"上北郡東北町","中村道ノ下","","Tohoku-machi, Kamikita-gun","Nakamura Michinoshimo",""]],
	"0392612":[[2,"上北郡東北町","狼ノ沢","","Tohoku-machi, Kamikita-gun","Oinosawa",""],[2,"上北郡東北町","沼添左ノ平","","Tohoku-machi, Kamikita-gun","Numasoesanotaira",""],[2,"上北郡東北町","浜台","","Tohoku-machi, Kamikita-gun","Hamadai",""]],
	"0392613":[[2,"上北郡東北町","子ノ鳥平","","Tohoku-machi, Kamikita-gun","Nenotoritai",""],[2,"上北郡東北町","野田頭","","Tohoku-machi, Kamikita-gun","Nodagashira",""],[2,"上北郡東北町","野田頭山","","Tohoku-machi, Kamikita-gun","Nodagashirayama",""],[2,"上北郡東北町","野田尻","","Tohoku-machi, Kamikita-gun","Nodajiri",""]],
	"0392614":[[2,"上北郡東北町","切左坂道ノ下","","Tohoku-machi, Kamikita-gun","Kirisazakamichinoshimo",""]],
	"0392615":[[2,"上北郡東北町","細津","","Tohoku-machi, Kamikita-gun","Hosotsu",""],[2,"上北郡東北町","萌出道ノ上","","Tohoku-machi, Kamikita-gun","Modashi Michinokami",""],[2,"上北郡東北町","萌出道ノ下","","Tohoku-machi, Kamikita-gun","Modashi Michinoshimo",""]],
	"0392616":[[2,"上北郡東北町","切左坂道ノ上","","Tohoku-machi, Kamikita-gun","Kirisazakamichinokami",""]],
	"0392617":[[2,"上北郡東北町","水喰","","Tohoku-machi, Kamikita-gun","Mizuhami",""],[2,"上北郡東北町","水喰向","","Tohoku-machi, Kamikita-gun","Mizuhamimukai",""]],
	"0392621":[[2,"上北郡東北町","田ノ沢","","Tohoku-machi, Kamikita-gun","Tanosawa",""]],
	"0392622":[[2,"上北郡東北町","浜家苫","","Tohoku-machi, Kamikita-gun","Hamaketoba",""],[2,"上北郡東北町","船ケ沢","","Tohoku-machi, Kamikita-gun","Funegasawa",""]],
	"0392623":[[2,"上北郡東北町","大久保","","Tohoku-machi, Kamikita-gun","Okubo",""],[2,"上北郡東北町","鶴ケ崎","","Tohoku-machi, Kamikita-gun","Tsurugasaki",""],[2,"上北郡東北町","横志多","","Tohoku-machi, Kamikita-gun","Yokoshida",""]],
	"0392624":[[2,"上北郡東北町","蓼内久保","","Tohoku-machi, Kamikita-gun","Tatenaikubo",""],[2,"上北郡東北町","古屋敷","","Tohoku-machi, Kamikita-gun","Furuyashiki",""],[2,"上北郡東北町","道ノ北","","Tohoku-machi, Kamikita-gun","Michinokita",""]],
	"0392625":[[2,"上北郡東北町","長久保","","Tohoku-machi, Kamikita-gun","Nagakubo",""]],
	"0392626":[[2,"上北郡東北町","後久保","","Tohoku-machi, Kamikita-gun","Ushirokubo",""],[2,"上北郡東北町","上久保","","Tohoku-machi, Kamikita-gun","Kamikubo",""],[2,"上北郡東北町","堤尻","","Tohoku-machi, Kamikita-gun","Tsutsumijiri",""]],
	"0392627":[[2,"上北郡東北町","漆玉","","Tohoku-machi, Kamikita-gun","Shittama",""]],
	"0392631":[[2,"上北郡東北町","滝沢平","","Tohoku-machi, Kamikita-gun","Takisawataira",""]],
	"0392632":[[2,"上北郡東北町","日影林ノ上山","","Tohoku-machi, Kamikita-gun","Hikagehayashinokamiyama",""]],
	"0392633":[[2,"上北郡東北町","素柄邸","","Tohoku-machi, Kamikita-gun","Sugarayashiki",""],[2,"上北郡東北町","和山平","","Tohoku-machi, Kamikita-gun","Wayamataira",""]],
	"0392634":[[2,"上北郡東北町","往来ノ下","","Tohoku-machi, Kamikita-gun","Orainoshimo",""]],
	"0392635":[[2,"上北郡東北町","乙越","","Tohoku-machi, Kamikita-gun","Otsukoshi",""],[2,"上北郡東北町","舘","","Tohoku-machi, Kamikita-gun","Date",""],[2,"上北郡東北町","鳥口平","","Tohoku-machi, Kamikita-gun","Toriguchitai",""]],
	"0392636":[[2,"上北郡東北町","往来ノ上","","Tohoku-machi, Kamikita-gun","Orainokami",""]],
	"0392641":[[2,"上北郡東北町","枋木","","Tohoku-machi, Kamikita-gun","Kobonoki",""]],
	"0392642":[[2,"上北郡東北町","寒水","","Tohoku-machi, Kamikita-gun","Hiyamizu",""],[2,"上北郡東北町","寒水下","","Tohoku-machi, Kamikita-gun","Hiyamizushimo",""],[2,"上北郡東北町","寒水山","","Tohoku-machi, Kamikita-gun","Hiyamizuyama",""]],
	"0392643":[[2,"上北郡東北町","乙部道ノ上","","Tohoku-machi, Kamikita-gun","Otobe Michinokami",""],[2,"上北郡東北町","乙部道ノ下","","Tohoku-machi, Kamikita-gun","Otobe Michinoshimo",""]],
	"0392644":[[2,"上北郡東北町","保戸沢家ノ上","","Tohoku-machi, Kamikita-gun","Hodosawa Ienokami",""],[2,"上北郡東北町","保戸沢家ノ前","","Tohoku-machi, Kamikita-gun","Hodosawa Ienomae",""],[2,"上北郡東北町","保戸沢家ノ後","","Tohoku-machi, Kamikita-gun","Hodosawa Ienoshiro",""]],
	"0392645":[[2,"上北郡東北町","外蛯沢前平","","Tohoku-machi, Kamikita-gun","Sotoebisawa Maetai",""]],
	"0392646":[[2,"上北郡東北町","外蛯沢西平","","Tohoku-machi, Kamikita-gun","Sotoebisawa Nishitai",""]],
	"0392647":[[2,"上北郡東北町","外蛯沢後久保","","Tohoku-machi, Kamikita-gun","Sotoebisawa Ushirokubo",""]],
	"0392648":[[2,"上北郡東北町","外蛯沢北久保","","Tohoku-machi, Kamikita-gun","Sotoebisawa Kitakubo",""]],
	"0392651":[[2,"上北郡東北町","大沢","","Tohoku-machi, Kamikita-gun","Osawa",""]],
	"0392652":[[2,"上北郡東北町","ほとけ沢","","Tohoku-machi, Kamikita-gun","Hotokesawa",""]],
	"0392653":[[2,"上北郡東北町","下山","","Tohoku-machi, Kamikita-gun","Shimoyama",""]],
	"0392654":[[2,"上北郡東北町","塔ノ沢山","","Tohoku-machi, Kamikita-gun","Tonosawayama",""]],
	"0392655":[[2,"上北郡東北町","内蛯沢道ノ上","","Tohoku-machi, Kamikita-gun","Uchiebisawa Michinokami",""]],
	"0392656":[[2,"上北郡東北町","内蛯沢向","","Tohoku-machi, Kamikita-gun","Uchiebisawa Mukai",""]],
	"0392657":[[2,"上北郡東北町","赤川道","","Tohoku-machi, Kamikita-gun","Akagawamichi",""]],
	"0392661":[[2,"上北郡東北町","上笹橋","","Tohoku-machi, Kamikita-gun","Kamisasabashi",""]],
	"0392662":[[2,"上北郡東北町","下笹橋","","Tohoku-machi, Kamikita-gun","Shimosasabashi",""]],
	"0392663":[[2,"上北郡東北町","舘花","","Tohoku-machi, Kamikita-gun","Datehana",""]],
	"0392664":[[2,"上北郡東北町","乙供","","Tohoku-machi, Kamikita-gun","Ottomo",""]],
	"0392665":[[2,"上北郡東北町","柳沢","","Tohoku-machi, Kamikita-gun","Yanagizawa",""]],
	"0392666":[[2,"上北郡東北町","乙供山","","Tohoku-machi, Kamikita-gun","Ottomoyama",""]],
	"0392667":[[2,"上北郡東北町","膳前","","Tohoku-machi, Kamikita-gun","Zemmae",""]],
	"0392668":[[2,"上北郡東北町","北膳前","","Tohoku-machi, Kamikita-gun","Kitazemmae",""],[2,"上北郡東北町","篠内平","","Tohoku-machi, Kamikita-gun","Shinonaitai",""]],
	"0392671":[[2,"上北郡東北町","小沢","","Tohoku-machi, Kamikita-gun","Ozawa",""]],
	"0392672":[[2,"上北郡東北町","栗山添","","Tohoku-machi, Kamikita-gun","Kuriyamazoi",""],[2,"上北郡東北町","向籏屋","","Tohoku-machi, Kamikita-gun","Mukaihataya",""]],
	"0392673":[[2,"上北郡東北町","馬尻","","Tohoku-machi, Kamikita-gun","Umajiri",""],[2,"上北郡東北町","大籏屋","","Tohoku-machi, Kamikita-gun","Ohataya",""],[2,"上北郡東北町","向屋敷","","Tohoku-machi, Kamikita-gun","Mukaiyashiki",""],[2,"上北郡東北町","山ノ下","","Tohoku-machi, Kamikita-gun","Yamanoshita",""]],
	"0392674":[[2,"上北郡東北町","千曳下山","","Tohoku-machi, Kamikita-gun","Chibiki Shimoyama",""],[2,"上北郡東北町","夫雑原","","Tohoku-machi, Kamikita-gun","Buzohara",""]],
	"0392675":[[2,"上北郡東北町","千曳","","Tohoku-machi, Kamikita-gun","Chibiki",""]],
	"0392676":[[2,"上北郡東北町","下板橋","","Tohoku-machi, Kamikita-gun","Shimoitabashi",""]],
	"0392677":[[2,"上北郡東北町","夫雑原下山","","Tohoku-machi, Kamikita-gun","Buzoharashimoyama",""]],
	"0392678":[[2,"上北郡東北町","狐沢山","","Tohoku-machi, Kamikita-gun","Kitsunesawayama",""],[2,"上北郡東北町","坂ノ下","","Tohoku-machi, Kamikita-gun","Sakanoshita",""],[2,"上北郡東北町","田面木","","Tohoku-machi, Kamikita-gun","Tamogi",""],[2,"上北郡東北町","長者久保","","Tohoku-machi, Kamikita-gun","Chojakubo",""]],
	"0392681":[[2,"上北郡東北町","家ノ前","","Tohoku-machi, Kamikita-gun","Ienomae",""],[2,"上北郡東北町","山添","","Tohoku-machi, Kamikita-gun","Yamazoi",""]],
	"0392682":[[2,"上北郡東北町","石坂","","Tohoku-machi, Kamikita-gun","Ishizaka",""],[2,"上北郡東北町","湯沢","","Tohoku-machi, Kamikita-gun","Yuzawa",""]],
	"0392683":[[2,"上北郡東北町","板橋山","","Tohoku-machi, Kamikita-gun","Itabashiyama",""],[2,"上北郡東北町","大平","","Tohoku-machi, Kamikita-gun","Odaira",""]],
	"0392684":[[2,"上北郡東北町","向平","","Tohoku-machi, Kamikita-gun","Mukaitai",""]],
	"0392685":[[2,"上北郡東北町","家ノ下タ","","Tohoku-machi, Kamikita-gun","Ienoshita",""],[2,"上北郡東北町","上板橋家ノ後","","Tohoku-machi, Kamikita-gun","Kamiitabashi Ienoshiro",""]],
	"0392686":[[2,"上北郡東北町","宇道坂","","Tohoku-machi, Kamikita-gun","Udosaka",""],[2,"上北郡東北町","塞ノ神","","Tohoku-machi, Kamikita-gun","Sainokami",""],[2,"上北郡東北町","添ノ沢","","Tohoku-machi, Kamikita-gun","Soenosawa",""]],
	"0392687":[[2,"上北郡東北町","上清水目","","Tohoku-machi, Kamikita-gun","Kamishimizume",""],[2,"上北郡東北町","林ノ下","","Tohoku-machi, Kamikita-gun","Hayashinoshita",""]],
	"0392688":[[2,"上北郡東北町","大撫沢","","Tohoku-machi, Kamikita-gun","Onadesawa",""]],
	"0392711":[[2,"上北郡七戸町","中天間舘","","Shichinohe-machi, Kamikita-gun","Nakatemmadate",""]],
	"0392712":[[2,"上北郡七戸町","北天間舘","","Shichinohe-machi, Kamikita-gun","Kitatemmadate",""]],
	"0392713":[[2,"上北郡七戸町","東天間舘","","Shichinohe-machi, Kamikita-gun","Higashitemmadate",""]],
	"0392714":[[2,"上北郡七戸町","上志多","","Shichinohe-machi, Kamikita-gun","Kamishida",""]],
	"0392715":[[2,"上北郡七戸町","尾山頭","","Shichinohe-machi, Kamikita-gun","Oyamagashira",""]],
	"0392716":[[2,"上北郡七戸町","菩提木","","Shichinohe-machi, Kamikita-gun","Bodaigi",""]],
	"0392717":[[2,"上北郡七戸町","柳平","","Shichinohe-machi, Kamikita-gun","Yanagitaira",""]],
	"0392721":[[2,"上北郡七戸町","志茂川原","","Shichinohe-machi, Kamikita-gun","Shimokawara",""]],
	"0392722":[[2,"上北郡七戸町","向川原","","Shichinohe-machi, Kamikita-gun","Mukaikawara",""]],
	"0392723":[[2,"上北郡七戸町","下志多","","Shichinohe-machi, Kamikita-gun","Shimoshita",""]],
	"0392724":[[2,"上北郡七戸町","上平","","Shichinohe-machi, Kamikita-gun","Kamitaira",""]],
	"0392725":[[2,"上北郡七戸町","上川原","","Shichinohe-machi, Kamikita-gun","Kamikawara",""]],
	"0392726":[[2,"上北郡七戸町","李川原","","Shichinohe-machi, Kamikita-gun","Sumomokawara",""]],
	"0392731":[[2,"上北郡七戸町","後平","","Shichinohe-machi, Kamikita-gun","Ushirotaira",""]],
	"0392732":[[2,"上北郡七戸町","卒古沢","","Shichinohe-machi, Kamikita-gun","Sotsukozawa",""]],
	"0392733":[[2,"上北郡七戸町","天間舘前川原","","Shichinohe-machi, Kamikita-gun","Temmadatemaekawara",""]],
	"0392741":[[2,"上北郡七戸町","猪ノ鼻","","Shichinohe-machi, Kamikita-gun","Inohana",""]],
	"0392742":[[2,"上北郡七戸町","舟場向川久保","","Shichinohe-machi, Kamikita-gun","Funabamukaigawakubo",""]],
	"0392743":[[2,"上北郡七戸町","寺沢前","","Shichinohe-machi, Kamikita-gun","Terasawamae",""]],
	"0392744":[[2,"上北郡七戸町","塚長根","","Shichinohe-machi, Kamikita-gun","Tsukanagane",""]],
	"0392745":[[2,"上北郡七戸町","夷堂","","Shichinohe-machi, Kamikita-gun","Ebisudo",""]],
	"0392746":[[2,"上北郡七戸町","附田川目","","Shichinohe-machi, Kamikita-gun","Tsukutakawame",""]],
	"0392747":[[2,"上北郡七戸町","附田家ノ前","","Shichinohe-machi, Kamikita-gun","Tsukutaienomae",""]],
	"0392748":[[2,"上北郡七戸町","南舘向","","Shichinohe-machi, Kamikita-gun","Minamidatemukai",""]],
	"0392751":[[2,"上北郡七戸町","貝塚家ノ前","","Shichinohe-machi, Kamikita-gun","Kaizukaienomae",""]],
	"0392752":[[2,"上北郡七戸町","鉢森平","","Shichinohe-machi, Kamikita-gun","Hachimoritai",""]],
	"0392753":[[2,"上北郡七戸町","竿打川原","","Shichinohe-machi, Kamikita-gun","Saochikawara",""]],
	"0392754":[[2,"上北郡七戸町","地蔵堂","","Shichinohe-machi, Kamikita-gun","Jizodo",""]],
	"0392755":[[2,"上北郡七戸町","榎林家ノ前","","Shichinohe-machi, Kamikita-gun","Enokibayashiienomae",""]],
	"0392756":[[2,"上北郡七戸町","榎林家ノ後","","Shichinohe-machi, Kamikita-gun","Enokibayashiienoshiro",""]],
	"0392757":[[2,"上北郡七戸町","卒古沢南平","","Shichinohe-machi, Kamikita-gun","Sotsukozawaminamitai",""]],
	"0392761":[[2,"上北郡七戸町","二ツ森家ノ後","","Shichinohe-machi, Kamikita-gun","Futatsumoriienoshiro",""]],
	"0392762":[[2,"上北郡七戸町","二ツ森家ノ下","","Shichinohe-machi, Kamikita-gun","Futatsumoriienoshita",""]],
	"0392763":[[2,"上北郡七戸町","二ツ森家ノ表","","Shichinohe-machi, Kamikita-gun","Futatsumoriienomote",""]],
	"0392771":[[2,"上北郡七戸町","姥沢","","Shichinohe-machi, Kamikita-gun","Ubasawa",""]],
	"0392772":[[2,"上北郡七戸町","下田坪","","Shichinohe-machi, Kamikita-gun","Shimotatsubo",""]],
	"0392773":[[2,"上北郡七戸町","前左野","","Shichinohe-machi, Kamikita-gun","Maesano",""]],
	"0392774":[[2,"上北郡七戸町","柴舘道ノ下","","Shichinohe-machi, Kamikita-gun","Shibadatemichinoshimo",""]],
	"0392775":[[2,"上北郡七戸町","李沢道ノ下","","Shichinohe-machi, Kamikita-gun","Sumomozawamichinoshimo",""]],
	"0392776":[[2,"上北郡七戸町","李沢家ノ前","","Shichinohe-machi, Kamikita-gun","Sumomozawaienomae",""]],
	"0392777":[[2,"上北郡七戸町","李沢家ノ後","","Shichinohe-machi, Kamikita-gun","Sumomozawaienoshiro",""]],
	"0392778":[[2,"上北郡七戸町","坂ノ外","","Shichinohe-machi, Kamikita-gun","Sakanosoto",""]],
	"0392779":[[2,"上北郡七戸町","榎林古屋敷","","Shichinohe-machi, Kamikita-gun","Enokibayashifuruyashiki",""]],
	"0392781":[[2,"上北郡七戸町","花松林ノ根","","Shichinohe-machi, Kamikita-gun","Hanamatsuhayashinone",""]],
	"0392782":[[2,"上北郡七戸町","中岫太田嶋","","Shichinohe-machi, Kamikita-gun","Nakagukiotashima",""]],
	"0392783":[[2,"上北郡七戸町","中岫番屋","","Shichinohe-machi, Kamikita-gun","Nakagukibanya",""]],
	"0392784":[[2,"上北郡七戸町","中岫長沢下","","Shichinohe-machi, Kamikita-gun","Nakagukinagasawashimo",""]],
	"0392785":[[2,"上北郡七戸町","中岫村ノ上","","Shichinohe-machi, Kamikita-gun","Nakagukimuranokami",""]],
	"0392786":[[2,"上北郡七戸町","中岫東道添","","Shichinohe-machi, Kamikita-gun","Nakagukihigashimichizoe",""]],
	"0392801":[[2,"上北郡七戸町","野崎","","Shichinohe-machi, Kamikita-gun","Nozaki",""]],
	"0392802":[[2,"上北郡七戸町","野崎前平","","Shichinohe-machi, Kamikita-gun","Nozakimaehira",""]],
	"0392803":[[2,"上北郡七戸町","野崎森ノ下","","Shichinohe-machi, Kamikita-gun","Nozakimorinoshimo",""]],
	"0392804":[[2,"上北郡七戸町","野崎狐久保","","Shichinohe-machi, Kamikita-gun","Nozakikitsunekubo",""]],
	"0392805":[[2,"上北郡七戸町","原久保","","Shichinohe-machi, Kamikita-gun","Harakubo",""]],
	"0392811":[[2,"上北郡七戸町","天間舘荒谷","","Shichinohe-machi, Kamikita-gun","Temmadatearaya",""]],
	"0392812":[[2,"上北郡七戸町","小田下","","Shichinohe-machi, Kamikita-gun","Kodashita",""]],
	"0392813":[[2,"上北郡七戸町","小田平","","Shichinohe-machi, Kamikita-gun","Kodatai",""]],
	"0392814":[[2,"上北郡七戸町","道ノ下","","Shichinohe-machi, Kamikita-gun","Michinoshimo",""]],
	"0392815":[[2,"上北郡七戸町","森ノ下","","Shichinohe-machi, Kamikita-gun","Morinoshimo",""]],
	"0392816":[[2,"上北郡七戸町","家ノ裏","","Shichinohe-machi, Kamikita-gun","Ienora",""]],
	"0392821":[[2,"上北郡七戸町","大平","","Shichinohe-machi, Kamikita-gun","Odaira",""]],
	"0392822":[[2,"上北郡七戸町","小又","","Shichinohe-machi, Kamikita-gun","Komata",""]],
	"0392823":[[2,"上北郡七戸町","館ノ下","","Shichinohe-machi, Kamikita-gun","Datenoshita",""]],
	"0392824":[[2,"上北郡七戸町","家ノ下","","Shichinohe-machi, Kamikita-gun","Ienoshita",""]],
	"0392825":[[2,"上北郡七戸町","家ノ上","","Shichinohe-machi, Kamikita-gun","Ienokami",""]],
	"0392826":[[2,"上北郡七戸町","中野","","Shichinohe-machi, Kamikita-gun","Nakano",""]],
	"0392827":[[2,"上北郡七戸町","森ノ上","","Shichinohe-machi, Kamikita-gun","Morinokami",""]],
	"0392828":[[2,"上北郡七戸町","森ケ沢","","Shichinohe-machi, Kamikita-gun","Morigasawa",""]],
	"0392831":[[2,"上北郡七戸町","金沢平","","Shichinohe-machi, Kamikita-gun","Kanazawataira",""]],
	"0392832":[[2,"上北郡七戸町","道ノ上","","Shichinohe-machi, Kamikita-gun","Michinokami",""]],
	"0392833":[[2,"上北郡七戸町","家ノ前","","Shichinohe-machi, Kamikita-gun","Ienomae",""]],
	"0392834":[[2,"上北郡七戸町","向中野川向","","Shichinohe-machi, Kamikita-gun","Mukainakanokawamukai",""]],
	"0392835":[[2,"上北郡七戸町","松ケ沢","","Shichinohe-machi, Kamikita-gun","Matsugasawa",""]],
	"0392841":[[2,"上北郡七戸町","下鳥谷部","","Shichinohe-machi, Kamikita-gun","Shimotoriyabe",""]],
	"0392842":[[2,"上北郡七戸町","中鳥谷","","Shichinohe-machi, Kamikita-gun","Nakatoriya",""]],
	"0392843":[[2,"上北郡七戸町","橋ノ上","","Shichinohe-machi, Kamikita-gun","Hashinokami",""]],
	"0392844":[[2,"上北郡七戸町","手代森","","Shichinohe-machi, Kamikita-gun","Teshiromori",""]],
	"0392845":[[2,"上北郡七戸町","作田道","","Shichinohe-machi, Kamikita-gun","Sakutamichi",""]],
	"0392846":[[2,"上北郡七戸町","鳥谷部","","Shichinohe-machi, Kamikita-gun","Toriyabe",""]],
	"0392851":[[2,"上北郡七戸町","堰根","","Shichinohe-machi, Kamikita-gun","Sekine",""]],
	"0392852":[[2,"上北郡七戸町","さそう","","Shichinohe-machi, Kamikita-gun","Saso",""]],
	"0392853":[[2,"上北郡七戸町","さそう平","","Shichinohe-machi, Kamikita-gun","Sasotai",""]],
	"0392854":[[2,"上北郡七戸町","高井名","","Shichinohe-machi, Kamikita-gun","Takaina",""]],
	"0392855":[[2,"上北郡七戸町","底田","","Shichinohe-machi, Kamikita-gun","Sokota",""]],
	"0392856":[[2,"上北郡七戸町","古和備","","Shichinohe-machi, Kamikita-gun","Kowasonae",""]],
	"0392857":[[2,"上北郡七戸町","天間舘倉越","","Shichinohe-machi, Kamikita-gun","Temmadatekurakoshi",""]],
	"0392861":[[2,"上北郡七戸町","天間舘大沢","","Shichinohe-machi, Kamikita-gun","Temmadateosawa",""]],
	"0392862":[[2,"上北郡七戸町","夏間木","","Shichinohe-machi, Kamikita-gun","Natsumagi",""]],
	"0392863":[[2,"上北郡七戸町","十枝内","","Shichinohe-machi, Kamikita-gun","Toshinai",""]],
	"0392864":[[2,"上北郡七戸町","下モ川原","","Shichinohe-machi, Kamikita-gun","Shimokawara",""]],
	"0392865":[[2,"上北郡七戸町","市ノ渡","","Shichinohe-machi, Kamikita-gun","Ichinowatari",""]],
	"0392866":[[2,"上北郡七戸町","栗ノ木沢","","Shichinohe-machi, Kamikita-gun","Kurinokisawa",""]],
	"0392871":[[2,"上北郡七戸町","白石","","Shichinohe-machi, Kamikita-gun","Shiroishi",""]],
	"0392872":[[2,"上北郡七戸町","下タ川原","","Shichinohe-machi, Kamikita-gun","Shitakawara",""]],
	"0392873":[[2,"上北郡七戸町","天間舘寒水","","Shichinohe-machi, Kamikita-gun","Temmadatekansui",""]],
	"0392874":[[2,"上北郡七戸町","坪川原","","Shichinohe-machi, Kamikita-gun","Tsubokawara",""]],
	"0392875":[[2,"上北郡七戸町","淋代","","Shichinohe-machi, Kamikita-gun","Sabishiro",""]],
	"0392876":[[2,"上北郡七戸町","堰代","","Shichinohe-machi, Kamikita-gun","Sekishiro",""]],
	"0392877":[[2,"上北郡七戸町","五庵ノ下","","Shichinohe-machi, Kamikita-gun","Goannoshita",""]],
	"0393100":[[2,"上北郡野辺地町","","","Noheji-machi, Kamikita-gun","",""]],
	"0393101":[[2,"上北郡野辺地町","浜掛","","Noheji-machi, Kamikita-gun","Hamakake",""]],
	"0393102":[[2,"上北郡野辺地町","米内沢","","Noheji-machi, Kamikita-gun","Yonaisawa",""]],
	"0393103":[[2,"上北郡野辺地町","田名部道","","Noheji-machi, Kamikita-gun","Tanabumichi",""]],
	"0393104":[[2,"上北郡野辺地町","大月平","","Noheji-machi, Kamikita-gun","Otsukitai",""]],
	"0393105":[[2,"上北郡野辺地町","有戸鳥井平","","Noheji-machi, Kamikita-gun","Aritotoriitai",""],[2,"上北郡野辺地町","木明","","Noheji-machi, Kamikita-gun","Kimyo",""],[2,"上北郡野辺地町","東太田沢","","Noheji-machi, Kamikita-gun","Higashiotasawa",""],[2,"上北郡野辺地町","干草橋","","Noheji-machi, Kamikita-gun","Hikusabashi",""]],
	"0393106":[[2,"上北郡野辺地町","蟹田","","Noheji-machi, Kamikita-gun","Kanita",""],[2,"上北郡野辺地町","古明前","","Noheji-machi, Kamikita-gun","Furumyomae",""],[2,"上北郡野辺地町","明前","","Noheji-machi, Kamikita-gun","Myomae",""]],
	"0393107":[[2,"上北郡野辺地町","小沢平","","Noheji-machi, Kamikita-gun","Ozawadai",""]],
	"0393108":[[2,"上北郡野辺地町","有戸","","Noheji-machi, Kamikita-gun","Arito",""],[2,"上北郡野辺地町","下道","","Noheji-machi, Kamikita-gun","Shitamichi",""],[2,"上北郡野辺地町","中田","","Noheji-machi, Kamikita-gun","Nakata",""]],
	"0393109":[[2,"上北郡野辺地町","向田","","Noheji-machi, Kamikita-gun","Mukaida",""]],
	"0393111":[[2,"上北郡野辺地町","石神裏","","Noheji-machi, Kamikita-gun","Ishigamiura",""]],
	"0393112":[[2,"上北郡野辺地町","中道","","Noheji-machi, Kamikita-gun","Nakamichi",""]],
	"0393113":[[2,"上北郡野辺地町","田狭沢","","Noheji-machi, Kamikita-gun","Tabasamizawa",""]],
	"0393114":[[2,"上北郡野辺地町","助佐小路","","Noheji-machi, Kamikita-gun","Sukesakoji",""]],
	"0393115":[[2,"上北郡野辺地町","タラノ木","","Noheji-machi, Kamikita-gun","Taranoki",""]],
	"0393116":[[2,"上北郡野辺地町","赤坂","","Noheji-machi, Kamikita-gun","Akasaka",""]],
	"0393117":[[2,"上北郡野辺地町","下坂","","Noheji-machi, Kamikita-gun","Shimosaka",""]],
	"0393118":[[2,"上北郡野辺地町","寺ノ沢","","Noheji-machi, Kamikita-gun","Teranosawa",""]],
	"0393121":[[2,"上北郡野辺地町","船橋","","Noheji-machi, Kamikita-gun","Funabashi",""]],
	"0393122":[[2,"上北郡野辺地町","雑吉沢","","Noheji-machi, Kamikita-gun","Zoyoshizawa",""]],
	"0393123":[[2,"上北郡野辺地町","種川","","Noheji-machi, Kamikita-gun","Tanekawa",""]],
	"0393124":[[2,"上北郡野辺地町","白岩","","Noheji-machi, Kamikita-gun","Shiraiwa",""]],
	"0393125":[[2,"上北郡野辺地町","坊ノ塚","","Noheji-machi, Kamikita-gun","Bonotsuka",""]],
	"0393126":[[2,"上北郡野辺地町","下前田","","Noheji-machi, Kamikita-gun","Shimomaeda",""]],
	"0393127":[[2,"上北郡野辺地町","上川原","","Noheji-machi, Kamikita-gun","Kamikawara",""]],
	"0393128":[[2,"上北郡野辺地町","上前田","","Noheji-machi, Kamikita-gun","Kamimaeda",""],[2,"上北郡野辺地町","昼場","","Noheji-machi, Kamikita-gun","Hiruba",""]],
	"0393129":[[2,"上北郡野辺地町","新田","","Noheji-machi, Kamikita-gun","Shinden",""],[2,"上北郡野辺地町","戸田ノ沢","","Noheji-machi, Kamikita-gun","Todanosawa",""],[2,"上北郡野辺地町","餅粟川原","","Noheji-machi, Kamikita-gun","Mochiawakawara",""]],
	"0393131":[[2,"上北郡野辺地町","野辺地","","Noheji-machi, Kamikita-gun","Noheji",""]],
	"0393141":[[2,"上北郡野辺地町","鳴沢","","Noheji-machi, Kamikita-gun","Narusawa",""]],
	"0393142":[[2,"上北郡野辺地町","久田","","Noheji-machi, Kamikita-gun","Kunden",""]],
	"0393143":[[2,"上北郡野辺地町","川目","","Noheji-machi, Kamikita-gun","Kawame",""],[2,"上北郡野辺地町","中屋敷","","Noheji-machi, Kamikita-gun","Nakayashiki",""]],
	"0393144":[[2,"上北郡野辺地町","一ノ渡","","Noheji-machi, Kamikita-gun","Ichinowatari",""]],
	"0393145":[[2,"上北郡野辺地町","松ノ木平","","Noheji-machi, Kamikita-gun","Matsunokitai",""]],
	"0393146":[[2,"上北郡野辺地町","下松ノ木平","","Noheji-machi, Kamikita-gun","Shimomatsunokitai",""]],
	"0393147":[[2,"上北郡野辺地町","下与田川","","Noheji-machi, Kamikita-gun","Shimoyotagawa",""]],
	"0393148":[[2,"上北郡野辺地町","与田川尻","","Noheji-machi, Kamikita-gun","Yotagawajiri",""]],
	"0393151":[[2,"上北郡野辺地町","白岩向","","Noheji-machi, Kamikita-gun","Shiraiwa Mukai",""]],
	"0393152":[[2,"上北郡野辺地町","下小中野","","Noheji-machi, Kamikita-gun","Shimokonakano",""]],
	"0393153":[[2,"上北郡野辺地町","中小中野","","Noheji-machi, Kamikita-gun","Nakakonakano",""]],
	"0393154":[[2,"上北郡野辺地町","上小中野","","Noheji-machi, Kamikita-gun","Kamikonakano",""]],
	"0393155":[[2,"上北郡野辺地町","切明","","Noheji-machi, Kamikita-gun","Kiriake",""]],
	"0393156":[[2,"上北郡野辺地町","枇杷野","","Noheji-machi, Kamikita-gun","Biwano",""]],
	"0393157":[[2,"上北郡野辺地町","獅子沢","","Noheji-machi, Kamikita-gun","Shishizawa",""],[2,"上北郡野辺地町","松ノ木","","Noheji-machi, Kamikita-gun","Matsunoki",""]],
	"0393158":[[2,"上北郡野辺地町","観音林後","","Noheji-machi, Kamikita-gun","Kannombayashiushiro",""]],
	"0393159":[[2,"上北郡野辺地町","観音林脇","","Noheji-machi, Kamikita-gun","Kannombayashiwaki",""]],
	"0393161":[[2,"上北郡野辺地町","馬門道","","Noheji-machi, Kamikita-gun","Makadomichi",""]],
	"0393162":[[2,"上北郡野辺地町","笹館","","Noheji-machi, Kamikita-gun","Sasadate",""]],
	"0393163":[[2,"上北郡野辺地町","新町裏","","Noheji-machi, Kamikita-gun","Shimmachiura",""]],
	"0393164":[[2,"上北郡野辺地町","前田","","Noheji-machi, Kamikita-gun","Maeda",""]],
	"0393165":[[2,"上北郡野辺地町","観音林前田","","Noheji-machi, Kamikita-gun","Kannombayashimaeda",""]],
	"0393166":[[2,"上北郡野辺地町","二本木向前田","","Noheji-machi, Kamikita-gun","Nihonkimukaimaeda",""]],
	"0393167":[[2,"上北郡野辺地町","二本木向","","Noheji-machi, Kamikita-gun","Nihonkimukai",""]],
	"0393168":[[2,"上北郡野辺地町","前平","","Noheji-machi, Kamikita-gun","Maehira",""]],
	"0393171":[[2,"上北郡野辺地町","上御手洗瀬","","Noheji-machi, Kamikita-gun","Kamimitarase",""],[2,"上北郡野辺地町","下御手洗瀬","","Noheji-machi, Kamikita-gun","Shimomitarase",""],[2,"上北郡野辺地町","滝田","","Noheji-machi, Kamikita-gun","Takita",""],[2,"上北郡野辺地町","槻ノ木","","Noheji-machi, Kamikita-gun","Tsukinoki",""],[2,"上北郡野辺地町","二本木","","Noheji-machi, Kamikita-gun","Nihonki",""],[2,"上北郡野辺地町","二十平","","Noheji-machi, Kamikita-gun","Hatachitai",""],[2,"上北郡野辺地町","御手洗瀬","","Noheji-machi, Kamikita-gun","Mitarase",""]],
	"0393172":[[2,"上北郡野辺地町","鳥井平","","Noheji-machi, Kamikita-gun","Toriitai",""]],
	"0393173":[[2,"上北郡野辺地町","陣場川原","","Noheji-machi, Kamikita-gun","Jimbagawara",""]],
	"0393174":[[2,"上北郡野辺地町","大平下","","Noheji-machi, Kamikita-gun","Odaishita",""],[2,"上北郡野辺地町","上河渡頭","","Noheji-machi, Kamikita-gun","Kamikadogashira",""],[2,"上北郡野辺地町","下河渡頭","","Noheji-machi, Kamikita-gun","Shimokadogashira",""],[2,"上北郡野辺地町","田端","","Noheji-machi, Kamikita-gun","Tabata",""]],
	"0393175":[[2,"上北郡野辺地町","地続山","","Noheji-machi, Kamikita-gun","Jitsuzukiyama",""],[2,"上北郡野辺地町","湯沢","","Noheji-machi, Kamikita-gun","Yuzawa",""],[2,"上北郡野辺地町","湯沢尻","","Noheji-machi, Kamikita-gun","Yuzawajiri",""]],
	"0393176":[[2,"上北郡野辺地町","中渡","","Noheji-machi, Kamikita-gun","Nakawatari",""]],
	"0393177":[[2,"上北郡野辺地町","柴崎","","Noheji-machi, Kamikita-gun","Shibasaki",""],[2,"上北郡野辺地町","八ノ木谷地","","Noheji-machi, Kamikita-gun","Hanokiyachi",""]],
	"0393178":[[2,"上北郡野辺地町","家ノ上","","Noheji-machi, Kamikita-gun","Ienoe",""]],
	"0393179":[[2,"上北郡野辺地町","馬門","","Noheji-machi, Kamikita-gun","Makado",""]],
	"0393200":[[2,"上北郡六ヶ所村","","","Rokkasho-mura, Kamikita-gun","",""]],
	"0393211":[[2,"上北郡六ヶ所村","出戸","","Rokkasho-mura, Kamikita-gun","Deto",""]],
	"0393212":[[2,"上北郡六ヶ所村","尾駮","","Rokkasho-mura, Kamikita-gun","Obuchi",""]],
	"0393213":[[2,"上北郡六ヶ所村","鷹架","","Rokkasho-mura, Kamikita-gun","Takahoko",""]],
	"0393214":[[2,"上北郡六ヶ所村","平沼","","Rokkasho-mura, Kamikita-gun","Hiranuma",""]],
	"0393215":[[2,"上北郡六ヶ所村","倉内","","Rokkasho-mura, Kamikita-gun","Kurauchi",""]],
	"0393300":[[2,"東津軽郡平内町","","","Hiranai-machi, Higashitsugaru-gun","",""]],
	"0393301":[[2,"東津軽郡平内町","東田沢","","Hiranai-machi, Higashitsugaru-gun","Higashitazawa",""]],
	"0393302":[[2,"東津軽郡平内町","白砂","","Hiranai-machi, Higashitsugaru-gun","Shirasu",""]],
	"0393303":[[2,"東津軽郡平内町","東滝","","Hiranai-machi, Higashitsugaru-gun","Higashitaki",""]],
	"0393311":[[2,"東津軽郡平内町","福館","","Hiranai-machi, Higashitsugaru-gun","Fukudate",""]],
	"0393312":[[2,"東津軽郡平内町","浅所","","Hiranai-machi, Higashitsugaru-gun","Asadokoro",""]],
	"0393313":[[2,"東津軽郡平内町","沼館","","Hiranai-machi, Higashitsugaru-gun","Numadate",""]],
	"0393314":[[2,"東津軽郡平内町","盛田","","Hiranai-machi, Higashitsugaru-gun","Morita",""]],
	"0393315":[[2,"東津軽郡平内町","福島","","Hiranai-machi, Higashitsugaru-gun","Fukushima",""]],
	"0393321":[[2,"東津軽郡平内町","小湊","","Hiranai-machi, Higashitsugaru-gun","Kominato",""]],
	"0393331":[[2,"東津軽郡平内町","浜子","","Hiranai-machi, Higashitsugaru-gun","Hamago",""]],
	"0393332":[[2,"東津軽郡平内町","清水川","","Hiranai-machi, Higashitsugaru-gun","Shimizugawa",""]],
	"0393333":[[2,"東津軽郡平内町","松野木","","Hiranai-machi, Higashitsugaru-gun","Matsunoki",""]],
	"0393341":[[2,"東津軽郡平内町","薬師野","","Hiranai-machi, Higashitsugaru-gun","Yakushino",""]],
	"0393342":[[2,"東津軽郡平内町","口広","","Hiranai-machi, Higashitsugaru-gun","Kuchihiro",""]],
	"0393343":[[2,"東津軽郡平内町","狩場沢","","Hiranai-machi, Higashitsugaru-gun","Karibasawa",""]],
	"0393351":[[2,"東津軽郡平内町","外童子","","Hiranai-machi, Higashitsugaru-gun","Sotodoji",""]],
	"0393352":[[2,"東津軽郡平内町","内童子","","Hiranai-machi, Higashitsugaru-gun","Uchidoji",""]],
	"0393353":[[2,"東津軽郡平内町","田茂木","","Hiranai-machi, Higashitsugaru-gun","Tamogi",""]],
	"0393361":[[2,"東津軽郡平内町","藤沢","","Hiranai-machi, Higashitsugaru-gun","Fujisawa",""]],
	"0393362":[[2,"東津軽郡平内町","増田","","Hiranai-machi, Higashitsugaru-gun","Masuta",""]],
	"0393363":[[2,"東津軽郡平内町","山口","","Hiranai-machi, Higashitsugaru-gun","Yamaguchi",""]],
	"0393364":[[2,"東津軽郡平内町","小豆沢","","Hiranai-machi, Higashitsugaru-gun","Azukisawa",""]],
	"0393371":[[2,"東津軽郡平内町","中野","","Hiranai-machi, Higashitsugaru-gun","Nakano",""]],
	"0393372":[[2,"東津軽郡平内町","土屋","","Hiranai-machi, Higashitsugaru-gun","Tsuchiya",""]],
	"0393373":[[2,"東津軽郡平内町","浪打","","Hiranai-machi, Higashitsugaru-gun","Namiuchi",""]],
	"0393381":[[2,"東津軽郡平内町","茂浦","","Hiranai-machi, Higashitsugaru-gun","Mora",""]],
	"0393382":[[2,"東津軽郡平内町","稲生","","Hiranai-machi, Higashitsugaru-gun","Ino",""]],
	"0393501":[[2,"青森市","浅虫","","Aomori-shi","Asamushi",""]],
	"0393502":[[2,"青森市","久栗坂","","Aomori-shi","Kugurizaka",""]],
	"0393503":[[2,"青森市","野内","","Aomori-shi","Nonai",""]],
	"0393504":[[2,"青森市","矢田","","Aomori-shi","Yada",""]],
	"0393505":[[2,"青森市","宮田","","Aomori-shi","Miyata",""]],
	"0393506":[[2,"青森市","三本木","","Aomori-shi","Sambongi",""]],
	"0393507":[[2,"青森市","馬屋尻","","Aomori-shi","Mayajiri",""]],
	"0393524":[[2,"青森市","滝沢","","Aomori-shi","Takisawa",""]],
	"0394100":[[2,"上北郡横浜町","","","Yokohama-machi, Kamikita-gun","",""]],
	"0394101":[[2,"上北郡横浜町","林尻","","Yokohama-machi, Kamikita-gun","Hayashijiri",""]],
	"0394102":[[2,"上北郡横浜町","浜田","","Yokohama-machi, Kamikita-gun","Hamada",""]],
	"0394103":[[2,"上北郡横浜町","川太郎川目","","Yokohama-machi, Kamikita-gun","Kawatarokawame",""]],
	"0394104":[[2,"上北郡横浜町","下苗代川目","","Yokohama-machi, Kamikita-gun","Shimonawashirokawame",""]],
	"0394105":[[2,"上北郡横浜町","苗代川目","","Yokohama-machi, Kamikita-gun","Nawashirokawame",""]],
	"0394106":[[2,"上北郡横浜町","有畑","","Yokohama-machi, Kamikita-gun","Arihata",""]],
	"0394111":[[2,"上北郡横浜町","大畑","","Yokohama-machi, Kamikita-gun","Ohata",""]],
	"0394112":[[2,"上北郡横浜町","夷ケ沢平","","Yokohama-machi, Kamikita-gun","Ezogasawataira",""]],
	"0394113":[[2,"上北郡横浜町","家ノ前川目","","Yokohama-machi, Kamikita-gun","Ienomaekawame",""]],
	"0394114":[[2,"上北郡横浜町","大豆田","","Yokohama-machi, Kamikita-gun","Mameda",""]],
	"0394115":[[2,"上北郡横浜町","稲荷平","","Yokohama-machi, Kamikita-gun","Inaritaira",""]],
	"0394116":[[2,"上北郡横浜町","中畑","","Yokohama-machi, Kamikita-gun","Nakahata",""]],
	"0394117":[[2,"上北郡横浜町","鶏沢","","Yokohama-machi, Kamikita-gun","Niwatorizawa",""]],
	"0394121":[[2,"上北郡横浜町","桧木","","Yokohama-machi, Kamikita-gun","Hinoki",""]],
	"0394122":[[2,"上北郡横浜町","鶏ケ唄","","Yokohama-machi, Kamikita-gun","Torigauta",""]],
	"0394123":[[2,"上北郡横浜町","茅平","","Yokohama-machi, Kamikita-gun","Kayataira",""]],
	"0394124":[[2,"上北郡横浜町","川尻","","Yokohama-machi, Kamikita-gun","Kawajiri",""]],
	"0394131":[[2,"上北郡横浜町","椛名木","","Yokohama-machi, Kamikita-gun","Kabanaki",""]],
	"0394132":[[2,"上北郡横浜町","太郎須田","","Yokohama-machi, Kamikita-gun","Tarosuda",""]],
	"0394133":[[2,"上北郡横浜町","舘の後","","Yokohama-machi, Kamikita-gun","Tatenoshiro",""]],
	"0394134":[[2,"上北郡横浜町","林の脇","","Yokohama-machi, Kamikita-gun","Hayashinowaki",""]],
	"0394135":[[2,"上北郡横浜町","林の後","","Yokohama-machi, Kamikita-gun","Hayashinoshiro",""]],
	"0394136":[[2,"上北郡横浜町","横浜","","Yokohama-machi, Kamikita-gun","Yokohama",""]],
	"0394137":[[2,"上北郡横浜町","下川原","","Yokohama-machi, Kamikita-gun","Shimogawara",""]],
	"0394138":[[2,"上北郡横浜町","塚名平","","Yokohama-machi, Kamikita-gun","Tsukanataira",""]],
	"0394141":[[2,"上北郡横浜町","三保野","","Yokohama-machi, Kamikita-gun","Mihono",""]],
	"0394142":[[2,"上北郡横浜町","上イタヤノ木","","Yokohama-machi, Kamikita-gun","Kamiitayanoki",""]],
	"0394143":[[2,"上北郡横浜町","屋敷形","","Yokohama-machi, Kamikita-gun","Yashikigata",""]],
	"0394144":[[2,"上北郡横浜町","浜懸","","Yokohama-machi, Kamikita-gun","Hamagake",""]],
	"0394145":[[2,"上北郡横浜町","寺下","","Yokohama-machi, Kamikita-gun","Terashita",""]],
	"0394151":[[2,"上北郡横浜町","向平","","Yokohama-machi, Kamikita-gun","Mukaitaira",""]],
	"0394152":[[2,"上北郡横浜町","百目木","","Yokohama-machi, Kamikita-gun","Domeki",""]],
	"0394153":[[2,"上北郡横浜町","吹越","","Yokohama-machi, Kamikita-gun","Fukkoshi",""]],
	"0394154":[[2,"上北郡横浜町","明神平","","Yokohama-machi, Kamikita-gun","Myojintaira",""]],
	"0394155":[[2,"上北郡横浜町","豊栄平","","Yokohama-machi, Kamikita-gun","Toyosakataira",""]],
	"0394156":[[2,"上北郡横浜町","雲雀平","","Yokohama-machi, Kamikita-gun","Hibaritaira",""]],
	"0394157":[[2,"上北郡横浜町","二又","","Yokohama-machi, Kamikita-gun","Futamata",""]],
	"0394221":[[2,"下北郡東通村","猿ケ森","","Higashidori-mura, Shimokita-gun","Sarugamori",""]],
	"0394222":[[2,"下北郡東通村","砂子又","","Higashidori-mura, Shimokita-gun","Sunagomata",""]],
	"0394223":[[2,"下北郡東通村","小田野沢","","Higashidori-mura, Shimokita-gun","Odanosawa",""]],
	"0394224":[[2,"下北郡東通村","白糠","","Higashidori-mura, Shimokita-gun","Shiranuka",""]],
	"0394301":[[2,"上北郡六ヶ所村","泊","","Rokkasho-mura, Kamikita-gun","Tomari",""]],
	"0394401":[[2,"むつ市","大畑町","","Mutsu-shi","Ohatamachi",""]],
	"0394402":[[2,"むつ市","大畑町正津川","","Mutsu-shi","Ohatamachi Shozugawa",""]],
	"0394500":[[2,"下北郡風間浦村","","","Kazamaura-mura, Shimokita-gun","",""]],
	"0394501":[[2,"下北郡風間浦村","下風呂","","Kazamaura-mura, Shimokita-gun","Shimofuro",""]],
	"0394502":[[2,"下北郡風間浦村","易国間","","Kazamaura-mura, Shimokita-gun","Ikokuma",""]],
	"0394503":[[2,"下北郡風間浦村","蛇浦","","Kazamaura-mura, Shimokita-gun","Hebiura",""]],
	"0394600":[[2,"下北郡大間町","","","Oma-machi, Shimokita-gun","",""]],
	"0394601":[[2,"下北郡大間町","大間","","Oma-machi, Shimokita-gun","Oma",""]],
	"0394602":[[2,"下北郡大間町","奥戸","","Oma-machi, Shimokita-gun","Okoppe",""]],
	"0394700":[[2,"下北郡佐井村","","","Sai-mura, Shimokita-gun","",""]],
	"0394701":[[2,"むつ市","川内町","","Mutsu-shi","Kawauchimachi",""]],
	"0394711":[[2,"下北郡佐井村","佐井","","Sai-mura, Shimokita-gun","Sai",""]],
	"0394712":[[2,"下北郡佐井村","長後","","Sai-mura, Shimokita-gun","Chogo",""]],
	"0395201":[[2,"むつ市","川内町","","Mutsu-shi","Kawauchimachi",""]],
	"0395202":[[2,"むつ市","川内町桧川","","Mutsu-shi","Kawauchimachihinokigawa",""]],
	"0395203":[[2,"むつ市","川内町宿野部","","Mutsu-shi","Kawauchimachishukunohe",""]],
	"0395204":[[2,"むつ市","川内町蛎崎","","Mutsu-shi","Kawauchimachikakizaki",""]],
	"0395304":[[2,"むつ市","川内町蛎崎","","Mutsu-shi","Kawauchimachikakizaki",""]],
	"0395321":[[2,"むつ市","脇野沢源藤城","","Mutsu-shi","Wakinosawa Gendoshiro",""]],
	"0395322":[[2,"むつ市","脇野沢滝山","","Mutsu-shi","Wakinosawa Takiyama",""]],
	"0395323":[[2,"むつ市","脇野沢七引","","Mutsu-shi","Wakinosawa Shichibiki",""]],
	"0395324":[[2,"むつ市","脇野沢田ノ頭","","Mutsu-shi","Wakinosawa Tanokashira",""]],
	"0395325":[[2,"むつ市","脇野沢辰内","","Mutsu-shi","Wakinosawa Tatsuchi",""]],
	"0395326":[[2,"むつ市","脇野沢桂沢","","Mutsu-shi","Wakinosawa Katsurazawa",""]],
	"0395327":[[2,"むつ市","脇野沢本村","","Mutsu-shi","Wakinosawa Honson",""]],
	"0395331":[[2,"むつ市","脇野沢渡向","","Mutsu-shi","Wakinosawa Watamukai",""]],
	"0395332":[[2,"むつ市","脇野沢瀬野川目","","Mutsu-shi","Wakinosawa Senokawame",""]],
	"0395333":[[2,"むつ市","脇野沢黒岩","","Mutsu-shi","Wakinosawa Kuroiwa",""]],
	"0395334":[[2,"むつ市","脇野沢新井田","","Mutsu-shi","Wakinosawa Niida",""]],
	"0395335":[[2,"むつ市","脇野沢寄浪","","Mutsu-shi","Wakinosawa Kinami",""]],
	"0395336":[[2,"むつ市","脇野沢蛸田","","Mutsu-shi","Wakinosawa Takoda",""]],
	"0395337":[[2,"むつ市","脇野沢九艘泊","","Mutsu-shi","Wakinosawa Kusodomari",""]],
	"0395341":[[2,"むつ市","脇野沢鹿間平","","Mutsu-shi","Wakinosawa Shikamadaira",""]],
	"0395342":[[2,"むつ市","脇野沢小沢","","Mutsu-shi","Wakinosawa Kozawa",""]],
	"0395343":[[2,"むつ市","脇野沢小サ沢","","Mutsu-shi","Wakinosawa Kosasawa",""]],
	"0395344":[[2,"むつ市","脇野沢稲平","","Mutsu-shi","Wakinosawa Inadaira",""]],
	"0395345":[[2,"むつ市","脇野沢赤坂","","Mutsu-shi","Wakinosawa Akasaka",""]],
	"0395346":[[2,"むつ市","脇野沢口広","","Mutsu-shi","Wakinosawa Kuchihiro",""]]
})
