zipdata({
	"9870000":[[4,"遠田郡美里町","","","Misato-machi, Toda-gun","",""]],
	"9870001":[[4,"遠田郡美里町","藤ケ崎","","Misato-machi, Toda-gun","Fujigasaki",""]],
	"9870002":[[4,"遠田郡美里町","藤ケ崎町","","Misato-machi, Toda-gun","Fujigasakicho",""]],
	"9870003":[[4,"遠田郡美里町","南小牛田","","Misato-machi, Toda-gun","Minamikogota",""]],
	"9870004":[[4,"遠田郡美里町","牛飼","","Misato-machi, Toda-gun","Ushikai",""]],
	"9870005":[[4,"遠田郡美里町","北浦","","Misato-machi, Toda-gun","Kitaura",""]],
	"9870006":[[4,"遠田郡美里町","関根","","Misato-machi, Toda-gun","Sekine",""]],
	"9870011":[[4,"遠田郡美里町","桜木町","","Misato-machi, Toda-gun","Sakuragicho",""]],
	"9870012":[[4,"遠田郡美里町","素山町","","Misato-machi, Toda-gun","Soyamacho",""]],
	"9870013":[[4,"遠田郡美里町","素山","","Misato-machi, Toda-gun","Soyama",""]],
	"9870014":[[4,"遠田郡美里町","志賀町","","Misato-machi, Toda-gun","Shigacho",""]],
	"9870015":[[4,"遠田郡美里町","青生","","Misato-machi, Toda-gun","Ao",""]],
	"9870021":[[4,"遠田郡美里町","平針","","Misato-machi, Toda-gun","Hirabari",""]],
	"9870022":[[4,"遠田郡美里町","荻埣","","Misato-machi, Toda-gun","Ogizone",""]],
	"9870024":[[4,"遠田郡美里町","中埣","","Misato-machi, Toda-gun","Nakazone",""],[4,"遠田郡美里町","成田","","Misato-machi, Toda-gun","Narita",""]],
	"9870025":[[4,"遠田郡美里町","中高城","","Misato-machi, Toda-gun","Nakatakagi",""]],
	"9870026":[[4,"遠田郡美里町","南高城","","Misato-machi, Toda-gun","Minamitakagi",""]],
	"9870031":[[4,"遠田郡美里町","高田","","Misato-machi, Toda-gun","Takada",""]],
	"9870032":[[4,"遠田郡美里町","学田","","Misato-machi, Toda-gun","Gakuden",""]],
	"9870033":[[4,"遠田郡美里町","小町井","","Misato-machi, Toda-gun","Komachii",""]],
	"9870034":[[4,"遠田郡美里町","化粧坂","","Misato-machi, Toda-gun","Keshozaka",""]],
	"9870035":[[4,"遠田郡美里町","志賀殿","","Misato-machi, Toda-gun","Shigaden",""]],
	"9870036":[[4,"遠田郡美里町","妻の神","","Misato-machi, Toda-gun","Sainokami",""]],
	"9870037":[[4,"遠田郡美里町","新藤ケ崎","","Misato-machi, Toda-gun","Shinfujigasaki",""]],
	"9870038":[[4,"遠田郡美里町","駅東","","Misato-machi, Toda-gun","Ekihigashi",""]],
	"9870041":[[4,"遠田郡美里町","峯山","","Misato-machi, Toda-gun","Mineyama",""]],
	"9870042":[[4,"遠田郡美里町","峯山浦","","Misato-machi, Toda-gun","Mineyamaura",""]],
	"9870043":[[4,"遠田郡美里町","新妻の神","","Misato-machi, Toda-gun","Shinsainokami",""]],
	"9870044":[[4,"遠田郡美里町","西舘","","Misato-machi, Toda-gun","Nishidate",""]],
	"9870045":[[4,"遠田郡美里町","内役田","","Misato-machi, Toda-gun","Uchiyakuden",""]],
	"9870046":[[4,"遠田郡美里町","役田","","Misato-machi, Toda-gun","Yakuden",""]],
	"9870051":[[4,"遠田郡美里町","上意江","","Misato-machi, Toda-gun","Joie",""]],
	"9870052":[[4,"遠田郡美里町","砂子田","","Misato-machi, Toda-gun","Sunagoda",""]],
	"9870053":[[4,"遠田郡美里町","叔廼前","","Misato-machi, Toda-gun","Shukunomae",""]],
	"9870054":[[4,"遠田郡美里町","塔の越","","Misato-machi, Toda-gun","Tonokoshi",""]],
	"9870055":[[4,"遠田郡美里町","新一本柳","","Misato-machi, Toda-gun","Shinipponyanagi",""]],
	"9870056":[[4,"遠田郡美里町","一本柳","","Misato-machi, Toda-gun","Ipponyanagi",""]],
	"9870057":[[4,"遠田郡美里町","狐山","","Misato-machi, Toda-gun","Kitsuneyama",""]],
	"9870058":[[4,"遠田郡美里町","塩釜","","Misato-machi, Toda-gun","Shiogama",""]],
	"9870059":[[4,"遠田郡美里町","塩釜添","","Misato-machi, Toda-gun","Shiogamazoe",""]],
	"9870061":[[4,"遠田郡美里町","下境","","Misato-machi, Toda-gun","Shimosakai",""]],
	"9870062":[[4,"遠田郡美里町","待井","","Misato-machi, Toda-gun","Machii",""]],
	"9870063":[[4,"遠田郡美里町","小沼","","Misato-machi, Toda-gun","Konuma",""]],
	"9870064":[[4,"遠田郡美里町","小沼添","","Misato-machi, Toda-gun","Konumazoi",""]],
	"9870065":[[4,"遠田郡美里町","勘堂","","Misato-machi, Toda-gun","Kando",""]],
	"9870066":[[4,"遠田郡美里町","二ツ檀","","Misato-machi, Toda-gun","Futatsudan",""]],
	"9870067":[[4,"遠田郡美里町","大所","","Misato-machi, Toda-gun","Daidokoro",""]],
	"9870068":[[4,"遠田郡美里町","新大所","","Misato-machi, Toda-gun","Shindaidokoro",""]],
	"9870069":[[4,"遠田郡美里町","北原","","Misato-machi, Toda-gun","Kitahara",""]],
	"9870100":[[4,"遠田郡涌谷町","","","Wakuya-cho, Toda-gun","",""]],
	"9870101":[[4,"遠田郡涌谷町","桜町裏","","Wakuya-cho, Toda-gun","Sakurachoura",""]],
	"9870102":[[4,"遠田郡涌谷町","表桜町","","Wakuya-cho, Toda-gun","Omotesakuracho",""]],
	"9870103":[[4,"遠田郡涌谷町","裏桜町","","Wakuya-cho, Toda-gun","Urasakuracho",""]],
	"9870104":[[4,"遠田郡涌谷町","田沼町","","Wakuya-cho, Toda-gun","Tanumacho",""]],
	"9870105":[[4,"遠田郡涌谷町","練丑町","","Wakuya-cho, Toda-gun","Neriushicho",""]],
	"9870106":[[4,"遠田郡涌谷町","六軒町","","Wakuya-cho, Toda-gun","Rokkencho",""]],
	"9870107":[[4,"遠田郡涌谷町","六軒町裏","","Wakuya-cho, Toda-gun","Rokkenchoura",""]],
	"9870111":[[4,"遠田郡涌谷町","柳町","","Wakuya-cho, Toda-gun","Yanagicho",""]],
	"9870112":[[4,"遠田郡涌谷町","桑木荒","","Wakuya-cho, Toda-gun","Kuwanokiara",""]],
	"9870113":[[4,"遠田郡涌谷町","渋江","","Wakuya-cho, Toda-gun","Shibue",""],[4,"遠田郡涌谷町","古道下二本杉","","Wakuya-cho, Toda-gun","Furumichishitanihonsugi",""]],
	"9870114":[[4,"遠田郡涌谷町","新町裏","","Wakuya-cho, Toda-gun","Shimmachiura",""]],
	"9870115":[[4,"遠田郡涌谷町","新町","","Wakuya-cho, Toda-gun","Shimmachi",""]],
	"9870121":[[4,"遠田郡涌谷町","涌谷","","Wakuya-cho, Toda-gun","Wakuya",""]],
	"9870130":[[4,"遠田郡涌谷町","新九軒前","","Wakuya-cho, Toda-gun","Shinkukemmae",""]],
	"9870131":[[4,"遠田郡涌谷町","北田","","Wakuya-cho, Toda-gun","Kitada",""]],
	"9870132":[[4,"遠田郡涌谷町","蔵人沖名","","Wakuya-cho, Toda-gun","Kurandokina",""],[4,"遠田郡涌谷町","小谷地","","Wakuya-cho, Toda-gun","Koyachi",""]],
	"9870133":[[4,"遠田郡涌谷町","赤間屋敷","","Wakuya-cho, Toda-gun","Akamayashiki",""],[4,"遠田郡涌谷町","掃部沖名","","Wakuya-cho, Toda-gun","Kamonokina",""],[4,"遠田郡涌谷町","後藤江","","Wakuya-cho, Toda-gun","Gotoe",""],[4,"遠田郡涌谷町","今左衛門沖名","","Wakuya-cho, Toda-gun","Konzaemonokina",""],[4,"遠田郡涌谷町","新田","","Wakuya-cho, Toda-gun","Shinden",""],[4,"遠田郡涌谷町","関谷沖名","","Wakuya-cho, Toda-gun","Sekiyaokina",""],[4,"遠田郡涌谷町","台所橋道下","","Wakuya-cho, Toda-gun","Daidokorobashimichishita",""],[4,"遠田郡涌谷町","鷹野橋下中瀬","","Wakuya-cho, Toda-gun","Takanobashishimonakaze",""]],
	"9870134":[[4,"遠田郡涌谷町","北五反田","","Wakuya-cho, Toda-gun","Kitagotanda",""],[4,"遠田郡涌谷町","九軒","","Wakuya-cho, Toda-gun","Kuken",""],[4,"遠田郡涌谷町","五反田","","Wakuya-cho, Toda-gun","Gotanda",""],[4,"遠田郡涌谷町","佐山木","","Wakuya-cho, Toda-gun","Sayamagi",""],[4,"遠田郡涌谷町","地不足道","","Wakuya-cho, Toda-gun","Jibusokumichi",""],[4,"遠田郡涌谷町","西谷地","","Wakuya-cho, Toda-gun","Nishiyachi",""],[4,"遠田郡涌谷町","二歩","","Wakuya-cho, Toda-gun","Nibu",""],[4,"遠田郡涌谷町","蘭場谷地","","Wakuya-cho, Toda-gun","Rambayachi",""]],
	"9870135":[[4,"遠田郡涌谷町","小蓋谷地","","Wakuya-cho, Toda-gun","Kobutayachi",""],[4,"遠田郡涌谷町","三十軒","","Wakuya-cho, Toda-gun","Sanjukken",""]],
	"9870136":[[4,"遠田郡涌谷町","一本柳","","Wakuya-cho, Toda-gun","Ipponyanagi",""]],
	"9870137":[[4,"遠田郡涌谷町","新中島乙","","Wakuya-cho, Toda-gun","Shinnakajimaotsu",""],[4,"遠田郡涌谷町","中島","","Wakuya-cho, Toda-gun","Nakajima",""],[4,"遠田郡涌谷町","中島乙","","Wakuya-cho, Toda-gun","Nakajimaotsu",""],[4,"遠田郡涌谷町","中島川前","","Wakuya-cho, Toda-gun","Nakajimakawamae",""],[4,"遠田郡涌谷町","中島甲","","Wakuya-cho, Toda-gun","Nakajimako",""]],
	"9870138":[[4,"遠田郡涌谷町","新境堀下","","Wakuya-cho, Toda-gun","Shinsakaiborishita",""]],
	"9870139":[[4,"遠田郡涌谷町","新台所橋","","Wakuya-cho, Toda-gun","Shindaidokorobashi",""]],
	"9870140":[[4,"遠田郡涌谷町","新沖新田","","Wakuya-cho, Toda-gun","Shinokishinden",""]],
	"9870141":[[4,"遠田郡涌谷町","田町裏","","Wakuya-cho, Toda-gun","Tamachiura",""]],
	"9870142":[[4,"遠田郡涌谷町","浦町","","Wakuya-cho, Toda-gun","Uramachi",""]],
	"9870143":[[4,"遠田郡涌谷町","長柄町","","Wakuya-cho, Toda-gun","Nagaecho",""]],
	"9870144":[[4,"遠田郡涌谷町","沖新田","","Wakuya-cho, Toda-gun","Okishinden",""],[4,"遠田郡涌谷町","小山下","","Wakuya-cho, Toda-gun","Koyamashita",""],[4,"遠田郡涌谷町","下新田","","Wakuya-cho, Toda-gun","Shimoshinden",""],[4,"遠田郡涌谷町","砂田","","Wakuya-cho, Toda-gun","Sunata",""],[4,"遠田郡涌谷町","八百刈","","Wakuya-cho, Toda-gun","Happyakugari",""],[4,"遠田郡涌谷町","薔薇島","","Wakuya-cho, Toda-gun","Barajima",""]],
	"9870145":[[4,"遠田郡涌谷町","市道","","Wakuya-cho, Toda-gun","Ichimichi",""],[4,"遠田郡涌谷町","烏鴉","","Wakuya-cho, Toda-gun","Ugarasu",""],[4,"遠田郡涌谷町","尾切","","Wakuya-cho, Toda-gun","Ogire",""],[4,"遠田郡涌谷町","鞍掛","","Wakuya-cho, Toda-gun","Kuragake",""],[4,"遠田郡涌谷町","花勝山","","Wakuya-cho, Toda-gun","Kekatsuyama",""],[4,"遠田郡涌谷町","新尾切","","Wakuya-cho, Toda-gun","Shinogire",""],[4,"遠田郡涌谷町","新名鰭","","Wakuya-cho, Toda-gun","Shinnabire",""],[4,"遠田郡涌谷町","名鰭","","Wakuya-cho, Toda-gun","Nabire",""]],
	"9870146":[[4,"遠田郡涌谷町","中下道","","Wakuya-cho, Toda-gun","Nakagedo",""]],
	"9870147":[[4,"遠田郡涌谷町","下道","","Wakuya-cho, Toda-gun","Gedo",""]],
	"9870148":[[4,"遠田郡涌谷町","三軒屋敷","","Wakuya-cho, Toda-gun","Sangenyashiki",""]],
	"9870149":[[4,"遠田郡涌谷町","新後藤江","","Wakuya-cho, Toda-gun","Shingotoe",""]],
	"9870151":[[4,"遠田郡涌谷町","小塚","","Wakuya-cho, Toda-gun","Kozuka",""]],
	"9870161":[[4,"遠田郡涌谷町","川原町","","Wakuya-cho, Toda-gun","Kawaramachi",""]],
	"9870162":[[4,"遠田郡涌谷町","本町","","Wakuya-cho, Toda-gun","Motomachi",""]],
	"9870163":[[4,"遠田郡涌谷町","立町","","Wakuya-cho, Toda-gun","Tatsucho",""]],
	"9870164":[[4,"遠田郡涌谷町","刈萱町","","Wakuya-cho, Toda-gun","Karukayacho",""]],
	"9870165":[[4,"遠田郡涌谷町","追廻町","","Wakuya-cho, Toda-gun","Oimawashicho",""]],
	"9870171":[[4,"遠田郡涌谷町","上郡","","Wakuya-cho, Toda-gun","Kamigori",""]],
	"9870172":[[4,"遠田郡涌谷町","下郡","","Wakuya-cho, Toda-gun","Shimogori",""]],
	"9870281":[[4,"遠田郡涌谷町","小里","","Wakuya-cho, Toda-gun","Osato",""]],
	"9870282":[[4,"遠田郡涌谷町","太田","","Wakuya-cho, Toda-gun","Ota",""]],
	"9870283":[[4,"遠田郡涌谷町","吉住","","Wakuya-cho, Toda-gun","Yoshizumi",""]],
	"9870284":[[4,"遠田郡涌谷町","猪岡短台","","Wakuya-cho, Toda-gun","Inokatandai",""]],
	"9870285":[[4,"遠田郡涌谷町","箟岳","","Wakuya-cho, Toda-gun","Nonodake",""]],
	"9870286":[[4,"遠田郡涌谷町","成沢","","Wakuya-cho, Toda-gun","Narisawa",""]],
	"9870301":[[4,"登米市","米山町善王寺","","Tome-shi","Yoneyamacho Zennoji",""]],
	"9870302":[[4,"登米市","米山町沼田","","Tome-shi","Yoneyamacho Numata",""],[4,"登米市","米山町櫓場","","Tome-shi","Yoneyamacho Yaguraba",""],[4,"登米市","米山町櫓場下","","Tome-shi","Yoneyamacho Yagurabashita",""]],
	"9870303":[[4,"登米市","米山町田畑西","","Tome-shi","Yoneyamacho Tabatanishi",""],[4,"登米市","米山町田畑前","","Tome-shi","Yoneyamacho Tabatamae",""]],
	"9870304":[[4,"登米市","米山町内","","Tome-shi","Yoneyamacho Uchi",""],[4,"登米市","米山町中道東","","Tome-shi","Yoneyamacho Nakamichihigashi",""],[4,"登米市","米山町中道前","","Tome-shi","Yoneyamacho Nakamichimae",""]],
	"9870305":[[4,"登米市","米山町川前","","Tome-shi","Yoneyamacho Kawamae",""],[4,"登米市","米山町水門","","Tome-shi","Yoneyamacho Suimon",""],[4,"登米市","米山町八反","","Tome-shi","Yoneyamacho Hattan",""]],
	"9870306":[[4,"登米市","米山町地蔵川","","Tome-shi","Yoneyamacho Jizogawa",""],[4,"登米市","米山町土佐ケ渕","","Tome-shi","Yoneyamacho Tosagafuchi",""]],
	"9870307":[[4,"登米市","米山町愛宕下","","Tome-shi","Yoneyamacho Atagoshita",""],[4,"登米市","米山町愛宕前","","Tome-shi","Yoneyamacho Atagomae",""],[4,"登米市","米山町犬子松","","Tome-shi","Yoneyamacho Inukomatsu",""],[4,"登米市","米山町猿ケ崎","","Tome-shi","Yoneyamacho Sarugasaki",""]],
	"9870308":[[4,"登米市","米山町小待井","","Tome-shi","Yoneyamacho Komachii",""],[4,"登米市","米山町小待井下","","Tome-shi","Yoneyamacho Komachiishita",""],[4,"登米市","米山町待井下","","Tome-shi","Yoneyamacho Machiishita",""]],
	"9870309":[[4,"登米市","米山町舘下","","Tome-shi","Yoneyamacho Dateshita",""],[4,"登米市","米山町舘前","","Tome-shi","Yoneyamacho Datemae",""]],
	"9870311":[[4,"登米市","米山町桜岡","","Tome-shi","Yoneyamacho Sakuraoka",""]],
	"9870321":[[4,"登米市","米山町西野","","Tome-shi","Yoneyamacho Nishino",""]],
	"9870331":[[4,"登米市","米山町中津山","","Tome-shi","Yoneyamacho Nakatsuyama",""]],
	"9870341":[[4,"登米市","豊里町大沢","","Tome-shi","Toyosatocho Osawa",""],[4,"登米市","豊里町大沢沼田","","Tome-shi","Toyosatocho Osawanumata",""],[4,"登米市","豊里町大沢谷岐","","Tome-shi","Toyosatocho Osawayagi",""],[4,"登米市","豊里町十二沢","","Tome-shi","Toyosatocho Junisawa",""],[4,"登米市","豊里町竹ノ沢","","Tome-shi","Toyosatocho Takenosawa",""]],
	"9870342":[[4,"登米市","豊里町山根","","Tome-shi","Toyosatocho Yamane",""],[4,"登米市","豊里町山根前","","Tome-shi","Toyosatocho Yamanemae",""]],
	"9870343":[[4,"登米市","豊里町小谷地","","Tome-shi","Toyosatocho Koyachi",""],[4,"登米市","豊里町沢尻","","Tome-shi","Toyosatocho Sawajiri",""]],
	"9870344":[[4,"登米市","豊里町境沢","","Tome-shi","Toyosatocho Sakaizawa",""],[4,"登米市","豊里町佐野","","Tome-shi","Toyosatocho Sano",""],[4,"登米市","豊里町迫","","Tome-shi","Toyosatocho Hasama",""]],
	"9870345":[[4,"登米市","豊里町中谷岐","","Tome-shi","Toyosatocho Nakayagi",""],[4,"登米市","豊里町福沢","","Tome-shi","Toyosatocho Fukusawa",""]],
	"9870346":[[4,"登米市","豊里町白鳥山","","Tome-shi","Toyosatocho Shiratoriyama",""],[4,"登米市","豊里町白鳥","","Tome-shi","Toyosatocho Shirotori",""],[4,"登米市","豊里町白鳥前","","Tome-shi","Toyosatocho Shirotorimae",""]],
	"9870351":[[4,"登米市","豊里町久寿田","","Tome-shi","Toyosatocho Kusuda",""],[4,"登米市","豊里町久寿田前","","Tome-shi","Toyosatocho Kusudamae",""]],
	"9870352":[[4,"登米市","豊里町寿崎","","Tome-shi","Toyosatocho Susaki",""]],
	"9870353":[[4,"登米市","豊里町笑沢","","Tome-shi","Toyosatocho Emisawa",""],[4,"登米市","豊里町大椚","","Tome-shi","Toyosatocho Okunugi",""],[4,"登米市","豊里町平林","","Tome-shi","Toyosatocho Hirabayashi",""]],
	"9870354":[[4,"登米市","豊里町上沼田","","Tome-shi","Toyosatocho Uwanumata",""],[4,"登米市","豊里町下沼田","","Tome-shi","Toyosatocho Shimonumata",""],[4,"登米市","豊里町昭和","","Tome-shi","Toyosatocho Showa",""],[4,"登米市","豊里町中沼田","","Tome-shi","Toyosatocho Nakanumada",""],[4,"登米市","豊里町沼田","","Tome-shi","Toyosatocho Numata",""]],
	"9870355":[[4,"登米市","豊里町後沢田","","Tome-shi","Toyosatocho Ushirosawada",""],[4,"登米市","豊里町保手","","Tome-shi","Toyosatocho Hode",""]],
	"9870356":[[4,"登米市","豊里町芝下","","Tome-shi","Toyosatocho Shibashita",""],[4,"登米市","豊里町杢沢","","Tome-shi","Toyosatocho Mokusawa",""]],
	"9870357":[[4,"登米市","豊里町蕪木","","Tome-shi","Toyosatocho Kabuki",""],[4,"登米市","豊里町鳥越","","Tome-shi","Toyosatocho Torigoe",""]],
	"9870358":[[4,"登米市","豊里町加々巻","","Tome-shi","Toyosatocho Kagamaki",""],[4,"登米市","豊里町小巻","","Tome-shi","Toyosatocho Komaki",""],[4,"登米市","豊里町新加々巻","","Tome-shi","Toyosatocho Shinkagamaki",""],[4,"登米市","豊里町長根浦","","Tome-shi","Toyosatocho Naganeura",""]],
	"9870359":[[4,"登米市","豊里町八反","","Tome-shi","Toyosatocho Hatsutan",""],[4,"登米市","豊里町本地八反","","Tome-shi","Toyosatocho Honchihatsutan",""]],
	"9870361":[[4,"登米市","豊里町新田町","","Tome-shi","Toyosatocho Shindemmachi",""]],
	"9870362":[[4,"登米市","豊里町上町裏","","Tome-shi","Toyosatocho Kamimachiura",""],[4,"登米市","豊里町小口前","","Tome-shi","Toyosatocho Koguchimae",""],[4,"登米市","豊里町東待井下","","Tome-shi","Toyosatocho Higashimachiishita",""]],
	"9870363":[[4,"登米市","豊里町五反田","","Tome-shi","Toyosatocho Gotanda",""],[4,"登米市","豊里町横町","","Tome-shi","Toyosatocho Yokocho",""]],
	"9870364":[[4,"登米市","豊里町下古屋","","Tome-shi","Toyosatocho Shimokoya",""],[4,"登米市","豊里町土手下","","Tome-shi","Toyosatocho Doteshita",""],[4,"登米市","豊里町本地土手下","","Tome-shi","Toyosatocho Honchidoteshita",""]],
	"9870365":[[4,"登米市","豊里町新町","","Tome-shi","Toyosatocho Shimmachi",""]],
	"9870366":[[4,"登米市","豊里町浦軒","","Tome-shi","Toyosatocho Uraken",""],[4,"登米市","豊里町上屋浦","","Tome-shi","Toyosatocho Kamiyaura",""],[4,"登米市","豊里町下屋浦","","Tome-shi","Toyosatocho Shimoyaura",""]],
	"9870367":[[4,"登米市","豊里町川前","","Tome-shi","Toyosatocho Kawamae",""]],
	"9870368":[[4,"登米市","豊里町七ツ塚","","Tome-shi","Toyosatocho Nanatsuzuka",""],[4,"登米市","豊里町町浦","","Tome-shi","Toyosatocho Machiura",""],[4,"登米市","豊里町南町浦","","Tome-shi","Toyosatocho Minamimachiura",""]],
	"9870371":[[4,"登米市","豊里町大曲","","Tome-shi","Toyosatocho Omagari",""],[4,"登米市","豊里町唐崎","","Tome-shi","Toyosatocho Karasaki",""],[4,"登米市","豊里町十丁田","","Tome-shi","Toyosatocho Jitchoda",""]],
	"9870372":[[4,"登米市","豊里町西前田","","Tome-shi","Toyosatocho Nishimaeda",""],[4,"登米市","豊里町前田","","Tome-shi","Toyosatocho Maeda",""]],
	"9870373":[[4,"登米市","豊里町内町浦","","Tome-shi","Toyosatocho Uchimachiura",""],[4,"登米市","豊里町切津","","Tome-shi","Toyosatocho Kitsutsu",""],[4,"登米市","豊里町南切津","","Tome-shi","Toyosatocho Minamikitsutsu",""]],
	"9870374":[[4,"登米市","豊里町東二ツ屋","","Tome-shi","Toyosatocho Higashifutatsuya",""]],
	"9870375":[[4,"登米市","豊里町二ツ屋","","Tome-shi","Toyosatocho Futatsuya",""]],
	"9870376":[[4,"登米市","豊里町新細沼","","Tome-shi","Toyosatocho Shinhosonuma",""],[4,"登米市","豊里町細沼","","Tome-shi","Toyosatocho Hosonuma",""],[4,"登米市","豊里町細沼田","","Tome-shi","Toyosatocho Hosonumata",""]],
	"9870377":[[4,"登米市","豊里町内一番江","","Tome-shi","Toyosatocho Uchiichibane",""],[4,"登米市","豊里町外一番江","","Tome-shi","Toyosatocho Sotoichibane",""]],
	"9870378":[[4,"登米市","豊里町鏡形","","Tome-shi","Toyosatocho Kagamigata",""],[4,"登米市","豊里町新田鏡形","","Tome-shi","Toyosatocho Shindenkagamigata",""]],
	"9870379":[[4,"登米市","豊里町剣先","","Tome-shi","Toyosatocho Kenzaki",""]],
	"9870381":[[4,"登米市","豊里町新長前","","Tome-shi","Toyosatocho Shinnagamae",""],[4,"登米市","豊里町長前","","Tome-shi","Toyosatocho Nagamae",""]],
	"9870382":[[4,"登米市","豊里町上谷地","","Tome-shi","Toyosatocho Kamiyachi",""]],
	"9870383":[[4,"登米市","豊里町外五番江","","Tome-shi","Toyosatocho Sotogobane",""],[4,"登米市","豊里町外三番江","","Tome-shi","Toyosatocho Sotosambane",""],[4,"登米市","豊里町外七番江","","Tome-shi","Toyosatocho Sotonanabane",""],[4,"登米市","豊里町外二番江","","Tome-shi","Toyosatocho Sotonibane",""],[4,"登米市","豊里町外八番江","","Tome-shi","Toyosatocho Sotohachibane",""],[4,"登米市","豊里町外四番江","","Tome-shi","Toyosatocho Sotoyombane",""],[4,"登米市","豊里町外六番江","","Tome-shi","Toyosatocho Sotorokubane",""]],
	"9870384":[[4,"登米市","豊里町十五貫","","Tome-shi","Toyosatocho Jugokan",""],[4,"登米市","豊里町十五貫谷地","","Tome-shi","Toyosatocho Jugokanyachi",""]],
	"9870385":[[4,"登米市","豊里町内田","","Tome-shi","Toyosatocho Uchita",""],[4,"登米市","豊里町内畑","","Tome-shi","Toyosatocho Uchihata",""],[4,"登米市","豊里町下九","","Tome-shi","Toyosatocho Shimogyu",""]],
	"9870401":[[4,"登米市","南方町高石","","Tome-shi","Minamikatamachi Takaishi",""],[4,"登米市","南方町高石浦","","Tome-shi","Minamikatamachi Takaishiura",""],[4,"登米市","南方町西山成","","Tome-shi","Minamikatamachi Nishiyamanari",""],[4,"登米市","南方町西山成前","","Tome-shi","Minamikatamachi Nishiyamanarimae",""],[4,"登米市","南方町八の森","","Tome-shi","Minamikatamachi Hachinomori",""],[4,"登米市","南方町山成","","Tome-shi","Minamikatamachi Yamanari",""],[4,"登米市","南方町山成前","","Tome-shi","Minamikatamachi Yamanarimae",""]],
	"9870402":[[4,"登米市","南方町板倉","","Tome-shi","Minamikatamachi Itakura",""],[4,"登米市","南方町板倉後","","Tome-shi","Minamikatamachi Itakuraushiro",""],[4,"登米市","南方町後屋敷待井","","Tome-shi","Minamikatamachi Ushiroyashikimachii",""],[4,"登米市","南方町沢田","","Tome-shi","Minamikatamachi Sawada",""],[4,"登米市","南方町沢田前","","Tome-shi","Minamikatamachi Sawadamae",""],[4,"登米市","南方町沢田待井","","Tome-shi","Minamikatamachi Sawadamachii",""],[4,"登米市","南方町沢田屋敷","","Tome-shi","Minamikatamachi Sawadayashiki",""],[4,"登米市","南方町新沢田","","Tome-shi","Minamikatamachi Shinsawada",""],[4,"登米市","南方町鶴代","","Tome-shi","Minamikatamachi Tsurushiro",""],[4,"登米市","南方町戸根屋敷","","Tome-shi","Minamikatamachi Toneyashiki",""],[4,"登米市","南方町中山","","Tome-shi","Minamikatamachi Nakayama",""],[4,"登米市","南方町待井","","Tome-shi","Minamikatamachi Machii",""],[4,"登米市","南方町松島屋敷","","Tome-shi","Minamikatamachi Matsushimayashiki",""]],
	"9870403":[[4,"登米市","南方町内ノ目","","Tome-shi","Minamikatamachi Uchinome",""],[4,"登米市","南方町王塚","","Tome-shi","Minamikatamachi Otsuka",""],[4,"登米市","南方町河面","","Tome-shi","Minamikatamachi Kawazura",""],[4,"登米市","南方町鴻ノ木","","Tome-shi","Minamikatamachi Konoki",""],[4,"登米市","南方町小山","","Tome-shi","Minamikatamachi Koyama",""],[4,"登米市","南方町二ツ橋","","Tome-shi","Minamikatamachi Futatsubashi",""],[4,"登米市","南方町峯","","Tome-shi","Minamikatamachi Mine",""],[4,"登米市","南方町薬師島屋敷","","Tome-shi","Minamikatamachi Yakushijimayashiki",""]],
	"9870404":[[4,"登米市","南方町新島前","","Tome-shi","Minamikatamachi Shinshimamae",""],[4,"登米市","南方町新丸ノ内","","Tome-shi","Minamikatamachi Shimmarunochi",""]],
	"9870405":[[4,"登米市","南方町新中山","","Tome-shi","Minamikatamachi Shinnakayama",""]],
	"9870411":[[4,"登米市","南方町天沼","","Tome-shi","Minamikatamachi Amanuma",""],[4,"登米市","南方町瀬ノ淵","","Tome-shi","Minamikatamachi Senofuchi",""],[4,"登米市","南方町寺袋","","Tome-shi","Minamikatamachi Terabukuro",""]],
	"9870412":[[4,"登米市","南方町上ケ戸","","Tome-shi","Minamikatamachi Agato",""],[4,"登米市","南方町雷","","Tome-shi","Minamikatamachi Ikazuchi",""],[4,"登米市","南方町大涌戸","","Tome-shi","Minamikatamachi Owakudo",""],[4,"登米市","南方町大門","","Tome-shi","Minamikatamachi Daimon",""],[4,"登米市","南方町照井","","Tome-shi","Minamikatamachi Terui",""],[4,"登米市","南方町峯前","","Tome-shi","Minamikatamachi Minemae",""]],
	"9870413":[[4,"登米市","南方町上原","","Tome-shi","Minamikatamachi Kamihara",""],[4,"登米市","南方町下原前","","Tome-shi","Minamikatamachi Shimoharamae",""],[4,"登米市","南方町宿畑","","Tome-shi","Minamikatamachi Shukubata",""],[4,"登米市","南方町中原","","Tome-shi","Minamikatamachi Nakahara",""],[4,"登米市","南方町原","","Tome-shi","Minamikatamachi Hara",""],[4,"登米市","南方町原浦","","Tome-shi","Minamikatamachi Haraura",""],[4,"登米市","南方町原前","","Tome-shi","Minamikatamachi Haramae",""],[4,"登米市","南方町原屋敷","","Tome-shi","Minamikatamachi Harayashiki",""]],
	"9870414":[[4,"登米市","南方町内鰐丸","","Tome-shi","Minamikatamachi Uchiwanimaru",""],[4,"登米市","南方町大村","","Tome-shi","Minamikatamachi Omura",""],[4,"登米市","南方町大村前","","Tome-shi","Minamikatamachi Omuramae",""],[4,"登米市","南方町新山成浦","","Tome-shi","Minamikatamachi Shinyamanariura",""],[4,"登米市","南方町松葉","","Tome-shi","Minamikatamachi Matsuba",""],[4,"登米市","南方町松葉表","","Tome-shi","Minamikatamachi Matsubaomote",""],[4,"登米市","南方町松葉前","","Tome-shi","Minamikatamachi Matsubamae",""],[4,"登米市","南方町山成浦","","Tome-shi","Minamikatamachi Yamanariura",""],[4,"登米市","南方町鰐丸","","Tome-shi","Minamikatamachi Wanimaru",""]],
	"9870415":[[4,"登米市","南方町真ケ沼","","Tome-shi","Minamikatamachi Maganuma",""]],
	"9870421":[[4,"登米市","南方町大畑","","Tome-shi","Minamikatamachi Obata",""],[4,"登米市","南方町仕込","","Tome-shi","Minamikatamachi Shikomi",""],[4,"登米市","南方町新井宿","","Tome-shi","Minamikatamachi Niijuku",""],[4,"登米市","南方町南大畑前","","Tome-shi","Minamikatamachi Minamiobatamae",""]],
	"9870422":[[4,"登米市","南方町大畠前","","Tome-shi","Minamikatamachi Ohatamae",""],[4,"登米市","南方町川前","","Tome-shi","Minamikatamachi Kawamae",""],[4,"登米市","南方町新大畑前","","Tome-shi","Minamikatamachi Shinobatamae",""],[4,"登米市","南方町新田","","Tome-shi","Minamikatamachi Shinden",""],[4,"登米市","南方町瀬川","","Tome-shi","Minamikatamachi Segawa",""],[4,"登米市","南方町東川前","","Tome-shi","Minamikatamachi Higashikawamae",""],[4,"登米市","南方町蛇沼","","Tome-shi","Minamikatamachi Hebinuma",""],[4,"登米市","南方町室田","","Tome-shi","Minamikatamachi Murota",""],[4,"登米市","南方町山崎","","Tome-shi","Minamikatamachi Yamazaki",""]],
	"9870423":[[4,"登米市","南方町大嶽","","Tome-shi","Minamikatamachi Odake",""],[4,"登米市","南方町大嶽前","","Tome-shi","Minamikatamachi Odakemae",""],[4,"登米市","南方町大嶽山","","Tome-shi","Minamikatamachi Odakeyama",""],[4,"登米市","南方町烏田","","Tome-shi","Minamikatamachi Karasuda",""],[4,"登米市","南方町ぜん荷前","","Tome-shi","Minamikatamachi Zenkamae",""],[4,"登米市","南方町ぜん荷山","","Tome-shi","Minamikatamachi Zenkayama",""],[4,"登米市","南方町館","","Tome-shi","Minamikatamachi Tate",""],[4,"登米市","南方町堂地","","Tome-shi","Minamikatamachi Dochi",""],[4,"登米市","南方町堂地前","","Tome-shi","Minamikatamachi Dochimae",""],[4,"登米市","南方町堀切","","Tome-shi","Minamikatamachi Hokkiri",""],[4,"登米市","南方町本郷大嶽","","Tome-shi","Minamikatamachi Hongoodake",""]],
	"9870424":[[4,"登米市","南方町風張","","Tome-shi","Minamikatamachi Kazahari",""],[4,"登米市","南方町館浦","","Tome-shi","Minamikatamachi Tateura",""],[4,"登米市","南方町細川","","Tome-shi","Minamikatamachi Hosokawa",""],[4,"登米市","南方町細川浦","","Tome-shi","Minamikatamachi Hosokawaura",""],[4,"登米市","南方町細川前","","Tome-shi","Minamikatamachi Hosokawamae",""],[4,"登米市","南方町南沢","","Tome-shi","Minamikatamachi Minamizawa",""],[4,"登米市","南方町南細川","","Tome-shi","Minamikatamachi Minamihosokawa",""]],
	"9870425":[[4,"登米市","南方町梶沼","","Tome-shi","Minamikatamachi Kajinuma",""],[4,"登米市","南方町梶沼川前","","Tome-shi","Minamikatamachi Kajinumakawamae",""],[4,"登米市","南方町梶沼前","","Tome-shi","Minamikatamachi Kajinumamae",""],[4,"登米市","南方町上砥落","","Tome-shi","Minamikatamachi Kamitotoshi",""],[4,"登米市","南方町下砥落","","Tome-shi","Minamikatamachi Shimototoshi",""],[4,"登米市","南方町十二山","","Tome-shi","Minamikatamachi Juniyama",""],[4,"登米市","南方町新上砥落","","Tome-shi","Minamikatamachi Shinkamitotoshi",""],[4,"登米市","南方町新砥落","","Tome-shi","Minamikatamachi Shintotoshi",""],[4,"登米市","南方町田中浦","","Tome-shi","Minamikatamachi Tanakaura",""],[4,"登米市","南方町砥落","","Tome-shi","Minamikatamachi Totoshi",""],[4,"登米市","南方町沼向","","Tome-shi","Minamikatamachi Numamukai",""],[4,"登米市","南方町米袋","","Tome-shi","Minamikatamachi Yonebukuro",""],[4,"登米市","南方町米袋浦","","Tome-shi","Minamikatamachi Yonebukurora",""],[4,"登米市","南方町米袋前","","Tome-shi","Minamikatamachi Yonebukuromae",""]],
	"9870426":[[4,"登米市","南方町大袋","","Tome-shi","Minamikatamachi Obukuro",""],[4,"登米市","南方町大袋浦","","Tome-shi","Minamikatamachi Obukurora",""],[4,"登米市","南方町樟","","Tome-shi","Minamikatamachi Kunugi",""],[4,"登米市","南方町樟土手外","","Tome-shi","Minamikatamachi Kunugidotesoto",""],[4,"登米市","南方町成田","","Tome-shi","Minamikatamachi Narita",""],[4,"登米市","南方町若狭前","","Tome-shi","Minamikatamachi Wakasamae",""]],
	"9870431":[[4,"登米市","南方町一ノ曲","","Tome-shi","Minamikatamachi Ichinomagari",""],[4,"登米市","南方町大埣","","Tome-shi","Minamikatamachi Ozone",""],[4,"登米市","南方町太田","","Tome-shi","Minamikatamachi Ota",""],[4,"登米市","南方町新一ノ曲","","Tome-shi","Minamikatamachi Shinichinomagari",""],[4,"登米市","南方町横前","","Tome-shi","Minamikatamachi Yokomae",""]],
	"9870432":[[4,"登米市","南方町青笹","","Tome-shi","Minamikatamachi Aozasa",""],[4,"登米市","南方町狼掛","","Tome-shi","Minamikatamachi Oinogake",""],[4,"登米市","南方町上窪田","","Tome-shi","Minamikatamachi Kamikubota",""],[4,"登米市","南方町窪田","","Tome-shi","Minamikatamachi Kubota",""],[4,"登米市","南方町新畑岡下","","Tome-shi","Minamikatamachi Shinhataokashita",""],[4,"登米市","南方町堤田","","Tome-shi","Minamikatamachi Tsutsumita",""],[4,"登米市","南方町畑岡","","Tome-shi","Minamikatamachi Hataoka",""],[4,"登米市","南方町畑岡下","","Tome-shi","Minamikatamachi Hataokashita",""]],
	"9870433":[[4,"登米市","南方町大平","","Tome-shi","Minamikatamachi Odaira",""],[4,"登米市","南方町大平前","","Tome-shi","Minamikatamachi Odairamae",""],[4,"登米市","南方町長者原","","Tome-shi","Minamikatamachi Chojahara",""],[4,"登米市","南方町中ノ口","","Tome-shi","Minamikatamachi Nakanokuchi",""],[4,"登米市","南方町沼崎","","Tome-shi","Minamikatamachi Numasaki",""],[4,"登米市","南方町沼崎前","","Tome-shi","Minamikatamachi Numasakimae",""]],
	"9870441":[[4,"登米市","南方町青島前","","Tome-shi","Minamikatamachi Aoshimamae",""],[4,"登米市","南方町青島待井","","Tome-shi","Minamikatamachi Aoshimamachii",""],[4,"登米市","南方町青島屋敷","","Tome-shi","Minamikatamachi Aoshimayashiki",""],[4,"登米市","南方町新青島前","","Tome-shi","Minamikatamachi Shinaoshimamae",""],[4,"登米市","南方町新鳩峯","","Tome-shi","Minamikatamachi Shinhatomine",""]],
	"9870442":[[4,"登米市","南方町後高石","","Tome-shi","Minamikatamachi Ushirotakaishi",""],[4,"登米市","南方町茶臼森","","Tome-shi","Minamikatamachi Chausumori",""],[4,"登米市","南方町茶臼森前","","Tome-shi","Minamikatamachi Chausumorimae",""],[4,"登米市","南方町中高石","","Tome-shi","Minamikatamachi Nakatakaishi",""],[4,"登米市","南方町中高石浦","","Tome-shi","Minamikatamachi Nakatakaishiura",""]],
	"9870443":[[4,"登米市","南方町板ケ沢","","Tome-shi","Minamikatamachi Itagasawa",""],[4,"登米市","南方町一網","","Tome-shi","Minamikatamachi Ichiaji",""],[4,"登米市","南方町大坂前","","Tome-shi","Minamikatamachi Ozakamae",""],[4,"登米市","南方町大西","","Tome-shi","Minamikatamachi Onishi",""],[4,"登米市","南方町表前","","Tome-shi","Minamikatamachi Omotemae",""],[4,"登米市","南方町苔野谷地","","Tome-shi","Minamikatamachi Kokenoyachi",""],[4,"登米市","南方町新野谷地","","Tome-shi","Minamikatamachi Shinnoyachi",""],[4,"登米市","南方町外浦","","Tome-shi","Minamikatamachi Sotora",""],[4,"登米市","南方町長根","","Tome-shi","Minamikatamachi Nagane",""],[4,"登米市","南方町長根下","","Tome-shi","Minamikatamachi Naganeshita",""],[4,"登米市","南方町野谷地","","Tome-shi","Minamikatamachi Noyachi",""]],
	"9870444":[[4,"登米市","南方町尼池","","Tome-shi","Minamikatamachi Amaike",""],[4,"登米市","南方町大上","","Tome-shi","Minamikatamachi Ogami",""],[4,"登米市","南方町大森前","","Tome-shi","Minamikatamachi Omorimae",""],[4,"登米市","南方町三代前","","Tome-shi","Minamikatamachi Sandaimae",""],[4,"登米市","南方町下新山","","Tome-shi","Minamikatamachi Shimoshinzan",""],[4,"登米市","南方町角欠前","","Tome-shi","Minamikatamachi Tsunogakemae",""],[4,"登米市","南方町間内","","Tome-shi","Minamikatamachi Mauchi",""],[4,"登米市","南方町間内前","","Tome-shi","Minamikatamachi Mauchimae",""],[4,"登米市","南方町実沢","","Tome-shi","Minamikatamachi Misawa",""],[4,"登米市","南方町柳沢","","Tome-shi","Minamikatamachi Yanagisawa",""],[4,"登米市","南方町柳沢前","","Tome-shi","Minamikatamachi Yanagisawamae",""],[4,"登米市","南方町横代","","Tome-shi","Minamikatamachi Yokodai",""]],
	"9870445":[[4,"登米市","南方町上平貝","","Tome-shi","Minamikatamachi Kamihiragai",""],[4,"登米市","南方町下平貝","","Tome-shi","Minamikatamachi Shimohiragai",""],[4,"登米市","南方町銭金壇","","Tome-shi","Minamikatamachi Zeniganedan",""],[4,"登米市","南方町中須崎","","Tome-shi","Minamikatamachi Nakasusaki",""],[4,"登米市","南方町平貝","","Tome-shi","Minamikatamachi Hiragai",""],[4,"登米市","南方町翌沢","","Tome-shi","Minamikatamachi Yokusawa",""]],
	"9870446":[[4,"登米市","南方町新高石浦","","Tome-shi","Minamikatamachi Shintakaishiura",""]],
	"9870447":[[4,"登米市","南方町新長根下","","Tome-shi","Minamikatamachi Shinnaganeshita",""]],
	"9870500":[[4,"登米市","","","Tome-shi","",""]],
	"9870511":[[4,"登米市","迫町佐沼","","Tome-shi","Hasamacho Sanuma",""]],
	"9870512":[[4,"登米市","迫町森","","Tome-shi","Hasamacho Mori",""]],
	"9870513":[[4,"登米市","迫町北方","","Tome-shi","Hasamacho Kitakata",""]],
	"9870601":[[4,"登米市","中田町石森","","Tome-shi","Nakadacho Ishinomori",""]],
	"9870602":[[4,"登米市","中田町上沼","","Tome-shi","Nakadacho Uwanuma",""]],
	"9870611":[[4,"登米市","中田町浅水","","Tome-shi","Nakadacho Asamizu",""]],
	"9870621":[[4,"登米市","中田町宝江黒沼","","Tome-shi","Nakadacho Takaraekuronuma",""]],
	"9870622":[[4,"登米市","中田町宝江新井田","","Tome-shi","Nakadacho Takaraeniida",""]],
	"9870623":[[4,"登米市","中田町宝江森","","Tome-shi","Nakadacho Takaraemori",""]],
	"9870701":[[4,"登米市","登米町小島","","Tome-shi","Toyomamachi Kojima",""]],
	"9870702":[[4,"登米市","登米町寺池","","Tome-shi","Toyomamachi Teraike",""]],
	"9870703":[[4,"登米市","登米町日根牛","","Tome-shi","Toyomamachi Hineushi",""]],
	"9870704":[[4,"登米市","登米町日野渡","","Tome-shi","Toyomamachi Hinoto",""]],
	"9870901":[[4,"登米市","東和町米川","","Tome-shi","Towacho Yonekawa",""]],
	"9870902":[[4,"登米市","東和町米谷","","Tome-shi","Towacho Maiya",""]],
	"9870903":[[4,"登米市","東和町錦織","","Tome-shi","Towacho Nishikiori",""]],
	"9871101":[[4,"石巻市","前谷地","","Ishinomaki-shi","Maeyachi",""]],
	"9871102":[[4,"石巻市","和渕","","Ishinomaki-shi","Wabuchi",""]],
	"9871103":[[4,"石巻市","北村","","Ishinomaki-shi","Kitamura",""]],
	"9871221":[[4,"石巻市","須江","","Ishinomaki-shi","Sue",""]],
	"9871222":[[4,"石巻市","広渕","","Ishinomaki-shi","Hirobuchi",""]],
	"9871301":[[4,"大崎市","松山須摩屋","","Osaki-shi","Matsuyama Sumaya",""]],
	"9871302":[[4,"大崎市","松山長尾","","Osaki-shi","Matsuyama Nagao",""]],
	"9871303":[[4,"大崎市","松山金谷","","Osaki-shi","Matsuyama Kanaya",""]],
	"9871304":[[4,"大崎市","松山千石","","Osaki-shi","Matsuyama Sengoku",""]],
	"9871305":[[4,"大崎市","松山次橋","","Osaki-shi","Matsuyama Tsugihashi",""]],
	"9871306":[[4,"大崎市","松山下伊場野","","Osaki-shi","Matsuyama Shimoibano",""]],
	"9872001":[[4,"栗原市","高清水蟹沢尻","","Kurihara-shi","Takashimizu Kanisawashiri",""]],
	"9872002":[[4,"栗原市","高清水八重壁","","Kurihara-shi","Takashimizu Yaekabe",""]],
	"9872003":[[4,"栗原市","高清水福塚","","Kurihara-shi","Takashimizu Fukutsuka",""]],
	"9872004":[[4,"栗原市","高清水浦南沢","","Kurihara-shi","Takashimizu Uraminamisawa",""]],
	"9872005":[[4,"栗原市","高清水忽滑沢","","Kurihara-shi","Takashimizu Nukarisawa",""]],
	"9872011":[[4,"栗原市","高清水京の沢","","Kurihara-shi","Takashimizu Kyonosawa",""]],
	"9872012":[[4,"栗原市","高清水中の沢","","Kurihara-shi","Takashimizu Nakanosawa",""]],
	"9872013":[[4,"栗原市","高清水欠屋敷","","Kurihara-shi","Takashimizu Kakeyashiki",""]],
	"9872014":[[4,"栗原市","高清水大沢","","Kurihara-shi","Takashimizu Osawa",""]],
	"9872015":[[4,"栗原市","高清水西中里","","Kurihara-shi","Takashimizu Nishinakazato",""]],
	"9872016":[[4,"栗原市","高清水茂路具多","","Kurihara-shi","Takashimizu Moroguta",""]],
	"9872017":[[4,"栗原市","高清水石沢","","Kurihara-shi","Takashimizu Ishizawa",""]],
	"9872018":[[4,"栗原市","高清水石沢浦","","Kurihara-shi","Takashimizu Ishizawaura",""]],
	"9872021":[[4,"栗原市","高清水神原","","Kurihara-shi","Takashimizu Kampara",""]],
	"9872022":[[4,"栗原市","高清水原","","Kurihara-shi","Takashimizu Hara",""]],
	"9872023":[[4,"栗原市","高清水熊野堂","","Kurihara-shi","Takashimizu Kumanodo",""]],
	"9872024":[[4,"栗原市","高清水小山田","","Kurihara-shi","Takashimizu Oyamada",""]],
	"9872025":[[4,"栗原市","高清水大西","","Kurihara-shi","Takashimizu Onishi",""]],
	"9872026":[[4,"栗原市","高清水熊野","","Kurihara-shi","Takashimizu Kumano",""]],
	"9872027":[[4,"栗原市","高清水若宮","","Kurihara-shi","Takashimizu Wakamiya",""]],
	"9872028":[[4,"栗原市","高清水日向","","Kurihara-shi","Takashimizu Hinata",""]],
	"9872031":[[4,"栗原市","高清水新田","","Kurihara-shi","Takashimizu Shinden",""]],
	"9872032":[[4,"栗原市","高清水横手","","Kurihara-shi","Takashimizu Yokote",""]],
	"9872033":[[4,"栗原市","高清水浅野","","Kurihara-shi","Takashimizu Azano",""]],
	"9872034":[[4,"栗原市","高清水明官","","Kurihara-shi","Takashimizu Myokan",""]],
	"9872035":[[4,"栗原市","高清水浅野前","","Kurihara-shi","Takashimizu Azanomae",""]],
	"9872036":[[4,"栗原市","高清水南沢","","Kurihara-shi","Takashimizu Minamisawa",""]],
	"9872041":[[4,"栗原市","高清水要の森","","Kurihara-shi","Takashimizu Yonomori",""]],
	"9872042":[[4,"栗原市","高清水宿の沢","","Kurihara-shi","Takashimizu Shukunosawa",""]],
	"9872043":[[4,"栗原市","高清水手取","","Kurihara-shi","Takashimizu Tedori",""]],
	"9872044":[[4,"栗原市","高清水堤下","","Kurihara-shi","Takashimizu Tsutsumishita",""]],
	"9872045":[[4,"栗原市","高清水西手取","","Kurihara-shi","Takashimizu Nishitetori",""]],
	"9872051":[[4,"栗原市","高清水三森","","Kurihara-shi","Takashimizu Mimori",""]],
	"9872052":[[4,"栗原市","高清水宮脇","","Kurihara-shi","Takashimizu Miyanowaki",""]],
	"9872053":[[4,"栗原市","高清水渕際","","Kurihara-shi","Takashimizu Fuchigiwa",""]],
	"9872054":[[4,"栗原市","高清水沖","","Kurihara-shi","Takashimizu Oki",""]],
	"9872055":[[4,"栗原市","高清水五月田","","Kurihara-shi","Takashimizu Satsukida",""]],
	"9872111":[[4,"栗原市","高清水影の沢","","Kurihara-shi","Takashimizu Kagenosawa",""]],
	"9872112":[[4,"栗原市","高清水上折木","","Kurihara-shi","Takashimizu Kamioriki",""]],
	"9872113":[[4,"栗原市","高清水折木","","Kurihara-shi","Takashimizu Oriki",""]],
	"9872114":[[4,"栗原市","高清水下折木","","Kurihara-shi","Takashimizu Shimoriki",""]],
	"9872115":[[4,"栗原市","高清水一本松","","Kurihara-shi","Takashimizu Ippommatsu",""]],
	"9872116":[[4,"栗原市","高清水来光沢","","Kurihara-shi","Takashimizu Raikozawa",""]],
	"9872121":[[4,"栗原市","高清水上佐野","","Kurihara-shi","Takashimizu Kamisano",""]],
	"9872122":[[4,"栗原市","高清水中佐野","","Kurihara-shi","Takashimizu Nakasano",""]],
	"9872123":[[4,"栗原市","高清水新佐野","","Kurihara-shi","Takashimizu Shinsano",""]],
	"9872124":[[4,"栗原市","高清水下佐野","","Kurihara-shi","Takashimizu Shimosano",""]],
	"9872125":[[4,"栗原市","高清水十二の神","","Kurihara-shi","Takashimizu Juninokami",""]],
	"9872126":[[4,"栗原市","高清水大寺","","Kurihara-shi","Takashimizu Daitera",""]],
	"9872127":[[4,"栗原市","高清水佐野沢田","","Kurihara-shi","Takashimizu Sanosawada",""],[4,"栗原市","高清水太子堂","","Kurihara-shi","Takashimizu Taishido",""]],
	"9872128":[[4,"栗原市","高清水佐野丁","","Kurihara-shi","Takashimizu Sanocho",""]],
	"9872131":[[4,"栗原市","高清水水の手","","Kurihara-shi","Takashimizu Mizunote",""]],
	"9872132":[[4,"栗原市","高清水東館","","Kurihara-shi","Takashimizu Higashitate",""]],
	"9872133":[[4,"栗原市","高清水桜丁","","Kurihara-shi","Takashimizu Sakuracho",""]],
	"9872141":[[4,"栗原市","高清水上外沢田","","Kurihara-shi","Takashimizu Kamisotosawata",""],[4,"栗原市","高清水北甚六原","","Kurihara-shi","Takashimizu Kitajinrokuhara",""]],
	"9872142":[[4,"栗原市","高清水外沢田","","Kurihara-shi","Takashimizu Sotosawada",""]],
	"9872143":[[4,"栗原市","高清水覚満寺","","Kurihara-shi","Takashimizu Kakumanji",""]],
	"9872144":[[4,"栗原市","高清水台町","","Kurihara-shi","Takashimizu Daimachi",""]],
	"9872145":[[4,"栗原市","高清水向野","","Kurihara-shi","Takashimizu Mukaino",""]],
	"9872146":[[4,"栗原市","高清水乙牧堀","","Kurihara-shi","Takashimizu Otsumakibori",""],[4,"栗原市","高清水甲牧堀","","Kurihara-shi","Takashimizu Komakibori",""],[4,"栗原市","高清水丁牧堀","","Kurihara-shi","Takashimizu Teimakibori",""],[4,"栗原市","高清水丙牧堀","","Kurihara-shi","Takashimizu Heimakibori",""]],
	"9872147":[[4,"栗原市","高清水観音沢","","Kurihara-shi","Takashimizu Kannonzawa",""],[4,"栗原市","高清水観音堂","","Kurihara-shi","Takashimizu Kannondo",""]],
	"9872151":[[4,"栗原市","高清水東浦","","Kurihara-shi","Takashimizu Higashiura",""],[4,"栗原市","高清水仰ケ返り","","Kurihara-shi","Takashimizu Mukegaeri",""]],
	"9872152":[[4,"栗原市","高清水天王沢","","Kurihara-shi","Takashimizu Tennosawa",""]],
	"9872153":[[4,"栗原市","高清水北原","","Kurihara-shi","Takashimizu Kitahara",""]],
	"9872154":[[4,"栗原市","高清水南原","","Kurihara-shi","Takashimizu Minamihara",""]],
	"9872155":[[4,"栗原市","高清水萱刈","","Kurihara-shi","Takashimizu Kayakari",""]],
	"9872156":[[4,"栗原市","高清水千神","","Kurihara-shi","Takashimizu Sengami",""]],
	"9872157":[[4,"栗原市","高清水中の茎","","Kurihara-shi","Takashimizu Nakanokuki",""]],
	"9872158":[[4,"栗原市","高清水上萩田","","Kurihara-shi","Takashimizu Kamihagita",""],[4,"栗原市","高清水新中の茎","","Kurihara-shi","Takashimizu Shinnakanokuki",""],[4,"栗原市","高清水本道","","Kurihara-shi","Takashimizu Motomichi",""]],
	"9872159":[[4,"栗原市","高清水松の木沢田","","Kurihara-shi","Takashimizu Matsunokisawada",""]],
	"9872161":[[4,"栗原市","高清水神明","","Kurihara-shi","Takashimizu Shimmei",""]],
	"9872162":[[4,"栗原市","高清水丁神明","","Kurihara-shi","Takashimizu Teishimmei",""]],
	"9872163":[[4,"栗原市","高清水勝負ケ町","","Kurihara-shi","Takashimizu Shobugamachi",""]],
	"9872164":[[4,"栗原市","高清水新神明","","Kurihara-shi","Takashimizu Shinshimmei",""]],
	"9872171":[[4,"栗原市","高清水長福寺","","Kurihara-shi","Takashimizu Chofukuji",""]],
	"9872172":[[4,"栗原市","高清水松原","","Kurihara-shi","Takashimizu Matsubara",""]],
	"9872173":[[4,"栗原市","高清水桂葉","","Kurihara-shi","Takashimizu Katsuraha",""]],
	"9872174":[[4,"栗原市","高清水上桂葉","","Kurihara-shi","Takashimizu Kamikatsuraha",""]],
	"9872175":[[4,"栗原市","高清水五輪","","Kurihara-shi","Takashimizu Gorin",""]],
	"9872176":[[4,"栗原市","高清水西善光寺","","Kurihara-shi","Takashimizu Nishizenkoji",""]],
	"9872177":[[4,"栗原市","高清水新桂葉","","Kurihara-shi","Takashimizu Shinkatsuraha",""]],
	"9872181":[[4,"栗原市","高清水東善光寺","","Kurihara-shi","Takashimizu Higashizenkoji",""]],
	"9872182":[[4,"栗原市","高清水中里","","Kurihara-shi","Takashimizu Nakazato",""]],
	"9872183":[[4,"栗原市","高清水袖山","","Kurihara-shi","Takashimizu Sodeyama",""]],
	"9872184":[[4,"栗原市","高清水善光寺","","Kurihara-shi","Takashimizu Zenkoji",""]],
	"9872185":[[4,"栗原市","高清水新町","","Kurihara-shi","Takashimizu Aramachi",""]],
	"9872186":[[4,"栗原市","高清水中町","","Kurihara-shi","Takashimizu Nakamachi",""]],
	"9872187":[[4,"栗原市","高清水本町","","Kurihara-shi","Takashimizu Motomachi",""]],
	"9872188":[[4,"栗原市","高清水小山下","","Kurihara-shi","Takashimizu Oyamashita",""]],
	"9872189":[[4,"栗原市","高清水下町","","Kurihara-shi","Takashimizu Shitamachi",""]],
	"9872200":[[4,"栗原市","","","Kurihara-shi","",""]],
	"9872201":[[4,"栗原市","築館富","","Kurihara-shi","Tsukidate Tomi",""]],
	"9872202":[[4,"栗原市","築館城生野","","Kurihara-shi","Tsukidate Jono",""]],
	"9872203":[[4,"栗原市","築館下宮野","","Kurihara-shi","Tsukidate Shimomiyano",""]],
	"9872204":[[4,"栗原市","築館黒瀬","","Kurihara-shi","Tsukidate Kurose",""]],
	"9872205":[[4,"栗原市","築館宮野中央","","Kurihara-shi","Tsukidate Miyanochuo",""]],
	"9872211":[[4,"栗原市","築館源光","","Kurihara-shi","Tsukidate Genko",""]],
	"9872212":[[4,"栗原市","築館木戸","","Kurihara-shi","Tsukidate Kido",""]],
	"9872213":[[4,"栗原市","築館内南沢","","Kurihara-shi","Tsukidate Uchiminamizawa",""]],
	"9872214":[[4,"栗原市","築館内沢","","Kurihara-shi","Tsukidate Uchisawa",""]],
	"9872215":[[4,"栗原市","築館高田","","Kurihara-shi","Tsukidate Takada",""]],
	"9872216":[[4,"栗原市","築館伊豆","","Kurihara-shi","Tsukidate Izu",""]],
	"9872221":[[4,"栗原市","築館下待井","","Kurihara-shi","Tsukidate Shimomachii",""]],
	"9872222":[[4,"栗原市","築館外南沢","","Kurihara-shi","Tsukidate Sotominamizawa",""]],
	"9872223":[[4,"栗原市","築館萩沢","","Kurihara-shi","Tsukidate Hagisawa",""]],
	"9872224":[[4,"栗原市","築館横須賀","","Kurihara-shi","Tsukidate Yokosuka",""]],
	"9872225":[[4,"栗原市","築館太田","","Kurihara-shi","Tsukidate Ota",""]],
	"9872226":[[4,"栗原市","築館八沢","","Kurihara-shi","Tsukidate Yasawa",""]],
	"9872227":[[4,"栗原市","築館光屋敷","","Kurihara-shi","Tsukidate Hikariyashiki",""]],
	"9872228":[[4,"栗原市","築館川添","","Kurihara-shi","Tsukidate Kawazoe",""]],
	"9872229":[[4,"栗原市","築館三峰","","Kurihara-shi","Tsukidate Mitsumine",""]],
	"9872231":[[4,"栗原市","築館赤坂","","Kurihara-shi","Tsukidate Akasaka",""]],
	"9872232":[[4,"栗原市","築館沢入","","Kurihara-shi","Tsukidate Sawairi",""]],
	"9872233":[[4,"栗原市","築館照越","","Kurihara-shi","Tsukidate Terukoshi",""]],
	"9872234":[[4,"栗原市","築館新八ツ沢","","Kurihara-shi","Tsukidate Shinyatsuzawa",""]],
	"9872235":[[4,"栗原市","築館築館","","Kurihara-shi","Tsukidate Tsukidate",""]],
	"9872236":[[4,"栗原市","築館蟹沢","","Kurihara-shi","Tsukidate Kanisawa",""]],
	"9872241":[[4,"栗原市","築館館下","","Kurihara-shi","Tsukidate Tateshita",""]],
	"9872242":[[4,"栗原市","築館館沢","","Kurihara-shi","Tsukidate Tatesawa",""]],
	"9872243":[[4,"栗原市","築館萩沢東","","Kurihara-shi","Tsukidate Hagisawahigashi",""],[4,"栗原市","築館萩沢南","","Kurihara-shi","Tsukidate Hagisawaminami",""]],
	"9872244":[[4,"栗原市","築館西小山","","Kurihara-shi","Tsukidate Nishikoyama",""]],
	"9872245":[[4,"栗原市","築館荒田沢","","Kurihara-shi","Tsukidate Aratazawa",""]],
	"9872246":[[4,"栗原市","築館上高森","","Kurihara-shi","Tsukidate Kamitakamori",""]],
	"9872247":[[4,"栗原市","築館下高森","","Kurihara-shi","Tsukidate Shimotakamori",""]],
	"9872251":[[4,"栗原市","築館藤木","","Kurihara-shi","Tsukidate Fujiki",""]],
	"9872252":[[4,"栗原市","築館薬師","","Kurihara-shi","Tsukidate Yakushi",""]],
	"9872253":[[4,"栗原市","築館青野","","Kurihara-shi","Tsukidate Aono",""]],
	"9872261":[[4,"栗原市","築館久伝","","Kurihara-shi","Tsukidate Kyuden",""]],
	"9872262":[[4,"栗原市","築館唐竹林","","Kurihara-shi","Tsukidate Karatakebayashi",""]],
	"9872263":[[4,"栗原市","築館新田","","Kurihara-shi","Tsukidate Shinden",""],[4,"栗原市","築館薬師ケ丘","","Kurihara-shi","Tsukidate Yakushigaoka",""]],
	"9872264":[[4,"栗原市","築館薬師台","","Kurihara-shi","Tsukidate Yakushidai",""]],
	"9872265":[[4,"栗原市","築館小淵西","","Kurihara-shi","Tsukidate Kobuchinishi",""],[4,"栗原市","築館小淵東","","Kurihara-shi","Tsukidate Kobuchihigashi",""],[4,"栗原市","築館境田","","Kurihara-shi","Tsukidate Sakaida",""],[4,"栗原市","築館佐野原","","Kurihara-shi","Tsukidate Sanohara",""]],
	"9872271":[[4,"栗原市","築館芋埣","","Kurihara-shi","Tsukidate Imozone",""]],
	"9872272":[[4,"栗原市","築館留場","","Kurihara-shi","Tsukidate Tomeba",""]],
	"9872273":[[4,"栗原市","築館左足","","Kurihara-shi","Tsukidate Koedate",""]],
	"9872274":[[4,"栗原市","築館新成田西","","Kurihara-shi","Tsukidate Shinnaritanishi",""],[4,"栗原市","築館成田","","Kurihara-shi","Tsukidate Narita",""]],
	"9872275":[[4,"栗原市","築館上宮野","","Kurihara-shi","Tsukidate Kamimiyano",""]],
	"9872301":[[4,"栗原市","一迫大川口","","Kurihara-shi","Ichihasama Okawaguchi",""]],
	"9872302":[[4,"栗原市","一迫片子沢","","Kurihara-shi","Ichihasama Katagozawa",""]],
	"9872303":[[4,"栗原市","一迫川口","","Kurihara-shi","Ichihasama Kawaguchi",""]],
	"9872304":[[4,"栗原市","一迫北沢","","Kurihara-shi","Ichihasama Kitazawa",""]],
	"9872305":[[4,"栗原市","一迫狐崎","","Kurihara-shi","Ichihasama Kitsunezaki",""]],
	"9872306":[[4,"栗原市","一迫嶋躰","","Kurihara-shi","Ichihasama Shimatai",""]],
	"9872307":[[4,"栗原市","一迫清水目","","Kurihara-shi","Ichihasama Suzunome",""]],
	"9872308":[[4,"栗原市","一迫真坂","","Kurihara-shi","Ichihasama Masaka",""]],
	"9872309":[[4,"栗原市","一迫柳目","","Kurihara-shi","Ichihasama Yanaginome",""]],
	"9872311":[[4,"栗原市","一迫御崎","","Kurihara-shi","Ichihasama Misaki",""]],
	"9872312":[[4,"栗原市","一迫沖浦","","Kurihara-shi","Ichihasama Okiura",""]],
	"9872313":[[4,"栗原市","一迫沖","","Kurihara-shi","Ichihasama Oki",""]],
	"9872314":[[4,"栗原市","一迫岡田","","Kurihara-shi","Ichihasama Okada",""]],
	"9872315":[[4,"栗原市","一迫間杭元","","Kurihara-shi","Ichihasama Kenguimoto",""]],
	"9872316":[[4,"栗原市","一迫小坂本","","Kurihara-shi","Ichihasama Kosakamoto",""]],
	"9872317":[[4,"栗原市","一迫久保田","","Kurihara-shi","Ichihasama Kubota",""]],
	"9872318":[[4,"栗原市","一迫松の木","","Kurihara-shi","Ichihasama Matsunoki",""]],
	"9872319":[[4,"栗原市","一迫宮前","","Kurihara-shi","Ichihasama Miyamae",""]],
	"9872321":[[4,"栗原市","一迫横町","","Kurihara-shi","Ichihasama Yokomachi",""]],
	"9872322":[[4,"栗原市","一迫横町浦","","Kurihara-shi","Ichihasama Yokomachiura",""]],
	"9872323":[[4,"栗原市","一迫女子町","","Kurihara-shi","Ichihasama Megomachi",""]],
	"9872324":[[4,"栗原市","一迫三嶋","","Kurihara-shi","Ichihasama Mishima",""]],
	"9872325":[[4,"栗原市","一迫坂下西","","Kurihara-shi","Ichihasama Sakashitanishi",""]],
	"9872326":[[4,"栗原市","一迫山崎","","Kurihara-shi","Ichihasama Yamazaki",""]],
	"9872327":[[4,"栗原市","一迫天神","","Kurihara-shi","Ichihasama Tenjin",""]],
	"9872328":[[4,"栗原市","一迫土川","","Kurihara-shi","Ichihasama Tsuchikawa",""]],
	"9872329":[[4,"栗原市","一迫細越","","Kurihara-shi","Ichihasama Hosogoe",""]],
	"9872331":[[4,"栗原市","一迫萩生","","Kurihara-shi","Ichihasama Hagiu",""]],
	"9872332":[[4,"栗原市","一迫高橋","","Kurihara-shi","Ichihasama Takahashi",""]],
	"9872333":[[4,"栗原市","一迫要害","","Kurihara-shi","Ichihasama Yogai",""]],
	"9872334":[[4,"栗原市","一迫神山","","Kurihara-shi","Ichihasama Shinzan",""]],
	"9872335":[[4,"栗原市","一迫高田","","Kurihara-shi","Ichihasama Takada",""]],
	"9872336":[[4,"栗原市","一迫荒屋敷","","Kurihara-shi","Ichihasama Arayashiki",""]],
	"9872337":[[4,"栗原市","一迫松原沢","","Kurihara-shi","Ichihasama Matsubarazawa",""]],
	"9872338":[[4,"栗原市","一迫日向","","Kurihara-shi","Ichihasama Hinata",""]],
	"9872339":[[4,"栗原市","一迫上中島","","Kurihara-shi","Ichihasama Kaminakajima",""]],
	"9872341":[[4,"栗原市","一迫中屋敷浦","","Kurihara-shi","Ichihasama Nakayashikiura",""]],
	"9872342":[[4,"栗原市","一迫沢田","","Kurihara-shi","Ichihasama Sawada",""]],
	"9872343":[[4,"栗原市","一迫一本杉","","Kurihara-shi","Ichihasama Ipponsugi",""]],
	"9872344":[[4,"栗原市","一迫宮下","","Kurihara-shi","Ichihasama Miyajita",""]],
	"9872345":[[4,"栗原市","一迫屋敷田","","Kurihara-shi","Ichihasama Yashikida",""]],
	"9872346":[[4,"栗原市","一迫大清水","","Kurihara-shi","Ichihasama Osuzu",""]],
	"9872347":[[4,"栗原市","一迫平館","","Kurihara-shi","Ichihasama Hiradate",""]],
	"9872348":[[4,"栗原市","一迫大平沢","","Kurihara-shi","Ichihasama Ohirasawa",""]],
	"9872349":[[4,"栗原市","一迫大際","","Kurihara-shi","Ichihasama Daigiwa",""]],
	"9872351":[[4,"栗原市","一迫宇南田","","Kurihara-shi","Ichihasama Unanda",""]],
	"9872352":[[4,"栗原市","一迫鹿込","","Kurihara-shi","Ichihasama Shishigome",""]],
	"9872353":[[4,"栗原市","一迫上久保","","Kurihara-shi","Ichihasama Kamikubo",""]],
	"9872354":[[4,"栗原市","一迫西風","","Kurihara-shi","Ichihasama Narai",""]],
	"9872355":[[4,"栗原市","一迫鍛冶屋敷","","Kurihara-shi","Ichihasama Kajiyashiki",""]],
	"9872356":[[4,"栗原市","一迫山沢","","Kurihara-shi","Ichihasama Yamasawa",""]],
	"9872357":[[4,"栗原市","一迫沼田","","Kurihara-shi","Ichihasama Numata",""]],
	"9872358":[[4,"栗原市","一迫下小僧","","Kurihara-shi","Ichihasama Shimokozo",""]],
	"9872359":[[4,"栗原市","一迫佐野原","","Kurihara-shi","Ichihasama Sanobara",""]],
	"9872361":[[4,"栗原市","一迫中小僧","","Kurihara-shi","Ichihasama Nakakozo",""]],
	"9872362":[[4,"栗原市","一迫大栗","","Kurihara-shi","Ichihasama Oguri",""]],
	"9872363":[[4,"栗原市","一迫佐野","","Kurihara-shi","Ichihasama Sano",""]],
	"9872364":[[4,"栗原市","一迫岩ケ沢","","Kurihara-shi","Ichihasama Iwagasawa",""]],
	"9872365":[[4,"栗原市","一迫新米","","Kurihara-shi","Ichihasama Shimmai",""]],
	"9872366":[[4,"栗原市","一迫論田","","Kurihara-shi","Ichihasama Ronden",""]],
	"9872367":[[4,"栗原市","一迫上大土","","Kurihara-shi","Ichihasama Kamiodo",""]],
	"9872368":[[4,"栗原市","一迫下大土","","Kurihara-shi","Ichihasama Shimoodo",""]],
	"9872369":[[4,"栗原市","一迫荒町","","Kurihara-shi","Ichihasama Aramachi",""]],
	"9872371":[[4,"栗原市","一迫川台","","Kurihara-shi","Ichihasama Kawadai",""]],
	"9872372":[[4,"栗原市","一迫青木","","Kurihara-shi","Ichihasama Aoki",""]],
	"9872373":[[4,"栗原市","一迫不動西","","Kurihara-shi","Ichihasama Fudonishi",""]],
	"9872374":[[4,"栗原市","一迫清水原","","Kurihara-shi","Ichihasama Shimizubara",""]],
	"9872511":[[4,"栗原市","花山本沢","","Kurihara-shi","Hanayama Honsawa",""]],
	"9872512":[[4,"栗原市","花山草木沢","","Kurihara-shi","Hanayama Kusakisawa",""]]
})
