zipdata({
	"9830000":[[4,"仙台市宮城野区","","","Miyagino-ku, Sendai-shi","",""]],
	"9830001":[[4,"仙台市宮城野区","港","","Miyagino-ku, Sendai-shi","Minato",""]],
	"9830002":[[4,"仙台市宮城野区","蒲生","","Miyagino-ku, Sendai-shi","Gamo",""]],
	"9830003":[[4,"仙台市宮城野区","岡田","","Miyagino-ku, Sendai-shi","Okada",""]],
	"9830004":[[4,"仙台市宮城野区","岡田西町","","Miyagino-ku, Sendai-shi","Okadanishimachi",""]],
	"9830005":[[4,"仙台市宮城野区","福室","","Miyagino-ku, Sendai-shi","Fukumuro",""]],
	"9830006":[[4,"仙台市宮城野区","白鳥","","Miyagino-ku, Sendai-shi","Shiratori",""]],
	"9830007":[[4,"仙台市宮城野区","仙台港北","","Miyagino-ku, Sendai-shi","Sendaikokita",""]],
	"9830011":[[4,"仙台市宮城野区","栄","","Miyagino-ku, Sendai-shi","Sakae",""]],
	"9830012":[[4,"仙台市宮城野区","出花","","Miyagino-ku, Sendai-shi","Ideka",""]],
	"9830013":[[4,"仙台市宮城野区","中野","","Miyagino-ku, Sendai-shi","Nakano",""]],
	"9830014":[[4,"仙台市宮城野区","高砂","","Miyagino-ku, Sendai-shi","Takasago",""]],
	"9830021":[[4,"仙台市宮城野区","田子","","Miyagino-ku, Sendai-shi","Tago",""]],
	"9830023":[[4,"仙台市宮城野区","福田町","","Miyagino-ku, Sendai-shi","Fukudamachi",""]],
	"9830024":[[4,"仙台市宮城野区","鶴巻","","Miyagino-ku, Sendai-shi","Tsurumaki",""]],
	"9830025":[[4,"仙台市宮城野区","福田町南","","Miyagino-ku, Sendai-shi","Fukudamachiminami",""]],
	"9830026":[[4,"仙台市宮城野区","田子西","","Miyagino-ku, Sendai-shi","Tagonishi",""]],
	"9830031":[[4,"仙台市宮城野区","小鶴","","Miyagino-ku, Sendai-shi","Kozuru",""]],
	"9830032":[[4,"仙台市宮城野区","仙石","","Miyagino-ku, Sendai-shi","Sengoku",""]],
	"9830033":[[4,"仙台市宮城野区","福住町","","Miyagino-ku, Sendai-shi","Fukuzumimachi",""]],
	"9830034":[[4,"仙台市宮城野区","扇町","","Miyagino-ku, Sendai-shi","Ogimachi",""]],
	"9830035":[[4,"仙台市宮城野区","日の出町","","Miyagino-ku, Sendai-shi","Hinodemachi",""]],
	"9830036":[[4,"仙台市宮城野区","苦竹","","Miyagino-ku, Sendai-shi","Nigatake",""],[4,"仙台市宮城野区","原町苦竹","","Miyagino-ku, Sendai-shi","Haranomachinigatake",""]],
	"9830037":[[4,"仙台市宮城野区","平成","","Miyagino-ku, Sendai-shi","Heisei",""]],
	"9830038":[[4,"仙台市宮城野区","新田","","Miyagino-ku, Sendai-shi","Shinden",""]],
	"9830039":[[4,"仙台市宮城野区","新田東","","Miyagino-ku, Sendai-shi","Shindenhigashi",""]],
	"9830041":[[4,"仙台市宮城野区","南目館","","Miyagino-ku, Sendai-shi","Minaminometate",""]],
	"9830042":[[4,"仙台市宮城野区","東宮城野","","Miyagino-ku, Sendai-shi","Higashimiyagino",""]],
	"9830043":[[4,"仙台市宮城野区","萩野町","","Miyagino-ku, Sendai-shi","Haginomachi",""]],
	"9830044":[[4,"仙台市宮城野区","宮千代","","Miyagino-ku, Sendai-shi","Miyachiyo",""]],
	"9830045":[[4,"仙台市宮城野区","宮城野","","Miyagino-ku, Sendai-shi","Miyagino",""]],
	"9830046":[[4,"仙台市宮城野区","西宮城野","","Miyagino-ku, Sendai-shi","Nishimiyagino",""]],
	"9830047":[[4,"仙台市宮城野区","銀杏町","","Miyagino-ku, Sendai-shi","Ichomachi",""]],
	"9830803":[[4,"仙台市宮城野区","小田原","","Miyagino-ku, Sendai-shi","Odawara",""]],
	"9830811":[[4,"仙台市宮城野区","小田原清水沼通","","Miyagino-ku, Sendai-shi","Odawara Shimizunumadori",""]],
	"9830812":[[4,"仙台市宮城野区","小田原弓ノ町","","Miyagino-ku, Sendai-shi","Odawara Yuminomachi",""]],
	"9830813":[[4,"仙台市宮城野区","小田原牛小屋丁","","Miyagino-ku, Sendai-shi","Odawara Ushigoyacho",""]],
	"9830814":[[4,"仙台市宮城野区","小田原大行院丁","","Miyagino-ku, Sendai-shi","Odawara Daigyoincho",""]],
	"9830815":[[4,"仙台市宮城野区","小田原広丁","","Miyagino-ku, Sendai-shi","Odawara Hirocho",""]],
	"9830816":[[4,"仙台市宮城野区","小田原金剛院丁","","Miyagino-ku, Sendai-shi","Odawara Kongoincho",""]],
	"9830817":[[4,"仙台市宮城野区","小田原山本丁","","Miyagino-ku, Sendai-shi","Odawara Yamamotocho",""]],
	"9830821":[[4,"仙台市宮城野区","岩切","","Miyagino-ku, Sendai-shi","Iwakiri",""]],
	"9830822":[[4,"仙台市宮城野区","燕沢東","","Miyagino-ku, Sendai-shi","Tsubamesawahigashi",""]],
	"9830823":[[4,"仙台市宮城野区","燕沢","","Miyagino-ku, Sendai-shi","Tsubamesawa",""]],
	"9830824":[[4,"仙台市宮城野区","鶴ケ谷","","Miyagino-ku, Sendai-shi","Tsurugaya",""]],
	"9830825":[[4,"仙台市宮城野区","鶴ケ谷北","","Miyagino-ku, Sendai-shi","Tsurugayakita",""]],
	"9830826":[[4,"仙台市宮城野区","鶴ケ谷東","","Miyagino-ku, Sendai-shi","Tsurugayahigashi",""]],
	"9830828":[[4,"仙台市宮城野区","岩切分台","","Miyagino-ku, Sendai-shi","Iwakiribundai",""]],
	"9830831":[[4,"仙台市宮城野区","自由ケ丘","","Miyagino-ku, Sendai-shi","Jiyugaoka",""]],
	"9830832":[[4,"仙台市宮城野区","安養寺","","Miyagino-ku, Sendai-shi","Anyoji",""]],
	"9830833":[[4,"仙台市宮城野区","東仙台","","Miyagino-ku, Sendai-shi","Higashisendai",""]],
	"9830834":[[4,"仙台市宮城野区","松岡町","","Miyagino-ku, Sendai-shi","Matsuokacho",""]],
	"9830835":[[4,"仙台市宮城野区","大梶","","Miyagino-ku, Sendai-shi","Okaji",""]],
	"9830836":[[4,"仙台市宮城野区","幸町","","Miyagino-ku, Sendai-shi","Saiwaicho",""]],
	"9830837":[[4,"仙台市宮城野区","枡江","","Miyagino-ku, Sendai-shi","Masue",""]],
	"9830838":[[4,"仙台市宮城野区","二の森","","Miyagino-ku, Sendai-shi","Ninomori",""]],
	"9830839":[[4,"仙台市宮城野区","蟹沢","","Miyagino-ku, Sendai-shi","Kanisawa",""]],
	"9830841":[[4,"仙台市宮城野区","原町","","Miyagino-ku, Sendai-shi","Haranomachi",""]],
	"9830842":[[4,"仙台市宮城野区","五輪","","Miyagino-ku, Sendai-shi","Gorin",""]],
	"9830843":[[4,"仙台市宮城野区","二十人町通","","Miyagino-ku, Sendai-shi","Nijunimmachidori",""]],
	"9830844":[[4,"仙台市宮城野区","原町南目","","Miyagino-ku, Sendai-shi","Haranomachiminaminome",""]],
	"9830845":[[4,"仙台市宮城野区","清水沼","","Miyagino-ku, Sendai-shi","Shimizunuma",""]],
	"9830851":[[4,"仙台市宮城野区","榴ケ岡","","Miyagino-ku, Sendai-shi","Tsutsujigaoka",""]],
	"9830852":[[4,"仙台市宮城野区","榴岡","","Miyagino-ku, Sendai-shi","Tsutsujigaoka",""]],
	"9830853":[[4,"仙台市宮城野区","東六番丁","","Miyagino-ku, Sendai-shi","Higashi6-bancho",""]],
	"9830861":[[4,"仙台市宮城野区","鉄砲町","","Miyagino-ku, Sendai-shi","Teppomachi",""]],
	"9830862":[[4,"仙台市宮城野区","二十人町","","Miyagino-ku, Sendai-shi","Nijunimmachi",""]],
	"9830863":[[4,"仙台市宮城野区","車町","","Miyagino-ku, Sendai-shi","Kurumamachi",""]],
	"9830864":[[4,"仙台市宮城野区","名掛丁","","Miyagino-ku, Sendai-shi","Nakakecho",""]],
	"9830865":[[4,"仙台市宮城野区","元寺小路","","Miyagino-ku, Sendai-shi","Mototerakoji",""]],
	"9830866":[[4,"仙台市宮城野区","花京院通","","Miyagino-ku, Sendai-shi","Kakyoindori",""]],
	"9830867":[[4,"仙台市宮城野区","鉄砲町東","","Miyagino-ku, Sendai-shi","Teppomachihigashi",""]],
	"9830868":[[4,"仙台市宮城野区","鉄砲町中","","Miyagino-ku, Sendai-shi","Teppomachinaka",""]],
	"9830869":[[4,"仙台市宮城野区","鉄砲町西","","Miyagino-ku, Sendai-shi","Teppomachinishi",""]]
})
