zipdata({
	"3300000":[[11,"さいたま市中央区","","","Chuo-ku, Saitama-shi","",""],[11,"さいたま市浦和区","","","Urawa-ku, Saitama-shi","",""]],
	"3300041":[[11,"さいたま市浦和区","三崎","","Urawa-ku, Saitama-shi","Misaki",""]],
	"3300042":[[11,"さいたま市浦和区","木崎","","Urawa-ku, Saitama-shi","Kizaki",""]],
	"3300043":[[11,"さいたま市浦和区","大東","","Urawa-ku, Saitama-shi","Daito",""]],
	"3300044":[[11,"さいたま市浦和区","瀬ケ崎","","Urawa-ku, Saitama-shi","Segasaki",""]],
	"3300045":[[11,"さいたま市浦和区","皇山町","","Urawa-ku, Saitama-shi","Kozancho",""]],
	"3300046":[[11,"さいたま市浦和区","大原","","Urawa-ku, Saitama-shi","Ohara",""]],
	"3300051":[[11,"さいたま市浦和区","駒場","","Urawa-ku, Saitama-shi","Komaba",""]],
	"3300052":[[11,"さいたま市浦和区","本太","","Urawa-ku, Saitama-shi","Motobuto",""]],
	"3300053":[[11,"さいたま市浦和区","前地","","Urawa-ku, Saitama-shi","Maeji",""]],
	"3300054":[[11,"さいたま市浦和区","東岸町","","Urawa-ku, Saitama-shi","Higashikishicho",""]],
	"3300055":[[11,"さいたま市浦和区","東高砂町","","Urawa-ku, Saitama-shi","Higashitakasagocho",""]],
	"3300056":[[11,"さいたま市浦和区","東仲町","","Urawa-ku, Saitama-shi","Higashinakacho",""]],
	"3300061":[[11,"さいたま市浦和区","常盤","","Urawa-ku, Saitama-shi","Tokiwa",""]],
	"3300062":[[11,"さいたま市浦和区","仲町","","Urawa-ku, Saitama-shi","Nakacho",""]],
	"3300063":[[11,"さいたま市浦和区","高砂","","Urawa-ku, Saitama-shi","Takasago",""]],
	"3300064":[[11,"さいたま市浦和区","岸町","","Urawa-ku, Saitama-shi","Kishicho",""]],
	"3300065":[[11,"さいたま市浦和区","神明","","Urawa-ku, Saitama-shi","Shimmei",""]],
	"3300071":[[11,"さいたま市浦和区","上木崎","","Urawa-ku, Saitama-shi","Kamikizaki",""]],
	"3300072":[[11,"さいたま市浦和区","領家","","Urawa-ku, Saitama-shi","Ryoke",""]],
	"3300073":[[11,"さいたま市浦和区","元町","","Urawa-ku, Saitama-shi","Motocho",""]],
	"3300074":[[11,"さいたま市浦和区","北浦和","","Urawa-ku, Saitama-shi","Kitaurawa",""]],
	"3300075":[[11,"さいたま市浦和区","針ヶ谷","","Urawa-ku, Saitama-shi","Harigaya",""]],
	"3300081":[[11,"さいたま市中央区","新都心","","Chuo-ku, Saitama-shi","Shintoshin ",""]],
	"3300800":[[11,"さいたま市大宮区","","","Omiya-ku, Saitama-shi","",""]],
	"3300801":[[11,"さいたま市大宮区","土手町","","Omiya-ku, Saitama-shi","Dotecho",""]],
	"3300802":[[11,"さいたま市大宮区","宮町","","Omiya-ku, Saitama-shi","Miyacho",""]],
	"3300803":[[11,"さいたま市大宮区","高鼻町","","Omiya-ku, Saitama-shi","Takahanacho",""]],
	"3300804":[[11,"さいたま市大宮区","堀の内町","","Omiya-ku, Saitama-shi","Horinochicho",""]],
	"3300805":[[11,"さいたま市大宮区","寿能町","","Omiya-ku, Saitama-shi","Junocho",""]],
	"3300834":[[11,"さいたま市大宮区","天沼町","","Omiya-ku, Saitama-shi","Amanumacho",""]],
	"3300835":[[11,"さいたま市大宮区","北袋町","","Omiya-ku, Saitama-shi","Kitabukurocho",""]],
	"3300836":[[11,"さいたま市大宮区","大原","","Omiya-ku, Saitama-shi","Ohara",""]],
	"3300841":[[11,"さいたま市大宮区","東町","","Omiya-ku, Saitama-shi","Azumacho",""]],
	"3300842":[[11,"さいたま市大宮区","浅間町","","Omiya-ku, Saitama-shi","Sengencho",""]],
	"3300843":[[11,"さいたま市大宮区","吉敷町","","Omiya-ku, Saitama-shi","Kishikicho",""]],
	"3300844":[[11,"さいたま市大宮区","下町","","Omiya-ku, Saitama-shi","Shimocho",""]],
	"3300845":[[11,"さいたま市大宮区","仲町","","Omiya-ku, Saitama-shi","Nakacho",""]],
	"3300846":[[11,"さいたま市大宮区","大門町","","Omiya-ku, Saitama-shi","Daimoncho",""]],
	"3300851":[[11,"さいたま市大宮区","櫛引町","","Omiya-ku, Saitama-shi","Kushihikicho",""]],
	"3300852":[[11,"さいたま市大宮区","大成町","","Omiya-ku, Saitama-shi","Onaricho",""]],
	"3300853":[[11,"さいたま市大宮区","錦町","","Omiya-ku, Saitama-shi","Nishikicho",""]],
	"3300854":[[11,"さいたま市大宮区","桜木町","","Omiya-ku, Saitama-shi","Sakuragicho",""]],
	"3300855":[[11,"さいたま市大宮区","上小町","","Omiya-ku, Saitama-shi","Kamikocho",""]],
	"3300856":[[11,"さいたま市大宮区","三橋","","Omiya-ku, Saitama-shi","Mihashi",""]],
	"3306001":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306002":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306003":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306004":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306005":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306006":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306007":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306008":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306009":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306010":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306011":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306012":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306013":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306014":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306015":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306016":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306017":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306018":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306019":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306020":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306021":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306022":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306023":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306024":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306025":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306026":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306027":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306028":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306029":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306030":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306031":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306032":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306033":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306034":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306035":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]],
	"3306090":[[11,"さいたま市中央区","新都心明治安田生命さいたま新都心","","Chuo-ku, Saitama-shi","Shintoshin Meijiyasudaseimeisaitama",""]]
})
