zipdata({
	"9110000":[[18,"勝山市","","","Katsuyama-shi","",""]],
	"9110001":[[18,"勝山市","北谷町小原","","Katsuyama-shi","Kitadanicho Ohara",""]],
	"9110002":[[18,"勝山市","北谷町木根橋","","Katsuyama-shi","Kitadanicho Kinehashi",""]],
	"9110003":[[18,"勝山市","北谷町河合","","Katsuyama-shi","Kitadanichokogo",""]],
	"9110004":[[18,"勝山市","北谷町北六呂師","","Katsuyama-shi","Kitadanicho Kitarokuroshi",""],[18,"勝山市","北谷町中尾","","Katsuyama-shi","Kitadanicho Nakao",""]],
	"9110005":[[18,"勝山市","北谷町杉山","","Katsuyama-shi","Kitadanicho Sugiyama",""]],
	"9110006":[[18,"勝山市","北谷町谷","","Katsuyama-shi","Kitadanicho Tani",""]],
	"9110011":[[18,"勝山市","野向町牛ケ谷","","Katsuyama-shi","Nomukicho Ushigatani",""]],
	"9110012":[[18,"勝山市","野向町薬師神谷","","Katsuyama-shi","Nomukicho Yakushigamiya",""]],
	"9110013":[[18,"勝山市","野向町深谷","","Katsuyama-shi","Nomukicho Fukadani",""]],
	"9110014":[[18,"勝山市","野向町聖丸","","Katsuyama-shi","Nomukicho Hijirimaru",""]],
	"9110015":[[18,"勝山市","野向町竹林","","Katsuyama-shi","Nomukicho Takebayashi",""]],
	"9110016":[[18,"勝山市","野向町龍谷","","Katsuyama-shi","Nomukicho Ryudani",""]],
	"9110017":[[18,"勝山市","野向町北野津又","","Katsuyama-shi","Nomukicho Kitanotsumata",""],[18,"勝山市","野向町横倉","","Katsuyama-shi","Nomukicho Yokokura",""]],
	"9110021":[[18,"勝山市","村岡町栃神谷","","Katsuyama-shi","Murokocho Tochigamiya",""]],
	"9110022":[[18,"勝山市","村岡町暮見","","Katsuyama-shi","Murokocho Kuremi",""],[18,"勝山市","芳野ケ原","","Katsuyama-shi","Yoshinogahara",""]],
	"9110023":[[18,"勝山市","村岡町寺尾","","Katsuyama-shi","Murokocho Terao",""]],
	"9110024":[[18,"勝山市","村岡町浄土寺","","Katsuyama-shi","Murokocho Jodoji",""]],
	"9110025":[[18,"勝山市","村岡町五本寺","","Katsuyama-shi","Murokocho Gohonji",""]],
	"9110026":[[18,"勝山市","村岡町黒原","","Katsuyama-shi","Murokocho Kurohara",""]],
	"9110031":[[18,"勝山市","長山町","","Katsuyama-shi","Nagayamacho",""]],
	"9110032":[[18,"勝山市","芳野町","","Katsuyama-shi","Yoshinocho",""]],
	"9110033":[[18,"勝山市","栄町","","Katsuyama-shi","Sakaemachi",""]],
	"9110034":[[18,"勝山市","滝波町","","Katsuyama-shi","Takinamicho",""]],
	"9110035":[[18,"勝山市","郡町","","Katsuyama-shi","Korimachi",""]],
	"9110041":[[18,"勝山市","荒土町北新在家","","Katsuyama-shi","Aradocho Kitashinzaike",""],[18,"勝山市","荒土町清水島","","Katsuyama-shi","Aradocho Shimizushima",""],[18,"勝山市","荒土町布市","","Katsuyama-shi","Aradocho Nunoichi",""]],
	"9110042":[[18,"勝山市","荒土町田名部","","Katsuyama-shi","Aradocho Tanabe",""],[18,"勝山市","荒土町松田","","Katsuyama-shi","Aradocho Matsuta",""]],
	"9110043":[[18,"勝山市","荒土町新保","","Katsuyama-shi","Aradocho Shimbo",""]],
	"9110044":[[18,"勝山市","荒土町松ケ崎","","Katsuyama-shi","Aradocho Matsugasaki",""]],
	"9110045":[[18,"勝山市","荒土町伊波","","Katsuyama-shi","Aradocho Inami",""],[18,"勝山市","荒土町妙金島","","Katsuyama-shi","Aradocho Myokinjima",""]],
	"9110046":[[18,"勝山市","荒土町中清水","","Katsuyama-shi","Aradocho Nakashimizu",""],[18,"勝山市","荒土町堀名","","Katsuyama-shi","Aradocho Horime",""],[18,"勝山市","荒土町堀名中清水","","Katsuyama-shi","Aradocho Horimenakashimizu",""]],
	"9110047":[[18,"勝山市","荒土町北宮地","","Katsuyama-shi","Aradocho Kitamiyaji",""]],
	"9110048":[[18,"勝山市","荒土町境","","Katsuyama-shi","Aradocho Sakai",""],[18,"勝山市","荒土町新道","","Katsuyama-shi","Aradocho Shindo",""],[18,"勝山市","荒土町戸倉","","Katsuyama-shi","Aradocho Tokura",""],[18,"勝山市","荒土町西ケ原","","Katsuyama-shi","Aradocho Nishigahara",""],[18,"勝山市","荒土町別所","","Katsuyama-shi","Aradocho Bessho",""],[18,"勝山市","荒土町細野","","Katsuyama-shi","Aradocho Hosono",""],[18,"勝山市","荒土町細野口","","Katsuyama-shi","Aradocho Hosonoguchi",""]],
	"9110051":[[18,"勝山市","北郷町新町","","Katsuyama-shi","Kitagocho Aramachi",""],[18,"勝山市","北郷町志比原","","Katsuyama-shi","Kitagocho Shiiwara",""],[18,"勝山市","北郷町檜曽谷","","Katsuyama-shi","Kitagocho Hisodani",""]],
	"9110052":[[18,"勝山市","北郷町西妙金島","","Katsuyama-shi","Kitagocho Nishimyokinjima",""]],
	"9110053":[[18,"勝山市","北郷町上森川","","Katsuyama-shi","Kitagocho Kamimorikawa",""],[18,"勝山市","北郷町下森川","","Katsuyama-shi","Kitagocho Shimomorikawa",""],[18,"勝山市","北郷町森川","","Katsuyama-shi","Kitagocho Morikawa",""]],
	"9110054":[[18,"勝山市","北郷町東野","","Katsuyama-shi","Kitagocho Higashino",""]],
	"9110055":[[18,"勝山市","北郷町伊知地","","Katsuyama-shi","Kitagocho Ijichi",""],[18,"勝山市","北郷町岩屋","","Katsuyama-shi","Kitagocho Iwaya",""],[18,"勝山市","北郷町上野","","Katsuyama-shi","Kitagocho Uwano",""]],
	"9110056":[[18,"勝山市","北郷町坂東島","","Katsuyama-shi","Kitagocho Bandojima",""]],
	"9110801":[[18,"勝山市","沢町","","Katsuyama-shi","Sawamachi",""]],
	"9110802":[[18,"勝山市","昭和町","","Katsuyama-shi","Showamachi",""]],
	"9110803":[[18,"勝山市","旭町","","Katsuyama-shi","Asahimachi",""]],
	"9110804":[[18,"勝山市","元町","","Katsuyama-shi","Motomachi",""]],
	"9110805":[[18,"勝山市","立川町","","Katsuyama-shi","Tatekawacho",""]],
	"9110806":[[18,"勝山市","本町","","Katsuyama-shi","Hommachi",""]],
	"9110811":[[18,"勝山市","片瀬","","Katsuyama-shi","Katase",""],[18,"勝山市","片瀬町","","Katsuyama-shi","Katasecho",""]],
	"9110812":[[18,"勝山市","猪野","","Katsuyama-shi","Ino",""]],
	"9110813":[[18,"勝山市","猪野口","","Katsuyama-shi","Inokuchi",""]],
	"9110814":[[18,"勝山市","若猪野","","Katsuyama-shi","Wakaino",""]],
	"9110815":[[18,"勝山市","上高島","","Katsuyama-shi","Kamitakajima",""],[18,"勝山市","北市","","Katsuyama-shi","Kitaichi",""],[18,"勝山市","下高島","","Katsuyama-shi","Shimotakajima",""],[18,"勝山市","高島","","Katsuyama-shi","Takajima",""],[18,"勝山市","西高島","","Katsuyama-shi","Nishitakajima",""]],
	"9110816":[[18,"勝山市","猪野毛屋","","Katsuyama-shi","Inokeya",""],[18,"勝山市","毛屋","","Katsuyama-shi","Keya",""],[18,"勝山市","毛屋町","","Katsuyama-shi","Keyacho",""],[18,"勝山市","下毛屋","","Katsuyama-shi","Shimokeya",""]],
	"9110817":[[18,"勝山市","旭毛屋町","","Katsuyama-shi","Asahikeyacho",""]],
	"9110821":[[18,"勝山市","平泉寺町岡横江","","Katsuyama-shi","Heisenjicho Okayokoe",""]],
	"9110822":[[18,"勝山市","平泉寺町神野","","Katsuyama-shi","Heisenjicho Shinno",""],[18,"勝山市","平泉寺町平泉寺","","Katsuyama-shi","Heisenjicho Heisenji",""]],
	"9110823":[[18,"勝山市","平泉寺町赤尾","","Katsuyama-shi","Heisenjicho Akao",""]],
	"9110824":[[18,"勝山市","平泉寺町池ケ原","","Katsuyama-shi","Heisenjicho Ikegahara",""],[18,"勝山市","平泉寺町大矢谷","","Katsuyama-shi","Heisenjicho Oyadani",""],[18,"勝山市","平泉寺町小矢谷","","Katsuyama-shi","Heisenjicho Koyadani",""]],
	"9110825":[[18,"勝山市","平泉寺町岩ケ野","","Katsuyama-shi","Heisenjicho Iwagano",""],[18,"勝山市","平泉寺町上野","","Katsuyama-shi","Heisenjicho Ueno",""]],
	"9110826":[[18,"勝山市","平泉寺町壁倉","","Katsuyama-shi","Heisenjicho Kabekura",""]],
	"9110827":[[18,"勝山市","平泉寺町笹尾","","Katsuyama-shi","Heisenjicho Sasao",""]],
	"9110828":[[18,"勝山市","平泉寺町大渡","","Katsuyama-shi","Heisenjicho Owatari",""],[18,"勝山市","平泉寺町経塚","","Katsuyama-shi","Heisenjicho Kyozuka",""]],
	"9110831":[[18,"勝山市","遅羽町千代田","","Katsuyama-shi","Osowacho Chiyoda",""],[18,"勝山市","遅羽町中島","","Katsuyama-shi","Osowacho Nakajima",""],[18,"勝山市","遅羽町比島","","Katsuyama-shi","Osowacho Hishima",""]],
	"9110832":[[18,"勝山市","遅羽町蓬生","","Katsuyama-shi","Osowacho Yomogi",""]],
	"9110833":[[18,"勝山市","遅羽町北山","","Katsuyama-shi","Osowacho Kitayama",""]],
	"9110834":[[18,"勝山市","遅羽町大袋","","Katsuyama-shi","Osowacho Obukuro",""],[18,"勝山市","遅羽町新道","","Katsuyama-shi","Osowacho Shindo",""]],
	"9110835":[[18,"勝山市","遅羽町ほう崎","","Katsuyama-shi","Osowacho Hoki",""]],
	"9110836":[[18,"勝山市","遅羽町下荒井","","Katsuyama-shi","Osowacho Shimoarai",""]],
	"9110841":[[18,"勝山市","鹿谷町発坂","","Katsuyama-shi","Shikadanicho Hossaka",""]],
	"9110842":[[18,"勝山市","鹿谷町志田","","Katsuyama-shi","Shikadanicho Shida",""]],
	"9110843":[[18,"勝山市","鹿谷町杉俣","","Katsuyama-shi","Shikadanicho Sugimata",""],[18,"勝山市","鹿谷町本郷","","Katsuyama-shi","Shikadanicho Hongo",""]],
	"9110844":[[18,"勝山市","鹿谷町東遅羽口","","Katsuyama-shi","Shikadanicho Higashiosowaguchi",""],[18,"勝山市","鹿谷町西遅羽口","","Katsuyama-shi","Shikadanicho Nishiosowaguchi",""]],
	"9110845":[[18,"勝山市","鹿谷町矢戸口","","Katsuyama-shi","Shikadanicho Yatoguchi",""]],
	"9110846":[[18,"勝山市","鹿谷町北西俣","","Katsuyama-shi","Shikadanicho Kitanishimata",""]],
	"9110847":[[18,"勝山市","鹿谷町西光寺","","Katsuyama-shi","Shikadanicho Saikoji",""]],
	"9110848":[[18,"勝山市","鹿谷町出村","","Katsuyama-shi","Shikadanicho Demura",""],[18,"勝山市","鹿谷町保田","","Katsuyama-shi","Shikadanicho Hota",""],[18,"勝山市","鹿谷町保田出村","","Katsuyama-shi","Shikadanicho Hotademura",""]]
})
